### ISSUE TITLE
Can't establish ngrok tunnel

### ISSUE THREAD

**Issue by profgeek** [inconshreveable/ngrok#100]
I am using Ubuntu 12.04.  I installed ngrok but when I try to create a tunnel I get the following error:

Invalid address server_addr 'ngrokd.ngrok.com:443': lookup ngrokd.ngrok.com.: no DNS servers

It appears that it can't find ngrokd.ngrok.com, however I can ping that server and receive a response just fine.  I've looked on Google for the error, but don't find anyone who has documented it.  I'd like to get ngrok to work (I donated some $ to it), but can't seem to get beyond this point.  I'm trying to use the -authtoken with it, but even without it I get the same error.

**Comment by imranzahid01** [comment]
I am having the `panic: Error reading asset assets/client/tls/ngrokroot.crt` error.
I followed the guide to host ngrok on my own server, I am using Ubuntu on my server, and when I make the client for windows like `GOOS=windows GOARCH=386 make release` then in `bin/windows_386` I can see `ngrok.exe` created. I ssh this file on my windows machine, and when I try to run it I get the above error.

Any ideas what might be causing this?
Following is the console output from Ubuntu:
```
root@myserver:~/ngrok# GOOS=windows GOARCH=386 make release-client
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
	-debug=false \
	-o=src/ngrok/client/assets/assets_release.go \
	assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
	-debug=false \
	-o=src/ngrok/server/assets/assets_release.go \
	assets/server/...
go get -tags 'release' -d -v ngrok/...
go install -tags 'release' ngrok/main/ngrok
root@myserver:~/ngrok# cd bin
root@myserver:~/ngrok/bin# cd windows_386/
root@myserver:~/ngrok/bin/windows_386# ls
ngrok.exe
```

**Comment by hibooboo2** [comment]
Are you sure you need 386 and not amd_64 as you arch?

**Comment by imranzahid01** [comment]
my bad, using arch as amd_64 fixes the problem, thanks

**Comment by hibooboo2** [comment]
Your welcome.

**Comment by paulindax** [comment]
Link is not working any more and i really need this build..am on ubuntu 32bit

**Comment by LongBeachHXC** [comment]
I'm having the same issues as ProfGeek 

Invalid address server_addr 'ngrokd.ngrok.com:443'

I'm running Ubuntu 16.04 LTS.

**Comment by Efrat19** [comment]
happened to me too at Ubuntu 16.04 LTS.
ive updated to ngrok 2.3.34 : https://ngrok.com/download
`ngrok http 80` works like a rocket
