### ISSUE TITLE
Sessions not persisting between requests

### ISSUE THREAD

**Issue by axsuul** [inconshreveable/ngrok#102]
I'm currently using ngrok to tunnel to my Rails app on port 3000 that is running on a vagrant VM. So if my vagrant VM is running on `10.0.0.1`, then the command I run is

```
ngrok 10.0.0.1:3000
```

However, none of my session variables are persisting (so can't login, etc). In Chrome Developer Tools, everything in Session Storage is empty. Is this expected?

**Comment by kershner** [comment]
I see this is closed without any information as to why.  I am having the same issue - ngrok (v2.1.14) is seemingly not saving any session variables.  Is there any more information you could provide about ngrok and session data handling?
