### ISSUE TITLE
makeslice: len out of range

### ISSUE THREAD

**Issue by FacuM** [inconshreveable/ngrok#110]
System fails when attemping to attach proxy server (server_addr) from Terminal Emulator on Android :(
![screenshot_2014-04-07-22-28-42](https://cloud.githubusercontent.com/assets/3741108/2639106/58e1e690-bebe-11e3-8d7e-3639c5b14665.png)

**Comment by casdr** [comment]
I'm having this issue as well, @lukerattei have you been able to fix this?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
