### ISSUE TITLE
Can add a new command line option for open the Web console in remote?

### ISSUE THREAD

**Issue by saighost** [inconshreveable/ngrok#116]
I try ngrok on my Raspberry Pi with ssh. If I want to open the web console, need to open a vnc server on it.

**Comment by matthewjewell** [comment]
+1 / Same issue using ngrok with a VM (Homestead). Would be nice to see something a little cleaner than tunnelling 4040.

**Comment by inconshreveable** [comment]
@matthewjewell what about tunneling port 4040 doesn't feel clean? ngrok 2.0 supports disabling introspection and seems to cover this use case pretty smoothly.

**Comment by inconshreveable** [comment]
won't fix for 1.x
