### ISSUE TITLE
Wildcard subdomains for custom domains.

### ISSUE THREAD

**Issue by ragusource** [inconshreveable/ngrok#131]
Please add the ability to have subdomains for custom domains. E.G. If you add the following subdomain:

    foo.example.com

It would be handy to be able to create custom subdomains such as:

    bar.foo.example.com

Using the subdomain option in cli or yml config.

**Comment by docksteaderluke** [comment]
+1
I fall into one of those situations that requires wildcard subdomains.

**Comment by docksteaderluke** [comment]
As @JimmyRittenborg said, It seems possible to reserve a wildcard subdomain *.example.com on ngrok.com *but* specifying foo.example.com in the ngrok config file doesn't work. Even if each subdomain had to be specified in the config file but worked with the wildcard mapping on ngrok.com that would be a big step forward. It would at least eliminate the number of people emailing @inconshreveable asking for more reserved domains :)

**Comment by inconshreveable** [comment]
wildcards are supported in ngrok 2.x. won't fix in 1.x

**Comment by voarsh2** [comment]
> wildcards are supported in ngrok 2.x. won't fix in 1.x

Um. I can't get wildcards working in the YAML....

**Comment by natanparmigianoreis** [comment]
> > wildcards are supported in ngrok 2.x. won't fix in 1.x
> 
> Um. I can't get wildcards working in the YAML....

Make sure to 'quote' the domain in the config file, ie: hostname: '*.example.com'
'*' is a special char in yml
