### ISSUE TITLE
SSE support

### ISSUE THREAD

**Issue by vincentbernat** [inconshreveable/ngrok#135]
ngrok seems to buffer the whole data before sending it to the client. This doesn't work when chunked data are streamed, like for example when using SSE (server-sent streams).

**Comment by blindman2k** [comment]
+1 for chunked transfer encoding support.

**Comment by inconshreveable** [comment]
This is fixed in 2.x. Technically  it works in 1.x, but never worked in the hosted 1.x version of ngrok.com because nginx was the frontend proxy. closing
