### ISSUE TITLE
how can i use gccgo to compile the source code?

### ISSUE THREAD

**Issue by zd108** [inconshreveable/ngrok#141]

**Comment by zd108** [comment]
Hi dosgo, I have rewritten ngrok client in C language.

**Comment by dosgo** [comment]
Hello zd108, am looking forward to the client C language, which means that can be ported to any device, can disclose under progress.

**Comment by dosgo** [comment]
Hi zd108,I found a python client.

**Comment by zd108** [comment]
Hi dosgo, The client is already running in my embedded systems, and I am testing its stability.

**Comment by dosgo** [comment]
Join DDNS feature?

**Comment by dosgo** [comment]
Hi zd108,I also try to use the C language rewrite ngrok client, is currently experiencing, OPENSSL does not support multi-threading issues, seeking help.
