### ISSUE TITLE
How do I compile ngrok on Windows?

### ISSUE THREAD

**Issue by paambaati** [inconshreveable/ngrok#142]
I use Windows 7, and would like to compile ngrok, if that is even possible. Has anyone had success compiling on Windows?

**Comment by MRACHINI** [comment]
i did something like this

GOOS=windows GOARCH=386 make release-server release-client

what is the difference ?

**Comment by StudioEtrange** [comment]
If you want windows binaries
you could use this https://github.com/StudioEtrange/ngrok-build
but on macosx or linux. It will cross compile and produce windows binaries
