### ISSUE TITLE
ssh login permission denied

### ISSUE THREAD

**Issue by HouCoder** [inconshreveable/ngrok#145]
i'm use ngrok forward my linux server 22 port to a dynamic dmaiain, when i use ssh to connect my linux server: `ssh me@xxx.ngrok.com`, but here is the problem: after i enter the password the server response `Permission denied, please try again`, then i use command `ssh me@192.168.1.103` and enter the same password success login the server. i don't get it why i enter the right password the server still response Permission denied.

thanks

**Comment by Klavyeli** [comment]
In the locator, the ngrok works smoothly, but it does not allow in the shell, but it is allowed to remove the zip in.

**Comment by Klavyeli** [comment]
Locatorda, ngrok sorunsuz çalışır, ancak kabuğa izin vermez, ancak zip içinde kaldırılmasına izin verilir 
./ngrok: İzin reddedildi ??????
