### ISSUE TITLE
Can not ssh or ftp into ngroked server

### ISSUE THREAD

**Issue by animationista** [inconshreveable/ngrok#147]
I run ngrok on a Raspberry PI server but for some reason my password is not accepted when sshing or ftping.

http works.

Starting ngrok with /usr/local/bin/ngrok/ngrok -subdomain=mycustomdomain -proto=tcp 22
Sshing I got the ssh keypair question but then in response to my password I get
Permission denied, please try again.

Starting with port 21, trying to ftp I get 
Connection attempt failed with "ECONNREFUSED - Connection refused by server".

I can both ssh and ftp into the server using local IP.
If I forward to another server of mine I can't get that to accept my ssh password either.
ngrok -subdomain=mycustomdomain anotherdomain.other.com:22

I have registered with -authtoken

What might be wrong?

**Comment by akkisinghpanchaal** [comment]
How did you know what random port ngrok threw on terminal?

**Comment by iamhrishikeshpadhye** [comment]
> > Thank's!
> > I figured out that I sahould NOT use -p 22 but the random port ngrok gives in the terminal UI...
> > Now I can both ssh and sftp into my server using ngrok.
> 
> Can you please explain how you did SFTP through ngrok? I am able to do SSH using ngrok but I can't do SFTP.
> I had run
> `ngrok tcp 22`
> on the server machine and on the client :
> `sftp <user>@2.tcp.ngrok.io -p <ngrok port>`
> Is this the correct way?

I got it! 
I was using '-p' for passing the port number which is not correct.
The correct command is : 
`sftp -oPort=<ngrok tcp port> user@0.tcp.ngrok.io`

**Comment by ItsSpyNex** [comment]
> > > Thank's!
> > > I figured out that I sahould NOT use -p 22 but the random port ngrok gives in the terminal UI...
> > > Now I can both ssh and sftp into my server using ngrok.
> > 
> > 
> > Can you please explain how you did SFTP through ngrok? I am able to do SSH using ngrok but I can't do SFTP.
> > I had run
> > `ngrok tcp 22`
> > on the server machine and on the client :
> > `sftp <user>@2.tcp.ngrok.io -p <ngrok port>`
> > Is this the correct way?
> 
> I got it! I was using '-p' for passing the port number which is not correct. The correct command is : `sftp -oPort=<ngrok tcp port> user@0.tcp.ngrok.io`

help a brother out here lol, i have sftp server running on my local network i dont know how to expose it to the internet, iam kind of a noob as well

**Comment by RobertNissan** [comment]
eso solo funciona en termux, pero para Es File Explore no funciona bro, teniendo en cuenta el puerto ssh para ngrok
ngrok tcp 8022
sftp -oPort=<ngrok tcp port> <user_termux>@6.tcp.ngrok.io
