### ISSUE TITLE
Using grok with local subdomain

### ISSUE THREAD

**Issue by christhesoul** [inconshreveable/ngrok#152]
Hey. I paid, so I feel okay about asking what may be a stupid question. :)

Okay, so I am developing a Rails application locally. It uses custom subdomains. So when I start my rails server and visit `foo.myapp.dev:3000` I see the correct view for the `foo` account.

So now I want to use ngrok so I can see this in Virtual Box (yep, I'm doing IE layout fixes), but I'm not sure how to do it.

I tried this:
`~/Sites/ngrok foo.myapp.dev:3000`
which starts ngrok fine, but no dice.

Can anybody point me in the right direction?

Thanks

**Comment by ultraN** [comment]
For unpaid users:
ngrok http -host-header=rewrite <your-custom-local-domain>:80

**Comment by ilgityildirim** [comment]
Unpaid users and others can use this [gist](https://gist.github.com/ilgityildirim/2e736279cc628db674e9eb3145f8c5a7) as well

**Comment by kevin1193** [comment]
nice! Thanks

**Comment by half2me** [comment]
> For unpaid users:
> `ngrok http -host-header=rewrite [your-custom-local-domain]:[port]`

Thank you! :+1:
