### ISSUE TITLE
Accessing Web Interface via Virtualbox/Vagrant

### ISSUE THREAD

**Issue by jaydrogers** [inconshreveable/ngrok#153]
Hello,

I have an Ubuntu 12.04 Server guest running via Vagrant & Virtualbox. The Ubuntu guest is behind a virtualbox managed NAT network connection. When I fire up ngrok on the guest, I do see this message come across the screen:

`Web Interface                 127.0.0.1:4040`

Since there isn't a web browser on my Ubuntu guest, I am trying to access it from my Host (Mac OS X). I port forwarded 4041 to 4040 on my Ubuntu guest. When I type in **http://localhost:4041** on my Mac, I get an error message:

![screen shot 2014-07-23 at 8 40 32 am](https://cloud.githubusercontent.com/assets/3174134/3673743/e31fbff8-126f-11e4-8b16-52dfa6d47a39.png)

When I ssh into my Ubuntu guest and `curl http://localhost:4040` I get the following output:

`
<a href="/http/in">Found</a>.
`

Is it possible to configure ngrok to allow a connection from another host? Am I doing something wrong?

**Comment by jonnywilliamson** [comment]
To save anyone else 30mins of their life

```
web_addr: 0.0.0.0:4040
```

Is the newer setting name that you must use in the config file. Guess who didn't see that for AGES.....

**Comment by mablae** [comment]
@jonnywilliamson Thx, you saved me time !

**Comment by carliitozcorrea** [comment]
Thanks! @jonnywilliamson

**Comment by andkirby** [comment]
Still having an issue...

Inside vagrant/virtualbox:
```
$ cat ~/.ngrok2/ngrok.yml
authtoken: lih7yl7yu.........kuytu6b
web_addr: localhost:4040

$ curl localhost:4040 -Ls
<html>
    <head>
        <title>ngrok</title>
[...]
```
In host env:
```
$ curl localhost:4040 -Ls

(exit with code 56)
```

Double checked: mapping has been added properly.
