### ISSUE TITLE
Can ngrok support NTLM?

### ISSUE THREAD

**Issue by samrain** [inconshreveable/ngrok#155]
I have a Sharepoint Service in my company's network.

I want to access it by ngrok.

code is that: `./ngrok 192.168.1.80:80`

But after I put my id and pw again and again,I can't login.

error is that:

GET / HTTP/1.1
Host: 619df972.ngrok.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip,deflate,sdch
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4
Authorization: NTLM TlRMTVNTUAABAAAAB4IIAAAAAAAAAAAAAAAAAAAAAAA=
Connection: close
Cookie: _ga=GA1.2.842445084.1406196054
X-Forwarded-Proto: https
X-Real-Ip: 14.63.172.180

401 Unauthorized
Content-Length	["1251"]
Content-Type	["text/html"]
Date	["Fri, 25 Jul 2014 10:40:34 GMT"]
Microsoftsharepointteamservices	["12.0.0.4518"]
Server	["Microsoft-IIS/6.0"]
Www-Authenticate	["NTLM TlRMTVNTUAACAAAAFgAWADgAAAAFgooCHaUolw2J6bQAAAAAAAAAAGwAbABOAAAABQLODgAAAA9DAE8AUABSAEkAWgBFAC0AUwBWAFIAAgAWAEMATwBQAFIASQBaAEUALQBTAFYAUgABABYAQwBPAFAAUgBJAFoARQAtAFMAVgBSAAQAFgBjAG8AcAByAGkAegBlAC0AcwB2AHIAAwAWAGMAbwBwAHIAaQB6AGUALQBzAHYAcgAAAAAA"]
X-Powered-By	["ASP.NET"]

GET / HTTP/1.1
Host: 619df972.ngrok.com
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/34.0.1847.116 Chrome/34.0.1847.116 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip,deflate,sdch
Accept-Language: zh-CN,zh;q=0.8,en-US;q=0.6,en;q=0.4
Authorization: NTLM TlRMTVNTUAADAAAAGAAYAFoAAAAYABgAcgAAAAAAAABAAAAACgAKAEAAAAAQABAASgAAAAAAAAAAAAAABYIIAGgAYQBuAHkAdQBoAGEAbgB5AHUALQBwAGMApfUiZdvMnkAAAAAAAAAAAAAAAAAAAAAA3z5PntglzHIV+PQAOcSJw/lXKzJcdJYl
Connection: close
Cookie: _ga=GA1.2.842445084.1406196054
X-Forwarded-Proto: https
X-Real-Ip: 14.63.172.180

401 Unauthorized
Content-Length	["1251"]
Content-Type	["text/html"]
Date	["Fri, 25 Jul 2014 10:39:26 GMT"]
Microsoftsharepointteamservices	["12.0.0.4518"]
Server	["Microsoft-IIS/6.0"]
Www-Authenticate	["Negotiate","NTLM"]
X-Powered-By	["ASP.NET"]

**Comment by inconshreveable** [comment]
won't fix, closing

**Comment by Abenezer** [comment]
@inconshreveable  can you please investigate more.. i really need NTLM auth to work with ngrok

**Comment by manoelleiteufal** [comment]
I Have the same error. anybody can help us?
