### ISSUE TITLE
IP Filter

### ISSUE THREAD

**Issue by un1kum** [inconshreveable/ngrok#156]
How about IP filter for control access to TCP-tunnels?

**Comment by lietu** [comment]
This is the only thing missing that's preventing me from using ngrok. I don't trust having a fully open connection to my development environment and I imagine making a local firewall try and filter traffic from ngrok would be .. challenging at best.

Best would be an optional CIDR filter, so e.g. something like: `--allow-ip=1.2.3.4` or `--allow-cidr=1.2.3.0/24` .. alternatively both options could be `--allow`

**Comment by inconshreveable** [comment]
This is supported in ngrok 2.x (somewhat at an account level, and will eventually be available at a tunnel level). won't fix for 1.x
