### ISSUE TITLE
how to run ngrok as a windows service [resolved]

### ISSUE THREAD

**Issue by codesve** [inconshreveable/ngrok#160]
Hi, I want to run the ngrok in background as a windows service, is there a approach?
thank you!

**Comment by codesve** [comment]
@IgorGanapolsky There is no `pause` in my bat file, just`start /b ./ngrok -config=C:\Users\codesve\.ngrok -log=stdout start 127.codesve.com > ngrok.log 2>&1`. And I don't know why the script kills itself, sorry!

**Comment by IgorGanapolsky** [comment]
What I mean is - try running this .bat file, and you see it disappears from
the screen right away.  That wouldn't happen if there was a `pause` command
in the .bat file.

Igor

**Comment by lalo312** [comment]
Hello  I have found a solution, run sc create ngrok binpath= "cmd /c \"c:\tmp\ngrok.exe\" http 80"
Then hit net start ngrok, that will leave the process on a diferent thread
