### ISSUE TITLE
tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

### ISSUE THREAD

**Issue by chengziqing** [inconshreveable/ngrok#165]
debug in my pc,run display error:
control recovering from failure tls: either ServerName or InsecureSkipVerify must be specified in the tls.Config

**Comment by shenshouer** [comment]
ngrokd server builded in local pc cannot connect by the ngrok client which build in local pc too. but the grok client can connect to de ngrok.com. So I think there has some bug in code.

**Comment by inconshreveable** [comment]
won't fix, closing
