### ISSUE TITLE
[question] MIPS builds?

### ISSUE THREAD

**Issue by jdstroy** [inconshreveable/ngrok#166]
Would you be willing to provide Linux/MIPS builds as well for ngrok? This would be excellent for the numerous inexpensive IoT devices that run Linux on MIPS CPUs.  (I see that equinox.io is also owned by you...)

**Comment by michalliu** [comment]
Don't try it, you are wasting your time. Because i have tried.

**Comment by michalliu** [comment]
I suggest you use https://github.com/dosgo/ngrok-c instead

**Comment by dosgo** [comment]
@michalliu  你好，你在用ngrok-c吗？感觉如何？

**Comment by OllivanderMe** [comment]
@dosgo 具体操作步骤不是很详细，我家路由急需一个ngrok客户端

**Comment by inconshreveable** [comment]
mips64 is targeted by Go now. mips64 builds for 2.x may show up soon. never for 1.x though, closing

**Comment by jdstroy** [comment]
Something to keep in mind... most of the IoT MIPS targets are MIPS32 targets, not MIPS64 targets.

**Comment by inconshreveable** [comment]
@jdstroy Yeah, it basically just depends on whether someone eventually wants to add support to the go toolchain for mips32 targets. It's possible that gccgo makes this a viable possibility if I have time to dig into getting builds set up with it
