### ISSUE TITLE
kill a tunnel registered on a reserved subdomain

### ISSUE THREAD

**Issue by AshHeskes** [inconshreveable/ngrok#167]
Is there any way to force the closing of a tunnel associated to a reserved subdomain within my account.

There seems to be an issue with with the `node ngrok` lib that doesn't correctly kill a tunnel when the program using it unexpectedly crashes. This causes the tunnel to remain open according to ngrok so trying to connect a new tunnel on that subdomain is impossible.

I understand this may be impossible to deal with for general subdomains issued by ngrok. However I'm using a reserved subdomain on a payed account. It would be good if I had the power to force kill any active tunnels on that subdomain.

**Comment by msolomonTMG** [comment]
+1

**Comment by jakeleboeuf** [comment]
+1

**Comment by ericraio** [comment]
+1

**Comment by docksteaderluke** [comment]
+1

**Comment by wassupnari** [comment]
+1

**Comment by cloud9coding** [comment]
+1

**Comment by SynapseR** [comment]
+1

**Comment by cyogrant** [comment]
+1

**Comment by inconshreveable** [comment]
Yep, working on a fix for this right now. Fix will address another issue that causes a tunnel to 'hang open' for ~5 minutes after it was intentionally closed.

**Comment by inconshreveable** [comment]
The latest cause of tunnels hanging open has been resolved. Apologies for the problems with the service. I'll leave this issue open since there's still no way to "force close" a tunnel, but the chances that you'll need to do that are now much more rare.

**Comment by mrnnn** [comment]
Still have detached sessions referring to my home ip while at work. 2 sessions in fact, even though i'm only allowed one. not sure how that happened :-). Anyway, it'd be nice to be able to detach them if you know the auth token & secret, or through the ngrok client portal.

**Comment by inconshreveable** [comment]
no longer an issue in the hosted service

**Comment by ZackBurtPoncho** [comment]
How do we programmatically kill detached sessions in order to deal with this error?

**Comment by Hedgehogking** [comment]
+1

**Comment by KharitonOff** [comment]
I can't restart my ngrok connection:
```
Tunnel session failed: Your account 'XYZ' is limited to 1 simultaneous ngrok client session.
Active ngrok client sessions in region 'us':
  - 414c40ed9afc1756ffa78f2d32fc3617 (155.56.44.134:63846)
```
I've got this issue using ngrok@2.0.0

**Comment by juergen-vogel** [comment]
@KharitonOff You can fix it by setting your authcode once again. When you're logged in you can find it here: https://dashboard.ngrok.com/get-started

`$ ./ngrok authtoken YOUR-TOKEN`

**Comment by jonjaques** [comment]
`killall ngrok`

**Comment by sjordan1975** [comment]
Having issue today and suggest "You can fix it by setting your authcode once again. When you're logged in you can find it here: https://dashboard.ngrok.com/get-started" did not work

**Comment by chriscohoat** [comment]
@sjordan1975 it's in the Admin tab:
 ![Admin Tab](http://i.imgur.com/xB610Vq.png)

**Comment by theo-bittencourt** [comment]
Facing same issue now.
Refreshing authcode didn't work.

**Comment by vladich** [comment]
> @KharitonOff You can fix it by setting your authcode once again. When you're logged in you can find it here: https://dashboard.ngrok.com/get-started
> 
> `$ ./ngrok authtoken YOUR-TOKEN`

this doesn't work

**Comment by synth** [comment]
Experiencing same issue. We tried resetting authtoken and no dice. It would be great if there was a way to kill the tunnel from the website.

**Comment by aszalacinski** [comment]
Experiencing same issue as well.

**Comment by ryanckulp** [comment]
i shared this on another related issue but we baked our own solution here:
https://blog.fomo.com/remotely-kill-ngrok-session/

**Comment by gavinsmith** [comment]
+1. Resetting token doesn't work, no running processes on the client, it's just perma-reserved on my account. No way to kill it from the web UI or CLI tool.

**Comment by chris-rowe** [comment]
+1 on what @gavinsmith said above.  Nothing is terminating the tunnel making ngrok unusable on my system

**Comment by airtwo** [comment]
+1

**Comment by iwhitedevil** [comment]
Any one found a solution for this
Tunnel session failed: Your account 'XYZ' is limited to 1 simultaneous ngrok client session.
Active ngrok client sessions in region 'us':
  - 414c40ed9afc1756ffa78f2d32fc3617 (155.56.44.134:63846)

**Comment by joelbernstein** [comment]
Why is this closed? There's still no way to kill a tunnel registered on a reserved subdomain. Please, ffs, don't close tickets with genuine unfixed issues in! People have been complaining about this for SIX YEARS. We pay for the Ngrok service. This isn't good enough. The suggested "fix" of resetting the authtoken does nothing.

**Comment by joelbernstein** [comment]
> no longer an issue in the hosted service

Literally still an issue 4 years later. Still no fix?

`The tunnel [...] is already bound to another tunnel session`

Some other colleague has apparently left ngrok running, on a named tunnel instance. This blocks everybody else. How do we get it back?

**Comment by joelbernstein** [comment]
`This ngrok agent does not support remote stopping: version 2.1.18 does not support this operation. (ERR_NGROK_805)`

**Comment by Kingofhack-9** [comment]
Hello gents try this.

sudo ./ngrok http <port> 

full cmd: sudo ./ngrok http 6070

<port>-Have to mention which port you want to forward for example 8080

**Comment by joelbernstein** [comment]
Why would using sudo help? I'm not trying to bind to a low tcp port.

**Comment by Vonisoa** [comment]
I'm facing the same issue on windows. Any idea how to solve it?

**Comment by genvalen** [comment]
+1

**Comment by genvalen** [comment]
> @KharitonOff You can fix it by setting your authcode once again. When you're logged in you can find it here: https://dashboard.ngrok.com/get-started
> 
> `$ ./ngrok authtoken YOUR-TOKEN`

On a mac. I was able fix my issue by following the advice quoted above and adding another step. 

First I generated a new token on the dashboard (scroll down dashboard https://dashboard.ngrok.com/get-started and click on "reset authtoken"):
 
 Next I ran:
`$ ngrok authtoken NEW-TOKEN` 

Last, I deleted the .ngrok configuration file and directory:
`~/.ngrok2`
`rm ngrok.yml`
`rm -r .ngrok2`

**Comment by howelon** [comment]
will this ever be fixed or do I just have to make a new ngrok account now

**Comment by TigranSaharian** [comment]
Window version:
tskill /A ngrok

Unix command:
killall ngrok

**Comment by joelbernstein** [comment]
No, that's not the issue
