### ISSUE TITLE
Add CLI option to check ngrok connection status

### ISSUE THREAD

**Issue by insekt** [inconshreveable/ngrok#179]
For example
root@server# ngrok status
Connected

root@server# ngrok status
Not connected: {reason}

As for now I have to use sed/awk/grep to parse log file, though I do not need log file.

**Comment by alvaroemmanuel** [comment]
+1

I'm running ngrok as a service and every time the internet is down, the tunnel drops (it's a crappy connection, I know).

It would be so useful if I can only ask ngrok the status of the tunnel, so I can simply restart the service if it's down.

**Comment by jkburges** [comment]
+1

Related: I'd like to be able to query what the forwarding address is (from the CLI) for use as a parameter in to my app which is being developed.

e.g.:

```
$ root@server# ngrok status
Tunnel Status: online
...
Forwarding: http://abc123.ngrok.io -> localhost:4567                                                                 
Forwarding: https://abc123.ngrok.io -> localhost:4567                                                                
```

... or perhaps in a more machine-readable format such as JSON.

**Comment by inconshreveable** [comment]
Yeah, I agree this should be an endpoint on the ngrok client API https://ngrok.com/docs#client-api

**Comment by jkburges** [comment]
The client API will meet my needs - nice!  Thanks for pointing me in the right direction @inconshreveable.

**Comment by inconshreveable** [comment]
still an issue for ngrok 2.X, there's no endpoint for it yet. closing because it's a 2.x issue
