### ISSUE TITLE
make: bin/go-bindata：command not found

### ISSUE THREAD

**Issue by cleocn** [inconshreveable/ngrok#181]
Why I get this error when make:

[root@Centos7-15 ngrok]# make
go fmt ngrok/...
GOOS="" GOARCH="" go get github.com/jteeuwen/go-bindata/go-bindata
bin/go-bindata -nomemcopy -pkg=assets -tags=debug \
    -debug=true \
    -o=src/ngrok/client/assets/assets_debug.go \
    assets/client/...
make: bin/go-bindata：command not found
make: **\* [client-assets] error 127

help me .

**Comment by davidangel** [comment]
I also ran into this issue when I didn't have Go installed. Following @cleocn's solution worked.

**Comment by maojiawei** [comment]
I use the command "go get github.com/jteeuwen/go-bindata".It shows that
package bufio: unrecognized import path "bufio" (import path does not begin with hostname)

**Comment by hktalent** [comment]
> The following seems to work
> 
> go get github.com/jteeuwen/go-bindata
> cd $GOPATH/src/github.com/jteeuwen/go-bindata/go-bindata
> go build
```
# to sys use
ln -s "${GOPATH}/src/github.com/jteeuwen/go-bindata/go-bindata/go-bindata" /usr/bin/go-bindata
# to cur use
mkdir bin
ln -s "${GOPATH}/src/github.com/jteeuwen/go-bindata/go-bindata/go-bindata" bin/go-bindata

ln -s /usr/bin/go-bindata bin/go-bindata
cd -
make
```
> copy go-bindata into any directory on your PATH
