### ISSUE TITLE
Service Error's out before I can input path specifications

### ISSUE THREAD

**Issue by aliyarobinson** [inconshreveable/ngrok#184]
Hi, 
So, as soon as I run ngrok I get the following error and am unable to type anything into the terminal:

   /Users/MYNAME/ngrok ; exit;

   MYNAME: /Users/MYNAME
   ->/Users/MYNAME/ngrok ; exit;
   Error: Specify a local port to tunnel to, or an ngrok command.

   Example: To expose port 80, run 'ngrok 80'
   logout

   [Process completed]

How can I fix this?

Thanks!

-Aliya

**Comment by Hamorim85** [comment]
How do you change the port argument to ngrok?
