### ISSUE TITLE
Accept multiple http users in single tunnel

### ISSUE THREAD

**Issue by JLuc** [inconshreveable/ngrok#185]
Enhancement : Allow to have multiple http users in single tunnel

As for now 
<pre>ngrok -httpauth "loone:passone" -httpauth "lotwo:passtwo" 80</pre>
only enables 'lotwo' auth.
'loone' is ignored.

Accept this syntax to create both loone and lotwo users. 
Or accept another syntax that enables it.
Or document it if it exists.

**Comment by JLuc** [comment]
How is it as with version 2 ?

**Comment by inconshreveable** [comment]
not supported in 2.x and no plans to add support. more advanced auth cases can be handled by applications or may happen via SSO
