### ISSUE TITLE
How to run on a proxy connection?

### ISSUE THREAD

**Issue by federomano** [inconshreveable/ngrok#186]
Hi, im not a programmer, so i've read this line in the Docs:
> The ngrok configuration file is loaded by default from ~/.ngrok

So im in OSX, and i've created a file in my Home directory with just this:
`http_proxy: "http://myCompanyProxy:3333"`

But ngrok still holds on "connecting".
What can be happening?
Thanks

**Comment by inconshreveable** [comment]
Awesome, glad you got it working! You're absolutely right that the documentation could be more clear. I'll add that to my todo list for docs improvements. Thanks!
