### ISSUE TITLE
How to ngrok for mydomain.com?

### ISSUE THREAD

**Issue by cnluzhang** [inconshreveable/ngrok#188]
I want create a local ngrok server, and it's has a help page, so the architecture is:
mydomain.com/www.mydomain.com -> nginx (website)
*.mydomain.com -> ngrokd (for tunnel service)
So I run ngrok client in local server and create a tunnel from nginx (8080) to www.mydomain.com(80).
(for the "www" subdomain to my help website)

But when I enter mydomain.com (without subdomain), it says "Tunnel mydomain.com not found", how to set it?

That is to say, how to point www.mydomain/mydomain.com to my nginx service?

Thanks.

**Comment by inconshreveable** [comment]
You're looking for a a way to rewrite the host name, which is issue #132 

Please reopen if I'm misunderstanding you

**Comment by cnluzhang** [comment]
In fact, my question is not about ngrok client settings.
I have a ngrok server to provide tunnel serivces for my team, I want to create a website to show how ngrok works and the steps to config their ngrok client for my own ngrok server.
So there are two server program listen 80 and 443, the one is ngrokd, the other one is nginx (for my website), I want to:
1. when people visit www.mydomain.com or mydomain.com, they can visit my website to learn ngrok.
2. when people use ngrok client, they can obtain sub.mydomain.com as their ngrok subdomain tunnel.

But the question is when I run ngrokd program first, I can't set my nginx listen 80/443, so I set nginx listen

**Comment by cnluzhang** [comment]
But the question is when I run ngrokd program first, I can't set my nginx listen 80/443, so I set nginx listen 8080, and run a ngrok client to proxy 8080 to 80 and set subdomain to www, so people can visit www.mydomain.com to visit my nginx website.

1. the solution is so tricky...
2. people can't visit mydomain.com (without www as subdomain), they will receive "Tunnel mydomain.com not found"

**Comment by inconshreveable** [comment]
Ah, this is outside the scope of the ngrok open source project. ngrok.com accomplishes this by listening on two different IP addresses.
