### ISSUE TITLE
How can I run ngrok on tomato?

### ISSUE THREAD

**Issue by ffplayer** [inconshreveable/ngrok#191]
I have try to run the linux/arm version on my router with tomato fireware.
But only
root@unknown:/tmp/home/root# ngrok 80
/home/root/ngrok: line 1: syntax error: unexpected "("

what can I do?

Look forward for answer~~~

**Comment by inconshreveable** [comment]
Try compiling from source for linux/arm. It's likely that the linux/arm build targets a different ARM version than your tomato router
