### ISSUE TITLE
server_addr

### ISSUE THREAD

**Issue by pkpowell** [inconshreveable/ngrok#193]
Hey guys
I have ngrok set up to use my own domain with "server_addr: fqdn:4443" in ".ngrok" and it works flawlessly.
Today I discovered that all my tcp connections are also available via the ngrok.com domain, i.e. both "ssh fqdn -l phil -p 50000" and "ssh ngrok.com -l phil -p 50000" point to the same address! 
I checked the "auth_token:" line in ".ngrok" but it has been deleted/commented out, which should prevent your ngrokd from handing out custom ports, right?). As far as I can tell http is not affected.
Is this by design? Should I have disabled/added something before compiling?
Cheers
Phil

**Comment by inconshreveable** [comment]
This sounds very wrong unless you have a CNAME from fqdn -> ngrok.com, which is the only way it makes sense. Otherwise, I'd be very curious to see a repro.

**Comment by pkpowell** [comment]
Hey Alan

My words exactly!
I checked my DNS subdomains but found nothing weird.

But it turns out I can use any domain!

>  ssh -p 52022 ard@ngrok.com
Warning: Permanently added '[ngrok.com]:52022,[173.255.204.192]:52022' 
(RSA) to the list of known hosts.

>  ssh -p 52022 ard@blabla.org
Warning: Permanently added '[blabla.org]:52022,[148.251.76.34]:52022' 
(RSA) to the list of known hosts.

>  ssh -p 52022 ard@sesamestreet.com
Warning: Permanently added 
'[sesamestreet.com]:52022,[162.242.179.26]:52022' (RSA) to the list of 
known hosts.

and it connects!

Which is probably due to my router sendingports 40000-60000 to my ngrokd 
server. Does that make sense? It only does this from home - I could have 
sworn I tested it from work...
I guess ssh doesn't/can't check if it's really connecting to the domain 
it says it is, which is a bit strange. Maybe i should check my ssh 
settings. Any idea where to start?

Sorry for barking up the wrong tree and thanks for ngrok (which is awesome!)

Cheers
Phil

**Comment by inconshreveable** [comment]
Whew! For a while there I was no longer certain I understood how the internet worked. You might want to see if there's a way to tell your router to only forward those ports when the traffic is received from the WAN.

I'm not familiar enough with the SSH security model to know if there's a way to add more strict checking of the hostname a la TLS. From a quick browsing of http://www.ietf.org/rfc/rfc4252.txt it doesn't look like that's possible.

**Comment by pkpowell** [comment]
Yes, I'll have a look at what's going on in my router. I think originally 
there was a reason for forwarding the ports on the inside.
I had a look at ssh_config and sshd_config but it all looks fairly standard.

The ngrok logs contain a few messages like this:

"Error while updating ngrok: crypto/rsa: verification error"

are these normal? Superficially everything's working fine.
