### ISSUE TITLE
src/gopkg.in/yaml.v1/encode.go:188: undefined: strings.IndexByte

### ISSUE THREAD

**Issue by unnikked** [inconshreveable/ngrok#197]
I'm trying to compile the client but I get this error: 

```bash
make release-client release-server
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
		-debug=false \
		-o=src/ngrok/client/assets/assets_release.go \
		assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
		-debug=false \
		-o=src/ngrok/server/assets/assets_release.go \
		assets/server/...
go get -tags 'release' -d -v ngrok/...
go install -tags 'release' ngrok/main/ngrok
# gopkg.in/yaml.v1
src/gopkg.in/yaml.v1/encode.go:188: undefined: strings.IndexByte
make: *** [client] Error 2
```

For generating Self-Signed cert I followed this [gist](https://gist.github.com/lyoshenka/002b7fbd801d0fd21f2f)

I'm on a Ubuntu 12.04, thank you for any input.

**Comment by unnikked** [comment]
I managed to solve it by compiling the source code on my Laptop instead of directly on my VPS. 

Strange behavior by the way.

**Comment by inconshreveable** [comment]
I'm guessing that your VPS is using an older version of Go which doesn't support the API strings.IndexByte. We might have to update the README with the minimum required version of Go needed to compile.
