### ISSUE TITLE
tunnel status reconnecting

### ISSUE THREAD

**Issue by PencilSoft** [inconshreveable/ngrok#199]
i use ngrok so many times and when i try to make a tannel this red line is out to my 
Tunnel status reconnecting
Please help

**Comment by inconshreveable** [comment]
Please direct questions which are about the ngrok.com service to me via email. Please send as many details about what you were trying to do and the result you observed (what your configuration file is, what command line options you used, details about the network you're running on, whether it worked before and is no longer working, etc)

Thanks!

**Comment by PencilSoft** [comment]
thanks For relpay for my issues 
The problem with the network of my university 
when i go back to my home my apps using ngrok tunnel working well 
So the problem with the network of the university :-1:  Do NOT allow the connection 
I do not know why that !!!
But its work well in home and other networks 
thanks again
