### ISSUE TITLE
Multi-part upload crashing ngrok

### ISSUE THREAD

**Issue by janajri** [inconshreveable/ngrok#200]
I've been attempting to debug a multi-part upload bug on my nodejs server but continue to accidentally crash my ngrok proxy every time I send the multipart request. I was able to run it with the log flag. Here is stack trace output:

Also, I was able to reproduce this using POSTMAN as a REST client as well as a nodejs script using the requestjs library.

Please let me know if there's anything else I can provide.

[01/21/15 10:51:08] [INFO] [client] Tunnel established at http://inbox.ngrok.com
[01/21/15 10:51:08] [DEBG] [ctl:54bb452c] Waiting to read message
[01/21/15 10:51:08] [DEBG] [ctl:54bb452c] Reading message with length: 121
[01/21/15 10:51:08] [DEBG] [ctl:54bb452c] Read message {"Type":"NewTunnel","Payload":{"ReqId":"f1d72968b2a9ff3d","Url":"https://inbox.ngrok.com","Protocol":"https","Error":""}}
[01/21/15 10:51:08] [INFO] [client] Tunnel established at https://inbox.ngrok.com
[01/21/15 10:51:08] [DEBG] [ctl:54bb452c] Waiting to read message
[01/21/15 10:51:08] [INFO] No update available
[01/21/15 10:51:08] [DEBG] [pxy:18eafdb] Waiting to read message
[01/21/15 10:51:28] [DEBG] [ctl:54bb452c] Writing message: {"Type":"Ping","Payload":{}}
[01/21/15 10:51:28] [DEBG] [ctl:54bb452c] Reading message with length: 28
[01/21/15 10:51:28] [DEBG] [ctl:54bb452c] Read message {"Type":"Pong","Payload":{}}
[01/21/15 10:51:28] [DEBG] [ctl:54bb452c] Waiting to read message
[01/21/15 10:51:29] [DEBG] [pxy:18eafdb] Reading message with length: 95
[01/21/15 10:51:29] [DEBG] [pxy:18eafdb] Read message {"Type":"StartProxy","Payload":{"Url":"https://inbox.ngrok.com","ClientAddr":"67.243.184.236"}}
[01/21/15 10:51:29] [DEBG] [ctl:54bb452c] Reading message with length: 32
[01/21/15 10:51:29] [DEBG] [prv:6b822aa0] New connection to: 127.0.0.1:9090
[01/21/15 10:51:29] [INFO] [prv:6b822aa0] Joined with connection pxy:18eafdb
[01/21/15 10:51:29] [DEBG] [ctl:54bb452c] Read message {"Type":"ReqProxy","Payload":{}}
[01/21/15 10:51:29] [DEBG] [ctl:54bb452c] Waiting to read message
[01/21/15 10:51:29] [DEBG] [pxy:6596f7d6] New connection to: 96.126.125.171:443
[01/21/15 10:51:29] [DEBG] [pxy:6596f7d6] Writing message: {"Type":"RegProxy","Payload":{"ClientId":"0a52b3c51f6e6d9b293294fb3a75e6df"}}
[01/21/15 10:51:29] [DEBG] [pxy:6596f7d6] Waiting to read message
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x20 pc=0x15c521]

goroutine 21 [running]:
runtime.panic(0x3821a0, 0x868bd9)
	/Users/aes/src/gonative/go/src/pkg/runtime/panic.c:266 +0xb6
bytes.(*Buffer).ReadFrom(0xc2101043f0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/bytes/buffer.go:169 +0x1f1
ngrok/proto.extractBody(0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:57 +0x60
ngrok/proto.(*Http).readRequests(0xc21003c540, 0xc21032e730, 0xc2101c9d20, 0x38ade0, 0xc21030b5c0)
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:96 +0x2f8
created by ngrok/proto.(*Http).WrapConn
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:66 +0x98

goroutine 1 [select]:
ngrok/client.(*Controller).Run(0xc21004fa80, 0xc210049380)
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:194 +0xa57
ngrok/client.Main()
	/Users/aes/src/ngrok/src/ngrok/client/main.go:51 +0x258
main.main()
	/Users/aes/src/ngrok/src/ngrok/main/ngrok/ngrok.go:8 +0x1a

goroutine 3 [chan receive]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc210070000, 0xb11140, 0xc210000008)
	/Users/aes/src/ngrok/src/code.google.com/p/log4go/termlog.go:27 +0x60
created by code.google.com/p/log4go.NewConsoleLogWriter
	/Users/aes/src/ngrok/src/code.google.com/p/log4go/termlog.go:19 +0x67

goroutine 5 [syscall]:
os/signal.loop()
	/Users/aes/src/gonative/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
	/Users/aes/src/gonative/go/src/pkg/os/signal/signal_unix.go:27 +0x31

goroutine 6 [runnable]:
code.google.com/p/log4go.ConsoleLogWriter.run(0xc210070420, 0xb11140, 0xc210000008)
	/Users/aes/src/ngrok/src/code.google.com/p/log4go/termlog.go:27 +0x60
created by code.google.com/p/log4go.NewConsoleLogWriter
	/Users/aes/src/ngrok/src/code.google.com/p/log4go/termlog.go:19 +0x67

goroutine 7 [syscall]:
runtime.goexit()
	/Users/aes/src/gonative/go/src/pkg/runtime/proc.c:1394

goroutine 8 [select]:
ngrok/util.func·001()
	/Users/aes/src/ngrok/src/ngrok/util/broadcast.go:20 +0x3ed
created by ngrok/util.NewBroadcast
	/Users/aes/src/ngrok/src/ngrok/util/broadcast.go:42 +0x129

goroutine 9 [select]:
ngrok/util.func·001()
	/Users/aes/src/ngrok/src/ngrok/util/broadcast.go:20 +0x3ed
created by ngrok/util.NewBroadcast
	/Users/aes/src/ngrok/src/ngrok/util/broadcast.go:42 +0x129

goroutine 10 [chan receive]:
github.com/rcrowley/go-metrics.(*meterArbiter).tick(0x86fb40)
	/Users/aes/src/ngrok/src/github.com/rcrowley/go-metrics/meter.go:221 +0x4e
created by github.com/rcrowley/go-metrics.NewMeter
	/Users/aes/src/ngrok/src/github.com/rcrowley/go-metrics/meter.go:40 +0x1a1

goroutine 11 [select]:
ngrok/util.func·001()
	/Users/aes/src/ngrok/src/ngrok/util/broadcast.go:20 +0x3ed
created by ngrok/util.NewBroadcast
	/Users/aes/src/ngrok/src/ngrok/util/broadcast.go:42 +0x129

goroutine 12 [IO wait]:
net.runtime_pollWait(0xb12f30, 0x72, 0x0)
	/Users/aes/src/gonative/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210049ca0, 0x72, 0xb110c0, 0x23)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210049ca0, 0x23, 0xb110c0)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).accept(0xc210049c40, 0x4c7ca8, 0x0, 0xb110c0, 0x23)
	/Users/aes/src/gonative/go/src/pkg/net/fd_unix.go:382 +0x2c2
net.(*TCPListener).AcceptTCP(0xc210000740, 0x18, 0xc210096838, 0x1dc143)
	/Users/aes/src/gonative/go/src/pkg/net/tcpsock_posix.go:233 +0x47
net.(*TCPListener).Accept(0xc210000740, 0xb11f10, 0xc2100b9db0, 0x0, 0x0)
	/Users/aes/src/gonative/go/src/pkg/net/tcpsock_posix.go:243 +0x27
net/http.(*Server).Serve(0xc2100f32d0, 0xb11f68, 0xc210000740, 0x0, 0x0)
	/Users/aes/src/gonative/go/src/pkg/net/http/server.go:1622 +0x91
net/http.(*Server).ListenAndServe(0xc2100f32d0, 0xc2100f32d0, 0x2800000000)
	/Users/aes/src/gonative/go/src/pkg/net/http/server.go:1612 +0xa0
net/http.ListenAndServe(0xc21001ea10, 0xe, 0x0, 0x0, 0x2fc20, ...)
	/Users/aes/src/gonative/go/src/pkg/net/http/server.go:1677 +0x6d
ngrok/client/views/web.func·009()
	/Users/aes/src/ngrok/src/ngrok/client/views/web/view.go:69 +0x39
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

goroutine 13 [chan receive]:
ngrok/client/views/web.(*WebHttpView).updateHttp(0xc2100f3280)
	/Users/aes/src/ngrok/src/ngrok/client/views/web/http.go:149 +0xab
ngrok/client/views/web.*WebHttpView.(ngrok/client/views/web.updateHttp)·fm()
	/Users/aes/src/ngrok/src/ngrok/client/views/web/http.go:87 +0x26
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

goroutine 14 [sleep]:
time.Sleep(0x13a52453c000)
	/Users/aes/src/gonative/go/src/pkg/runtime/time.goc:31 +0x31
ngrok/client.autoUpdate(0xb11e00, 0xc210058d00, 0xc2100486a0, 0x14)
	/Users/aes/src/ngrok/src/ngrok/client/update_release.go:82 +0x25d
ngrok/client.func·006()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:186 +0x4a
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

goroutine 15 [IO wait]:
net.runtime_pollWait(0xb12e88, 0x72, 0x0)
	/Users/aes/src/gonative/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc210049e60, 0x72, 0xb110c0, 0x23)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc210049e60, 0x23, 0xb110c0)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210049e00, 0xc210109000, 0x1000, 0x1000, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210000818, 0xc210109000, 0x1000, 0x1000, 0x9d8748, ...)
	/Users/aes/src/gonative/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc210102570, 0xb13310, 0xc210000818, 0x5, 0xc210000818, ...)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc210050a00, 0x17, 0x0, 0xddd01)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc210050a00, 0xc210334a48, 0x8, 0x8, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:897 +0x135
ngrok/conn.(*loggedConn).Read(0xc21003c8c0, 0xc210334a48, 0x8, 0x8, 0x8, ...)
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:1 +0x69
io.ReadAtLeast(0xb13720, 0xc21003c8c0, 0xc210334a48, 0x8, 0x8, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:288 +0xf6
io.ReadFull(0xb13720, 0xc21003c8c0, 0xc210334a48, 0x8, 0x8, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:306 +0x71
encoding/binary.Read(0xb13720, 0xc21003c8c0, 0xb11588, 0xc21003c8c0, 0x2c6500, ...)
	/Users/aes/src/gonative/go/src/pkg/encoding/binary/binary.go:146 +0x103
ngrok/msg.readMsgShared(0xb13098, 0xc21003c8c0, 0x0, 0x0, 0x0, ...)
	/Users/aes/src/ngrok/src/ngrok/msg/conn.go:14 +0x15f
ngrok/msg.ReadMsg(0xb13098, 0xc21003c8c0, 0x0, 0x0, 0x0, ...)
	/Users/aes/src/ngrok/src/ngrok/msg/conn.go:37 +0x55
ngrok/client.(*ClientModel).control(0xc210058d00)
	/Users/aes/src/ngrok/src/ngrok/client/model.go:289 +0xb65
ngrok/client.(*ClientModel).Run(0xc210058d00)
	/Users/aes/src/ngrok/src/ngrok/client/model.go:179 +0x3f
ngrok/client/mvc.Model.Run·fm()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:187 +0x2e
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

goroutine 17 [select]:
ngrok/client.(*ClientModel).heartbeat(0xc210058d00, 0xc2102abe60, 0xb13098, 0xc21003c8c0)
	/Users/aes/src/ngrok/src/ngrok/client/model.go:410 +0x670
ngrok/client.func·010()
	/Users/aes/src/ngrok/src/ngrok/client/model.go:284 +0x40
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

goroutine 18 [semacquire]:
sync.runtime_Semacquire(0xc2103349c8)
	/Users/aes/src/gonative/go/src/pkg/runtime/sema.goc:199 +0x30
sync.(*WaitGroup).Wait(0xc21031bf20)
	/Users/aes/src/gonative/go/src/pkg/sync/waitgroup.go:127 +0x14b
ngrok/conn.Join(0xb21550, 0xc21032e730, 0xb13098, 0xc210337340, 0xc21030b5c0, ...)
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:217 +0x22f
ngrok/client.func·011()
	/Users/aes/src/ngrok/src/ngrok/client/model.go:388 +0x16e
github.com/rcrowley/go-metrics.(*StandardTimer).Time(0xc2100b97e0, 0xc210308f30)
	/Users/aes/src/ngrok/src/github.com/rcrowley/go-metrics/timer.go:203 +0x45
ngrok/client.(*ClientModel).proxy(0xc210058d00)
	/Users/aes/src/ngrok/src/ngrok/client/model.go:393 +0xbfc
ngrok/client.*ClientModel.(ngrok/client.proxy)·fm()
	/Users/aes/src/ngrok/src/ngrok/client/model.go:295 +0x26
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

goroutine 19 [IO wait]:
net.runtime_pollWait(0xb12de0, 0x72, 0x0)
	/Users/aes/src/gonative/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2101041b0, 0x72, 0xb110c0, 0x23)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2101041b0, 0x23, 0xb110c0)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210104150, 0xc210114c00, 0x400, 0x400, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210110688, 0xc210114c00, 0x400, 0x400, 0x20cda, ...)
	/Users/aes/src/gonative/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc210119b40, 0xb13310, 0xc210110688, 0x5, 0xc210110688, ...)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc210050c80, 0x17, 0x0, 0x8)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc210050c80, 0xc2102d0000, 0x1000, 0x1000, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:897 +0x135
bufio.(*Reader).fill(0xc21027ce40)
	/Users/aes/src/gonative/go/src/pkg/bufio/bufio.go:91 +0x110
bufio.(*Reader).Peek(0xc21027ce40, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/bufio/bufio.go:119 +0xcb
net/http.(*persistConn).readLoop(0xc210057f00)
	/Users/aes/src/gonative/go/src/pkg/net/http/transport.go:687 +0xb7
created by net/http.(*Transport).dialConn
	/Users/aes/src/gonative/go/src/pkg/net/http/transport.go:528 +0x607

goroutine 20 [select]:
net/http.(*persistConn).writeLoop(0xc210057f00)
	/Users/aes/src/gonative/go/src/pkg/net/http/transport.go:791 +0x271
created by net/http.(*Transport).dialConn
	/Users/aes/src/gonative/go/src/pkg/net/http/transport.go:529 +0x61e

goroutine 22 [runnable]:
ngrok/proto.(*Http).readResponses(0xc21003c540, 0xc21032e730, 0xc2101c9d20)
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:104 +0x67
created by ngrok/proto.(*Http).WrapConn
	/Users/aes/src/ngrok/src/ngrok/proto/http.go:67 +0xc3

goroutine 24 [semacquire]:
sync.runtime_Syncsemacquire(0xc210343af8)
	/Users/aes/src/gonative/go/src/pkg/runtime/sema.goc:257 +0xca
sync.(*Cond).Wait(0xc210343ae8)
	/Users/aes/src/gonative/go/src/pkg/sync/cond.go:62 +0x89
io.(*pipe).write(0xc210343a80, 0xc2103ae000, 0xa6, 0x8000, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/io/pipe.go:94 +0x1fe
io.(*PipeWriter).Write(0xc2103349a0, 0xc2103ae000, 0xa6, 0x8000, 0xa6, ...)
	/Users/aes/src/gonative/go/src/pkg/io/pipe.go:161 +0x5f
io.(*teeReader).Read(0xc21031bec0, 0xc2103ae000, 0x8000, 0x8000, 0xa6, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:487 +0xd3
ngrok/conn.(*Tee).Read(0xc21032e730, 0xc2103ae000, 0x8000, 0x8000, 0x8000, ...)
	/Users/aes/src/ngrok/src/ngrok/conn/tee.go:62 +0x64
io.Copy(0xb132e8, 0xc210337340, 0xb216c0, 0xc21032e730, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:352 +0x1c8
ngrok/conn.func·002(0xb13098, 0xc210337340, 0xb21550, 0xc21032e730, 0xc2103349c0)
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:204 +0x142
created by ngrok/conn.Join
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:215 +0x131

goroutine 25 [IO wait]:
net.runtime_pollWait(0xb12be8, 0x72, 0x0)
	/Users/aes/src/gonative/go/src/pkg/runtime/netpoll.goc:116 +0x6a
net.(*pollDesc).Wait(0xc2102163e0, 0x72, 0xb110c0, 0x23)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:81 +0x34
net.(*pollDesc).WaitRead(0xc2102163e0, 0x23, 0xb110c0)
	/Users/aes/src/gonative/go/src/pkg/net/fd_poll_runtime.go:86 +0x30
net.(*netFD).Read(0xc210216380, 0xc2101e8000, 0x1000, 0x1000, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/net/fd_unix.go:204 +0x2a0
net.(*conn).Read(0xc210334a98, 0xc2101e8000, 0x1000, 0x1000, 0xde78e0, ...)
	/Users/aes/src/gonative/go/src/pkg/net/net.go:122 +0xc5
crypto/tls.(*block).readFromUntil(0xc2102b7420, 0xb13310, 0xc210334a98, 0x5, 0xc210334a98, ...)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:459 +0xb6
crypto/tls.(*Conn).readRecord(0xc210357a00, 0x17, 0x0, 0x1af1b)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:539 +0x107
crypto/tls.(*Conn).Read(0xc210357a00, 0xc21031a790, 0x8, 0x8, 0x0, ...)
	/Users/aes/src/gonative/go/src/pkg/crypto/tls/conn.go:897 +0x135
ngrok/conn.(*loggedConn).Read(0xc21030b800, 0xc21031a790, 0x8, 0x8, 0x8, ...)
	/Users/aes/src/ngrok/src/ngrok/conn/conn.go:1 +0x69
io.ReadAtLeast(0xb13720, 0xc21030b800, 0xc21031a790, 0x8, 0x8, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:288 +0xf6
io.ReadFull(0xb13720, 0xc21030b800, 0xc21031a790, 0x8, 0x8, ...)
	/Users/aes/src/gonative/go/src/pkg/io/io.go:306 +0x71
encoding/binary.Read(0xb13720, 0xc21030b800, 0xb11588, 0xc21030b800, 0x2c6500, ...)
	/Users/aes/src/gonative/go/src/pkg/encoding/binary/binary.go:146 +0x103
ngrok/msg.readMsgShared(0xb13098, 0xc21030b800, 0x0, 0x0, 0x0, ...)
	/Users/aes/src/ngrok/src/ngrok/msg/conn.go:14 +0x15f
ngrok/msg.ReadMsgInto(0xb13098, 0xc21030b800, 0x2c7c00, 0xc210300fa0, 0x0, ...)
	/Users/aes/src/ngrok/src/ngrok/msg/conn.go:46 +0x43
ngrok/client.(*ClientModel).proxy(0xc210058d00)
	/Users/aes/src/ngrok/src/ngrok/client/model.go:352 +0x383
ngrok/client.*ClientModel.(ngrok/client.proxy)·fm()
	/Users/aes/src/ngrok/src/ngrok/client/model.go:295 +0x26
ngrok/client.func·003()
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:96 +0x63
created by ngrok/client.(*Controller).Go
	/Users/aes/src/ngrok/src/ngrok/client/controller.go:97 +0x8b

**Comment by kageurufu** [comment]
Same error, log here: https://gist.github.com/db1a86c6c45f5710b344

**Comment by inconshreveable** [comment]
looks like a legit bug. definitely fixed in 2.x, but will leave it open here
