### ISSUE TITLE
IE11 SCRIPT12030: WebSocket Error: Network Error 12030

### ISSUE THREAD

**Issue by zhangwen9229** [inconshreveable/ngrok#202]
Using ngrok, When I Visit my test site，SocketIOJs(Client) report this error:SCRIPT12030: WebSocket Error: Network Error 12030.  The browser is  IE11,but Chrome is OK.
Then turn to long-polling , also can not work.

**Comment by inconshreveable** [comment]
Interesting, this warrants a closer look. It wouldn't surprise me if we were doing something that makes IE upset

**Comment by zhangwen9229** [comment]
Oh,I see,thank you.

**Comment by zomgbre** [comment]
I also have a similar issue.  I'm trying to tunnel through ngrok https to an http node.js app using socket.io. Originally it was over https, but ngrok did not like that...

**Comment by zhangwen9229** [comment]
Because it is not compatible with IE11.

**Comment by zomgbre** [comment]
Okay, thank you! I did not know.

**Comment by zhangwen9229** [comment]
My pleasure
