### ISSUE TITLE
Server failed to allocate tunnel: The tunnel {tunnel} is already registered.

### ISSUE THREAD

**Issue by cballou** [inconshreveable/ngrok#203]
I started receiving this message today via the command:

```bash
./ngrok start local.example.co 
Server failed to allocate tunnel: The tunnel http://local.example.co is already registered.
```

Not sure how to resolve. I haven't modified my `~/.ngrok` config file and it used to work swimmingly. I did a `ps aux | grep ngrok` and found nothing. I'm a paid user so I'm using a live subdomain.

**Comment by inconshreveable** [comment]
give it another try, there was a small hiccup

**Comment by ashramsey** [comment]
Started getting this this morning. Cant get it working. Help please :-)

**Comment by gunaseln** [comment]
same here - any help is appreciated.

**Comment by ashramsey** [comment]
Seemed to resolve itself after 30min of trying.

**Comment by inconshreveable** [comment]
This should be resolved now, apologies for the problems.

**Comment by gunaseln** [comment]
Thanks for the quick turnaround - totally appreciate it!
