### ISSUE TITLE
Missing informations

### ISSUE THREAD

**Issue by Martindelataille** [inconshreveable/ngrok#206]
When i run `ngrok 80`. Ngrok is launching but i have no information about requests or generated url.
I must do `ngrok -log stdout 80`.

Started using it since 4 month and had no problem before.

It is running on vagrant vm.

**Comment by inconshreveable** [comment]
That's odd. Has anything changed? You're using the same version and same launch command? It doesn't display a terminal UI? Are you running it in the foreground?
