### ISSUE TITLE
vnc over ngrok

### ISSUE THREAD

**Issue by shuntera** [inconshreveable/ngrok#207]
When I set up ngrok to open port 5900, or 5901 I get a URL that does not have a port number attached to it.

Most of the VNC clients I have expect there to be a port number after the URL, and some of them will default to adding port 5900 if you do not add one yourself.

Consequently I can't use ngrok to point to my VNC server. Anyone know of a way round that?

**Comment by inconshreveable** [comment]
Are you invoking ngrok asking for a TCP tunnel? (`ngrok -proto=tcp 5901`)

**Comment by Aldo-f** [comment]
Great, this is now a paid feature...

![image](https://user-images.githubusercontent.com/5683799/32097740-cbf92c5a-bb0a-11e7-911f-0859ea46f33a.png)
