### ISSUE TITLE
# Conn listed in ms

### ISSUE THREAD

**Issue by ChandlerSwift** [inconshreveable/ngrok#210]
On the Linux CLI, the number of connections is listed in milliseconds, and isn't (as far as I can tell) consistent - Sometimes a new connection will increment the number by one or ten, sometimes by a hundred, or even a few hundred per listed connection. Also, the "Avg Conn Time" occasionally pops up an extra s (shown below).
![error](https://cloud.githubusercontent.com/assets/8261698/6342953/456ba930-bba6-11e4-98fb-1f98ad6faa0c.PNG)
I also attached my config file, since with some previous configurations it has worked fine. 
![ngrok config](https://cloud.githubusercontent.com/assets/8261698/6342954/456c2acc-bba6-11e4-87a3-afc275c67305.PNG)

**Comment by inconshreveable** [comment]
Looks like a bug with how the UI works with many open tunnels. Leaving this one open.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
