### ISSUE TITLE
Wrong headers passed to localhost

### ISSUE THREAD

**Issue by pjc** [inconshreveable/ngrok#211]
On http://localhost:4040/http/in Ngrok shows the expected headers for a Shopify webhook call:

```
Accept  ["*/*"]
Accept-Encoding ["gzip;q=1.0,deflate;q=0.6,identity;q=0.3"]
Connection  ["close"]
Content-Length  ["925"]
Content-Type    ["application/json"]
User-Agent  ["Ruby"]
X-Forwarded-Proto   ["https"]
X-Newrelic-Id   ["VQQUUFNS"]
X-Newrelic-Transaction  ["PxQHWFQGAQAHVldbAVAFVFwIFB8EBw8RVU4aUgEKUQsAUgtXCFdSUFYODkNKQQsHBVdZUQAHFTs="]
X-Real-Ip   ["204.93.213.120"]
X-Shopify-Hmac-Sha256   ["0Cmazxv8kRZFuG+w2oW/eWmMLGZzbzkrU5aS7aUSi74="]
X-Shopify-Product-Id    ["432744632"]
X-Shopify-Shop-Domain   ["5webhooks.myshopify.com"]
X-Shopify-Topic ["products/create"]
```

However, when trying to access the headers in the corresponding controller:

```
(byebug) headers
{"X-Frame-Options"=>"SAMEORIGIN", "X-XSS-Protection"=>"1; mode=block", "X-Content-Type-Options"=>"nosniff"}
(byebug) headers["X-Shopify-Shop-Domain"]
nil
```

How do I access to the header value for "X-Shopify-Shop-Domain" ?

**Comment by cballou** [comment]
I'm also noticing similar issues dealing with CSRF tokens and the header `X-CSRF-Token` not being passed. I can see the outbound headers being set correctly via AJAX:

```
Accept:application/json, text/plain, */*
Accept-Encoding:gzip, deflate, sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Cookie:[omitted]
Host:[omitted]
Pragma:no-cache
Referer:[omitted]
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
X-CSRF-Token:[omitted]
```

Couldn't ngrok simply forward these custom headers on?

**Comment by inconshreveable** [comment]
could still be a bug, possibly not. may be it was just an issue with the ngrok.com hosted service. leaving this open.

**Comment by AnishShah** [comment]
I'm facing this same issue while working with GitHub webhooks. Any idea how to solve this?

**Comment by inconshreveable** [comment]
@AnishShah if you're dealing with 2.0, please send me an email. if you're talking about 1.X, it's hard to say without further investigation into this bug

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
