### ISSUE TITLE
Self-hosting ngrok with signed SSL cert

### ISSUE THREAD

**Issue by Frostman** [inconshreveable/ngrok#212]
Hi,

I have a wildcard SSL cert and I've like to setup self-hosted ngrok. Is there any instruction on doing it? I've only find instruction of how to setup self-hosted ngrok with self-signed SSL cert.

Thanks.

**Comment by ChandlerSwift** [comment]
Will this do what you want? https://github.com/inconshreveable/ngrok/blob/master/docs/SELFHOSTING.md#4-run-the-server

**Comment by Frostman** [comment]
Will it mean that anyone will be able to use it? I saw some options to replace base certs for server/client to make only specific clients able to use service.

**Comment by inconshreveable** [comment]
Using a wildcard cert should work the same way as using a normal cert. As opposed to a self-signed cert, you'd want to tell ngrok to trust the host root certificates (or find your CA's root certificate and recompile ngrok with that as the trusted root).

With regard to restricting access, you'd need TLS client authentication or some other authentication mechanism (like ngrok.com's authtokens).

**Comment by damtur** [comment]
Hey there,

I have question about *.host.com certificate. Why when I issue cert on *.host.com and compile code with same certificate ngrok client can't connect with server?
Why do I need *.host.com? Well to use https. I have been only able to set up tunnel with certificate issued on host.com. When after setting up a tunnel I type http://subdomain.host.com it works fine, but when I go to https://subdomain.host.com It doesn't work - it complains that certificate is not issued on subdomain.host.com but on host.com.
Also why if I create CA with host.com and then create server.crt with *.host.com it also doesn't work?
Can anyone please explain me how ngrok is using both those certs (root.pem and server.key, server.crt)

Thanks
