### ISSUE TITLE
Hello there

### ISSUE THREAD

**Issue by sonvirgo** [inconshreveable/ngrok#213]
My problem it how to improve user experience with web access. by more autonomous system.
I mean each time ngrok assign a subdomain to web server, there should be an option to execute a command to push that subdomain to some " static mail box" so that web client , in my case android webview, can auto connect to the correct sub domain. Something like DDNS but the trick is ngrok will post a special request to web server so that the server know its serving subdomain and server then place a message to the ''static mail box". (Of course this will involve SSL and CA for both ngrok and web server.....). 
As of my infer, this kind of inform action seem "fairer" to the web server as until now, server is dumb with respect to its hosting and serving environment. Less but not least, another problem arise is when I am using Facebook SDK Oauth2. It require app to register the domain with Facebook. This is obvious off scope. It would be more simple with static DNS, but will it be, in the near future, a "meta data protocol" for Facebook to update app registering domain the same mechanism as the web server upon receiving this special request?
Can this expand to be an extension to Web standard, who know?
Sun
(P/s sorry I forget to mention about CGI. Now CGI feel outdated, the trend is JSON, REST, DDNS, OAuth like in-house vs out source....)

**Comment by inconshreveable** [comment]
Can you contact me via email? That seems like a more appropriate place for this kind of full-solution discussion.

**Comment by sonvirgo** [comment]
hello alan


full=solution is very simple as I wrote but it involve facebook app register






Sent from Windows Mail





From: Alan Shreve
Sent: ‎Friday‎, ‎March‎ ‎6‎, ‎2015 ‎11‎:‎45‎ ‎AM
To: inconshreveable/ngrok
Cc: Xinhoilaxinh Hanoine





Can you contact me via email? That seems like a more appropriate place for this kind of full-solution discussion.
