### ISSUE TITLE
Define a fixed TCP listen port?

### ISSUE THREAD

**Issue by wwebb** [inconshreveable/ngrok#218]
Hello,

I'm running my own ngrokd server to allow me to access a video surveillance system that's behind a firewall. The system uses a lot of bandwidth, makes a lot of requests, but ngrokd has been incredibly stable and has worked flawlessly! The surveillance system I use (a software called BlueIris) requires me to use ngrok in TCP mode.

The server on which ngrokd runs was recently rebooted, and when I re-launched ngrokd the TCP port that I was automatically (and randomly?) assigned changed, which means I have to reconfigure all the clients that login to this surveillance system. 

Is there a way that I can define a fixed TCP listen port that ngrokd will use to forward? 

I'm using a config file with the following parameters:

    server_addr: domain.com:4443
    tunnels:
      blueiris:
        proto:
          tcp:8081

ngrokd will then say `forwarding http://domain.com:36523 -> 127.0.0.1:8081`. I would love to be able to keep the `36523` part fixed. I seem to get a new random port number every time the ngrokd server instance is restarted.

Thank you!

**Comment by metadaddy-sfdc** [comment]
I believe this was fixed by #42

**Comment by wwebb** [comment]
You absolutely are correct. I must be blind because I swear I didn't see this in the documentation, but it clearly is there. I am the same way at Home Depot; I can search the store for an hour, but until I ask the clerk for assistance and they point to where I have been looking the entire time, I won't see it!

Thank you for pointing this out, metadaddy-sfdc. The remote_port function works very well. ngrok is such a powerful tool.

    server_addr: domain.com:4443
    tunnels:
      blueiris:
        remote_port: 36523
        proto:
          tcp:8081

yields

    forwarding http://domain.com:36523 -> 127.0.0.1:8081

**Comment by LolzMartiz** [comment]
but can you specify the correct command for it
