### ISSUE TITLE
Ngrok traffic capture question

### ISSUE THREAD

**Issue by diwu1989** [inconshreveable/ngrok#220]
If ngrok is capturing all the traffic going over the tunnel, wouldn't this become a memory sink eventually?
Let's say that I want to run my tunnel for weeks at a time, would the memory usage just keep going up?
How do I disable the traffic capturing?

**Comment by is** [comment]
Ngrok do not cache captured traffic self. It broadcasts requests to all active browsers through websocket.

So you only see http requests after you open the monitor page.

**Comment by inconshreveable** [comment]
@is While it's true that ngrok broadcasts requests over websocket, it does also store them internally as part of a ring buffer:

https://github.com/inconshreveable/ngrok/blob/master/src/ngrok/client/views/web/http.go#L85
