### ISSUE TITLE
ngrok.com is down

### ISSUE THREAD

**Issue by TuxujPes** [inconshreveable/ngrok#221]
Hi,
not sure where to post this.
https://ngrok.com/ is "This webpage is not available", 
GET https://ngrok.com/ net::ERR_CONNECTION_REFUSED

as a result i can not use this service :(

Could it have some location, ip, w/e restriction?

**Comment by inconshreveable** [comment]
This is likely an issue with your network as ngrok has not been down. I've had various reports that there are some corporate networks and some countries that block ngrok entirely.
