### ISSUE TITLE
failed to allocate tunnel

### ISSUE THREAD

**Issue by KreativeKoder** [inconshreveable/ngrok#225]
getting this error and don't know how to resolve it:
Server failed to allocate tunnel: The tunnel [my registered ngrok name] is already registered.

**Comment by rpc4mv** [comment]
Also receiving this error. All ngrok processes were killed on my machine as well so that was not the issue.

**Comment by inconshreveable** [comment]
Should be resolved now, I've got a long term fix for this coming shortly.
