### ISSUE TITLE
Own server with token

### ISSUE THREAD

**Issue by zoic21** [inconshreveable/ngrok#228]
Hi,

I just discover your application and it seems to be just what I need, but I don't find a feature for own server : how can I limite user access, like this? 
token1 subdomain1
token2 subdomain2

With this, can I give token to user and limit it to a specify subdomain?

Thanks in advance for your time

**Comment by inconshreveable** [comment]
Limiting user access is only a feature of the hosted ngrok service and not part of the open source project.

**Comment by zoic21** [comment]
No problem I can add this feature.
