### ISSUE TITLE
Getting an "Syntax error: Unterminated quoted string" when trying to run a client from a self-hosted server

### ISSUE THREAD

**Issue by chadbrewyet** [inconshreveable/ngrok#229]
I used the processes found at the 2 links below.

http://www.svenbit.com/2014/09/run-ngrok-on-your-own-server/ 
https://gist.github.com/lyoshenka/002b7fbd801d0fd21f2f

I also used some of the fixes in this thread:

https://github.com/inconshreveable/ngrok/issues/84

However, when I go to run the client on a machine I get this error:

"./ngrok: 1: ./ngrok: Syntax error: Unterminated quoted string"

If I use a client that I downloaded straight from github, I can connect to the main ngrok server with no problem.  I would like to be able to host my own server so that I can keep everything in-house.

The server side is running Ubuntu Server v14.10.
Clients that I've tried with are running Ubuntu Desktop 14.04.2 and Raspbian 3.18.7.  Same behavior on both.  Ultimately, I would like my solution to use the Raspberry Pi so if there are any specific instructions to follow to use the ARM processor, please include that.

**Comment by inconshreveable** [comment]
old issue, closing.

This error message is related to running a build of ngrok with the wrong OS or architecture
