### ISSUE TITLE
strings.IndexByte

### ISSUE THREAD

**Issue by nassarofficial** [inconshreveable/ngrok#230]
# gopkg.in/yaml.v1
src/gopkg.in/yaml.v1/encode.go:188: undefined: strings.IndexByte
I keep getting this error although, im on Golang 1.1

**Comment by inconshreveable** [comment]
Golang 1.1 is too old to build ngrok. You'll need at least 1.3+

**Comment by nassarofficial** [comment]
I got the same error with 1.3.3, thats why I tried again with 1.1 to follow the readme

**Comment by nassarofficial** [comment]
deleted ngrok, and downloaded again and it worked.
