### ISSUE TITLE
Is NGrok working?

### ISSUE THREAD

**Issue by mribeiro** [inconshreveable/ngrok#231]
I have ngrok 1.7 and it stays in "connecting" status forever until it goes to "reconnecting".
I tried to go to ngrok.com to update the client but cannot access the website. Browsers gets stuck.

**Comment by mribeiro** [comment]
changed title

**Comment by covard** [comment]
I am having the same issue. Same version. It was working yesterday but this morning I get the same issue

``` shell
ngrok                                                                                                                                                              

Tunnel Status                 connecting
Version                       1.7/1.7
Web Interface                 127.0.0.1:4040
# Conn                        0
Avg Conn Time                 0.00ms

**Comment by mribeiro** [comment]
The browser just gave me e a 504 BAD GATEWAY after much attempts.
I should be general, I'd say

**Comment by philtr** [comment]
It looks like the servers are down. Can't access http://ngrok.com/.

**Comment by msolomonTMG** [comment]
I am unable to start a tunnel but https://ngrok.com/ is up for me.

I tried closing my existing tunnel w/ subdomain and restarting it. I get an error about how it is already registered. I could be experiencing something similar to this: https://github.com/inconshreveable/ngrok/issues/167 or ngrok might be having issues?

**Comment by inconshreveable** [comment]
All services are operational again.

This was an outage of the website and ngrok 1.0. ngrok 2.0 tunnels were unaffected. Apologies for the downtime.

**Comment by covard** [comment]
Yay :+1: it's working again. Thanks.
