### ISSUE TITLE
ngrok 2.0 doesn't run on linux/arm (raspberry pi) 

### ISSUE THREAD

**Issue by bgulotta** [inconshreveable/ngrok#232]
Getting the following error below when i try and upgrade to ngrok 2.0 on my pies:

runtime: g1: leftover defer argp=0x1091b660 pc=0x2d837c
	defer 0x10938100 argp=0x1091b660 pc=0x2d837c
	defer 0x10938000 argp=0x1091b7c4 pc=0x6b4f8
fatal error: traceback has leftover defers

runtime stack:
runtime.gothrow(0x54d3c0, 0x1d)
	/Users/aes/src/gonative/_go/src/runtime/panic.go:503 +0x84
runtime.gentraceback(0x2d8118, 0x1091b5f4, 0x91930, 0x109000a0, 0x0, 0x0, 0x7fffffff, 0x7ef29780, 0x7ef29788, 0x0, ...)
	/Users/aes/src/gonative/_go/src/runtime/traceback.go:445 +0x6bc
copystack(0x109000a0, 0x1000)
	/Users/aes/src/gonative/_go/src/runtime/stack.c:623 +0xfc
runtime.newstack()
	/Users/aes/src/gonative/_go/src/runtime/stack.c:789 +0x444
runtime.morestack()
	/Users/aes/src/gonative/_go/src/runtime/asm_arm.s:319 +0x4c

goroutine 1 [stack growth, locked to thread]:
gopkg.in/stack%2ev1.func·001()
	/Users/aes/src/ngrok/Godeps/_workspace/src/gopkg.in/stack.v1/stack.go:193 fp=0x1091b5f4 sp=0x1091b5f4
runtime.call16(0x1094ae6c, 0x1093811c, 0x0, 0x0)
	/Users/aes/src/gonative/_go/src/runtime/asm_arm.s:406 +0x70 fp=0x1091b608 sp=0x1091b5f4
runtime.gopanic(0x4917e8, 0x1091c018)
	/Users/aes/src/gonative/_go/src/runtime/panic.go:387 +0x3b4 fp=0x1091b640 sp=0x1091b608
runtime.panicdivide()
	/Users/aes/src/gonative/_go/src/runtime/panic.go:24 +0x54 fp=0x1091b654 sp=0x1091b640
gopkg.in/stack%2ev1.func·002(0x0)
	/Users/aes/src/ngrok/Godeps/_workspace/src/gopkg.in/stack.v1/stack.go:208 +0xc4 fp=0x1091b674 sp=0x1091b654
gopkg.in/stack%2ev1.findSigpanic(0x0)
	/Users/aes/src/ngrok/Godeps/_workspace/src/gopkg.in/stack.v1/stack.go:209 +0x58 fp=0x1091b688 sp=0x1091b674
gopkg.in/stack%2ev1.init()
	/Users/aes/src/ngrok/Godeps/_workspace/src/gopkg.in/stack.v1/stack.go:213 +0x74 fp=0x1091b694 sp=0x1091b688
main.init()
	/Users/aes/src/ngrok/Godeps/_workspace/src/github.com/inconshreveable/ngrok/web_ui.go:466 +0x64 fp=0x1091b7c0 sp=0x1091b694
runtime.main()
	/Users/aes/src/gonative/_go/src/runtime/proc.go:58 +0xf8 fp=0x1091b7e4 sp=0x1091b7c0
runtime.goexit()
	/Users/aes/src/gonative/_go/src/runtime/asm_arm.s:1322 +0x4 fp=0x1091b7e4 sp=0x1091b7e4

goroutine 2 [runnable]:
runtime.forcegchelper()
	/Users/aes/src/gonative/_go/src/runtime/proc.go:90
runtime.goexit()
	/Users/aes/src/gonative/_go/src/runtime/asm_arm.s:1322 +0x4

goroutine 3 [runnable]:
runtime.bgsweep()
	/Users/aes/src/gonative/_go/src/runtime/mgc0.go:82
runtime.goexit()
	/Users/aes/src/gonative/_go/src/runtime/asm_arm.s:1322 +0x4

goroutine 4 [runnable]:
runtime.runfinq()
	/Users/aes/src/gonative/_go/src/runtime/malloc.go:712
runtime.goexit()
	/Users/aes/src/gonative/_go/src/runtime/asm_arm.s:1322 +0x4

**Comment by inconshreveable** [comment]
Yep, I'm aware of this issue and looking into it. Can you tell me which version of Raspberry Pi you're running and the OS you have installed on it?

**Comment by bgulotta** [comment]
Sure I have both a raspberry pi 1 & 2 running the standard raspbian wheezy distro

**Comment by inconshreveable** [comment]
And ngrok 2.0 gives you the same failure on each of them?

**Comment by bgulotta** [comment]
yep

**Comment by inconshreveable** [comment]
This is resolved in version 2.0.16 (available on https://ngrok.com/download)
