### ISSUE TITLE
ngrok client created a lot of TCP connections

### ISSUE THREAD

**Issue by dfc643** [inconshreveable/ngrok#234]
ngrok client created a lot of TCP connections but cannot release or close.
But, Server side, The connection has been closed.

http://postimg.org/image/5bujv8u2p/
Tcpview on client,netstat on server.

http://postimg.org/image/9wgqa6ds1/
cause huge TCP connection.

How to solve this? thanks.

**Comment by dfc643** [comment]
the first screenshots after my restart ngrok client 10 mins.
If run ngrok client 10 hours or more, 300 or more conns  may create.

**Comment by inconshreveable** [comment]
what version of ngrok is this? (run `ngrok version`)

**Comment by dfc643** [comment]
@inconshreveable
> ngrok version
> 1.7

This version. download from ngrok official website.

**Comment by dfc643** [comment]
In Linux is ok，In Windows has this issue.
I tried on 2 PCs (Windows_7) all has the issue.
I tried on Raspberry Pi is ok.

**Comment by inconshreveable** [comment]
old issue, closing. could still be a legitimate problem in ngrok 1.X on windows
