### ISSUE TITLE
Noway to start the -config file 

### ISSUE THREAD

**Issue by pippo73** [inconshreveable/ngrok#235]
Hi all, I'm trying to start ngrok with the config parameter, but there is no way to make it work :(

# /usr/local/bin/ngrok -config="/root/.ngrok2/ngrok.yml"
# /usr/local/bin/ngrok -config=/root/.ngrok2/ngrok.yml
# /usr/local/bin/ngrok -config /root/.ngrok2/ngrok.yml

I always get response 

Incorrect Usage: flag provided but not defined: -config

What I do wrong?

VERSION: 2.0.17  precompiled for linux-arm systems

**Comment by inconshreveable** [comment]
You need to provide a command ('http', 'tcp', 'tls', ...) before the config flag like so:

```shell
ngrok http -config /root/.ngrok2/ngrok.yml 80
```

**Comment by pippo73** [comment]
if I try do it, it does not read the config file. :-(

but if I run the "services --all" everything is ok..

**Comment by inconshreveable** [comment]
Run:

```sh
ngrok http -config /root/.ngrok2/ngrok.yml -log stdout -log-level debug 80
```

The log output will show where ngrok tries to read the configuration file and any errors it encounters. It's possible your configuration file is malformed or that the command you're trying to invoke with it is improper. Please email me if you have further questions, these issues should be only for the ngrok code that is open source.

**Comment by som3akamal** [comment]
i want to start multiple tunnels using ngrok .. i edit the yml file with this lines:- 
tunnels:
first-app:
	addr: 80
	proto: http
second-app:
	addr: 3000
	proto: http   
but when i run command "ngrok start --all" it says " Error reading configuration file '/root/.ngrok2/ngrok.yml': config contains tab characters, YAML must use spaces for indentation
"
what could i do to fix this??... thanx

**Comment by azamet90** [comment]
> i want to start multiple tunnels using ngrok .. i edit the yml file with this lines:-
> tunnels:
> first-app:
> addr: 80
> proto: http
> second-app:
> addr: 3000
> proto: http
> but when i run command "ngrok start --all" it says " Error reading configuration file '/root/.ngrok2/ngrok.yml': config contains tab characters, YAML must use spaces for indentation
> "
> what could i do to fix this??... thanx
> ......................................................................
> ohhh i fix it using command " ./ngrok start -all "
> after adding the prev lines into the yml file
can you please post your yaml file here?

**Comment by GingerCam** [comment]
region: eu

tunnels:
  First-app:
    addr: 80
    proto: http

  Second-app:
    addr: 3000
    proto: http

you need the spaces, they are the main part

**Comment by aliasghar1401** [comment]
hey , guys you can do that from this way . i tryed that and  it is working for me .  
tunnels:
    first-app:
     addr: 80
     proto: http
    second-app:
     addr: 3000
     proto: http
