### ISSUE TITLE
unable to install ngrok as service

### ISSUE THREAD

**Issue by pippo73** [inconshreveable/ngrok#236]
as described here https://ngrok.com/docs/ngrok-link#install
but when I try to install it 

# /usr/local/bin/ngrok service install -config /root/.ngrok2/ngrok.yml

I get the following error

ERROR:  Unrecognized command: service

Any idea how to fix it?

thanks

**Comment by inconshreveable** [comment]
This is a feature of ngrok link, which is a separate product and not part of the standard ngrok developer tool.
