### ISSUE TITLE
https tunnel ... bad request ...  speaking plain HTTP to an SSL-enabled server port

### ISSUE THREAD

**Issue by danryu** [inconshreveable/ngrok#239]
Are SSL forwards currently implemented?

Bug https://github.com/inconshreveable/ngrok/issues/111 was closed but not sure if the implementation is there yet.

I'm running self-signed, self-hosted ngrokd (working VERY nicely) on Ubuntu 64bit, with Mac and Windows ngrok clients ... Would be just good to know if I can give my users option to forward their secure vhosts too. 

Thanks!

**Comment by inconshreveable** [comment]
This is implemented in 2.0 (https://ngrok.com/docs/2#tls)

**Comment by danryu** [comment]
Ok great. But will ngrok 2.0 be open-sourced and will I thus be able to run ngrokd self-hosted in my organisation? (Kind of a requirement for these guys .... )

**Comment by danryu** [comment]
Ok, just noticed the new 2.0 section in the FAQ, "Can I run my own ngrok server?" ... where you talk about a licensed on-prem version being available.

Thing is, I work for a charity, where I have just spent a fair amount of time investigating and then implementing the best non-commercial viable alternative to vagrantshare, which requires individual users to register (and later to pay) before using the functionality. This didn't suit the requirements so I went with ngrok/vagrant-foodshow. At the time the webpage was suggesting that the upcoming 2.0 release would also be open-sourced, but now you're saying that it's becoming a commercial product as well?

**Comment by inconshreveable** [comment]
Sorry for the slow reply. My intention is to eventually open source the ngrok 2.0 client (or perhaps portions of it). I haven't exactly decided on when or how best to do that, so it's on the back burner for now. It's unlikely that the server component of 2.0 will be available as OSS. Hope that helps, and if you want to discuss further, email would be the best channel.
