### ISSUE TITLE
Machine readable output of console commands

### ISSUE THREAD

**Issue by bazilio91** [inconshreveable/ngrok#240]
HI! I'm owner of [grunt-ngrok](https://github.com/bazilio91/grunt-ngrok) plugin and I'm interested in easy-to-read output or shared library (but I guess it's not possibe in go lang or disaster) of ngrok v1 and v2. But that would be great if you will keep in mind in v2 that machine readable output support is great.

**Comment by inconshreveable** [comment]
ngrok v2 actually exposes a client API for exactly this purpose. It supports machine readable status and operations to start/stop tunnels: https://ngrok.com/docs#client-api

Is it sufficient for your use?

**Comment by bazilio91** [comment]
Oh, looks great! But I can't see options like `remotePort` or `subdomain` in `POST/api/tunnels`. Do they work as before or deprecated?

**Comment by inconshreveable** [comment]
Yeah, it's exactly like you would think: https://ngrok.com/docs#start-tunnel

    Parameter names and behaviors are identical to those those defined in the configuration file. Use the tunnel definitions section as a reference for configuration parameters and their behaviors.

Admittedly this documentation is pretty poor and needs to be improved, sorry about that! Two examples of payloads you could post:

```json
{"name": "grunt-tunnel", "subdomain": "somename", "addr": 80, "proto": "http"
```

```json
{"name": "grunt-tcp-tunnel", "remote_addr": "1.tcp.ngrok.io:20011", "addr": 22, "proto": "tcp"
```

**Comment by bazilio91** [comment]
Great! I'll try to switch to api.
