### ISSUE TITLE
reconnecting (EOF)

### ISSUE THREAD

**Issue by petercn** [inconshreveable/ngrok#241]
ngrok was working fine for me a few days ago but now it just keeps giving me "reconnecting (EOF)" Any ideas on what could be causing that? corporate firewall (it worked fine through it at first)?

**Comment by inconshreveable** [comment]
Can you run `ngrok version`?

**Comment by petercn** [comment]
yep and it reports "ngrok version 2.0.17" which I believe is the latest

**Comment by inconshreveable** [comment]
That's unfortunate and likely a result of your firewall because the service is available and functioning properly. It's possible that the firewall was updated to block ngrok. You might want to ask your network administrator (or pull out tcpdump to get a better look at what's going on).

**Comment by shmdhussain** [comment]
@inconshreveable How to check My company firewall allows me to access ngrok, I am also getting the same error. PFA SS.
![image](https://cloud.githubusercontent.com/assets/4039657/9871019/c966e2c2-5ba1-11e5-9303-f4f9dffd3bc0.png)

**Comment by drdexter33** [comment]
I get the same error.

**Comment by roysarango** [comment]
If you are on a mac/linux machine use the ngrok command with sudo, i.e: sudo ./ngrok http 80. That should be enough to make it work.

**Comment by ShikherVerma** [comment]
I am also getting the same error. `sudo ./ngrok http 80` didn't work for me. :disappointed:

**Comment by roysarango** [comment]
Hi ShikherVerma. There's a type... the 'http' word isn't needed. Try this: sudo./ngrok 80

**Comment by ShikherVerma** [comment]
@roysarango thanks that worked :+1:
