### ISSUE TITLE
get stuck in reconnecting

### ISSUE THREAD

**Issue by facat** [inconshreveable/ngrok#242]
I compiled ngrok 1.7 from git source. Often the client is stuck in "reconnecting". After I restart the client everything is back to normal.

Below is log:

```
[2015/05/18 10:02:39 CST] [INFO] (ngrok/log.Info:112) Waiting 1 seconds before reconnecting
[2015/05/18 10:02:40 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [view] [term] Waiting for          update
[2015/05/18 10:02:40 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [ctl:7ffa9cd8] New connection to: 64.79.99.249:3434
[2015/05/18 10:02:40 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [ctl:7ffa9cd8] Writing     message: {"Type":"Auth","Payload":    {"Version":"2","MmVersion":"1.7","User":"","Password":"","OS":"linux","Arch":"arm","ClientId":"eba6c361    4f7baea52496a3453e811271"}}
[2015/05/18 10:02:51 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [ctl:7ffa9cd8] Closing
[2015/05/18 10:02:51 CST] [EROR] (ngrok/log.Error:120) control recovering from failure EOF
[2015/05/18 10:02:51 CST] [INFO] (ngrok/log.Info:112) Waiting 1 seconds before reconnecting
[2015/05/18 10:02:52 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [view] [term] Waiting for     update
[2015/05/18 10:02:53 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [ctl:1346ccd8] New     connection to: 64.79.99.249:3434
[2015/05/18 10:02:53 CST] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [ctl:1346ccd8] Writing     message: {"Type":"Auth","Payload":    {"Version":"2","MmVersion":"1.7","User":"","Password":"","OS":"linux","Arch":"arm","ClientId":"eba6c361    4f7baea52496a3453e811271"}}
```

It seems the client is waiting for server to response after "Writing message". Why doesn't the client retry writing after some time if no response received? I think this is why client is often stuck.

**Comment by inconshreveable** [comment]
pretty sure this could be a legitimate bug and not a network error. very likely related to misusing the `Read` call when it should be `ReadAll` if i remember correctly. leaving this open

**Comment by majinjing3** [comment]
@inconshreveable Wow, you are here now ? 
I have found you changed README.md. I like ngrok very much. Thank you for this amazing project !

**Comment by mtwilliams** [comment]
I've encountered this too! When trying to showcase something no less :(

Any ideas on workarounds?

**Comment by inconshreveable** [comment]
If you compiled ngrok and are not pointing it at your own server it will no longer work as the 1.X service has been shut down. The best ways to upgrade are to grab the latest version of ngrok 2.0: https://ngrok.com/download or to compile and deploy your own ngrok server

**Comment by sorawa** [comment]
Can client (version 2.x) support server(version 1.x) 

i had deploy a 1.7 server ..
can i download the 2.x client to connect ?

**Comment by inconshreveable** [comment]
@sorawa no, sorry, 1.7 and 2.0 are completely different and can not be used together

**Comment by stephenmeszaros** [comment]
Ran into this same bug and excuse my ignorance here, but how do you remove/unintstall version 1.x in order to use 2.x?

**Comment by inconshreveable** [comment]
All you need to do is simply delete the 1.x binary, ngrok doesn't have any other installed components.

**Comment by jjeffrey-bolste** [comment]
If any one needs help deploying 1.7 I am happy to help. wizardofmath@gmail.com

**Comment by sergiovilar** [comment]
I'm getting this error message:

```
[EROR] control recovering from failure dial tcp: lookup ngrokd.ngrok.com: no such host
```

Is ngrok down?

**Comment by inconshreveable** [comment]
no. the v1 ngrok service does not run any more. if you want to run ngrok 1.x you need to set up your own ngrok server. (see doc/SELFHOSTING) if you want to use the ngrok.com hosted service, you'll want to download the v2 binary from https://ngrok.com/download

**Comment by sergiovilar** [comment]
@inconshreveable ohh, ok! Thanks!

**Comment by mtz313** [comment]
ngrok reconnecting(EOF) issue coming

**Comment by manzoo16** [comment]
> no. the v1 ngrok service does not run any more. if you want to run ngrok 1.x you need to set up your own ngrok server. (see doc/SELFHOSTING) if you want to use the ngrok.com hosted service, you'll want to download the v2 binary from https://ngrok.com/download

But I downloaded v2 binary and still getting the same error. Session status - reconnecting. What could be the cause

**Comment by ajhello** [comment]
> > no. the v1 ngrok service does not run any more. if you want to run ngrok 1.x you need to set up your own ngrok server. (see doc/SELFHOSTING) if you want to use the ngrok.com hosted service, you'll want to download the v2 binary from https://ngrok.com/download
> 
> But I downloaded v2 binary and still getting the same error. Session status - reconnecting. What could be the cause

Did you ever find a solution to this problem?

**Comment by MNFrankie** [comment]
![ngrok](https://user-images.githubusercontent.com/13104940/75688258-3ddb4080-5cb0-11ea-85de-afad697bb67a.PNG)
Window not working. Any solution to date.

**Comment by armalitedev** [comment]
updating from 1.7.1 to 2.3.40 worked for me

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
