### ISSUE TITLE
ngrok refuses to launch from config

### ISSUE THREAD

**Issue by mikeher** [inconshreveable/ngrok#243]
I'm attempting to start ngrok from a config using this command:
ngrok start test
But it says tunnel session failed because subdomains are only available for paid plans.
Here's my config:
http://screencast.com/t/8K4V74Bfm

What to do? I can start a tunnel fine by issuing the standard command:
ngrok http 80
I attempted the subdomain thing yesterday from the commandline (no config) and got the error. But now I get it whenever I use the config.

Maybe it's caching it or something? Is there some way I can clear the installation completely and try from the beginning?

I'm running it from windows 8.

**Comment by inconshreveable** [comment]
Let's continue discussing this over email since it's related to the paid service and not the open source code.

**Comment by majidaldo** [comment]
same problem and i just installed ngrok

**Comment by cravindra** [comment]
Hi.
I'm having the same problem and I'm using the open source version.
"Tunnel session failed: Custom subdomains are only available for paid plans. Signup at https://ngrok.com/signup"
My Config file:
tunnels:
  llama:
    proto: http
    addr: 8080
The documentation says:
"subdomain: subdomain name to request. If unspecified, uses the tunnel name"
I haven't specified a subdomain. Why won't it take the default tunnel name?

**Comment by hishyn** [comment]
Hi there,

I'm having the same issue described above while trying out setting up a grunt task for pagespeed with ngrok, described here http://www.jamescryer.com/2014/06/12/grunt-pagespeed-and-ngrok-locally-testing/. Has there been some recent changes to the defaults?

**Comment by John-Appleseed** [comment]
Is there a free usage of the config file? What is an example config without subdomains?

```
tunnels:
  httpbin:
    proto: http
    addr: 3000
  demo:
    proto: http
    addr: 3001
```

**Comment by pyhedgehog** [comment]
> ...it's related to the paid service...

Does this means that issue will not be fixed?

**Comment by ShiftyMcCool** [comment]
I'm having this issue as well.  When I use a paid plan, the subdomain is getting added automatically from the config name (i.e. httpbin or demo).  When the subdomain key is added, that is used instead.  This is acceptable to me since I'm on a paid plan, but it is a bug that should be resolved.

**Comment by inconshreveable** [comment]
@pyhedgehog This is an issue that's going to be fixed. As @ShiftyMcCool pointed out, ngrok interprets the name of a tunnel as a subdomain when no `subdomain` key is specified. This was initially designed as a cool human-friendly feature, but it turns out to be pretty bad design decision because it means that updating ngrok to not do that will either 1) break existing users or 2) require new users to add a "version number" to their configuration file to opt-in to the new behavior. Since breaking existing users is not acceptable, it's going to be #2.

**Comment by pyhedgehog** [comment]
It could be solved by something like `subdomain: *`.

**Comment by fbattarra** [comment]
thank you @pyhedgehog : waiting for @inconshreveable to publish an official patch to allow multiple tunnels with no subdomain in config file, your workaround does the job and collecting everything needed in a bash script will provide me a way to have http and tcp connection to my local server, at once :-)

**Comment by betlab** [comment]
+1, please reopen this issue

**Comment by AYapejian** [comment]
Consider me a +1 for all these issues, I don't really care what the subdomain is as long as I can get the url outputted in the ngrok.connect callback.

**Comment by oytuntez** [comment]
+1

**Comment by kenji-siu-bitgamelabs** [comment]
The same parameters work on the command line. It only doesn't work when the parameters are saved in a configuration file. The `ngrok` command assumes that the name of the tunnel to be the name of the subdomain, and it could not be disabled. I tried:

```
    subdomain: ""
```

and

```
    subdomain: *
```

and

```
    subdomain:
```

but it didn't work!

**Comment by riccardo-takram** [comment]
This is a rather severe bug as it does not allow for the use of the config file on free plans so +1

**Comment by alberto2000** [comment]
This is a rather severe bug as it does not allow for the use of the config file on free plans so +1

**Comment by fbattarra** [comment]
It has been added: "Supported in ngrok 2.1+, won't fix for 1.x" 24 days ago; please see the [referenced issue](https://github.com/inconshreveable/ngrok/issues/159)

**Comment by babblebat** [comment]
I was getting this error then added authtoken: xxxxxxxxxxxxxxxxxxxxx at the start of the config file and everything works great now.

**Comment by srinivasan4554** [comment]
1) In ngrok.yml
authtoken: removed
region:us
 tunnels:
 
 http_apache:
 proto:http
 addr:8000
 
demo:
proto:http
addr:9090

2)application folder name:
http://localhost/mm/index.html
http://localhost/nn/index.html

i am planning to publish my 2 folders namely mm and nn from my localhost.
how do i define my folder's name in my ngrok.yml file and how to run in command prompt.
i got Error: Tunnel 'http_apache' not defined in config file.
please anyone can help me.
thanks in advance.

**Comment by gary-archer** [comment]
This might be a spacing issue so worth checking if you run into this. I experienced it with the latest ngrok when I did not have a space between this argument and its value:

console_ui:false

**Comment by hugorezende** [comment]
For those who are facing this problem, just add the `authtoken` on top of your `.yml`, like

```yml
authtoken: 4nq9771bPxe8ctg7LKr_2ClH7Y15Zqe4bWLWF9p
tunnels:
  app-foo:
    addr: 80
    proto: http
  vnc:
    addr: 5900
    proto: tcp
```
