### ISSUE TITLE
ngrok doesn't work on OpenShift DIY cartridge

### ISSUE THREAD

**Issue by mathias-github** [inconshreveable/ngrok#244]
For some reason, ngrok doesn't seem to work very well on my OpenShift DIY cartridge. I've set up a Minecraft server to test on, but whenever I try to connect to the server, I get kicked with a "Connection refused" message.

This appears in the log each time I try to join:
t=2015-05-26T17:31:10-0400 lvl=warn msg="failed to open private leg" id=aeb31b2e868b typ=proxy privaddr=127.9.195.129:25565 err="dial tcp 127.9.195.129:25565: connection refused"
t=2015-05-26T17:31:10-0400 lvl=info msg="join connections" obj=join id=bb117624aa01 l=nil r=<my_ip_address_censored>:41712

Is there any way to fix this?

**Comment by mathias-github** [comment]
Ngrok seems to be working fine for me right now. Must've been a temporary problem.

**Comment by inconshreveable** [comment]
That's weird, sorry I didn't get back to this. let's reopen if it happens again and we can dig deeper

**Comment by abepetrillo** [comment]
I'm getting this error as well. I can repeat it quite reliably.

The problem happens if I'm using two ngrok subdomains on two different machines (in different locations), for example:

NYserver: my-custom-doman.ngrok.io
LNserver: my-custom-doman2.ngrok.io

LNserver fails every time, and the logs have a similar message:
```
lvl=warn msg="failed to open private leg" id=be501436fe1e privaddr=localhost:5000 err="dial tcp 127.0.0.1:5000: connection refused"
```

**Comment by swarooppuranik** [comment]
I am getting the same issue. When the server is waiting for connections, suddenly these logs will appear in terminal. I am using pyngrok using eclipse ide

**Comment by legionyt** [comment]
> I am getting the same issue. When the server is waiting for connections, suddenly these logs will appear in terminal. I am using pyngrok using eclipse ide

I too have the same error :(

**Comment by Alexadran** [comment]
I have this problem too
