### ISSUE TITLE
Would ngrok work for OpenWrt?

### ISSUE THREAD

**Issue by zhiyin-im** [inconshreveable/ngrok#245]
I've tried and it didn't work:
root@OpenWrt:~# /tmp/ngrok --help
/tmp/ngrok: line 1: syntax error: unexpected word (expecting ")")
root@OpenWrt:~# /tmp/ngrok -help
/tmp/ngrok: line 1: syntax error: unexpected word (expecting ")")
root@OpenWrt:~# /tmp/ngrok
/tmp/ngrok: line 1: syntax error: unexpected word (expecting ")")

So, do I have to compile it by myself? Has anyone done this before? Any tips?

**Comment by inconshreveable** [comment]
This means you're trying to run an ngrok binary that is compiled for a different target platform. If your OpenWRT machine is ARM or x86, then you just need to download the appropriate binary from the website: https://ngrok.com/download

If you're trying to run on MIPS, PPC, or other CPU architectures, then this is not supported.

**Comment by eschooley** [comment]
Are there any plans to get ngrok working on OpenWrt with the MIPS architecture? The Arduino Yun runs on that set up, and I would love to use ngrok with it.

**Comment by inconshreveable** [comment]
The plan is to port ngrok to all modern platforms, but I don't have any timelines for any of them.

**Comment by OllivanderMe** [comment]
[root@PandoraBox:/data/ngrok]#bin/ngrok -config ngrok.conf start http
-ash: bin/ngrok: Permission denied

so sad
