### ISSUE TITLE
1.X possible issue with tcp tunnels?

### ISSUE THREAD

**Issue by nodje** [inconshreveable/ngrok#246]
All the tunnels I used to connect to without troubles don't seem to work anymore.
I don't use them often, so it's possible that I missed something the last time I used them successfully. Well, first new thing is ngrok 2.0... but it doesn't seem to affect the way 1.x works.

Basically, I can start the tunnels without trouble but I can't telnet them.

Here are the details that could possibly play a role:
- I'm located in China, so behind the GFW
- one machine instance, A, is behind a provider that NAT the connection so have no public IP. Ngrok is particularly useful with this pattern
- B machine has a public IP

I can't ```telnet ngrok.com <port>``` any of the 1.X successfully launched tunnel, either on machine A or B.
I can't telnet a 2.0 tcp tunnel started on machine A behind NAT

I **can** telnet a 2.0 HTTP connection on 80 on machine A behind NAT.
I can't telnet a 1.X HTTP connection on 80 on machine A behind NAT. 

What could possibly go wrong?

PS: 1.X is always 1.7, possibly 1.6 in some cases. DNS always resolve ngrok.com to 173.255.204.192 for 1.X

**Comment by inconshreveable** [comment]
this is almost guaranteed to be the GFW as I've received multiple reports that it's begun blocking access to ngrok. the easiest way is to check whether you can access the endpoints over a VPN

**Comment by nodje** [comment]
OK, I was about to add that I can't even telnet ngrok.com on port 80... which confirms suspicion.

BUT: I can't access the established tunnels from a server located outside China either. 

Which is odd: why do they allow ngrok to establish a connection to ngrok.com from within China to block the connection the other way? I can't make sense of this. They usually block everything going out, not thing coming in.

**Comment by alexellis** [comment]
I am a big ngrok fan and @inconshreveable is doing an amazing job. I wrote [inlets](https://github.com/alexellis/inlets) to try to help people who have this situation inside the enterprise. It has also received a lot of attention from people behind the GFW. It might be useful for you @nodje or other people landing here (like I did)
