### ISSUE TITLE
Implementing ngrokd authentication

### ISSUE THREAD

**Issue by sr105** [inconshreveable/ngrok#249]
I need to implement very simple authentication in ngrokd because it will be on a public facing server. I noticed that when connecting to "ngrokd.ngrok.com:443", the authentication error is returned by NewTunnel and not by NewControl. Is there a reason for that? I was going to put a simplistic check like this in NewControl:

    diff --git a/src/ngrok/server/control.go b/src/ngrok/server/control.go
    index 62f1a15..79a03e2 100644
    --- a/src/ngrok/server/control.go
    +++ b/src/ngrok/server/control.go
    @@ -101,6 +101,11 @@ func NewControl(ctlConn conn.Conn, authMsg *msg.Auth) {
                    return
            }

    +       if authMsg.User != "super_secret_auth_token" {
    +               failAuth(fmt.Errorf("Invalid authtoken %s", authMsg.User))
    +               return
    +       }
    +
            // register the control
            if replaced := controlRegistry.Add(c.id, c); replaced != nil {
                    replaced.shutdown.WaitComplete()

Is it so people can test their ngrok connections without authenticating?

**Comment by inconshreveable** [comment]
seems fine, ngrok's own auth is much more complex and I believe (haven't looked at the old code in a long time) does auth in both places
