### ISSUE TITLE
[Wordpress] Issue connecting to my Wordpress projects

### ISSUE THREAD

**Issue by paulbonneau** [inconshreveable/ngrok#251]
Hello and thanks in advance for reading this ticket,

I can't load any of my wordpress project when I use a ngrok http tunnel.
I precise that every other .html or .php are loading without a problem.

When I try to check one of my wordpress website by typing :" http://somerandomnumbersandletters.ngrok.io:8888/nameofmywordpressprojectdirectory/"
my browser start loading the page and like 30 seconds after it say that he can't reach the page.

I precise that I try the "relative-url" extension but it didn't solve anything.

Here is what displaying in the ngrok console.

                                                                                
    Tunnel Status                 online                                            
    Version                       2.0.19/2.0.19                                     
    Web Interface                 http://127.0.0.1:4040                             
    Forwarding                    http://54d08a17.ngrok.io -> localhost:8888        
    Forwarding                    https://54d08a17.ngrok.io -> localhost:8888       
                                                                                
    Connections                   ttl     opn     rt1     rt5     p50     p90       
                                  3       0       0.00    0.00    5.01    7.89      
                                                                                
    HTTP Requests                                                                   
    -------------                                                                   
                                                                                
    GET /                          200 OK                                           
    GET /                          200 OK                                           
    GET /Lavageauto/               301 Moved Permanently                            
    GET /favicon.ico               200 OK                                           
    GET /                          200 OK   

Thank you for your really useful app and sorry for my bad english (i'm french).

Paul.

**Comment by TomKita** [comment]
You need to use this http://54d08a17.ngrok.io without the 8888 port. It forwards to your localhost on port 8888.

**Comment by inconshreveable** [comment]
old ngrok 2.x issue, closing.
