### ISSUE TITLE
Assign the different web interface port?

### ISSUE THREAD

**Issue by CorcovadoMing** [inconshreveable/ngrok#252]
Can I assign the different port of local web interface?
(default it use 127.0.0.1:4040)

**Comment by hibooboo2** [comment]
https://github.com/inconshreveable/ngrok/blob/64ebca99eb355cae5a5498c76f8a318a782a0442/src/ngrok/client/config.go#L21 

https://github.com/inconshreveable/ngrok/blob/64ebca99eb355cae5a5498c76f8a318a782a0442/src/ngrok/client/config.go#L76

These lines indicate that if in the config yaml you specify ```inspect_addr``` as a port or ip it will change. @inconshreveable  Could tell you for sure. But I believe that is what will happen @CorcovadoMing

**Comment by inconshreveable** [comment]
In v2, this is the `web_addr` property in the config file. In v1 it's `inspect_addr`.
