### ISSUE TITLE
where is the second port?

### ISSUE THREAD

**Issue by frogeraie** [inconshreveable/ngrok#253]
I get this error message:
"You may only specify one port to tunnel to on the command line, got 2: [http 80]"
whereas I have tried to open only port 80. There should be a second port hidden somewhere. How could I find it?
Thanks!

**Comment by inconshreveable** [comment]
You're using an older version of ngrok (1.7). You can either use `ngrok 80` or grab the latest 2.0 version which has the new syntax here: https://ngrok.com/download

**Comment by mengqingmeng** [comment]
today，I used the latest version and remove it，then，the older version get the same message。How to solve this problem？
Thanks！

**Comment by bekkemsravan19** [comment]
I was facing the same problem. Try restarting the network.
/etc/init.d/networking restart. That fixed for me!

**Comment by mjames21** [comment]
use  ./ngrok http 80

**Comment by deepak-ranolia** [comment]
@mjames21  but when we use ./ngrok http 80/4200/8080 etc then we will get the error message on browser "invalid host header" and in ngrok terminal "304 not modified"
