### ISSUE TITLE
how to avoid multiples instances

### ISSUE THREAD

**Issue by solucionesmipc** [inconshreveable/ngrok#254]
Hi:

when user needs same subdomain for http and https the only way is from command "ngrok -subdomain =xxxxxxx 80"  and for use an aditional tunnel is mandatory to start another ngrok instance.

(if uses same subdomain in config file for http and https only starts http tunnel)

is there any way to solve it?

version 1.7 ngrok own server

Thanks

Diego

**Comment by inconshreveable** [comment]
this is supported in ngrok 2.x but i'm not sure it ever worked in 1.x. closing
