### ISSUE TITLE
Open Source 2.0

### ISSUE THREAD

**Issue by sammcj** [inconshreveable/ngrok#255]
I couldn't find an issue for this, but there's been a lot of discussion on [HN](https://news.ycombinator.com/item?id=10077883) around the fact that 2.x is not open source.

It does seem strange that you wouldn't start open and transparently right from the start?

**Comment by inconshreveable** [comment]
ngrok 2.0's client code may become open source at some point. Pieces will be released as they become ready. Some of it is already released as OSS libraries:

https://github.com/inconshreveable/muxado
https://github.com/inconshreveable/go-update

**Comment by cathalgarvey** [comment]
Was about to upgrade to Pro, as I use nGrok a lot and would like to stop remembering port numbers. But, I'm not about to install a closed binary on my home PC. Any idea when this may happen? This year? Next? Never? :-/

**Comment by inconshreveable** [comment]
The short answer is that there is no timeline for this. It's a possibility, but there's nothing else I can commit to beyond that right now.

**Comment by cathalgarvey** [comment]
Pity. Thanks for the answer at least.

**Comment by bbhoss** [comment]
Totally your choice, but I'm curious why you chose to close it up for 2.0? This is a great tool.

**Comment by inconshreveable** [comment]
Thanks! Sadly the realities and incentives of running ngrok as a business mean that it's better off for 2.0 to be closed.

**Comment by MOZGIII** [comment]
What changed since v1? Maybe there is another way: to have a closed source AND an Open Source version with the same API and networking fetaures/fixes to fit both worlds?
I can only use it a quick toy now, but if it were opensource and self-hosted usecases would change a lot.

**Comment by rileytg** [comment]
no news is bad news?

**Comment by cathalgarvey** [comment]
Yep, dead project, it seems.

--
@onetruecathal / @cathal@quitter.is

**Comment by engahmedgad** [comment]
Hello Is there is still no news from v2 open source client ?!

**Comment by MOZGIII** [comment]
I personally lost all the hope for it to release and switched to [frp](https://github.com/fatedier/frp). Some of my use cases don't allow running closed source binaries, if not that - I'd just purchase the ngrok cloud service. I don't care where the server-side is as long as I have access to the client's source, and running my own infrastructure costs money anyhow.
