### ISSUE TITLE
Publish gzipped version

### ISSUE THREAD

**Issue by achingbrain** [inconshreveable/ngrok#256]
Is there any chance you could publish gzipped versions of ngrok in addition to the zips?  It would make automated integration easier with platforms that don't understand zip files out of the box without additional libraries (node.js I'm mostly looking at you).

The idea would be to download an appropriate copy of ngrok during a module's preinstall phase and expand it - at this point only core modules are available as npm has yet to install any dependencies.

**Comment by inconshreveable** [comment]
Yes, this is coming, although it will be .tar.gz (you need an archive like zip or tar in order to guarantee that the mode bits are set properly when extracted)

**Comment by inconshreveable** [comment]
ngrok 2.x now publishes tgz images via equinox: https://dl.equinox.io/ngrok/ngrok/stable

The https://ngrok.com/download page will be getting an update soon so that it takes advantage of this and doesn't just show zips
