### ISSUE TITLE
Allow override of trusted root CA via flag / config

### ISSUE THREAD

**Issue by chris-prince** [inconshreveable/ngrok#257]
After encountering many issues with trying to run self-hosted ngrok (and eventually giving up), I have a feature request that may solve most problems: could you add a setting allowing users to specify a custom root CA to trust?

As an example of the problems this is meant to solve:

* When using a self-signed TLS certificate, it is currently necessary to recompile the ngrok client and server. (And even then, I believe you can only compile an ngrok v1 client, as the 2.0 sources are not available.)

* When using a CA-signed TLS certificate, the 'trust_host_root_certs' setting does not always work. (I exprienced this with a StartSSL-signed certificate and the ngrok 2.0 Windows client. There are also reported issues with the flag when using the ngrok Mac client.)

I believe these problems could be solved if I could specify the trusted root CA as an argument, rather than relying solely on the root CA compiled into the binary.  Is there any technical reason this could not be done?

**Comment by inconshreveable** [comment]
This is an option that's available in 2.0, although it's not much use since you can't run your own 2.0 server yet, and 1.X and 2.0 are not compatible. If you're still using 1.X, it should be pretty trivial to change the source to read this in from a file.
