### ISSUE TITLE
Is option -webport supported in version 2.0.19

### ISSUE THREAD

**Issue by striker88** [inconshreveable/ngrok#259]
ngrok version: 2.0.19
Platform: Centos Linux 6.3

I have looked at this page:
https://github.com/inconshreveable/ngrok/blob/master/docs/CHANGELOG.md
"IMPROVEMENT: The ngrok web ui can now be disabled with -webport=-1"

As far as I understand this comment, if we do not need the web interface which ngrok creates by default on port 4040, then we can disable it by using  -webport=-1 on the command line.

Issuing any of these two commands, throws Incorrect Usage error:
./ngrok http  --webport=-1 80
./ngrok http  -webport=-1 80

Is  -webport option included in the code and supported? Thanks.

**Comment by inconshreveable** [comment]
That changelog is from an old version and the interface has changed. If you want to disable the web UI in 2.X, use `web_addr` in your configuration file as documented here: https://ngrok.com/docs#config-options

**Comment by striker88** [comment]
I tried the suggested solution and it works. Thanks for the reply.
   Regards,
   Sam
