### ISSUE TITLE
Connect to client api outside server?

### ISSUE THREAD

**Issue by judoole** [inconshreveable/ngrok#264]
Is it possible to connect to the client api other than from the machine ngrok is running? Or a workaround? Like http://machine-ip:4040/api/tunnels

**Comment by inconshreveable** [comment]
It's possible to tell ngrok to forward port 4040 itself and create a separate tunnel to manipulate the client API. There's an example in the docs: https://ngrok.com/docs#config-examples

Doing this is extraordinarily dangerous without strong authentication.

**Comment by judoole** [comment]
Aha. I understand. And I also now understood that what I really was looking for was **web_adr**. Changing this from the default127.0.0.1:4040 to 0.0.0.0:4040 did exactly what I was looking for. Now the address is accessible from one docker container to another.

**Comment by inconshreveable** [comment]
ah awesome! sorry i misunderstood the question
