### ISSUE TITLE
Connection names and local ports on dashboard

### ISSUE THREAD

**Issue by pyhedgehog** [inconshreveable/ngrok#265]
When I use `tunnels` from `http://loopback:4040/api/tunnels` there are attributes like `tun.name` and `tun.conf.addr`that can help to distinguish tunnels. But on `https://dashboard.ngrok.com/` (`$('#preloaded').data('value').online_tunnels`) all this information is lost. Local address/port may be secure-sensible data, but name can be safely provided to understand which tunnel means what.
Same can be told about `metadata` config field.

**Comment by inconshreveable** [comment]
Yeah, these are only features of the ngrok link product, where metadata is available via API. I'm working on ways to make that functionality more available.
