### ISSUE TITLE
Inspect screen: Duration is not accurate or mislabeled

### ISSUE THREAD

**Issue by kdeenanauth** [inconshreveable/ngrok#267]
It appears the Duration on the inspect screen is actually the time the request happened relative to now (similar to the "ago" stat next to it.)

This should probably be either relabeled to "Duration ago" or fixed to be the time the response took.

**Comment by inconshreveable** [comment]
agreed completely. thanks for the report!

**Comment by inconshreveable** [comment]
ngrok 2.x issue, closing
