### ISSUE TITLE
Client Creation on Ubuntu

### ISSUE THREAD

**Issue by chkchaitu** [inconshreveable/ngrok#268]
Hi, have deploy ngrok-server using ubuntu repo and ngrokd starts without any issue. 

Would like to know how to create a client so that ngrok client can connect to this server.

Superb software, would be thankful if help can be extended

**Comment by inconshreveable** [comment]
There are instructions on how to set that up here: https://github.com/inconshreveable/ngrok/blob/master/docs/SELFHOSTING.md
