### ISSUE TITLE
ngrok 1 - no DNS servers

### ISSUE THREAD

**Issue by fsamir** [inconshreveable/ngrok#270]
Hi all,

I have ngrokd v1 running for a while and recently the clients stopped being able to connect, with the following error:
```
[ngrok] ####### [ngrok] DATA: [10/11/15 15:58:10] [EROR] Error while checking for update: Post https://api.equinox.io/1/Updates: dial tcp: lookup api.equinox.io: no DNS servers

[ngrok] ####### [ngrok] DATA: [10/11/15 15:58:11] [EROR] control recovering from failure dial tcp: lookup my.domain.com: no DNS servers
```

Any clues?

Thanks,
Franklin

**Comment by inconshreveable** [comment]
This looks very much like your box experienced some sort of network outage which at the very least prevented you from contacting any DNS servers. If the network restores, everything should come back up cleanly.

**Comment by fsamir** [comment]
No network outage.
Based on the error message and what I've read from another issue, some old ngrokd versions use  mechanis, other than the OS, to resolve DNS. 
Could the DNS resolution be done by a call to `https://api.equinox.io/1/Updates`?
If so, could it be that the service has changed and no longer supports nogrokd v1?

Thanks,
Franklin

**Comment by inconshreveable** [comment]
The equinox service is used for self-updating ngrok, but has no bearing on how the rest of the ngrok program runs and any failures to check for updates are ignored except for a log message.

DNS resolution is completely orthogonal and depends only on your operating system or the native-Go resolver, depending on how you built ngrok and what version of Go you built it with.

**Comment by fsamir** [comment]
Solved!

Issued happened because DNS resolution was changed inUbuntu 12.04:
http://www.stgraber.org/2012/02/24/dns-in-ubuntu-12-04/

Solution is at the bottom of this question:
https://askubuntu.com/questions/127498/resolv-conf-doesnt-get-set-on-reboot-when-networking-is-configured-for-static-i/308050#308050?newreg=0f667cd18a5349879eb2eb4bb1f40f90

You need to specify `dns-nameservers` in `/etc/network/interfaces`. For example:
```
auto eth0 inet manual
dns-nameservers 8.8.8.8 8.8.4.4
```
