### ISSUE TITLE
Ngrok Server failed to allocate tunnel: Invalid authtoken “token”

### ISSUE THREAD

**Issue by swati-yamgar** [inconshreveable/ngrok#275]
I am using ngrok 1.6 and I wanted to have a fixed URL for my application to share it with my colleagues. So I signed up on ngrok website and tried to set authtoken with the command

`ngrok -authtoken token 4000`

and got following error

`Server failed to allocate tunnel: Invalid authtoken 'token'.
This looks like an ngrok 2.0 authtoken, but you're using ngrok v1.
Download ngrok 2.0 from https://ngrok.com/download`

Then I downloaded ngrok for linux-32 bit, as I am using Linux Mint 17.1 32 bit. But still getting the same error. Also when I get the same error when I try to on the ngrok server with command:

`ngrok port-no`

I am not able to on the server now. Can I get a help to resolve this issue?

**Comment by swati-yamgar** [comment]
I am able to use the version 2.0 now, But when I try to use version 1.6 I still get the same error. How can I remove that authtoken?

**Comment by kaseebhotla85** [comment]
./ngrok authtoken <authtoken value> by executing this command from shell. But however in windows i am facing similar issue 
Tunnel session failed: The authtoken you specified does not look like a proper ngrok tunnel authtoken.
Your authtoken: <my_auth_token_value>
Instructions to install your authtoken are on your ngrok dashboard:
https://dashboard.ngrok.com/auth

ERR_NGROK_105

in which the token value actually the right one.

**Comment by digitaldavenyc** [comment]
+1 for this is issue

I just upgraded to a Pro account, my token is correct and getting this error

```
Tunnel session failed: The authtoken you specified is properly formed, but it is invalid.
Your authtoken: xxxx
This usually happens when:
    - You reset your authtoken
    - Your authtoken was for a team account that you were removed from
    - You are using ngrok link and this credential was explicitly revoked
Go to your ngrok dashboard and double check that your authtoken is correct:
https://dashboard.ngrok.com/auth

ERR_NGROK_107
```

**Comment by jamiecurle** [comment]
I am also experiencing this issue - a brand new account.

The token 100% matches the token in the dashboard.

```
Tunnel session failed: The authtoken you specified is properly formed, but it is invalid.
Your authtoken: xxxx
This usually happens when:
    - You reset your authtoken
    - Your authtoken was for a team account that you were removed from
    - You are using ngrok link and this credential was explicitly revoked
Go to your ngrok dashboard and double check that your authtoken is correct:
https://dashboard.ngrok.com/auth

ERR_NGROK_107
```

**Comment by Dico200** [comment]
Same issue for me.

**Comment by kalinchuk** [comment]
Same issue here. Any ideas?

**Comment by olsgreen** [comment]
Same for me, looks like a service issue.

**Comment by jamiecurle** [comment]
A few hours after I logged this, I was contacted by the author. It was a service issue.

A status page would be a massive win.

Also, in case people are not aware – this repo is for the 1st version of ngrok which is now discontinued and as such, these issues are no longer monitored.

**Comment by hackdrug** [comment]
23 hours past, i still get the same error. how about yours? did the error fix?

**Comment by jamiecurle** [comment]
I contacted via the help email address:  contact@ngrok.com.

It was 4 hours or so before I was contacted. That is the best option I think, given the fact that these issues are not monitored.

**Comment by hackdrug** [comment]
even using the ngrok 2.2.8 still get the same issue.. 2.2.10 not try. so we need to wait or what

**Comment by jamiecurle** [comment]
I would email the support address. It could very well be that this is a service issue.

**Comment by hackdrug** [comment]
thank you!

**Comment by hackdrug** [comment]
the service is online! its fix

**Comment by knagode** [comment]
My guess is that many people (including me) are confused (and landing on this thread) because they created `API token` instead of using proper authtoken `Getting Started -> Your Authtoken` section of ngrok website.

![Screenshot 2023-05-02 at 10 34 24](https://user-images.githubusercontent.com/4473199/235619229-2711fe29-3401-4bb2-bcb5-5f26725de810.png)

**Comment by phannh4tvinh** [comment]
Change again token then config it to project
