### ISSUE TITLE
Tunnel Status reconnection (EOF)

### ISSUE THREAD

**Issue by drdexter33** [inconshreveable/ngrok#276]
I've been trying to get ngrok to run on a development workstation in our LAN, however am consistently met with the Tunnel Status reconnection (EOF) message.

![3](https://cloud.githubusercontent.com/assets/15314276/10763960/57a473c6-7ca2-11e5-9555-752aac310701.png)

I can however get it to work properly on my personal laptop.

![2](https://cloud.githubusercontent.com/assets/15314276/10763913/2bcce0bc-7ca2-11e5-9b5e-8eb10f7ac7c9.png)

Is there a way to turn on logging to determine where this is failing?

thanks.

doug

**Comment by inconshreveable** [comment]
usually a firewall or proxy terminating the connection. for reference, logging can be enabled with `-log=stdout -log-level=debug`

old ngrok 2.x issue, closing
