### ISSUE TITLE
URLs unnecessarily long?

### ISSUE THREAD

**Issue by etdev** [inconshreveable/ngrok#277]
I've been getting randomly generated URLs of the following form:

`68425551.ngrok.io`

The part before `.ngrok.io` consists of eight numerical digits = `10^8` = `100,000,000` possible combinations (if my math is correct).

Is there any reason not to use alphanumeric characters instead?  If we make the URLs case-sensitive we could achieve nearly ten times the combinations with only 5 characters:

```
Five digits or lowercase/uppercase characters = 62^5 = 916,132,832 combinations
```

Even with just four characters, that's still over 14 million, which I feel should be enough.  This would allow for URLs of the following form:

```
a92F.ngrok.io
```

which is easier to remember / type into a smartphone browser etc.

Is there any interest in this?  If so I can try to implement it and open a PR.

**Comment by hibooboo2** [comment]
I would just do it. I'd use it. Open the pr. If you just make it so it is done optionally on ngrok daemon startup then it could please plenty.

**Comment by hibooboo2** [comment]
I believe that all you need to change is https://github.com/inconshreveable/ngrok/blob/master/src/ngrok/server/tunnel.go#L89.

@inconshreveable could correct me if I am wrong but it seems that generates the subdomain and if you change the way that is made it would happen here.

**Comment by inconshreveable** [comment]
willing to merge that PR if anyone wants to fix the format specifier. this change won't happen in the 2.x service though
