### ISSUE TITLE
ngrok url was reported as phishing site

### ISSUE THREAD

**Issue by striker88** [inconshreveable/ngrok#285]
I apologize if this may not be the right forum for an issue like this but I will post and see if I get feedback. We use ngrok free version for unit tests. Just today we noticed that at least a couple of our ngrok url's have been reported as possible phishing sites. We have tested this with both Chrome and Firefox and it is the same issue. We can still use the url and connect to the correct application.

We shutdown and restarted ngrok and got a new url. It is the same issue. We still get the phishing error message. This is the new url:
http://dbe6ddbc.ngrok.io

Is there any workaround that we need to do on our side?

**Comment by inconshreveable** [comment]
There's nothing you're doing wrong and no workaround at this time. I'm trying to work with the major browser vendors to get this resolved, but the process is very unhelpful.

If you can flag any ngrok.io domain you visit as not a phishing site, that will help.

**Comment by striker88** [comment]
Although the browser shows the warning message, ngrok connects to the correct application and we can use it. We will continue to use ngrok for our unit tests. Thanks for the feedback and prompt reply.

**Comment by inconshreveable** [comment]
The browser should no longer be showing a warning message, this was resolved.

**Comment by pernydev** [comment]
Issue is back.
