### ISSUE TITLE
API for renaming (changing?) tunnel

### ISSUE THREAD

**Issue by pyhedgehog** [inconshreveable/ngrok#288]
As per #159 `ngrok` unable to process `ngrok start tun1` if `tun1` defined with `http`/`https` protocol.
There are workaround like `ngrok http 80` but it names tunnels as `command line`. It would be pretty to have api for changing tunnel configuration (like `POST /api/tunnels/:name`). Also this will be useful to use with #287.

**Comment by inconshreveable** [comment]
ngrok 2.X issue, closing. also an unlikely feature. probably much easier to stop a tunnel and then restart it with new configuration if you need that
