### ISSUE TITLE
Feature request: timestamp on all incoming requests

### ISSUE THREAD

**Issue by carlosbutler** [inconshreveable/ngrok#291]
Please can you add a timestamp in the terminal output that includes a timestamp.

At the moment
`POST /notify                   200 OK`

Would like
`POST /notify                   200 OK | 2015-11-27 14:21:50` (or whatever reasonable format)

**Comment by inconshreveable** [comment]
might happen in 2.x at some point. could make the terminal noisy though. won't fix for 1.x though

**Comment by nratter** [comment]
I second this. Would be nice to have a timestamp on the log.

**Comment by SeriousLeeTV** [comment]
Perchance any movement on this in the last 7 years? 😅

**Comment by brattonr** [comment]
We're at version 3.3.0.  Can we please make this happen?  When I have the CMD window open for long periods of time, I can't tell from the output how recent an HTTP Request was.  Thanks!

**Comment by RonnieRocket147** [comment]
Same here, please prefix the output with a timestamp

**Comment by dzg** [comment]
I would also like this to be a thing.

**Comment by russorat** [comment]
continued in https://github.com/ngrok/ngrok/issues/8
