### ISSUE TITLE
Invoking POST on /api/tunnels crashes ngrok client

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [inconshreveable/ngrok#297]
# Configuration 
$ uname -a
Darwin mac.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

$ ngrok --version
ngrok version 2.0.19

# Steps to reproduce
1. In terminal 1, type "ngrok start --all", which will not start any tunnels because the tunnel configuration file is empty 

2. Now list all tunnels via CURL, which will work
$ curl -L http://localhost:4040/api/tunnels
{"tunnels":[],"uri":"/api/tunnels"}

3. Create a new tunnel definition in a JSON file. 
$ cat tunnel.json 
{
    "addr": "22",
    "proto": "tcp",
    "name": "ssh"
}

4. Now do a POST via CURL, which will crash ngrok
$curl -L -X POST  -H "Accept: application/json" -d@tunnel.json http://localhost:4040/api/tunnels
curl: (52) Empty reply from server

5. The ngrok Console shows a message such as 
param/parse: Target of param.Parse must be a pointer to a struct. We instead were passed a *map[string]interface {} This is a bug in your use of the param library. 

6. The same behaviour can be observed even when you start NGROK via "ngrok http 80" (Crash is consistent).

**Comment by inconshreveable** [comment]
This is a known and legitimate bug in the ngrok client. The plan is to fix it soon. In the meantime if anyone has this issue, you need to specify `-H "Content-Type: application/json"` not `Accept`.

Closing because this is a 1.X issue.

**Comment by morj** [comment]
@inconshreveable your documentation says "Request parameters may be encoded to the API using either `application/x-www-form-urlencoded` or `application/json`." How do I achieve that (with `application/x-www-form-urlencoded`)?
