### ISSUE TITLE
can't find tunnel if host contains secure port 443

### ISSUE THREAD

**Issue by martinlippert** [inconshreveable/ngrok#298]
access to an https tunnel fails if the hostname in the http request contains the port (":443") at the end. This works for http (":80"), but it doesn't seem to cut off for https with 443.

The http response contains:
Tunnel <whatever>.ngrok.io:443 not found

**Comment by martinlippert** [comment]
(btw, I can't change the library that is responsible for adding those ports to the host at the moment, therefore hoping that ngrok could cut this off in the same way it seems to do that for http at port 80.)

**Comment by inconshreveable** [comment]
This was fixed at some point in ngrok2 (which this issue was about)

**Comment by martinlippert** [comment]
Great, thanks for the feedback. Is there a better channel to report issues about ngrok2, btw, or is it fine to continue to use this channel?

**Comment by inconshreveable** [comment]
best channel is contact@ngrok.com for anything ngrok2-related, i'm going to try to keep this channel targeted exclusively at ngrok1
