### ISSUE TITLE
How to disable web GUI?

### ISSUE THREAD

**Issue by mhsjlw** [inconshreveable/ngrok#301]
Hi!

When I run ngrok I get this error:
```
remote: t=2016-01-21T12:16:01-0500 lvl=crit msg="command failed" err="web failed: listen tcp 127.0.0.1:4040: bind: permission denied"
remote: web failed: listen tcp 127.0.0.1:4040: bind: permission denied
```
I am assuming that this means it can't bind to 4040 which is the required port for the web view. How can I disable the web view?

**Comment by inconshreveable** [comment]
You're looking for `web_addr: false`in the configuration file: https://ngrok.com/docs#config-options

**Comment by samuelclay** [comment]
Is there a command line flag I can use instead of writing out a config file?
