### ISSUE TITLE
You may only specify one port to tunnel to on the command line, got 2

### ISSUE THREAD

**Issue by RenanSgorlom** [inconshreveable/ngrok#304]
When I try to run ngrok http 80 for example it gives me the error You may only specify one port to tunnel to on the command line, got 2:

I have the latest version of ngrok and I do have the authentication file already.

Thanks!

**Comment by rijotech** [comment]
I'm facing the same issue.

**Comment by inconshreveable** [comment]
This means you're trying to run an ngrok2 command with the older ngrok1 client. Either use the old syntax for an ngrok1 client `ngrok 80` or make sure you grab the latest ngrok from https://ngrok.com/download

**Comment by ajahongir** [comment]
had a same issue. removed installed client and download again - works fine.

**Comment by brianmituka** [comment]
use ./ngrok http 80

**Comment by Grace-Amondi** [comment]
./ngrok http 80 worked for me...thanks

**Comment by brianmituka** [comment]
or after extracting the ngrok zip filel, create a bin folder in your home directory and set it to your path so that you can call ngrok from anywhere in the system without the ./

**Comment by EdwardOkech** [comment]
./ngrok hhtp 80 works for me. thanks @brianmituka

**Comment by santunandi** [comment]
Thanks,it worked for me.

**Comment by Luneya** [comment]
Could this maybe be added in the docs?

**Comment by memayank00** [comment]
./ngrok http 80 working for me . thanks

**Comment by iyanuashiri** [comment]
sudo ngrok http 8000 ....This worked for me. You should use 'sudo' if ngrok is located on /usr/local/bin, because you need root access

**Comment by anu-kulkarni** [comment]
./ngrok http 80 worked Thank you

**Comment by kidoneself** [comment]
I have the same issue , I had kill the course who use 22，but it‘s useless , feeling bad

**Comment by dnjoe96** [comment]
./ngrok http 80 worked fined. Thanks
