### ISSUE TITLE
How to check created tunnels (not active)?

### ISSUE THREAD

**Issue by giopas** [inconshreveable/ngrok#305]
Hi,

It is definitely not an issue, but I wonder to know how can I see the http address of a tunnel I have created if I send the job on background like in the example below:

    [~] # ngrok http 8080 &

Infact, I cannot see any generated tunnel on my login page and I don't know where to look at (in the docs, maybe because it is too obvious, I cannot find information on it).

Thanks

EDIT: I have probably found the answer here http://stackoverflow.com/questions/34322988/view-random-ngrok-url-when-run-in-background

**Comment by inconshreveable** [comment]
Like you mentioned, the `/api/tunnels` endpoint is what you're looking for or to use `-subdomain` so you're guaranteed you know what URL is started.
