### ISSUE TITLE
log4go compiling error

### ISSUE THREAD

**Issue by rijotech** [inconshreveable/ngrok#307]
I'm facing some issues compiling ngrok, i keep getting 
```
package code.google.com/p/log4go: unable to detect version control system for code.google.com/ path
Makefile:8: recipe for target 'deps' failed
make: *** [deps] Error 1
```
Any solution for this problem?

**Comment by samgiles** [comment]
@rijotech I updated `src/ngrok/log/logging.go` to import 'github.com/alecthomas/log4go' rather than the google code version.

**Comment by rijotech** [comment]
@samgiles Thanks buddy that worked.
