### ISSUE TITLE
Failed to read valid http request: malformed HTTP request

### ISSUE THREAD

**Issue by rijotech** [inconshreveable/ngrok#309]
I have tried almost all tutorials on the internet related to ngrok and all I'm getting is Failed to read valid http request: malformed HTTP request i don't really know hot to fix it.
Can anybody give me a hand with this issue?

**Comment by rijotech** [comment]
Never mind i found the problem, wow really simple.

**Comment by unstatusthequo** [comment]
Care to share what the solution was?

**Comment by rijotech** [comment]
It was related to the cert and server port I forgot what I did I'll post my config when I get a chance.

**Comment by baochaofei** [comment]
The problem is solved, choose lower version of golang version 1.9.2
