### ISSUE TITLE
web interface at localhost:4040 not working

### ISSUE THREAD

**Issue by DDChiang** [inconshreveable/ngrok#313]
I did the basic install steps for ngrok. The public ngrok urls work and I can check out my project rendering on them. HOWEVER I'm unable to view the web interface at localhost:4040 and api calls to http://127.0.0.1:4040/api returns nothing.

Am I missing a step? Perhaps something is improperly configured?

**Comment by aswin-chauka** [comment]
I'm facing the same issue, what was the fix in this case?

**Comment by saippuakauppias** [comment]
> Note that I had to keep the log_level and log parameters in the config file, otherwise the curl command was not working

+1 for me!
@aswin-chauka thanks!!!!
