### ISSUE TITLE
student account

### ISSUE THREAD

**Issue by blackhat999** [inconshreveable/ngrok#314]
Hey @inconshreveable,

Just discovered ngrok. Totally awesome and will be very useful in my webdev stuff. I'm currently a student @ Brown Summit Middle School for Advanced Academics in the 8th grade. I am a C#, Web, C, C++, AVR, and electronics developer. My latest project was teaching Hour of Code classes at my school, where I used a custom Scratch curriculum (http://slides.com/bsmsph3enix/hourofcode#/) to teach students the fundamentals of CS by building a Pong game. I wrote my first program, a rather buggy C# calculator, when I was 8 or 9, and I wrote a full-featured, object-oriented command line temperate converter in Python when I was 10. I would like a free Basic account so I can set up ngrok to work with a subdomain of 0b00000000.me. For verification, my Guilford County Schools student email is agunt753@gaggle.gcsnc.com. Thanks and happy hacking!

**Comment by inconshreveable** [comment]
Happy to hook you up, please email me via alan at ngrok dot com, issues here aren't the most appropriate place for this.
