### ISSUE TITLE
GET /wordpress/ 301 Moved Permanently

### ISSUE THREAD

**Issue by DB1500** [inconshreveable/ngrok#315]
I use ngrok http tunnel to view my web designs on various devices. Recently I set up a wordpress development environment which all works fine. However, when I try to view using ngrok http tunnel the website loads for 20odd seconds then times out. The ngrok console spits out the following: 

ngrok by @inconshreveable                                       (Ctrl+C to quit)

Tunnel Status                 online
Version                       2.0.19/2.0.20
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://d33d0eff.ngrok.io -> localhost:8080
Forwarding                    https://d33d0eff.ngrok.io -> localhost:8080

Connections                   ttl     opn     rt1     rt5     p50     p90
                              4       0       0.00    0.01    5.18    8.27

HTTP Requests
-------------

GET /wordpress/                301 Moved Permanently
GET /favicon.ico               200 OK
GET /icons/image2.gif          200 OK
GET /icons/text.gif            200 OK
GET /icons/folder.gif          200 OK
GET /icons/blank.gif           200 OK
GET /                          200 OK

Is there a way around this?

**Comment by inconshreveable** [comment]
It's hard to say without knowing more about what's going on. Please contact email contact@ngrok.com, github will be exclusively for ngrok 1.X issues.

**Comment by thorsten-stripe** [comment]
The following steps worked for me

1) Update ngrok (Ctrl+u when ngrok is running)
2) adding the following two lines to wp-config:
```define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);
define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);```
3) Installing https://wordpress.org/plugins/relative-url/ in Wordpress

**Comment by johncrumpton** [comment]
@thorsten-stripe Thank you for providing the solution! The site loaded the site, however the css and other absolute links don't load. Did you find a work around?

**Comment by Kanhavishva** [comment]
Thanks @thorsten-stripe I added those two line, activated relative-url plugin and it worked fine, after that I deactivated relative-url plugin but its still working, Is that possible ?

**Comment by mahmudinm** [comment]
its not work with multisite

**Comment by SonGokussj4** [comment]
> The following steps worked for me
> 
> 1. Update ngrok (Ctrl+u when ngrok is running)
> 2. adding the following two lines to wp-config:
>    `define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);`
>    `define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);`
> 3. Installing https://wordpress.org/plugins/relative-url/ in Wordpress

Oh my got after so many tries I found this advice with this plugin and IT WORKS. It finally works... Neither of the else plugins worked, not defining absolute WP_SITEURL/HOME, not changing database... Just these 2 lines, this relative-url plugin and ngrok with command `ngrok http -host-header=rewrite wp.myserver` and voila. Thank you so much :-)

**Comment by omaratta2** [comment]
I have the same, issue while using SSL, I added these two lines but and even replaces HTTP with HTTPS but nothing changed. I'm using an auto-generated SSL certificate from Laragon local server.

**Comment by nkpz** [comment]
> > The following steps worked for me
> > 
> > 1. Update ngrok (Ctrl+u when ngrok is running)
> > 2. adding the following two lines to wp-config:
> >    `define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);`
> >    `define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);`
> > 3. Installing https://wordpress.org/plugins/relative-url/ in Wordpress
> 
> Oh my got after so many tries I found this advice with this plugin and IT WORKS. It finally works... Neither of the else plugins worked, not defining absolute WP_SITEURL/HOME, not changing database... Just these 2 lines, this relative-url plugin and ngrok with command `ngrok http -host-header=rewrite wp.myserver` and voila. Thank you so much :-)

Confirming that `host-header=rewrite` worked for me too! Thank you.

**Comment by oma-web-guy** [comment]
i tried this same meth

> The following steps worked for me
> 
> 1. Update ngrok (Ctrl+u when ngrok is running)
> 2. adding the following two lines to wp-config:
>    `define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);`
>    `define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);`
> 3. Installing https://wordpress.org/plugins/relative-url/ in Wordpress

i tried this same method but it did not work for me ,am using a xampp local server on mac

**Comment by arifktk32** [comment]
> > The following steps worked for me
> > 
> > 1. Update ngrok (Ctrl+u when ngrok is running)
> > 2. adding the following two lines to wp-config:
> >    `define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);`
> >    `define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);`
> > 3. Installing https://wordpress.org/plugins/relative-url/ in Wordpress
> 
> Oh my got after so many tries I found this advice with this plugin and IT WORKS. It finally works... Neither of the else plugins worked, not defining absolute WP_SITEURL/HOME, not changing database... Just these 2 lines, this relative-url plugin and ngrok with command `ngrok http -host-header=rewrite wp.myserver` and voila. Thank you so much :-)

This solution worked for me with a little change in the `ngrok` command. Instead of a single dash(hyphen) before the flag `host-header`, I had to write double dash/hyphen in the command `ngrok http --host-header=rewrite myvhost.test:8001`. You should replace the `myvhost.test:8001` with your own version of virtual host domain and port.

**Comment by Cristishor201** [comment]
> > The following steps worked for me
> > 
> > 1. Update ngrok (Ctrl+u when ngrok is running)
> > 2. adding the following two lines to wp-config:
> >    `define('WP_SITEURL', 'http://' . $_SERVER['HTTP_HOST']);`
> >    `define('WP_HOME', 'http://' . $_SERVER['HTTP_HOST']);`
> > 3. Installing https://wordpress.org/plugins/relative-url/ in Wordpress
> 
> Oh my got after so many tries I found this advice with this plugin and IT WORKS. It finally works... Neither of the else plugins worked, not defining absolute WP_SITEURL/HOME, not changing database... Just these 2 lines, this relative-url plugin and ngrok with command `ngrok http -host-header=rewrite wp.myserver` and voila. Thank you so much :-)

I found on [stackoverflow](https://stackoverflow.com/questions/45425721/invalid-host-header-when-ngrok-tries-to-connect-to-react-dev-server) this solution:
`ngrok http --host-header=rewrite 8080`
and the port 8080 should match the same port for MAMP / WAMP/ etc
