### ISSUE TITLE
Ngrok doesn't run on Linux/ARMhf

### ISSUE THREAD

**Issue by kousha-icracked** [inconshreveable/ngrok#318]
I'm trying to setup my own ngrok server. I have successfully tested this server when I connect with a Mac OS X, but with a Linux/ARMhf, I'm having problems. 

To compile the ngrok from source, I did:

    git clone https://github.com/inconshreveable/ngrok.git ngrok
    cd ngrok
    make release-client

I also copied over `ngrokroot.crt` to the folder `./assets/client/tls/ngrokroot.crt` before running `make`. I created a simple config file:

```
server_addr: myserver.com:4443
trust_host_root_certs: false
log_level: info
log_format: json
log: /var/log/ngrok.log
```
Then I ran my ngrok with `./ngrok -subdomain linux -config=./ngrok.cfg 8080` where on port `8080`, I'm running a simple web app. 

When I do this, on the server, I do get a new connection and it seems like it is established, but on the client/linux machine, nothing happens. It seems like the page command line just freezes (i.e. I do not get this:

```
Tunnel Status                 online
Version                       2.0/2.0
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://92832de0.ngrok.io -> localhost:80
Forwarding                    https://92832de0.ngrok.io -> localhost:80
```

I also tried to just download the Linux/Arm version directly from the Ngrok site, but running it returns the following error:

`err="user: Current not implemented on linux/arm"`

**Comment by inconshreveable** [comment]
Not sure how you're getting `Version 2.0` unless you changed that yourself. That looks like you're using an ngrok 2.0 binary from the website. 2.X is not compatible with 1.X. If you want to build a client to talk to your server you'll need to compile it from the source.

**Comment by kousha-icracked** [comment]
But I am compiling the source file from the git repository. The full tutorial that I have followed is [this](https://www.svenbit.com/2014/09/run-ngrok-on-your-own-server/)

Again, the client works absolutely fine when i run it from a Mac machine, but not at all when I run it from the linux arm machine.

**Comment by kousha-icracked** [comment]
This issue still has not been resolved. I am compiling `ngrok` from source. And I am sure that to the best of my knowledge, I am doing it right since the compiling works on a Mac OS X, but fails on a Linux ARM.

**Comment by inconshreveable** [comment]
if there's any error output at all from the source-compiled linux/arm binary, that'd be the easiest way to figure out what's going on. you said it freezes?

**Comment by kousha-icracked** [comment]
There are no errors/info. I enter the command:

`./ngrok -subdomain linux -config=./ngrok.cfg 8080`

And that is it, nothing else happens.

**Comment by inconshreveable** [comment]
could be the the configuration file or the source build is set up to disable the console UI for some reason, but I'm not really sure =/ might want to try enabling logging

**Comment by kousha-icracked** [comment]
I updated the config file to include `log_level: debug`. But no log files are created. Am I not enabling logging with that config file?
