### ISSUE TITLE
URL rewrites

### ISSUE THREAD

**Issue by Jmrich** [inconshreveable/ngrok#319]
Does ngrok support url rewrites? Not sure if anyone else has run into this or not, but when using ngrok the urls aren't served as ngrok.some-ip.io/some-url. Instead the are served as domain.dev/some-url which causes the urls to be returned as not found. I just tried out Finch and they do support rewriting all urls to the correct url, but I wasn't sure if ngrok had something like that that I couldn't find. BTW I am using host-header as I have multiple dev sites.

**Comment by inconshreveable** [comment]
ngrok 2.x supports rewriting the host header with the `host-header` option. very few if any clients include the full URL in the request line anymore, so rewriting the host header is usually enough.

ngrok 1.x support neither host header nor URL rewriting

**Comment by Jmrich** [comment]
Okay. Because when I use something like twilio its giving them the host-header of my dev site to try to fetch any other urls like domain.dev instead of ngrok.io. More than like likely something with the web server(homestead)?

**Comment by inconshreveable** [comment]
ah, I think I understand.

yes, that's some kind of issue with how your application server is construction the URLs that you're handing back to twilio.

ngrok does not rewrite redirects or URLs in the body of the response that you return

**Comment by fastmover** [comment]
I wouldn't say absolute URLs are an issue in the application, however, if ngrok had a URL replacement parameter for the response body that would be a really cool feature. 👍 🥇
