### ISSUE TITLE
Feature Request: Request Timestamp

### ISSUE THREAD

**Issue by abdielou** [inconshreveable/ngrok#320]
Hi,

This is a duplicate of issue #291.

You said back then that you might add it for v2. Was this implemented? How can I enable it?

**Comment by inconshreveable** [comment]
v2 support might be added eventually, but it has not been yet.

closing, as this repo is only for v1 issues

**Comment by nratter** [comment]
I second this. Would be nice to have a timestamp on the log.

**Comment by russorat** [comment]
continued in https://github.com/ngrok/ngrok/issues/8
