### ISSUE TITLE
Monitoring connection, and checking authtoken on self-hosted Ngrokd

### ISSUE THREAD

**Issue by kousha-icracked** [inconshreveable/ngrok#321]
I have setup my own `ngrokd` server. Now, I want to both monitor connections and the authtoken provided by the clients.

A client would call my server with:

     ngrok -authtoken=123abc -subdomain=myName -config=./ngrok.cfg 80

How do I then on the server intercept this, ensure that `authtoken` is valid before accepting the connection, and then also monitor usage/bandwidth?

**Comment by inconshreveable** [comment]
You'll need to fork the code to add some kind of authentication hook and then add an identity management system (/w database) or integrate with an existing one. Monitoring usage and bandwidth will also require modifying the code to collect those statistics.

Per the issue policy, this is not a critical bug in ngrok 1.x, closing.

**Comment by sr105** [comment]
If it helps, I only have one client authtoken and did it this way. Also, zero authentication is a bug IMO. Even if the code were simply modified to allow auth tokens from a simple text file, that would be sufficient for most.

```
diff --git a/src/ngrok/server/control.go b/src/ngrok/server/control.go
index 62f1a15..d0a3deb 100644
--- a/src/ngrok/server/control.go
+++ b/src/ngrok/server/control.go
@@ -101,6 +101,11 @@ func NewControl(ctlConn conn.Conn, authMsg *msg.Auth) {
                return
        }

+       if authMsg.User != "123abc" {
+               failAuth(fmt.Errorf("Invalid authtoken %s", authMsg.User))
+               return
+       }
+
        // register the control
        if replaced := controlRegistry.Add(c.id, c); replaced != nil {
                replaced.shutdown.WaitComplete()
```

**Comment by shellus** [comment]
@sr105 thx
