### ISSUE TITLE
Named tunels

### ISSUE THREAD

**Issue by luanfonceca** [inconshreveable/ngrok#324]
Hi folks, i would like to create somekind of named tunels, instead of generating some random url, it would give me something like: 

```
$ ngrok http 8000 --name myurl

ngrok by @inconshreveable                                                                                                                                  (Ctrl+C to quit)

Tunnel Status                 online
Version                       2.0.25/2.0.25
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040
Forwarding                    http://myurl.ngrok.io -> localhost:8000
Forwarding                    https://myurl.ngrok.io -> localhost:8000
```

Thanks in advance and sorry if this makes no sense at all.

o/

**Comment by inconshreveable** [comment]
This is available via the `-subdomain` option. Docs are here: https://ngrok.com/docs#subdomain

Closing this out as it's a question about ngrok 2.0. If you need continued help with this, please email contact@ngrok.com
