### ISSUE TITLE
allow ping timeout to be configurable

### ISSUE THREAD

**Issue by umasudhan** [inconshreveable/ngrok#325]
The ping timeout is currently hardcoded to 30 seconds in 
https://github.com/inconshreveable/ngrok/blob/master/src/ngrok/server/control.go#L16

It would help if this can be populated form the config file (to deal with bad connections for example)

**Comment by inconshreveable** [comment]
Yep, that seems like a very reasonable change for those who need it.

Closing, per ngrok's repository issue policy and this is not a crash or other failure of ngrok's functionality.

**Comment by Jlonghi** [comment]
did this feature ever get implemented?
