### ISSUE TITLE
MAKE this SHIT AGAIN OPEN SOURCE

### ISSUE THREAD

**Issue by TcG3nisys** [inconshreveable/ngrok#326]
MAKE this SHIT AGAIN OPEN SOURCE MAKE this SHIT AGAIN OPEN SOURCE MAKE this SHIT AGAIN OPEN SOURCE. We need more stuff like this to BE OPEN SOURCE !!!!!!

**Comment by inconshreveable** [comment]
thanks, i appreciate the sentiment, but there are no plans to do that

**Comment by TcG3nisys** [comment]
Aham but why guys? I never saw thing like that from open source to closed source. Most of the software goes from closed source to open source you go open soure to closed source.
