### ISSUE TITLE
import cycle not allowed

### ISSUE THREAD

**Issue by ZhuChaozheng** [inconshreveable/ngrok#328]
Dear inconshreveable,
    When I first build this project at 2015.12, I had finished successfully! Now, I want to build it again. However, it always errors,like it.
![image](https://cloud.githubusercontent.com/assets/8834221/14579888/51e79f26-03ed-11e6-8142-c14f4d4a54b5.png)
My environment is go1.4.2, Thank you for your listening!

**Comment by StudioEtrange** [comment]
give a try to https://github.com/StudioEtrange/ngrok-build

**Comment by inconshreveable** [comment]
this is some kind of issue with your set up, not sure what. maybe try a more recent version of Go?
