### ISSUE TITLE
be able to modify parameters when 'replaying' a server call

### ISSUE THREAD

**Issue by eroncanc** [inconshreveable/ngrok#329]
ngrok has been incredibly useful for me. would it be hard to allow editing a server call when looking at localhost:4040? What about exporting/importing the history/different calls for future use?

Those are two features would make life even better, and I'd be willing to put time to code them, thanks!

**Comment by inconshreveable** [comment]
definitely planned and on the roadmap for v2. not happening for v1, so closing this issue (this repo is only for v1 issues)
