### ISSUE TITLE
Does not work on Windows 32bit

### ISSUE THREAD

**Issue by mrizwan47** [inconshreveable/ngrok#331]
I tried it on Windows 7 32 bit, but it gave me this error:

`This version of E:\Development 2016\ngrok.exe is not compatible with the version
 of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.`

**Comment by inconshreveable** [comment]
Please click "More platforms" on the downloads page for 32-bit downloads: https://ngrok.com/download

This is not an issue with ngrok v1, closing.

**Comment by ruanqibu** [comment]
Hi,
I created a ngrok server on my centos7, make ngrokd for centos and ngrok.exe client for windows is finished, but the ngrok.exe client cant not work both windows7 and windows10, the error is the same with @mrizwan47's , my ngrok version is 2.x，how can i make a correct ngrok.exe client for windows, could you give me any solution please ?
Thank you very much !
