### ISSUE TITLE
SSH connection timeout

### ISSUE THREAD

**Issue by alberto2000** [inconshreveable/ngrok#333]
config file:
...
  ssh-access:
    addr: 22
    proto: tcp
    remote_addr: 1.tcp.eu.ngrok.io:xxxxx

Trying to connect with:
ssh -pxxxxx pi@1.tcp.eu.ngrok.io
...but the gets connection timeout

What could be the issue?

**Comment by inconshreveable** [comment]
hard to say, but please send me an email (alan at ngrok dot com) and I'd be happy to help you get this working and resolved.

this repository is only for issues with ngrok v1, closing.
