### ISSUE TITLE
After clearing the terminal ngrok won't redraw

### ISSUE THREAD

**Issue by jakeonrails** [inconshreveable/ngrok#334]
<img width="630" alt="screen shot 2016-04-25 at 4 00 31 pm" src="https://cloud.githubusercontent.com/assets/580084/14801555/def1f336-0afe-11e6-8d6f-0a56154cc221.png">

To reproduce:

1. Start ngrok
2. Hit Apple+K or Apple+R to clear your terminal screen
3. Witness ngrok not redraw any useful information.

Don't know if this is working as intended or clearing the terminal was never a use case that was built for.

My use case here was that I've got a bunch of requests already logged to the screen, I wanted to clear them out so I could focus on one request at a time. I do this a lot with my web server logs when doing testing of a single request.

**Comment by inconshreveable** [comment]
Not sure what version you're running here, but this is not a supported use case in any version of ngrok. ngrok 2.0 does have the ability to clear the request log from the web interface which will clear the requests in the terminal.
