### ISSUE TITLE
Compile the client error : unknown tls.Config field 'GetCertificate' in struct literal

### ISSUE THREAD

**Issue by mindcont** [inconshreveable/ngrok#335]
Hi,when i compile myself ngrok , i got an error like this 
![unknown tls config field](https://cloud.githubusercontent.com/assets/13744152/14911730/e94e3956-0e29-11e6-9bc5-63d41a4978c4.png)
than i go to [https://github.com/gorilla/websocket/blob/master/client.go](https://github.com/gorilla/websocket/blob/master/client.go) check out these three filelds like this
![client go](https://cloud.githubusercontent.com/assets/13744152/14912052/50e1c040-0e2c-11e6-964b-5ed1f8262bc6.png)
is i am alone? how can i fix this ? thanks a lot

**Comment by inconshreveable** [comment]
Please make sure to Compile with the latest version of Go (1.6). You can check with `go version`

**Comment by backylee** [comment]
problem solved？ same error

**Comment by mindcont** [comment]
@backylee 

 yes, like @inconshreveable  said ,you should make sure to Compile wite **Go version (1.6)** at last

**Comment by xiaohuanshu** [comment]
same error,but i have the latest version(1.6.2)

**Comment by itayo** [comment]
same issue for me and im on 1.6

**Comment by shawxing** [comment]
I have the same error on go version 1.7

**Comment by shl-kfy** [comment]
1.7 ok ( uninstall old firstly make sure root is new

**Comment by jmccorm** [comment]
I got around it with **go get github.com/bbb31/slurp** but then I ran into additional errors in gorilla's github project.
