### ISSUE TITLE
ngrok hosted service strips Authorization header

### ISSUE THREAD

**Issue by cbenard** [inconshreveable/ngrok#336]
I'm running `ngrok http 80` on OS X. Just downloaded latest stable 4 days ago.

A remote service is sending me an HTTP POST with an `Authorization: JWT [jwt token text here]` header. I thought they had a bug, but then I noticed in production, I do receive it.

I tested and reproed, and it appears that ngrok hosted service is stripping the `Authorization` header. I am not using any basic auth options with the command line tool. Only `ngrok http 80` and then using the https URL from ngrok to tunnel to my localhost http 80.

**Comment by inconshreveable** [comment]
ngrok (any version) does not strip any headers, so there's something odd going on here

can you please email me (alan at ngrok dot com) to resolve this? this repository is only for issues related to ngrok v1

**Comment by VSilantyev** [comment]
It was php issue, php does not include Authorization header under apache.
Workaround:
https://github.com/DABSquared/DABSquaredPushNotificationsBundle/blob/master/Controller/SafariController.php#L338
