### ISSUE TITLE
redirection from old virtualhost to xxxxxxx.ngrok.io in Google Chrome

### ISSUE THREAD

**Issue by deeplomacy** [inconshreveable/ngrok#341]
Hello,

I'm using Google Chrome 50 on Windows 8.1 / WampServer 2.5 with Apache 2.4.9
I'm working on a virtualhost **project.dev**, I wanted to tunnel it with ngrok and tried various command lines and options before managing to make it work.

I have since deleted all traces of this virtualhost in system32/etc/hosts and all wamp aliases.
Now when I enter **project.dev** in Chrome it redirects me to https://73a8c231.ngrok.io/ even when Wamp is not running.
My guess is that I messed up with the **-host-header=rewrite** option.

Does anybody have a clue how to get back to a normal url not found?
Thanks!

**Comment by inconshreveable** [comment]
This is almost 100% Chrome caching the redirect response. (Try it another browser that you don't normally use and you'll get what you expect).

**Comment by deeplomacy** [comment]
Thank you so much for the quick answer !
