### ISSUE TITLE
meet a problem when i go run the source code 

### ISSUE THREAD

**Issue by proudlily** [inconshreveable/ngrok#344]
when i go run the main function of the ngrok ,i meet a problem that

` ngrok/client/tls.go:9:2: no buildable Go source files in ngrok/client/assets`

what it is mean?
the way that i make makefile from ,i found the exe file .it is seccessful .but i go run the main function ,it is failed.

**Comment by inconshreveable** [comment]
You must use the Makefile to generate those files with: `make assets`

**Comment by proudlily** [comment]
i tried to `make assets`,
it truely to make the file of assets_debug.go from the package asserts.but when i tried to `go run main.go` ,it is failded that
`ngrok/client/tls.go:9:2: no buildable Go source files in ngrok/client/assets`

**Comment by seclog** [comment]
you should run it with -tag debug or -tag release

**Comment by proudlily** [comment]
@seclog thx any more!
