### ISSUE TITLE
Invalid address  'xxxx': missing port in address xxxx

### ISSUE THREAD

**Issue by faultylee** [inconshreveable/ngrok#346]
I'm running a self hosted version in docker while the client on Raspberry Pi. Both compiled from latest code from here. My config is
```
server_addr: xxx.xxx.xxx:4443
trust_host_root_certs: false
tunnels:
  test:
    proto:
      tcp: 22
```
I keep getting this error `Invalid address  'test': missing port in address test`. I've been looking around for sample config, this is the closest I can find that almost work. 

I was going through the code in `config.go` and it seems to be caused by `SplitHostPort()`. Incompatible Go version?

 I'm not Go expert but can roughly understand what goes where. Also based on the error message here https://github.com/inconshreveable/ngrok/blob/master/src/ngrok/client/config.go#L227 `test` (the tunnel name from config) end up in `addr` which seems where. 

My end goal is to have a fix port on the server side since I can only preset a fix number of ports to be exposed. Random port doesn't work for docker AFAIK.

**Comment by inconshreveable** [comment]
i'm guessing you're not invoking ngrok properly. you want to be running `ngrok start test`

**Comment by faultylee** [comment]
Thanks. The error is very misleading, lol
