### ISSUE TITLE
I have problem with https

### ISSUE THREAD

**Issue by uangshiyon** [inconshreveable/ngrok#347]
Here is what i did:

I followed this page (https://gist.github.com/lyoshenka/002b7fbd801d0fd21f2f) and finally got own ngrokd server worked, but only http is doing find, and when i tried to connect my localhost server using https , i got “**your connection is not private**” error on chrome and "**Failed to read valid https request: EOF**" on ngrokd server log, any ideas?

My message on client is:
ngrok                                                                                                   (Ctrl+C to quit)

Tunnel Status                 online
Version                       1.7/1.7
Forwarding                    http://web.ngrok.seanhwang.xyz:8000 -> 127.0.0.1:9443
Forwarding                    https://web.ngrok.seanhwang.xyz:8000 -> 127.0.0.1:9443
Web Interface                 127.0.0.1:4040
# Conn                        0
Avg Conn Time                 0.00ms

**Comment by inconshreveable** [comment]
your https and http endpoints shouldn't be listening on the same port (8000). i'm not sure how you configured it to do that, but that would explain why the server it can't properly differentiate between the two protocols

**Comment by uangshiyon** [comment]
I didn't listening on the same port (8000), i don't know why the client shown like this ,my server start script is like this
./ngrokd -domain="my.base.domain" -httpAddr=":8000" -httpsAddr=":8443"

**Comment by LouTerrailloune** [comment]
Same problem here, the custom https port is not properly handled and the https tunnel is not available.

**Comment by chenyongze** [comment]
2018-05-26T23:10:13.927256000Z [23:10:13 UTC 2018/05/26] [INFO] (ngrok/log.(*PrefixLogger).Info:83) [pub:5d776fb8] New connection from 60.10.155.14:55433
2018-05-26T23:10:14.035212000Z [23:10:14 UTC 2018/05/26] [WARN] (ngrok/log.(*PrefixLogger).Warn:87) [pub:5d776fb8] Failed to read valid https request: EOF
2018-05-26T23:10:14.035484000Z [23:10:14 UTC 2018/05/26] [DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:5d776fb8] Closing

**Comment by tommyxu97** [comment]
Have the same problem. I've tried a lot of times, only when I set http port as 80 and https port as 443 it works well. The client will forward the same port when setting other ports.

Tunnel Status                 online                                            
Version                       1.7/1.7                                           
Forwarding                    http://test.ngrok.***.com:5000 -> 127.0.0.1:8080 
Forwarding                    https://test.ngrok.***.com:5000 -> 127.0.0.1:8080
Web Interface                 127.0.0.1:4040                                    
# Conn                        0                                                 
Avg Conn Time                 0.00ms
