### ISSUE TITLE
ngrok as a forward proxy

### ISSUE THREAD

**Issue by pragmasoft-ua** [inconshreveable/ngrok#349]
Is it possible to use ngrok as a forward proxy? Given it does already have a nice introspection UI, it may make sense to use it as a forward proxy to monitor/log/debug outgoing connections..

**Comment by inconshreveable** [comment]
it's not really possible/advised to do that. it's definitely part of the ultimate vision though. good tools for this are charles, mitmproxy and runscope

**Comment by russorat** [comment]
continued in https://github.com/ngrok/ngrok/issues/11
