### ISSUE TITLE
when local is https，how to map？

### ISSUE THREAD

**Issue by Skyuf** [inconshreveable/ngrok#350]
when local server is https ,  how to map?

now I can get a "502 bad gateway" error

**Comment by pyhedgehog** [comment]
Map as a `tcp` tunnel.

**Comment by inconshreveable** [comment]
yep, or if you're using 2.X, a TLS tunnel may work as well

**Comment by Luneya** [comment]
I needed this as well to test some things on our local website before we go into production.
TLS is a paid service in ngrok. Can't try it out to see if it works.
And for TCP you need to sign up. 

But.. the signup page is offline :/

**Comment by burnray** [comment]
Thanks TCP works for me.
