### ISSUE TITLE
Flag `--remote-addr` not working?

### ISSUE THREAD

**Issue by acrodrig** [inconshreveable/ngrok#351]
Hello. Reading the document at https://ngrok.com/docs it said I could get a stable address via a purchased plan.

I went ahead and purchased `ngrok` PRO. Then I reserved an address and now I want to use it the way the document shows:

```
ngrok http --remote-addr 1.tcp.ngrok.io:XXXXX 3000
```

And I get the following error:

```
Incorrect Usage: flag provided but not defined: -remote-addr
```

I have used different variations on the flag (one dash, two dashes, no dashes) and always get the same. Can you help?

**Comment by inconshreveable** [comment]
Remote addrs are for TCP tunnels only, try:

`ngrok tcp --remote-addr 1.tcp.ngrok.io:XXXXX 30000`

or if you wanted a reserved HTTP name, try using a reserved domain instead.

In the future the best support channel for this is email, this repository is only for issues with the older open source v1 version of ngrok.
