### ISSUE TITLE
Invalid configuration property value for 'http_proxy', '127.0.0.1:1080': URL scheme must be 'http' or 'https'

### ISSUE THREAD

**Issue by csi0n** [inconshreveable/ngrok#352]
Invalid configuration property value for 'http_proxy', '127.0.0.1:1080': URL scheme must be 'http' or 'https'  i get this error info when i use 'ngrok http 80',how to fix this error ?

**Comment by inconshreveable** [comment]
prefix the value with `http://`, e.g.:

`http_proxy: http://127.0.0.1:1080`

**Comment by csi0n** [comment]
thanks.i have to repair the problem use
```javascript
set http_proxy=http://127.0.0.1:1080 
```

**Comment by arunprem** [comment]
Invalid configuration property value for 'http_proxy', '192.168.0.1:808': URL scheme must be 'http' or 'https'

but i have no proxy

**Comment by rutansh** [comment]
Invalid configuration property value for 'http_proxy', 'http://127.0.0.1:1080 ': parse http://127.0.0.1:1080 : invalid character " " in host name

**Comment by Kadri-coder** [comment]
Hello i get this error when i try to execute this comand :"ngrok http 8080" Invalid configuration property value for 'http_proxy', '127.0.0.1:1080': URL scheme must be 'http' or 'https'.
How can i solve this error please thanks

**Comment by devAmirHemmati** [comment]
I also had this issue ...
you must be add **sudo**  before your command

**Comment by MMDShen** [comment]
hi i have this error may you help me?
i put: ngrok http 80
i got: ERROR:  Invalid configuration property value for 'http_proxy_env', '127.0.0.1:54565': parse "127.0.0.1:54565": first path segment in URL cannot contain colon

**Comment by MMDShen** [comment]
wow **csi0n** idea helped me too
