### ISSUE TITLE
Basic Auth doesn't work on Windows 64

### ISSUE THREAD

**Issue by phathvu** [inconshreveable/ngrok#353]
I tried to install ngrok on Windows 10 64bit (ngrok version 2.1.3)
Then, started by running the following command: **"ngrok http -auth="test:123456" 8080"**
I could access to http://localhost:4040/, but failed to access to tunnel (e.g. http://33a92d55.ngrok.io/)
even I passed correct username/password. I also tested with Postman but no luck.

**Comment by inconshreveable** [comment]
not sure what's going on but this is unrelated to the v1 OSS project and not windows specific. that looks like a proper invocation of ngrok
