### ISSUE TITLE
Build failed in Ubuntu.

### ISSUE THREAD

**Issue by cnisky** [inconshreveable/ngrok#354]
I download the source code and build it in Ubuntu 14.04 64bit, but error occurred.
Can you tell me why? 
I didn't find solution in google. thanks.

root@iZ23zd5vrnsZ:~/ngrok# make release-server release-client 
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
                -debug=false \
                -o=src/ngrok/client/assets/assets_release.go \
                assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
                -debug=false \
                -o=src/ngrok/server/assets/assets_release.go \
                assets/server/...
go get -tags 'release' -d -v ngrok/...
go install -tags 'release' ngrok/main/ngrokd
go install -tags 'release' ngrok/main/ngrok
# github.com/gorilla/websocket
src/github.com/gorilla/websocket/client.go:361: unknown tls.Config field 'GetCertificate' in struct literal
src/github.com/gorilla/websocket/client.go:370: unknown tls.Config field 'ClientSessionCache' in struct literal
src/github.com/gorilla/websocket/client.go:373: unknown tls.Config field 'CurvePreferences' in struct literal
make: *** [client] Error 2
root@iZ23zd5vrnsZ:~/ngrok#

**Comment by inconshreveable** [comment]
Please build with the latest version of Go (1.7)
