### ISSUE TITLE
complie error

### ISSUE THREAD

**Issue by tb4coding** [inconshreveable/ngrok#355]
src/github.com/gorilla/websocket/client.go:361: unknown tls.Config field 'GetCertificate' in struct literal
src/github.com/gorilla/websocket/client.go:370: unknown tls.Config field 'ClientSessionCache' in struct literal
src/github.com/gorilla/websocket/client.go:373: unknown tls.Config field 'CurvePreferences' in struct literal

**Comment by inconshreveable** [comment]
please compile with the latest version of Go. thanks!

**Comment by iCrany** [comment]
![image](https://cloud.githubusercontent.com/assets/4019401/21288222/09fcf92c-c4b8-11e6-81c7-44583d4ec5c1.png)
Go version 1.7, but still got this errors
