### ISSUE TITLE
Tunnel session failed

### ISSUE THREAD

**Issue by KharitonOff** [inconshreveable/ngrok#358]
Hello,
since yesterday I cann't use ngrok anymore with my subdomain. I've lost my connection to the open session and now i can't restart it. Following message is shown:

```
Tunnel session failed: Your account 'XYZ' is limited to 1 simultaneous ngrok client session.
Active ngrok client sessions in region 'us':
  - 414c40ed9afc1756ffa78f2d32fc3617 (155.56.44.134:63846)
```
I've got this issue using ngrok@2.0.0

**Comment by inconshreveable** [comment]
please email contact@ngrok.com - this repository is only for issues with the open source project, thanks!

**Comment by shannuu** [comment]
Just type "killall ngrok" to terminate all your ngrok sessions and this worked for me
