### ISSUE TITLE
Header size limit causes 502 Bad Gateway

### ISSUE THREAD

**Issue by gullij** [inconshreveable/ngrok#360]
When tunneling HTTP traffic ngrok seems to impose a header size limit to the HTTP response.

Sending logging information to chrome-logger (https://craig.is/writing/chrome-logger/) can create a large HTTP response header that seems to cause ngrok send forward a 502 Bad Gateway but the ngrok inspector shows a valid response.

Accessing the same page locally will not generate that error unless you override your browser limit (256KiB in Chrome).

**Comment by dpolivy** [comment]
I think I may be hitting this -- we're setting a lot of cookies in a request and I'm getting a 502 from ngrok. Have you found any way to increase the ngrok limit or work around this issue?

**Comment by gullij** [comment]
Nope, we had to stop the chrome-logger data being sent in the header to cut the header size. Fortunately for us we had no use for this data, don't even know why it was active in the first place.

The ngrok problem remains as far as I know and I didn't find any way around it.

**Comment by inconshreveable** [comment]
This has been fixed. ngrok now supports larger headers and more lines per header. 16KB headers and up to 256 individual header lines

**Comment by terrydemco** [comment]
Chrome accepts headers up to 250KB, and utilities such as chromelogger generate headers up to 250KB. This limit needs to be upped to 250KB.

**Comment by synth** [comment]
We're hitting this with ScoutApp which adds a 58KB header for debugging. See above linked issue.
