### ISSUE TITLE
Possible to instruct ngrok to not insert X-Forwarded-* lines in header?

### ISSUE THREAD

**Issue by johngu** [inconshreveable/ngrok#362]
Sorry for posting the issue here but I could not find anything online about this.  I'm using ngrok to test out AWS API Gateway.  It seems that X-Forwarded-* lines causes called to get dropped by AWS.  Any way for me to instruct ngrok to stop inserting those lines?

**Comment by inconshreveable** [comment]
That's not possible at the moment, but it's a feature slated for the future. (of 2.x, not this project)
