### ISSUE TITLE
ngrok "host-header" not working. 

### ISSUE THREAD

**Issue by nasirkhan** [inconshreveable/ngrok#369]
I am using `ngrok version 2.1.14` and tried to use the command, `ngrok http -host-header=messenger-bot.dev 80`. But unfortunately i got the following error. `You may only specify one port to tunnel to on the command line, got 3: [http -host-header=messenger-bot.dev 80]`

need assistance to resolve this issue.

**Comment by inconshreveable** [comment]
you're not using version 2.1.4. You're using an older version (1.X). You can verify this by running `ngrok version`. You'll want to remove that binary from your system or download ngrok 2.X from https://ngrok.com/download and then invoke it with an absolute path, e.g. `/path/ngrok/ngrok http ...`
