### ISSUE TITLE
Headless mode

### ISSUE THREAD

**Issue by wprater** [inconshreveable/ngrok#37]
Would be nice to have a headless mode so I can run my proxies in foreman.

**Comment by brejoc** [comment]
@inconshreveable how am I getting the random subdomain when running ngrok in headless mode and not being able to access the web interface on port 4040?

**Comment by inconshreveable** [comment]
@brejoc not sure what version you're running, but if it's 2.0, please email me, this repository is only for issues with v1

**Comment by brejoc** [comment]
@inconshreveable Thanks, I just emailed you. I'm indeed using version 2.0.25.
