### ISSUE TITLE
termbox: fails to start on dump terminal (emacs shell)

### ISSUE THREAD

**Issue by velimir0xff** [inconshreveable/ngrok#370]
Fails to start with error
```
consoleui failed: Failed to initialize terminal: termbox: error while reading terminfo data: EOF
```

**Comment by inconshreveable** [comment]
Fun! ngrok hasn't been tested to run under an emacs shell, I'll put this on the backlog. For now, your best bet is to run it from another terminal.

This is not an issue with the 1.x OSS project, closing.

**Comment by mozey** [comment]
I get this same error in my dev environment:

OSX 10.10.5
VMWare Fusion Version 7.1.2
Ubuntu Server 12.04.3

SHH to Ubuntu with Terminal.app version 2.5.3, then

    > echo $0
    -bash

    > ./ngrok http 80
    consoleui failed: Failed to initialize terminal: termbox: error while reading terminfo data: termbox: unsupported terminal
