### ISSUE TITLE
unable to see output of ngrok.exe

### ISSUE THREAD

**Issue by oguzhantopcu** [inconshreveable/ngrok#372]
I'm connecting to my windows server via ssh, when I type "ngrok.exe http 80" in server, I can't see the new opening window that contains public url. is there any way to see output of the ngrok window?

**Comment by inconshreveable** [comment]
Sounds like a problem with how windows is doing TTYs. Windows SSH is new, it's not too surprising that this isn't working yet.

**Comment by inconshreveable** [comment]
This is an issue with ngrok 2.0, closing.
