### ISSUE TITLE
Better support for "light" terminal themes

### ISSUE THREAD

**Issue by rafaelrinaldi** [inconshreveable/ngrok#375]
First of all, I love ngrok. Thanks a lot for creating this awesome tool and for making it open source 👍 

So, I'm not really a fan of dark themes which means my terminal windows always have a light background. The thing is, I don't think ngrok really plays well with them. See:

![screen shot 2016-10-18 at 3 34 25 pm](https://cloud.githubusercontent.com/assets/87162/19493435/97427d38-9548-11e6-94b4-27e5d075aeae.png)
<sup><i>I have `console_ui_color` set to `transparent` and I use the papercolor theme for iTerm2</i></sup>

I'm willing to give this a try and introduce the concept of "themes" (at least light/dark) and create a way to specify this option via configs. Right now the only thing we have is `console_ui_color` which is not enough as you can see on my screenshot.

Just wanted to know two things:

1) Are you interested in adding this feature at all?
2) Do you have anything specific in mind for the implementation before I give it a shot?

Thanks!

**Comment by inconshreveable** [comment]
this project is no longer taking PRs except for critical bugfixes, but i appreciate the offer.

as for 2.x: a better 'light' based color scheme may come to ngrok at somepoint, but it's not going to happen anytime soon, sorry!
