### ISSUE TITLE
Every HTTP request is triggering a new connection

### ISSUE THREAD

**Issue by jayfresh** [inconshreveable/ngrok#376]
I've just installed the latest version of ngrok - server 2.1.8, and I'm finding that when I access a site running on 127.0.0.1, every HTTP request adds to the total connections, meaning I hit the connection limit really quickly.

The docs say that you shouldn't hit this limit if your browser uses keep-alive HTTP headers you'll be ok. However, I've tried this in Chrome and Firefox and they look to be using the keep-alive header.

Any thoughts about why I'd be having this problem?

**Comment by inconshreveable** [comment]
That's pretty weird. Is your local site sending back `Connection: close`? please ping me via email, this is for ngrok v1 issues only now

**Comment by dmorehead** [comment]
I'm seeing the same thing OSX v2.1.18  "too many connections" very quickly on my webgl app.

..otherwise, ngrok is F***ing awesome!

**Comment by shoshi** [comment]
Was there any resolution to this problem? I'm having the same issue running version 2.2.8 on macOS 10.12.6.

**Comment by dmorehead** [comment]
ah yes, the limitation went away as soon as I signed up for the free account on ngrok.
