### ISSUE TITLE
Is it possible to expose an HTTP proxy on localhost via ngrok?

### ISSUE THREAD

**Issue by vaharoni** [inconshreveable/ngrok#379]
I have `tinyproxy` installed on localhost (I also tried `squid` and failed similarly). It runs on port `8888`. This works:
```bash
curl -x localhost:8888 http://www.google.com
```
And I see output in the `tinyproxy` logs.

Now I run the latest version of `ngrok` and get the following forwarding established:
```
http://<identifier>.ngrok.io -> localhost:8888
```
If I open `http://<identifier>.ngrok.io` on my browser the `ngrok` connection counter goes up, and I successfully see `tinyproxy`'s "not implemented" error page.

However, this fails:
```bash
curl -x <identifier>.ngrok.io:80 http://www.google.com
# => curl: (56) Received HTTP code 404 from proxy after CONNECT
```
The `ngrok` counter does not go up, and I do not see messages in the `tinyproxy` logs, suggesting that the failure is before `ngrok` accepted the connection.

Is this something that `ngrok` cannot do?

**Comment by inconshreveable** [comment]
ngrok will not send through forward proxy requests (just as you wouldn't expect haproxy or nginx to do that either). you can do it with a TCP tunnel though:

ngrok tcp 8888
