### ISSUE TITLE
Ubuntu PPA?

### ISSUE THREAD

**Issue by cowboy** [inconshreveable/ngrok#381]
It would be really nice to have the latest ngrok installable via `apt-get`. Thanks!

**Comment by Schweigert** [comment]
1 ano pra por um PPA ¬¬ :broken_heart:

**Comment by seddighi78** [comment]
Please make the Ngrok PPA it would be really nice.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
