### ISSUE TITLE
After waking computer from sleep, session status is permanently reconnecting.

### ISSUE THREAD

**Issue by jcready** [inconshreveable/ngrok#382]
```
Session Status reconnecting (Your account may not run more than 12 tunnels over a single ngrok client session. The tunnels already running on this session are: ...
```

The session status provided by ngrok claims that the tunnels I had configured are still running, but they clearly are not because I cannot receive a response from any of them (while they still respond when hitting localhost:port directly). I can temporarily resolve the issue by exiting the ngrok process and restarting it. Is there a way to fix this issue permanently so that ngrok is able to successfully reconnect when waking my computer from sleep?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
