### ISSUE TITLE
ngrok crashed!

### ISSUE THREAD

**Issue by Sidong** [inconshreveable/ngrok#383]
panic: sync: inconsistent mutex state

goroutine 47 [running]:
ngrok/util.MakePanicTrace(0x4391c0, 0xc8204b6770, 0x0, 0x0)
	/Users/STONE/Downloads/ngrok/src/ngrok/util/errors.go:19 +0x89
ngrok/client.(*Controller).Go.func1.1(0xc82007cc00)
	/Users/STONE/Downloads/ngrok/src/ngrok/client/controller.go:90 +0x5c
panic(0x4391c0, 0xc8204b6770)
	/usr/local/Cellar/go/1.6.2/libexec/src/runtime/panic.go:443 +0x4e9
sync.(*Mutex).Lock(0xc8201682ec)
	/usr/local/Cellar/go/1.6.2/libexec/src/sync/mutex.go:75 +0x16d
github.com/rcrowley/go-metrics.(*StandardEWMA).Rate(0xc8201682d0, 0x0)
	/Users/STONE/Downloads/ngrok/src/github.com/rcrowley/go-metrics/ewma.go:89 +0x3a
github.com/rcrowley/go-metrics.(*StandardMeter).updateSnapshot(0xc820091500)
	/Users/STONE/Downloads/ngrok/src/github.com/rcrowley/go-metrics/meter.go:195 +0xb7
github.com/rcrowley/go-metrics.(*StandardMeter).Mark(0xc820091500, 0x1)
	/Users/STONE/Downloads/ngrok/src/github.com/rcrowley/go-metrics/meter.go:147 +0x10f
github.com/rcrowley/go-metrics.(*StandardTimer).Update(0xc820168330, 0xeb7ba0503f277174)
	/Users/STONE/Downloads/ngrok/src/github.com/rcrowley/go-metrics/timer.go:221 +0xce
github.com/rcrowley/go-metrics.(*StandardTimer).Time(0xc820168330, 0xc820061920)
	/Users/STONE/Downloads/ngrok/src/github.com/rcrowley/go-metrics/timer.go:213 +0x75
ngrok/client.(*ClientModel).proxy(0xc820162dd0)
	/Users/STONE/Downloads/ngrok/src/ngrok/client/model.go:393 +0x10a1
ngrok/client.(*ClientModel).(ngrok/client.proxy)-fm()
	/Users/STONE/Downloads/ngrok/src/ngrok/client/model.go:295 +0x20
ngrok/client.(*Controller).Go.func1(0xc82007cc00, 0xc8200b6dc0)
	/Users/STONE/Downloads/ngrok/src/ngrok/client/controller.go:96 +0x44
created by ngrok/client.(*Controller).Go
	/Users/STONE/Downloads/ngrok/src/ngrok/client/controller.go:97 +0x3f

**Comment by elimisteve** [comment]
What were you trying to do when this panic occurred?

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
