### ISSUE TITLE
Transparently forwarding HTTP `Host` headers

### ISSUE THREAD

**Issue by elimist** [inconshreveable/ngrok#387]
Hello,

I have a couple of HTTP services behind a reverse proxy that relies on HTTP `host` headers to properly route requests upstream. 

Is there any way to make ngrok simply forward the incoming request's `Host` header as-is?
I know there is an option to rewrite or specify headers via `ngrok http -host-header=rewrite xxx:80` and `ngrok http -host-header=xxx 80`, but these only allow requests to the one specified virtual host to go through.

What I would like is that ngrok simply passes the `Host` header on through to the local proxy transparently so that any client can specify an arbitrary `Host` in the request header.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
