### ISSUE TITLE
Error after unziping and running ./ngrok on Ubuntu bash(14.04) for Windows 10 (x64)

### ISSUE THREAD

**Issue by gopalrander** [inconshreveable/ngrok#390]
I am trying ngrok first time. Am I missing some configuration? 
-------------------------------------------------------------------------------------------------------------------
unexpected fault address 0x0
fatal error: fault
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x727b53]

goroutine 1 [running, locked to thread]:
runtime.throw(0xa632b3, 0x5)
        /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc42003b790 sp=0xc42003b770
runtime.sigpanic()
        /usr/local/go/src/runtime/sigpanic_unix.go:27 +0x288 fp=0xc42003b7e8 sp=0xc42003b790
github.com/go-stack/stack.findSigpanic.func1(0x0, 0xc42003b828, 0x0)
        /Users/aes/src/ngrok/vendor/src/github.com/go-stack/stack/stack.go:228 +0x53 fp=0xc42003b810 sp=0xc42003b7e8
github.com/go-stack/stack.findSigpanic(0xa72801)
        /Users/aes/src/ngrok/vendor/src/github.com/go-stack/stack/stack.go:229 +0x3d fp=0xc42003b840 sp=0xc42003b810
github.com/go-stack/stack.init()
        /Users/aes/src/ngrok/vendor/src/github.com/go-stack/stack/stack.go:233 +0xa2 fp=0xc42003b870 sp=0xc42003b840
github.com/inconshreveable/log15.init()
        /Users/aes/src/ngrok/vendor/src/github.com/inconshreveable/log15/syslog.go:56 +0x80 fp=0xc42003b8b0 sp=0xc42003b870
lib/shared.init()
        /Users/aes/src/ngrok/src/lib/shared/version.go:15 +0x47 fp=0xc42003b8b8 sp=0xc42003b8b0
main.init()
        /Users/aes/src/ngrok/src/ngrok/web_ui.go:568 +0x8d fp=0xc42003bf48 sp=0xc42003b8b8
runtime.main()
        /usr/local/go/src/runtime/proc.go:172 +0x1bf fp=0xc42003bfa0 sp=0xc42003bf48
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc42003bfa8 sp=0xc42003bfa0

**Comment by anoop901** [comment]
I am running into this same exact issue, with the same error message.

**Comment by vsub21** [comment]
I am as well, any advice?

**Comment by mbardelmeijer** [comment]
See #364:

> ngrok doesn't support running on windows bash yet (it's still in beta). this will be supported eventually when that product is stable.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
