### ISSUE TITLE
Allow for ngrok.yml to be shipped with the project

### ISSUE THREAD

**Issue by dkarlovi** [inconshreveable/ngrok#391]
I use ngrok as a sort of `vagrant share` replacement while developing on Docker. Mostly, it means I run `docker-compose up` on my local machine and then `ngrok http <port>`.

Please consider adding an ability to find&merge configuration files from CWD onward. It would be very useful if ngrok would allow for `.ngrok.yml` to be in the current folder (too), probably with heuristic searching and merging similar to [what Vagrant does](https://www.vagrantup.com/docs/vagrantfile/#lookup-path).

Basically
1) I have a project in `$HOME/Dev/Project`, running on Docker Compose on port 8000
2) I have a (versioned) `$HOME/Dev/Project/.ngrok.yml`:  

        tunnels:
          default:
            proto: http
            addr: 8000
3) I have `$HOME/.ngrok2/ngrok.yml`:  

        authtoken: <my auth token>
        region: eu

4) I run `ngrok start` in `$HOME/Dev/Project/subfolder`, it finds and merges all this and starts the default tunnel. It would allow for development teams to exchange Ngrok settings in a versioned manner (much like Docker, Vagrant, etc.) which turned out to be quite important in the long run.

**Comment by OmeGak** [comment]
Getting started with ngrok. This is exactly what I was looking for.
