### ISSUE TITLE
ngrok to a machine on the LAN

### ISSUE THREAD

**Issue by pieman64** [inconshreveable/ngrok#392]
@inconshreveable Hi Alan I have ngrok running on a Raspberry Pi and all the regular stuff is working fine.

However I want to be able to access a service, say a http webserver running on the LAN, via the Raspberry Pi. I have tried all the various options but no joy. Below is the error message I get in a browser:

```
Failed to complete tunnel connection

The connection to http://xxxxxx.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address 192.168.xxx.xxx:80.

Make sure that a web service is running on 192.168.10.xxx:xxx and that it is a valid address.

The error encountered was: dial tcp 192.168.xxx.xxx:80: getsockopt: no route to host
```
Is it possible with ngrok to access the webserver via the Pi and if so what is the syntax / set up details required?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
