### ISSUE TITLE
Forwarding to https with host rewrite?

### ISSUE THREAD

**Issue by ilyakatz** [inconshreveable/ngrok#395]
According to this issue

https://github.com/puma/puma-dev/issues/50

I can do something like this to get puma-dev to work

`
ngrok http -host-header=rewrite railsapp.dev:80
`

However, now I'm trying to make it work with ssl, just that ngrock forwards to my local https port, but looks like the `-host-header` options is not available for tls. Is there another way to do it?

/cc @jeffcoh23

**Comment by talkwaqar** [comment]
having same issue

**Comment by roboli** [comment]
Any news anyone?

**Comment by CarlosCuevas** [comment]
+1

**Comment by cabgfx** [comment]
+1

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
