### ISSUE TITLE
Session Status stuck on "reconnecting (x509: certificate signed by unknown authority)"

### ISSUE THREAD

**Issue by rposbo** [inconshreveable/ngrok#396]
On a company network I've started getting the status locked to

> Session Status                reconnecting (x509: certificate signed by unknown authority)

If I tether to my phone, it connects just fine; can anyone please tell me what certificate ngrok is complaining about (so that I can chase it up internally if necessary)?

It looks like there's a Cisco-WSA intercepting all traffic - could that be the cause?

Thanks!

**Comment by urbanfly** [comment]
@rposbo Did you ever find the answer? Did you have to get your company IT to whitelist a certain IP/Domain/Cert in the Cisco-WSA?

**Comment by SaschaMgnx** [comment]
Were you able to resolve this?

**Comment by rposbo** [comment]
Unfortunately I honestly can't remember; I think the wsa was edited to no longer mess with certificates
