### ISSUE TITLE
ngrok client crashed!

### ISSUE THREAD

**Issue by xinzf** [inconshreveable/ngrok#398]
OS：Macos 10.12.13

Log:

panic: sync: inconsistent mutex state

goroutine 231 [running]:
ngrok/util.MakePanicTrace(0x4436e0, 0xc820404fb0, 0x0, 0x0)
	/usr/local/ngrok/src/ngrok/util/errors.go:19 +0x89
ngrok/client.(*Controller).Go.func1.1(0xc820058c60)
	/usr/local/ngrok/src/ngrok/client/controller.go:90 +0x5c
panic(0x4436e0, 0xc820404fb0)
	/usr/lib/golang/src/runtime/panic.go:443 +0x4e9
sync.(*Mutex).Lock(0xc820058f70)
	/usr/lib/golang/src/sync/mutex.go:75 +0x16d
github.com/rcrowley/go-metrics.(*ExpDecaySample).update(0xc820058f60, 0xed02f5cc6, 0x1897ce76, 0x8a4480, 0x0)
	/usr/local/ngrok/src/github.com/rcrowley/go-metrics/sample.go:165 +0x43
github.com/rcrowley/go-metrics.(*ExpDecaySample).Update(0xc820058f60, 0x0)
	/usr/local/ngrok/src/github.com/rcrowley/go-metrics/sample.go:142 +0x59
github.com/rcrowley/go-metrics.(*StandardHistogram).Update(0xc820011960, 0x0)
	/usr/local/ngrok/src/github.com/rcrowley/go-metrics/histogram.go:199 +0x43
ngrok/client.(*ClientModel).proxy.func1()
	/usr/local/ngrok/src/ngrok/client/model.go:390 +0x22f
github.com/rcrowley/go-metrics.(*StandardTimer).Time(0xc8201562d0, 0xc82034c2a0)
	/usr/local/ngrok/src/github.com/rcrowley/go-metrics/timer.go:212 +0x3d
ngrok/client.(*ClientModel).proxy(0xc820150ea0)
	/usr/local/ngrok/src/ngrok/client/model.go:393 +0x10a1
ngrok/client.(*ClientModel).(ngrok/client.proxy)-fm()
	/usr/local/ngrok/src/ngrok/client/model.go:295 +0x20
ngrok/client.(*Controller).Go.func1(0xc820058c60, 0xc8204121e0)
	/usr/local/ngrok/src/ngrok/client/controller.go:96 +0x44
created by ngrok/client.(*Controller).Go
	/usr/local/ngrok/src/ngrok/client/controller.go:97 +0x3f

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
