### ISSUE TITLE
Stopping http tunnel via api only stops https version of it

### ISSUE THREAD

**Issue by tomolas** [inconshreveable/ngrok#399]
We need to start and stop tunnel programmatically for testing reasons. We are registered and paying.
So I tried to start a tunnel via api like this:
`curl -X POST -H "Content-Type: application/json" -d '{"name": "abcd", "proto": "http", "hostname": "abcd.ngrok.io", "host_header": "whatever.de", "addr": 80}' "http://localhost:4040/api/tunnels"`

This works and opens up 2 tunnels: 
- `http://abcd.ngrok.io -> localhost:80` and 
- `https://abcd.ngrok.io -> localhost:80`

After stopping tunnel like this: 
`curl -X DELETE -H "Content-Type: application/json" "http://localhost:4040/api/tunnels/abcd"`, only one of those two started get stopped and one stays up and running / hanging. This causes problems when trying to start a new tunnel again.

Response when trying to start "abcd" tunnel again is: 
`{"error_code":103,"status_code":502,"msg":"failed to start tunnel","details":{"err":"The tunnel http://abcd.ngrok.io is already bound to another tunnel session"}}`

Is there please a way to avoid this? Is this a bug?
Thank you for your help!

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
