### ISSUE TITLE
cursor disappears after killing ngrok session (iterm2, tmux, zsh)

### ISSUE THREAD

**Issue by arifb** [inconshreveable/ngrok#400]
If I start a session ie. `ngrok start app-tunnel` and then kill the process (ie. ctrl-c) the cursor at my terminal prompt is no longer there. I can still type input but the white cursor has disappeared.

Definitely a stretch to just file this sort of vague issue and have a fix out there but thought I would put it out there to see if others seeing the same. Think it's an ngrok issue as it's the only executable where I see this behaviour.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
