### ISSUE TITLE
Ngrok with Docker and Nginx Proxy

### ISSUE THREAD

**Issue by dotMastaz** [inconshreveable/ngrok#401]
Hello,

I have multi websites Docker container using port 80 on a Nginx Docker Proxy...
How to use Ngrok with Website using Nginx Proxy ?

Thank you

**Comment by DanishKhakwani** [comment]
Just run:  `ngrok http 80` (assuming you are binding port 80 with the exposed port)
I tried it on my multi-container (nginx, redis, postgresql, django) web-app.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
