### ISSUE TITLE
Ngrok stuck

### ISSUE THREAD

**Issue by minedun6** [inconshreveable/ngrok#402]
Been a while now that whenever I execute
     ngrok http 80

it just shows me a blinking cursor. Even after waiting for like 30mn, still on that state.
I already registred my token and it was actually working at first. Now it's not working anymore.

I could need a little help.

**Comment by tiaguinho** [comment]
Try
```bash
ngrok http 8080
```

If work,  you probably have another software using the port 80

**Comment by Isidora94** [comment]
I have the same problem, but it doesn't work with 8080 either. Do you have some troubleshooting method i could implement?

**Comment by tiaguinho** [comment]
@Isidora94 run this command to check the port is in use.

```bash
netstat -plnt
```

**Comment by augierakow** [comment]
Same issue for me to, it just hangs.

**Comment by caseysoftware** [comment]
Run `ngrok diagnose` to see what we see and resolve

These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
