### ISSUE TITLE
Feature request: Add ability to send requests using AbsoluteURI

### ISSUE THREAD

**Issue by RealistExperimenter** [inconshreveable/ngrok#403]
This is required for using ngrok as Reverse proxy for https connections and adding ability to put another proxy after ngrok. This will create "transparent" reverse proxy
Flow: 1. Some host sends https request in format: 
```
  POST https://somehost.com/some_resource HTTP/1.1
  Host: somehost.com
```
2. Ngrok works as Reverse proxy and changes host for some specified in settings host: "host_header: anotherhost.com"
request transformed into the format: 
```
  POST /some_resource HTTP/1.1
  Host: anotherhost.com
```
3. If we are using another proxy request will transform into the format:
```
  POST http://anotherhost.com/some_resource HTTP/1.1
  Host: anotherhost.com
```

So if server required secured connection then you will receive 400 error as response. 
From HTTP1.1 specification https://www.w3.org/Protocols/rfc2616/rfc2616-sec5.html

>  The absoluteURI form is REQUIRED when the request is being made to a proxy. The proxy is requested to forward the request or service it from a valid cache, and return the response. Note that the proxy MAY forward the request on to another proxy or directly to the server
> 
> specified by the absoluteURI. In order to avoid request loops, a proxy MUST be able to recognize all of its server names, including any aliases, local variations, and the numeric IP address. An example Request-Line would be:
> 
>        GET http://www.w3.org/pub/WWW/TheProject.html HTTP/1.1
> 
> To allow for transition to absoluteURIs in all requests in future versions of HTTP, all HTTP/1.1 servers MUST accept the absoluteURI form in requests, even though HTTP/1.1 clients will only generate them in requests to proxies. 

And perhaps the best way it is to add some settings to have ability to on or off this feature

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
