### ISSUE TITLE
Logging ngrok output

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#404]
I need to log because I will use the output/log file and use it to set something on a .net application. But when I run this:
`
ngrok start --all > hello.txt
`
It gets stuck and when I press Ctrl+C and check the file, there is no output in hello.txt

**Comment by Zakattacks** [comment]
This is because ngrok doesn't just run like a console command-- it kind of takes over the whole console (I forget what this is called) instead of just outputting like a normal printf or echo command. I'd like to know how to do this too.
Thanks!

**Comment by Ricardonacif** [comment]
Same

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
