### ISSUE TITLE
client status "reconnecting"?

### ISSUE THREAD

**Issue by Thstone37** [inconshreveable/ngrok#405]
I compiled ngrok server and ngrok client,and start ngrokd,there is my clound sever:go1.4,centOS7.2 64

![image](https://cloud.githubusercontent.com/assets/11756943/23842306/54e6843e-07ee-11e7-8ddd-ed7fb1c91d1d.png)

and there is ngrok.cfg

![image](https://cloud.githubusercontent.com/assets/11756943/23842317/6ce27732-07ee-11e7-9549-c3928a818942.png)

and there is client status
![image](https://cloud.githubusercontent.com/assets/11756943/23842435/37fe3352-07ef-11e7-94aa-881fae3d7b00.png)

and there is ping to ngrok.thstone37.xyz

![image](https://cloud.githubusercontent.com/assets/11756943/23842404/029d351e-07ef-11e7-8d4a-5e9f007ec488.png)

**Comment by mittjie** [comment]
Verify that your domain name resolves to the correct IP ： thstone37.xyz-->IP

**Comment by syoukaihou** [comment]
![image](https://user-images.githubusercontent.com/16933900/26974224-e62ea25c-4d4c-11e7-9df2-b07b1b316478.png)
you have to add record [thstone37.xyz -->182.254.232.128],and then check out.

**Comment by Mmpc1994** [comment]
![image](https://user-images.githubusercontent.com/17062182/28110403-e33a5946-6724-11e7-95c7-61bc8e612f69.png)
Please tell it is ok?
![image](https://user-images.githubusercontent.com/17062182/28110517-433cdd1e-6725-11e7-8b2c-b68f315f4050.png)
I do not know how to fix it.

**Comment by syoukaihou** [comment]
@Mmpc1994 did you open 4443 port? in normal it will be say "online" not "reconnecting".
[实现内网穿透](http://www.cnblogs.com/xxoome/p/6973648.html)

**Comment by Mmpc1994** [comment]
@syoukaihou 
thank for you answer.
it is 4443 port is open default? i think i do not close it.
did i need to do below?
![image](https://user-images.githubusercontent.com/17062182/28111710-015dd2b4-6729-11e7-8dbc-514cab10aa3f.png)

**Comment by syoukaihou** [comment]
@Mmpc1994 emmm, you can check your linux server first, to make sure 4443 port is opened.
`service iptables status`
![image](https://user-images.githubusercontent.com/16933900/28112278-ff5f6692-672a-11e7-9b45-473dce30f13b.png)

**Comment by Mmpc1994** [comment]
![image](https://user-images.githubusercontent.com/17062182/28147844-bfa1a4b2-67b5-11e7-9003-efab09c64185.png)
![image](https://user-images.githubusercontent.com/17062182/28147854-ceef190e-67b5-11e7-89b5-557113bba162.png)
4443 is open. i think the server is ok and  it is the client has problem. 
i do '''sudo GOOS=darwin GOARCH=amd64 make release-server release-client'' for client, i use mac.

**Comment by GiddyCode** [comment]
mine is saying 
Session Status                reconnecting..
please what should i do

**Comment by rainwen** [comment]
client add run param -log=stdout you can see detailed log
"ngrok -subdomain demo -log=stdout  -config=./config.cfg 81"
