### ISSUE TITLE
ngrok is not staying open on Windows 7 x64

### ISSUE THREAD

**Issue by xameeramir** [inconshreveable/ngrok#410]
Hello @inconshreveable,

`ngrok` is not staying open for some reason. Do I need to do some extra config Windows 7 x64 apart from just following the installation wizard?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
