### ISSUE TITLE
error when  I compile under windows server2003 , help 

### ISSUE THREAD

**Issue by hzgeyao** [inconshreveable/ngrok#413]
C:\ngrok>make release-server
go get github.com/jteeuwen/go-bindata/go-bindata
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/client/assets/assets_release.go \
        assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/server/assets/assets_release.go \
        assets/server/...
go get -tags 'release' -d -v ngrok/...
package ngrok/...: unrecognized import path "ngrok/..." (import path does not be
gin with hostname)
Makefile:8: recipe for target 'deps' failed
make: *** [deps] Error 1

**Comment by wmltyq** [comment]
Me too! How to solve it?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
