### ISSUE TITLE
Trojan: Win32/Clavior.G!cl in update

### ISSUE THREAD

**Issue by benjamin79** [inconshreveable/ngrok#414]
Hi,

after starting ngrok und updating windows blocks the downloaded file. It sees a Trojan: Win32/Clavior.G!cl  in the file. Are your servers under attack or is it a false alarm?

thanks

**Comment by cormacrelf** [comment]
Same here. Ngrok got pulled into quarantine. I don't want to restore it until I get a response.

**Comment by MatthijsMali** [comment]
I've had the same issues. Why was this issue closed?
[https://github.com/inconshreveable/ngrok/issues/424]()

**Comment by benjamin79** [comment]
This is for v1. Not vor v2. I´ve wrote them an email. But didn´t get an answer. They don´t seem to care.

**Comment by MatthijsMali** [comment]
Hmm that's not nice. Thanks for getting back to me.

Hartelijke groet,

Matthijs Mali

________________________________

**Comment by cormacrelf** [comment]
I emailed and got an answer (eventually) that it's Microsoft's fault for matching it. It's been submitted to Windows Defender's false positives now.

**Comment by MatthijsMali** [comment]
Nice! A little sidenote. I was asking and reporting this since I wrote an article for quasar framework to make Dev servers publicly accessible, where I mentioned ngrok.
________________________________
