### ISSUE TITLE
Exit and raise a descriptive message when an invalid configuration option is used

### ISSUE THREAD

**Issue by emil-petersen** [inconshreveable/ngrok#416]
I suggest that, when ngrok encounters an invalid configuration option in the yaml, it exits and raises a descriptive message.

I recently made the mistake of configuring `bind_tls` and `bind-tls` instead, and this configuration error cost a significant amount of time.

If ngrok had excited and called this out as an invalid configuration option, I would have double-checked the config, whereas I instead made the wrong assumption and went on a wild goose chase.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
