### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by siddiq-rehman** [inconshreveable/ngrok#418]
Hi,

While I am trying to run the ngrok file, I am getting the error as "x509: certificate signed by unknown authority". Earlier it was working fine. Currently I am working under proxy.

Config.YML file:

region: ap
console_ui: true
compress_conn: false
http_proxy: "http://myproxy:8080"
inspect_db_size: 50000000
log_level: info
log_format: json
log: D:/NGROK/ngrok.log
root_cas: trusted
update: true
update_channel: stable
web_addr: localhost:4040

@inconshreveable requesting you to help on this issue

**Comment by Firefox8821** [comment]
Do you have your Auth code?

**Comment by tomasdev** [comment]
Did you self-sign your certificates? If so, you'll need to add `trust_host_root_certs: false` to your configuration.

**Comment by huanz** [comment]
@tomasdev i have the same issue, your method doesn't work.

**Comment by Fed29** [comment]
+1

**Comment by siddiq-rehman** [comment]
Hi

To my understanding this issue occurs when proxy blocks ngrok domain. 

Regards
Siddiq Rehman

**Comment by jordantogether** [comment]
The cause of this issue is as @siddiq-rehman stated, if your proxy blocks the URL, ngrok gets a response back which it doesn't expect, which is a response from the proxy with a self-signed cert.

**Comment by surfjedi** [comment]
+1..

**Comment by azaeng04** [comment]
Anyone manage to figure out how to bypass this?

**Comment by mrGrigg** [comment]
> Anyone manage to figure out how to bypass this?

I'm not sure if this is the same situation, but we have a custom cert that caused some issues and I fixed it by setting this in the config:
`root_cas: host`

**Comment by mrGrigg** [comment]
The current version of ngrok configuration no longer has `trust_host_root_certs`.
It may have been updated to `root_cas`. 
I fixed the x509 issue by setting `root_cas: host`.

**Comment by riponbanik** [comment]
None of them works for me

**Comment by FLASH-99** [comment]
> The current version of ngrok configuration no longer has `trust_host_root_certs`.
> It may have been updated to `root_cas`.
> I fixed the x509 issue by setting `root_cas: host`.
> Perhaps this could help @azaeng04

where do you set this?

**Comment by mrGrigg** [comment]
@FLASH-99 In the config file `https://ngrok.com/docs#config-location` if there isn't one there, just create one and put `root_cas: host` at line 1.

**Comment by tango-j** [comment]
> Hi To my understanding this issue occurs when proxy blocks ngrok domain. Regards Siddiq Rehman
> […](#)
> On 28-Feb-2018, at 2:32 PM, Federico Angaramo ***@***.***> wrote: +1 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

I have self hosted the ngrokd server on aws. still i am getting this issue. 
also I am getting hits via proxy public IP address but not able to connect from client to server. Any work arounds?

**Comment by tango-j** [comment]
> The current version of ngrok configuration no longer has `trust_host_root_certs`.
> It may have been updated to `root_cas`.
> I fixed the x509 issue by setting `root_cas: host`.
> Perhaps this could help @azaeng04

Were you working behind the client?
did u use self-signed cert?
did u self host the server or using ngrok domain itself

**Comment by varKeytrap** [comment]
In the yml file, change `root_cas: host` to `root_cas: trusted`
Worked for me

**Comment by susenj** [comment]
None of these methods help. I am using the latest version of ngrok

**Comment by garethbrickman** [comment]
Latest docs for locating your `ngrok.yml` file: https://ngrok.com/docs/ngrok-agent/config#default-locations

**Comment by garethbrickman** [comment]
None of these methods helped for me either. My ngrok version is `3.1.1`. I am suspecting my company may have implemented a proxy without telling us.

Latest docs for locating your ngrok.yml file: https://ngrok.com/docs/ngrok-agent/config#default-locations

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
