### ISSUE TITLE
Run ngrok UDP & TCP together?

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#422]
Hello inconshreveable.

I have a question. This day I tried to forward my connection from a game server to public but failed.
I am trying to forward a port 27015, which is from a Counter-Strike game, and I want to forward it just so I can play with one friend online. When I connect to the 0.tcp.ngrok.io:16722 this is what I get in the game console:

] connect 0.tcp.ngrok.io:16722
NET Ports:  server 27015, client 27005
Server IP address 192.168.1.3:27015
Connecting to 0.tcp.ngrok.io:1672
Server has no UDP/IP Configured. Please try later.

Will you ever include a UDP in ngrok ?
Because the game server needs a UDP port instead of TCP.

Thanks in advance.

**Comment by BonsoirDiep** [comment]
Oh, I also have the same idea, WE LOVE CS.

Please let me know if you have solved it

**Comment by Famous5000** [comment]
This was rejected in #26, so sadly I don't think it'll come to pass. As much as I'd love using it, it just doesn't work.

**Comment by Bubeboi** [comment]
Wait can't you go in the config and make a second app that is UDP? and then when you open up ngrok just use the command ngrok start --all. Here I have an example:

authtoken: [YourToken]
tunnels:
  first-app:
    addr: 25565
    proto: tcp
  second-app:
    addr: 25565
    proto: udp

because I think in beta or alpha versions udp is an option. Of course, replace the token with your own, and set the port as the CS port. If there is no UDP, then man, why not?

**Comment by Bubeboi** [comment]
I used 25565 in my case because I am trying to get a Minecraft server to work

**Comment by Bubeboi** [comment]
Ok I found a thing that works @nurudinimsirovic Just follow this and you should be all ready! :)
https://stackoverflow.com/questions/25522360/ngrok-configure-multiple-port-in-same-domain

**Comment by nurudinimsirovic** [comment]
@Bubeboi UDP protocol is not implemented in ngrok, so no.
Only HTTP and TCP are supported.

Minecraft server can be started directly from Command line:
ngrok tcp {server_port} -region=eu

The reason its possible is because Minecraft uses TCP only connection.

**Comment by Bubeboi** [comment]
Dang ok idk then sorry 😢

**Comment by IshamMohamed** [comment]
Please bring UDP support due to this crononavirus situation

**Comment by MarkoPaul0** [comment]
I might be able to help, but I am not a gamer and I don't fully understand what you guys are trying to do.
I've built a tool that allows people to tunnel UDP traffic through a TCP connection (https://github.com/MarkoPaul0/DatagramTunneler). Sometimes people ask me if it works with ngrok. I just can't answer because so far people have been unable to clearly explain to me what they are trying to achieve. 

Have a look, and let me know if you think this could get you closer to solving your problem.

**Comment by Shvan11** [comment]
@MarkoPaul0 your looks great, but it does not work on windows :(. is there something similar for windows?

**Comment by MarkoPaul0** [comment]
@Shvan11 not that I'm aware of a windows equivalent, unfortunately. I could work on adding windows support but that would take more time than I have.

**Comment by frostfire1** [comment]
> I used 25565 in my case because I am trying to get a Minecraft server to work

how to use minecolab
i use doesn work

**Comment by frostfire1** [comment]
> Wait can't you go in the config and make a second app that is UDP? and then when you open up ngrok just use the command ngrok start --all. Here I have an example:
> 
> authtoken: [YourToken]
> tunnels:
> first-app:
> addr: 25565
> proto: tcp
> second-app:
> addr: 25565
> proto: udp
> 
> because I think in beta or alpha versions udp is an option. Of course, replace the token with your own, and set the port as the CS port. If there is no UDP, then man, why not?

how to use first app and tunnels ???

**Comment by Efealtan0909** [comment]
ERROR:  Error reading configuration file 'C:\Users\[im not saying my username for privacy reasons]\.ngrok2\ngrok.yml': YAML parsing error: Invalid protocol name 'udp'

**Comment by Famous5000** [comment]
> ERROR: Error reading configuration file 'C:\Users[im not saying my username for privacy reasons].ngrok2\ngrok.yml': YAML parsing error: Invalid protocol name 'udp'

UDP is not going to be supported by ngrok anytime soon as far as I have been able to tell, not my call, sorry.
This was requested a few times already, most notably #26.

**Comment by frostfire1** [comment]
> ERROR: Error reading configuration file 'C:\Users[im not saying my username for privacy reasons].ngrok2\ngrok.yml': YAML parsing error: Invalid protocol name 'udp'

use tcp

**Comment by explodersname** [comment]
I have found a good alternative to ngrok that is free and open source:
[https://github.com/fatedier/frp/](url)

**Comment by ShiftyTR** [comment]
I find this https://localtonet.com/

**Comment by GttMone** [comment]
> I found this https://localtonet.com/

OMG! Thank you so much!!! Best program for TCP & UDP!!!

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Continued in https://github.com/ngrok/ngrok/issues/4
