### ISSUE TITLE
Subdomains wildcard for free users (without reserved domains)

### ISSUE THREAD

**Issue by vedmant** [inconshreveable/ngrok#423]
Hi, I just wanted to use ngrok with my app, but it's just not working. The problem is that my web site doesn't have root domain, all routes has subdomains like admin.mysite.dev account.mysite.dev public.mysite.dev. When I try to make a tunnel like `ngrok http mysite.dev:80` I'm unable to access it using urls like http://admin.154cd0d1.ngrok.io http://account.154cd0d1.ngrok.io

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
