### ISSUE TITLE
Ngrok.com is down

### ISSUE THREAD

**Issue by owlstack** [inconshreveable/ngrok#425]
I'm trying to download the latest version of ngrok to use with Microsoft bot framework and I can't. Looks like https://ngrok.com/ is down. Where can I get an .exe then?

**Comment by sm4rk0** [comment]
It's up again.

**Comment by PavelPolyakov** [comment]
It's down for two days already.

**Comment by jpowell** [comment]
Still down

/cc @rorjeremy

**Comment by PavelPolyakov** [comment]
For me it was companies firewall :( for some reason ngrok.com is in some default blocking list.--Отправлено из мобильной Яндекс.Почты13.09.2017, 18:25, "Justin Powell" <notifications@github.com>:Still down
/cc @rorJeremy

**Comment by yuvraj650** [comment]
Now its again down shit man!

**Comment by caseysoftware** [comment]
For anyone finding this later. This repository is not maintained but you can track ngrok status here - https://status.ngrok.com/
