### ISSUE TITLE
OMG, I meet the error just now, How can I fix it ?

### ISSUE THREAD

**Issue by fushall1104** [inconshreveable/ngrok#426]
OS: centos 6.9 32
compliting ngrok on centos7.2_x64,
and ngrokd running on centos7.2_x64.
How  terrible it is!!!!

/usr/local/go/src/net/net.go:121 +0xba ngrok/conn.(*loggedConn).Read(0x8817f720, 0x88280000, 0x8000, 0x8000, 0x8052e65, 0x0, 0x0)                                                                         	<autogenerated>:3 +0x74                       io.(*teeReader).Read(0x1b358270, 0x88280000, 0x8000, 0x8000, 0x0, 0x0, 0x0)                  	/usr/local/go/src/io/io.go:495 +0x66                                                             ngrok/conn.(*Tee).Read(0x1cdcea20, 0x88280000, 0x8000, 0x8000, 0x0, 0x0, 0x0)                                                          	/usr/local/ngrok-master/src/ngrok/conn/tee.go:62 +0x62                                       io.Copy(0xb773bbc0, 0x1efd9f60, 0xb773bff0, 0x1cdcea20, 0x0, 0x0, 0x0, 0x0)                                  	/usr/local/go/src/io/io.go:362 +0x184                                                                              ngrok/conn.func·002(0xb773b8c8, 0x1efd9f60, 0xb773bec0, 0x1cdcea20, 0x1b358308)                                                                             	/usr/local/ngrok-master/src/ngrok/conn/conn.go:204 +0x10b                                                         created by ngrok/conn.Join   	/usr/local/ngrok-master/src/ngrok/conn/conn.go:215 +0x114                                                                  [root@ngroktest www]#

**Comment by LoganDark** [comment]
(Terribly bad) bad grammar, badly formatted error, minimal context... I believe this is one of the most stereotypical bad issues I've ever seen on GitHub.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
