### ISSUE TITLE
Facebook's hooks are blocked to ngrok?

### ISSUE THREAD

**Issue by Ricardo-Costa** [inconshreveable/ngrok#427]

**Comment by farahmaamar** [comment]
I don't know what is exactly the origin of this issue, but u can  quickly switch to machinabot.com , it's free , here is how to setup it,  https://medium.com/inside-machinabot/from-dev-to-live-part-1-how-to-start-testing-and-debugging-your-bot-locally-in-one-minute-74e4e334a449

**Comment by btomashvili** [comment]
@farahmaamar  How long are you waited for invitation? I need asap and still waiting

**Comment by farahmaamar** [comment]
I just sent you an invite right now , check your inbox!

**Comment by rohansood42** [comment]
I think there is some problem with the us server. eu works fine with facebook

**Comment by jminuscula** [comment]
@inconshreveable there's a bug open on Facebook suggesting this is on the ngrok side. Could you please give us an update about what might be going on?

https://developers.facebook.com/bugs/824028317765435/

eu.ngrok is not working for me and a lot of people either

**Comment by musaselim** [comment]
@Ricardo-Costa @btomashvili You can also use https://www.chatbotproxy.com/ to debug and proxy your requests from Facebook Messenger. Free version covers proxy, debugging and metrics. Feel free to try.

**Comment by ikasymov** [comment]
use for alternative beame-insta-ssl

**Comment by lukedubber** [comment]
Just ran into this issue as well.

**Comment by SirGordon** [comment]
why is this closed?

**Comment by chasms** [comment]
Using a paid account specifically for rich meta validators and they 502 on my ngrok.io subdomain. Requests don't show up in the dashboard, so looks like they are blocked on the DNS/LB/subdomain side of things. @inconshreveable can we reopen this ticket?

**Comment by jamesr2323** [comment]
This is also happening to me. Facebook retrieves this for my URL: 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head>
<body><p>kErrorAddressPrivate</p></body>
</html>
```

**Comment by aacook** [comment]
Me too. I'm a paying user. Is there any workaround?

**Comment by phbernard** [comment]
@inconshreveable Regarding the latest messages, this issue is still pending and should be re-opened.

Apparently Facebook did its job of making sure that [FB does block ngrok](https://developers.facebook.com/support/bugs/311158926025028#comment_card_section_322870321520555). It would be great if you could give it another check on your side.

**Comment by ninofiliu** [comment]
This is still an issue. Facebook open graph debugger is throwing `Could Not Connect To Server: Curl error 56 (RECV_ERROR)`

**Comment by ryancwalsh** [comment]
This worked for me: https://stackoverflow.com/questions/8569892/how-to-test-open-graph-on-localhost#comment97589973_46816051

**Comment by matthewhuang-camelot** [comment]
Indeed still seems to be an issue -- this should be re-opened. I'm a paying user as well

**Comment by roynasser** [comment]
+1 too... paying user

**Comment by hempels** [comment]
+1 ... paying user

**Comment by yakoveka** [comment]
+1 still doesn't work, returns 502 code

**Comment by AO-IO** [comment]
Still doesn't work error 502

**Comment by ryanrutan** [comment]
Any updates to this one?

**Comment by siaen** [comment]
This is still unfixed.

**Comment by yepelinux** [comment]
I've found that facebook is blocking some requests

`The url https://51bc-152-168-79-85.sa.ngrok.io/whatsapp/cloud-api/webhook has been identified as malicious and/or abusive.`

in response to save webhook 
![image](https://user-images.githubusercontent.com/660790/172015931-d8974b82-7edb-43e9-abeb-c5f79e345aca.png)

**Comment by hadnet** [comment]
Facebook is blocking the use o ngrok. Tried to use it for social login provider and I get this message
<img width="602" alt="Screen Shot 2022-07-26 at 10 44 16 PM" src="https://user-images.githubusercontent.com/13828833/181142352-ec3cd2a4-a775-45ce-97b6-42e98a37c1a9.png">

**Comment by ChesterSVK** [comment]
+1 Here as well, used for social login, it has been working untill today

**Comment by pgiu** [comment]
Still blocked :(

**Comment by leobaldoneto** [comment]
Still blocking here too.

I think Facebook's webhooks are stucking in Browser Warning of Ngrok. 

Bellow are the instructions to bypass the Browser Waning, but we can't control the how Facebook send requests to Ngrok.

![image](https://user-images.githubusercontent.com/28495813/200967068-d06a8853-2f4b-4f91-995b-9b6f035c084e.png)

**Comment by WableSanket** [comment]
Still blocked :(

**Comment by PSilvaCVT** [comment]
https://ngrok.com/partners/facebook

**Comment by pflajszer** [comment]
adding a param `--region us` (i.e. `ngrok http 7071 --region us` helped me with this.

**Comment by bnjunge** [comment]
@pflajszer works

**Comment by gshubham533** [comment]
I changed my ngrok region to us and now it is working fine.

Example cmd : ngrok http 8000 --region us

**Comment by deven96** [comment]
@pflajszer you saved me a ton... thanks!

**Comment by nazruld** [comment]
> adding a param `--region us` (i.e. `ngrok http 7071 --region us` helped me with this.

Thanks ... its working

**Comment by jakoguta** [comment]
> I changed my ngrok region to us and now it is working fine.
> 
> Example cmd : ngrok http 8000 --region us

Adding the `--region us` worked

**Comment by Suyash-Purwar** [comment]
Add `--region us` and it will work. Thank you very much @pflajszer
