### ISSUE TITLE
request Context is not properly closed when a client closes the connection

### ISSUE THREAD

**Issue by marwan-at-work** [inconshreveable/ngrok#428]
If you `curl` your ngrok URL, which proxies into a local Go server, then you hit Ctrl+C before the request is properly finished, the ngrok server will not close the connection and therefore `request.Context().Done()` does not properly send a signal to say a client has closed the connection. 

This is for ngrok v2.2.4

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
