### ISSUE TITLE
ngrok tunnel not found after working for few days?

### ISSUE THREAD

**Issue by ajmalkhanjamro** [inconshreveable/ngrok#432]
hello after searching alot on web and contacting ngrok support with no reply here i want to know what is the problem with ngrok i installed it on windows server 2008 and it worked few days but after few days now its saying tunnel not found error this happend to me quite a few times and had to change my server again and again now iam fed up of this what is the main issue can anybody tell me any fix for this

**Comment by stevenup** [comment]
Same problem as you. I find the ngrok server process is down every other day. I must start it manually.Hope someone solve the problem.

**Comment by jimtaylor123** [comment]
Me too, after just a few minutes.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
