### ISSUE TITLE
Ngrok not working when running a local instance of JIRA.

### ISSUE THREAD

**Issue by scheung38** [inconshreveable/ngrok#433]
This is my URL for my local JIRA instance:

http://localhost:2990/jira/secure/Dashboard.jspa
<img width="1104" alt="screen shot 2017-07-12 at 11 07 36" src="https://user-images.githubusercontent.com/1273014/28112834-5d6f263e-66f2-11e7-9348-3192f2100b80.png">
    $ ngrok http 2990

But the resulting http://8a37794e.ngrok.io returns:

    This 8a37794e.ngrok.io page can’t be found

**Comment by wilsonehusin** [comment]
This might have to do with the way JIRA redirects the page. For example, in Flask application, when host is set to `localhost` then the page will be accessible by the computer running it, but not to local network. `0.0.0.0` will make it available to external.

*Just a possibility...*

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
