### ISSUE TITLE
Stuck in 'reconnecting' when using personal hotspot

### ISSUE THREAD

**Issue by neoneye** [inconshreveable/ngrok#434]
When my Mac connects to the internet via broad band, then `ngrok` works fine and is awesome.

However when my Mac connects to the internet via my iPhone (3G personal hotspot), then `ngrok` stays in a `reconnecting` state. I have never experienced that `ngrok` worked. I wish to be able to use `ngrok` when I use personal hotspot (daily).

    PROMPT> cat ngrok.yml 
    authtoken: INSERT_AUTHTOKEN_HERE
    tunnels:
      meteor:
        proto: http
        addr: 8181
        bind_tls: true
        subdomain: insert_subdomain_here.eu.ngrok.io
    
    PROMPT> ngrok start --config='ngrok.yml' -log=stdout --all
    INFO[07-16|14:04:51] open config file                         path=/make/world/peace/ngrok.yml err=nil
    INFO[07-16|14:04:51] run component                            obj=controller comp="signal handler"
    INFO[07-16|14:04:51] run component                            obj=controller comp=updater
    INFO[07-16|14:04:51] run component                            obj=controller comp=web
    INFO[07-16|14:04:51] run component                            obj=controller comp="Tunnel session"
    INFO[07-16|14:04:51] run component                            obj=controller comp="memory storage"
    INFO[07-16|14:04:51] starting web service                     obj=web addr=127.0.0.1:4040
    EROR[07-16|14:04:51] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="dial tcp 12.34.56.78:443: connect: software caused connection abort"
    WARN[07-16|14:04:52] failed to check for update               obj=updater err="Post https://update.equinox.io/check: dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:04:52] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:04:53] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="Get https://dns.google.com/resolve?cd=true&name=tunnel.us.ngrok.com&type=A: dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:04:55] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="Get https://s3.amazonaws.com/dns.ngrok.com/tunnel.json: dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:04:57] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="[dial udp 8.8.8.8:53: connect: software caused connection abort dial udp 8.8.4.4:53: connect: software caused connection abort]"
    EROR[07-16|14:05:00] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:05:04] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="Get https://dns.google.com/resolve?cd=true&name=tunnel.us.ngrok.com&type=A: dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:05:12] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="Get https://s3.amazonaws.com/dns.ngrok.com/tunnel.json: dial tcp 12.34.56.78:443: connect: software caused connection abort"
    EROR[07-16|14:05:25] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="[dial udp 8.8.8.8:53: connect: software caused connection abort dial udp 8.8.4.4:53: connect: software caused connection abort]"
    EROR[07-16|14:05:42] failed to reconnect session              obj=csess id=59d8d5b7b5f1 err="dial tcp 12.34.56.78:443: connect: software caused connection abort"

I see `reconnecting` if I open `127.0.0.1:4040/status` in a browser.

# Setup

My Mac is currently connected via `Wi-Fi` to my iPhone. I have tried 3 different ways to connect my Mac with my iPhone: `Wi-Fi`, `iPhone USB`, `Bluetooth`. In all ways `ngrok` is in a `reconnecting` state.

macOS 10.12.5 Sierra

    PROMPT> uname -a
    Darwin makeworldpeace.local 16.6.0 Darwin Kernel Version 16.6.0: Fri Apr 14 16:21:16 PDT 2017; root:xnu-3789.60.24~6/RELEASE_X86_64 x86_64

iPhone6S running iOS 10.3.2 (14F89). My iPhone is not jailbroken, so I cannot change its firewall settings. It's a 3G connection.

It's the latest version of ngrok

    PROMPT> ngrok --version
    ngrok version 2.2.6

# Ideas

[PPTP support was removed for iOS10](https://support.apple.com/da-dk/HT206844) - I wonder if `ngrok` is affected by this?

**Comment by neoneye** [comment]
I solved it. It was a stupid mistake.

I have the [TripMode app](https://www.tripmode.ch/) installed, that prevents apps from using the internet while I'm on personal hotspot. So that my Mac isn't trying to run backup, sync file, auto update apps. This was also preventing `ngrok` from running.

**Comment by GiddyCode** [comment]
i also, am encountering the same issue... ngrok refused to connect when im using hotspot connection from my samsung phone....
it displays...
session status                         reconnecting..

**Comment by MNFrankie** [comment]
Same Issue, Did you get solution for this.
