### ISSUE TITLE
trailing / is required for ngrok

### ISSUE THREAD

**Issue by agnibha92** [inconshreveable/ngrok#435]
Hi I was checking my application with ngrok and previously it was accepting url that do not have a trailing / but now it throws bad request if I call a service without a trailing /. Can you please explain me why trailing / is required?

**Comment by akshaychhajed** [comment]
@AgnibhaBose please post exact command and output. That makes it easier to reproduce and debug if necessary.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
