### ISSUE TITLE
ERROR: Unrecognized command: service

### ISSUE THREAD

**Issue by xameeramir** [inconshreveable/ngrok#436]
We've got [ngrok.exe][1] setup inside:

    C:\Program Files\ngrok\ngrok.exe

Which we wanted to run as a service:

Hence, [as suggested ][2] we've created a `ngrok.yml` file at:

    C:\Program Files\ngrok\ngrok.yml

The content of which is the following:

    tunnels:
      tunnelOne:
        proto: http
        addr: 3000

 

The `path` variable is set to `C:\Program Files\ngrok`.

Whenever we run the following command:

    ngrok service install -config C:\Program Files\ngrok\ngrok.yml

It throws the following error:

>ERROR:  Unrecognized command: service

  [1]: https://ngrok.com/download
  [2]: https://ngrok.com/docs/ngrok-link#service

[Original post](https://stackoverflow.com/q/45088204/2404470)

**Comment by deepeeess** [comment]
Getting the same error in MacOS using ngrok 2.2.0.

**Comment by AliakseiMat** [comment]
I have the same error.

**Comment by Yusha813** [comment]
Same error here too.

**Comment by urbansciences** [comment]
I am getting this error on Linux too (Linux distro on Raspberry Pi)

**Comment by XCarrel** [comment]
Same thing here (Ubuntu)

**Comment by crorodriguezro** [comment]
Same error on Ubuntu

**Comment by mleyb** [comment]
same issue for me too, Win10 64

**Comment by leveredblackout** [comment]
this is for Ngrok-link a different product from baseline Ngrok. details here -> https://ngrok.com/product/ngrok-link

**Comment by MrFarhan** [comment]
facing the same issue with windows and typescript...

ERROR:  Unrecognized command: 3000

**Comment by habibun** [comment]
i tried install ngrok using snap
then this issue happened.


try to install ngrok using apt here: https://ngrok.com/docs/getting-started

this worked for me, i am using ubuntu 20.04

**Comment by PyMan142** [comment]
> for windows, probably just needa type `ngrok authtoken (your token here)` into the terminal and it should work

This was the fix, ty

**Comment by tornvallalexander** [comment]
Seems to be working on mac as well 👍

> for windows, probably just needa type `ngrok authtoken (your token here)` into the terminal and it should work

**Comment by huabin** [comment]
> Seems to be working on mac as well 👍

On macOS, you should download the latest ngrok file, and then run 

```
ngrok config add-authtoken <your token>
```

It will work.

**Comment by fuxiaoguo** [comment]
![image](https://user-images.githubusercontent.com/33563058/197398131-96f6d928-dc83-4ec1-bb85-b06f676109cb.png)
window worked

**Comment by arsidnaresh** [comment]
ngrok authtoken <your token>

it will work

**Comment by ixassj** [comment]
A mí me pone este error, alguien que me ayude pls 
![Uploading 16690885445935655334534024108086.jpg…]()

**Comment by viatanas** [comment]
> ngrok authtoken your token
> 
> it will work

That worked for me, thanks!

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
