### ISSUE TITLE
Wildcard subdomain on custom domain

### ISSUE THREAD

**Issue by suchitagarwal** [inconshreveable/ngrok#438]
Hey,
I have a custom domain, say `example.com`.

I want to create a tree as follows:

- devname1.example.com
  + site1.devname1.example.com
  + site2.devname1.example.com
- devname2.example.com
  + site3.devname2.example.com
  + site4.devname2.example.com

`devname1`, `devname2` are basically developers, each with their own set of subdomains, and `site1`, `site2` etc are arbitrary subdomains.

I reserved `devname1.example.com` and `*.devname1.example.com`, added a CNAME entry for `devname1` and a CNAME entry for `*.devname1`. This does not allow me access to `site1`, `site2` etc. It seems that I have to reserve `site1.devname1.example.com` etc as well to be able to access those. It would be great if there is a way to access `site1.devname1.example.com` without having to reserve each arbitrary `site` on ngrok.com

**Comment by suchitagarwal** [comment]
Also, if I access `site3.devname1.example.com` which is not registered, the running tunnels error out.

**Comment by afrazahmmad** [comment]
Facing same problem

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
I just dug this issue up and configured it in my account and it now works as expected.

- in ngrok, i registered `*.devname1.example.com`
- in my dns provider, i configured cnames for `*.devname1` and `_acme-challenge.devname1`.
- waited a bit for the dns entries to propagate
- started a tunnel `site1.devname1.example.com`
- visited and saw no cert errors
- started a tunnel `site3.devname1.example.com` and also saw no cert errors

i did not need to reserve `site1.devname1.example.com` or `site3.devname1.example.com`.
