### ISSUE TITLE
Allow For Data Modification Before Replay

### ISSUE THREAD

**Issue by Miserlou** [inconshreveable/ngrok#44]
Hey guys!

Love this application!

The only thing which would make it even more killer is the addition of the ability to not just replay data, but to edit the data before it is replayed. That would make debugging APIs with webhooks vastly easier, as it wouldn't depend on the 3rd party service!

Thanks so much!,

**Comment by inconshreveable** [comment]
still planning on this being supported at some point in 2.x. won't fix for 1.x. closing

**Comment by nikegp** [comment]
@inconshreveable is there an issue to follow for 2.x? It would be a really useful feature

**Comment by yugensoft** [comment]
+1 this would be very useful and put you a step ahead of the competition. This is a very frequent use case when testing integrations that receive webhooks.
