### ISSUE TITLE
Is ngrok down?

### ISSUE THREAD

**Issue by GuiSim** [inconshreveable/ngrok#440]
I get 

```
Session Status                reconnecting (internal server error)              
```

when connecting to the US server.

EU region works

**Comment by themroberts** [comment]
Same issue here. 
```EROR[07-31|15:31:20] failed to auth                           obj=tunSess err="internal server error"```

**Comment by wayne5w** [comment]
Same here.

**Comment by GuiSim** [comment]
Works now. Issue appears to be resolved.

Is there a status page for Ngrok? I'd like to learn these things via a better channel than github's issue page.

**Comment by wayne5w** [comment]
Yep, working here too.

**Comment by marcoarruda** [comment]
I'm having the same error right now,
Is there a status page?

![screenshot from 2018-11-05 12-58-27](https://user-images.githubusercontent.com/216738/48009449-830e5300-e0fa-11e8-98b3-2c93953817de.png)
