### ISSUE TITLE
Ngrok 2.2.8 ARM doesn't work anymore on Linux armhf ( android device )

### ISSUE THREAD

**Issue by 0v3rfl00w** [inconshreveable/ngrok#441]
Starting ngrok gives a warning and an error like this :

./ngrok
WARN[08-13|11:05:39] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/arm" $HOME=/data/data/com.termux/files/home
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
ngrok start foo bar baz          # start tunnels from the configuration file

VERSION:
   2.2.8

AUTHOR:
  inconshreveable - <alan@ngrok.com>

COMMANDS:
   authtoken    save authtoken to configuration file
   credits      prints author and licensing information
   http         start an HTTP tunnel
   start        start tunnels by name from the configuration file
   tcp          start a TCP tunnel
   tls          start a TLS tunnel
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command

And when trying to connect i got this :
![screenshot_20170813-121135](https://user-images.githubusercontent.com/28659493/29249096-da223ed6-8020-11e7-84c6-10e5aae08f89.png)
What's the probleme here ? thanks For this beautiful software .

**Comment by brunoecqgithub** [comment]
Did you resolve this? I have the same problem...

**Comment by mohammadhosseinime** [comment]
and me 🍰

**Comment by khozinul26** [comment]
Jjk

**Comment by lordfme** [comment]
What happens is ngrok tries to resolve a couple of addresses and connects to 127.0.0.1:53. This DNS server isn't listening if you use 3G/H+ (check with cmd "netstat -ant"). To enable the local DNS server and still use 3G/H+ turn on your hotspot.

Alternatively you could edit the /system/etc/hosts file if you have root and add the following lines so the DNS resolution isn't necessary (v 2.2.8)
216.58.223.206 dns.google.com
52.216.130.253 s3.amazonaws.com
52.15.79.231 tunnel.us.ngrok.com
54.173.32.212 update.equinox.io
127.0.0.1 localhost

Good luck

**Comment by ilanstar** [comment]
Is there  a way to resolve this issue without root? 
I checked whether $PREFIX/etc/hosts may work but it doesn't

**Comment by lordfme** [comment]
As I said above, simply turn on your mobile hotspot while using ngrok.

**Comment by ilanstar** [comment]
That indeed works, but it prohibits me from using WiFi. Is there a solution
that keeps both WiFi and manages to properly resolve the addresses?

**Comment by oneo766** [comment]
I am feeling this problem... my phone is not rooted...

**Comment by DarkIShadow** [comment]
First turn off your wifi connection (if you turn on). Then turn on mobile data and mobile hostpot and type 
./ngrok http 80
Problem solved ;-)

**Comment by loveablefellow007** [comment]
DarkIShadow using mobile data and hotspot in same time fixed my issue bro..
Thaaaaaankkkkkxxxx bro.💯💯💯

**Comment by DarkIShadow** [comment]
You're welcome bro.. 🤗

**Comment by SiddharthSingh0** [comment]
Thanks done nice solution

**Comment by KaravaliStudio** [comment]
I am facing this error ,even having strong inte
![IMG_20200430_195756](https://user-images.githubusercontent.com/63892972/80723821-b890d280-8b1e-11ea-8b4f-e78f26bc2f35.jpg)
rnet and hotspot is on.. please help

**Comment by greatidea1** [comment]
Does ngrok on android/termux not work on Wifi? My mobile data is limited and expensive

**Comment by heroys6** [comment]
> What happens is ngrok tries to resolve a couple of addresses and connects to 127.0.0.1:53. This DNS server isn't listening if you use 3G/H+ (check with cmd "netstat -ant"). To enable the local DNS server and still use 3G/H+ turn on your hotspot.
> 
> Alternatively you could edit the /system/etc/hosts file if you have root and add the following lines so the DNS resolution isn't necessary (v 2.2.8)
> ips...
> 

This is still the way, but ips is outdated, here is the new one:
8.8.4.4 dns.google.com
52.216.176.229 s3.amazonaws.com
18.189.209.170 tunnel.us.ngrok.com
52.6.123.150 update.equinox.io
At the moment I can use ngrok in Termux on Android 7.1 without cellular network + hotspot. But using only Wi-Fi.

**Comment by saurabh6017** [comment]
just use this file 
https://drive.google.com/file/d/15366TjwvIuD16oc9GoyEj61GOeDbym8o/view

**Comment by prajwal-on-github** [comment]
> First turn off your wifi connection (if you turn on). Then turn on mobile data and mobile hostpot and type
> ./ngrok http 80
> Problem solved ;-)

BlackAlpha0 thanks bro You solved my problem I opened github acc to only say thanks to You...ThankTou♥️

**Comment by BlackAlpha0** [comment]
> > First turn off your wifi connection (if you turn on). Then turn on mobile data and mobile hostpot and type
> > ./ngrok http 80
> > Problem solved ;-)
> 
> BlackAlpha0 thanks bro You solved my problem I opened github acc to only say thanks to You...ThankTou♥️
:3 💯

**Comment by dinukasal** [comment]
@saurabh6017 ngrok fixed one doesn't work

**Comment by dedshit** [comment]
> I am facing this error ,even having strong inte
> ![IMG_20200430_195756](https://user-images.githubusercontent.com/63892972/80723821-b890d280-8b1e-11ea-8b4f-e78f26bc2f35.jpg)
> rnet and hotspot is on.. please help



why dont u use old version of that

**Comment by Itslokani** [comment]
![Screenshot_20211109-181327](https://user-images.githubusercontent.com/93935449/140926356-dcf2058d-9922-4e6d-aba8-00a3e4deed90.png)
Can't start TCP server please help me please please

**Comment by Allsafecybertech** [comment]
Work fine, with mobile hotspot on

**Comment by ThatMG393** [comment]
Use PRoot

**Comment by sinhpn92** [comment]
Great solution to use mobile data and hotspot. But It is not the good solution. Have any suggest to solve it? I have same issue on my device Samsung galaxy s10+.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
