### ISSUE TITLE
Autostart and send ngrok endpoint url via email or similar?

### ISSUE THREAD

**Issue by mskogly** [inconshreveable/ngrok#443]
Working on a raspberry pi project that uses nodejs set up a webserver and two way communication, to be able to control two servos. I was planning of starting ngrok on bootup via crontab, like this https://github.com/inconshreveable/ngrok/issues/345 , but is there a way to grab the url to the endpoint ngrok generates, and pass it on to me using email, or pass it to node?

**Comment by Jigsaw-Jams** [comment]
You could use the client API to get the url

`curl http://localhost:4040/api/tunnels`
