### ISSUE TITLE
Tunnel not found for custom domain, works for free subdomain

### ISSUE THREAD

**Issue by 3rand** [inconshreveable/ngrok#444]
I am running a webapp on port 8000

When i bind to a reserved ngrok subdomain it works fine. When I use my own domain binding, the reserved cname gives me tunnel not found, also my domain is currently ERR_NAME_RESOLUTION_FAILED.

**Comment by Anthony-Love** [comment]
try your own domain to certificate

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
