### ISSUE TITLE
Facebook OpenGraph Crawler can not reach autogenerated links at ngrok.io

### ISSUE THREAD

**Issue by PeterBocan** [inconshreveable/ngrok#445]
[Facebook OG Debugger/Crawler](https://developers.facebook.com/tools/debug/og/object/) can not reach the `http://xxxxxxx.ngrok.io`, returns HTTP 503 and this response: 

```
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/REC-html40/loose.dtd">
<html>
<head><meta http-equiv="content-type" content="text/html; charset=utf-8"></head>
<body><p>kErrorAddressPrivate</p></body>
</html>
```

Thanks!

**Comment by cristiandan** [comment]
I got the same problem, did you find a workaround? @PeterBocan

**Comment by PeterBocan** [comment]
@cristiandan I was emailing to @inconshreveable and he said that's the issue on Facebook's side, and Facebook [Bug Report](https://developers.facebook.com/bugs/311158926025028) said it's not them. 

I would put my money on Facebook's fault. I am thinking of doing some workaround, but no, nothing got resolved.

**Comment by cristiandan** [comment]
I see, thanks !

**Comment by rmartin** [comment]
This issue is still pending. It appears since this was opened Facebook has ruled out the issue from their side. @PeterBocan is it possible to re-open this again?

Here are the threads that I found:

- Most Recent Thread with FB ruling out the Error code from FB Side - https://developers.facebook.com/bugs/311158926025028/

- Original Thread with issue still pending - https://developers.facebook.com/bugs/824028317765435/

**Comment by PeterBocan** [comment]
@rmartin I can.

**Comment by skwiryt** [comment]
Hello,
We are now a year older but the issue still seams to exist. At least I got it. Is there any solution?

**Comment by PeterBocan** [comment]
One simple solution: Don't use ngrok for now.

**Comment by stefanpl** [comment]
Switched to [localtunnel](https://localtunnel.github.io/www/) after reading this, sharing debugger works hassle-free. Plus it has nice urls!
Feels a tad bit slower than ngrok though.

**Comment by pomartel** [comment]
Ngrok on a custom domain did the trick for me! https://ngrok.com/docs#custom-domains

**Comment by brunoaugusto** [comment]
Too bad Custom Domains is a paid feature, barring the vast majority of developers from even testing

**Comment by phbernard** [comment]
@pomartel Custom domain didn't work for me, either with the (default) US region or EU region. Would you consider giving this "fix" another try? Your advice might lead people to subscribing to a paid service for nothing.

**Comment by pomartel** [comment]
Well I'm using ngrok on a custom domain every day and it works great! It works with Facebook crawler too. Just take a look at it here:

https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fdev.app.ps%2Ftest-poll

**Comment by phbernard** [comment]
Oh... **custom domains** and not custom subdomains (which I'm using). Silly me. Thank you for double-checking and sorry for the interruption.

**Comment by Nickan** [comment]
This issue still persists, have you guys solved it?

**Comment by PeterBocan** [comment]
No. By the list of ngrok open issues I see, I judge that no one really cares about this project whatsoever.

**Comment by Nickan** [comment]
That's a bummer, @PeterBocan did you find an alternative solution? Localtunnel has issues that I can't solve.

**Comment by umbrella-yaroslav-graboveckiy** [comment]
ouch =_=. Hello from 2020

**Comment by LeHoangLong** [comment]
Buying a custom domain on ngrok works

**Comment by dyelax** [comment]
@LeHoangLong I have a custom domain and it's still not working for me. I'm running `ngrok http 3000 -subdomain=<my-subdomain>`. Did you have to do anything different?

**Comment by pomartel** [comment]
Custom domain is not the same as a custom subdomain.

Le mar. 23 juin 2020 à 17:34, Matt Cooper <notifications@github.com> a
écrit :

**Comment by LeHoangLong** [comment]
> @LeHoangLong I have a custom domain and it's still not working for me. I'm running
> `ngrok http 3000 -subdomain=<my-subdomain>`.
> 
> Did you have to do anything different?

You have to be a pro user and purchase a domain name for this. 
Note that it does not work if you are planning to have your app reviewed by Facebook. For some reason, the reviewer weren't able to access my website even though others can. So i ended up have to use a gcloud vm instance. But for development a custom domain (not subdomain) is sufficient

**Comment by sweves** [comment]
hello from 2020 - localtunnel's back up domain works for this. Just run:

`lt -h "https://serverless.social" -p PORT`

**Comment by lupus-magnus** [comment]
Hello from 2021!
Any news from this? I was just trying to check my OpenGraph and Facebook doesn't allow the domains generated by localtunnel anymore. This code right here `lt -h "https://serverless.social" -p PORT` does not return me anything on the terminal. Help(?)

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
