### ISSUE TITLE
ngrok status reconnecting issue

### ISSUE THREAD

**Issue by imtvase** [inconshreveable/ngrok#446]
I am trying to generate http connection from my local server by using the ngrok version 2.X.X but I am getting the status as reconnect error, 

Please find the attach snap.
![ngrok](https://user-images.githubusercontent.com/31928487/30420314-c69e9d74-9956-11e7-8b19-a02da2848fec.png)

Please help me out on this.

**Comment by gonzaloserrano** [comment]
Any hints on this? Got the same thing.

**Comment by SirMorfield** [comment]
Did you try turning it off and on again?
No but seriously, for me it worked after two tries.
Or you have to wait a little longer.

**Comment by diwakar-dayalan** [comment]
same issue, any inputs / pointers pls

**Comment by gonzaloserrano** [comment]
Stopping and starting again does work, but then ngrok generates different links so in the end you lose the previous state. What it should do (maybe it does already, haven't checked) is to handle disconnections with exponential backoff reconnections.

**Comment by aniketstark** [comment]
i have sollution 
dont use ngrok
use apache2 and openssh installed it and
type this command

ssh -R 80:here your ip:4444 serveo.net

**Comment by carlin54** [comment]
Do you have a solution to fix ngrok? I haven't been able to find a solution. 
![image](https://user-images.githubusercontent.com/8703199/41962533-eac861d8-7a12-11e8-8595-91cbb7c9c30f.png)

**Comment by swaroopamir** [comment]
How resolve this? Kindly help me out

![ngrok](https://user-images.githubusercontent.com/19235176/45477580-75be9300-b75f-11e8-93f2-5085f0372cbe.PNG)

**Comment by joshiadvait8** [comment]
![image](https://user-images.githubusercontent.com/25084011/55348547-0cbd2380-54d5-11e9-87d0-71a57460aabe.png)
how to solve this?

**Comment by aniketstark** [comment]
use ssh server

**Comment by aniketstark** [comment]
which connection you want http or tcp tell me ok

**Comment by joshiadvait8** [comment]
Http

**Comment by aniketstark** [comment]
ok

**Comment by aniketstark** [comment]
wait  what you using cmd or linux or kali linux

**Comment by joshiadvait8** [comment]
Windows Cmd

**Comment by aniketstark** [comment]
apt install openssh
ssh -R 80:localhost:4444 serveo.net

**Comment by aniketstark** [comment]
what cmd i dont know about ok

**Comment by aniketstark** [comment]
but you can try

**Comment by joshiadvait8** [comment]
In Linux it's ngrok is working but in windows it's not 
Also I've tried serveo.net command but its showing 502 bad gateway for asp.net application i.e. IIS server application

**Comment by TOPATAMO** [comment]
Ok this thread was not helpful.

**Comment by nitesh-mishr** [comment]
[
![Screenshot_20190513-215145_Termux](https://user-images.githubusercontent.com/46121792/57637684-a6461d80-75c9-11e9-8672-5fe5d925de68.jpg)
](url)

I am getting this error what to do anyone help plsss

**Comment by Dee7praja** [comment]
Hii guys,

i was also facing the same issue with latest version of ngrok 

Now i download the its older version ngrok 2.2.8 
https://dl.equinox.io/ngrok/ngrok/stable/archive
And its working fine now...

**Comment by mahfuzt2** [comment]
use mobile network and turn on the hotspot. Then it will be online automatically.

**Comment by Jay991** [comment]
> wait what you using cmd or linux or kali linux

I'm on Ubuntu 19.10 having the same issue

**Comment by milkyway4ik777** [comment]
You know? It seems to me that some component is blocking sites, if you look carefully, it writes a Google site and much more, you can know what to do if there are programs that can unlock different sites and much more if it works in termux go in the system / etc / hosts folder and add another text, I can give it, after that everything will start working, but you need to have superuser (root) rights. And if you think logically, you can try to run the same thing, only on a PC device, try to find programs that can manage the hosts file or something like that.

**Comment by kattamani** [comment]
please help out of that i'm also getting same problem

**Comment by johnGachihi** [comment]
Could this be caused by firewalls on the internet provider. I switched my connection to another and it started working

**Comment by hazrul99** [comment]
the solutions is.  use ur mobile data and on hotspot.  tht it!  ez af

**Comment by alemdg** [comment]
my solution was doing ctrl+u (update) to latest version.

**Comment by adamhamlin** [comment]
It would at least be nice to query the connection status programmatically. Seems to only be available in the UI

**Comment by bparikh99** [comment]
> ![image](https://user-images.githubusercontent.com/25084011/55348547-0cbd2380-54d5-11e9-87d0-71a57460aabe.png)
> how to solve this?

can you please go to your system environment variable settings and if you see any http_proxy is set or not!!

**Comment by bparikh99** [comment]
> I am trying to generate http connection from my local server by using the ngrok version 2.X.X but I am getting the status as reconnect error,
> 
> Please find the attach snap.
> ![ngrok](https://user-images.githubusercontent.com/31928487/30420314-c69e9d74-9956-11e7-8b19-a02da2848fec.png)
> 
> Please help me out on this.

can you please go to your system environment variable settings and if you see any http_proxy is set or not!!

**Comment by Extinction32** [comment]
I have solution if you have a anonsurf in your linux just turn it on and turn on your ngrok and its will work

**Comment by skill2003** [comment]
> found the solution is easy

Write me to whatsapp

+51902462029 🤙💖

**Comment by Extinction32** [comment]
OkeyDikirim dari ponsel cerdas Samsung Galaxy saya.
-------- Pesan asli --------Dari: skill2003 <notifications@github.com> Tanggal: 17/05/20  15:03  (GMT+07:00) Ke: inconshreveable/ngrok <ngrok@noreply.github.com> Cc: Extinction32 <genonimo009@gmail.com>, Comment <comment@noreply.github.com> Subjek: Re: [inconshreveable/ngrok] ngrok status reconnecting issue (#446) 



found the solution is easy



Write me to whatsapp

+51902462029 🤙💖



—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/inconshreveable/ngrok/issues/446#issuecomment-629759238",

"url": "https://github.com/inconshreveable/ngrok/issues/446#issuecomment-629759238",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]

**Comment by heroys6** [comment]
For Android(Termux) users, try to turn on cellular network + Hotspot.

**Comment by 007sam007** [comment]
> > I am trying to generate http connection from my local server by using the ngrok version 2.X.X but I am getting the status as reconnect error,
> > Please find the attach snap.
> > ![ngrok](https://user-images.githubusercontent.com/31928487/30420314-c69e9d74-9956-11e7-8b19-a02da2848fec.png)
> > Please help me out on this.
> 
> can you please go to your system environment variable settings and if you see any http_proxy is set or not!!

Bro turn on your hotspot...and start a tunnel u will be online

**Comment by QXR9** [comment]
I will give the resolve %100 for everyone. I Tried to use cellular network and hotspot but it doesnt worked. The Real solution is : Download the older version of ngrok. ITS %100

**Comment by michalsoczynski** [comment]
Try to change region `ngrok http 80 --region=eu` or  download version `2.2.8` from https://dl.equinox.io/ngrok/ngrok/stable/archive

**Comment by Abhinow-katore** [comment]
![ngroke error](https://user-images.githubusercontent.com/67780238/92474261-2a79d680-f1f9-11ea-9a92-b3bb1d79dbb5.jpg)
Solved !!!!1
On your Hotspot (this will pretend as Router)

**Comment by nandini-klocrix** [comment]
> Try to change region `ngrok http 80 --region=eu` or download version `2.2.8` from https://dl.equinox.io/ngrok/ngrok/stable/archive

This solved my issue

**Comment by markvincenttyup** [comment]
> Try to change region `ngrok http 80 --region=eu` or download version `2.2.8` from https://dl.equinox.io/ngrok/ngrok/stable/archive

If eu doesn't work, you might use au. Mine work with ngrok tcp 22 --region=au

**Comment by Genghius** [comment]
> apt install openssh
> ssh -R 80:localhost:4444 serveo.net

serveo.net is not up, what alternatives are there?

**Comment by Genghius** [comment]
> Try to change region `ngrok http 80 --region=eu` or download version `2.2.8` from https://dl.equinox.io/ngrok/ngrok/stable/archive

still get the same issue.

**Comment by Zadpo** [comment]
> > > I am trying to generate http connection from my local server by using the ngrok version 2.X.X but I am getting the status as reconnect error,
> > > Please find the attach snap.
> > > ![ngrok](https://user-images.githubusercontent.com/31928487/30420314-c69e9d74-9956-11e7-8b19-a02da2848fec.png)
> > > Please help me out on this.
> > 
> > 
> > can you please go to your system environment variable settings and if you see any http_proxy is set or not!!
> 
> Bro turn on your hotspot...and start a tunnel u will be online

I also do that, but its not working

**Comment by jarhead1982** [comment]
> 
> 
> I am trying to generate http connection from my local server by using the ngrok version 2.X.X but I am getting the status as reconnect error,
> 
> Please find the attach snap.
> ![ngrok](https://user-images.githubusercontent.com/31928487/30420314-c69e9d74-9956-11e7-8b19-a02da2848fec.png)
> 
> Please help me out on this.

ok you shoud install version  2.2.8 of ngrok

**Comment by kmchmk** [comment]
For all the Termux users:

```
pkg update && pkg upgrade -y
pkg install zip wget -y
wget https://bin.equinox.io/a/e93TBaoFgZw/ngrok-2.2.8-linux-arm.zip
unzip ngrok-2.2.8-linux-arm.zip
chmod +x ngrok
./ngrok tcp 8022
```

And then from your client:
`ssh -p <port> <num>.tcp.ngrok.io`

**Comment by Dgulili** [comment]
![image](https://user-images.githubusercontent.com/58115735/131607289-d6c91c85-df8f-4dce-94bf-9f36a9c7afc9.png)

use mobile network

**Comment by arohacs** [comment]
Downgrading to 2.2.8 resolved the issue for me on Linux. 

To troubleshoot, I turned the firewall off, stripped it down to nothing, same issue, stuck connecting, not matter which region. Spent a couple hours messing around with this. 

This is not a firewall issue IMHO, this is a bug in any version above 2.2.8 - I tried the first few of versions of  2.3.x and they all failed the same way, red text, stuck connecting. 
So perhaps we could consider that 2.2.x is the even number and the stable version? But the instructions on the site download the latest, which serves up 2.3.40, which doesn't work for me: https://dashboard.ngrok.com/get-started/setup

Further, trying an old project that used v1.x to connect via docker works and serves a URL:  https://github.com/kugland/ngrok-tunnel-docker
So more evidence, in my experience, that this has nothing to do with firewalls or hotspots, and more to do with the newer versions that seem to have connection issues.

**Comment by FaithElijah** [comment]
In termux, there also has `termux-chroot` command for ngrok by typing `termux-chroot ngrok http 8080` and it worked.
(Sorry if my English are bad.)

**Comment by dustinpeng** [comment]
I tried 2.2.8 and 2.0.20, with region ap, same reconnecting issue today

**Comment by dustinpeng** [comment]
switch region solved the issue

**Comment by Emdad05** [comment]
Hey , everyone . 
 If u r facing the ngrok reconnecting error then i have the solution. 
Its simple , just turn on your mobile hotspot and open ngrok .

**Comment by Hessah95** [comment]
For me it was a silly mistake, I only forgot to verify my email 🙂 
I noticed that when I turned on the hotspot to use mobile network it returned a helpful error message

**Comment by ajwrynn** [comment]
I had the same issue. For me, turning off VPN solved it.

**Comment by tahaluindo** [comment]
![Screenshot_2023-03-11-21-07-52-861_com termux](https://user-images.githubusercontent.com/94370774/224489437-3d215a3b-dadf-4dda-bbd2-99ce964d019c.jpg)

Help me gaes

**Comment by nitinkanojiya8860** [comment]
Turn ON hotspot then try again

**Comment by BlackyTay** [comment]
A workaround found on YouTube, 
by installing Kali Linux, we can now use the ngrok with WiFi (neither data nor hotspot).

Credited to Grace, she deserved a like from us💕: [ https://www.youtube.com/watch?v=ztmgoY5T0QY&ab_channel=Grace](https://www.youtube.com/watch?v=ztmgoY5T0QY&ab_channel=Grace)

Steps:
1.  Install [**AnLinux - Run Linux on Android** -by EXA Lab](https://play.google.com/store/apps/dev?id=8450947575366721624)
![image](https://github.com/inconshreveable/ngrok/assets/49146462/aab72e1b-b90b-4862-86e2-5aacf7bade0b)
2. In **AnLinux**, choose *Kali* and copy the commands generated
![image](https://github.com/inconshreveable/ngrok/assets/49146462/18f8c469-d317-434e-be8f-993ad5b639b1)
![image](https://github.com/inconshreveable/ngrok/assets/49146462/3e954616-41ef-4c96-89cf-831136163002)
![image](https://github.com/inconshreveable/ngrok/assets/49146462/6b7a0213-2cb7-4a51-89ca-06a14cf00fde)
3. In **Termux**, paste and run the commands. (If you have issues with hash -r, try to remove it as like what I did)
![image](https://github.com/inconshreveable/ngrok/assets/49146462/9991e9e0-53fb-4e28-9892-5f702e1a4e0a)
4. Install ngrok for Kali (My way is different from the video, you can use any suitable method as well)
```tar xvzf ngrok-*.tgz -C kali-fs/root/```
![image](https://github.com/inconshreveable/ngrok/assets/49146462/a1bf7208-c24a-4ce2-bdd7-17600c36014e)
5. Start Kali Linux: 
```./start-kali.sh```
![image](https://github.com/inconshreveable/ngrok/assets/49146462/147af6fe-9c6a-4523-8f57-3bd885c9bf06)
6. Set permission for ngrok
```chmod +x ngrok```
![image](https://github.com/inconshreveable/ngrok/assets/49146462/1281d593-8506-446b-9314-370be839c48a)
7. Add authtoken for ngrok, get yours from [https://dashboard.ngrok.com/get-started/your-authtoken](https://dashboard.ngrok.com/get-started/your-authtoken)
![image](https://github.com/inconshreveable/ngrok/assets/49146462/7e6ae45c-917b-4a4a-8e2e-189d5e213905)
8. Viola, done
![image](https://github.com/inconshreveable/ngrok/assets/49146462/8bc5614e-8330-41ea-a6d8-9f8f69dd1eb6)
9. Leave a like for Grace: [ https://www.youtube.com/watch?v=ztmgoY5T0QY&ab_channel=Grace](https://www.youtube.com/watch?v=ztmgoY5T0QY&ab_channel=Grace)

**Comment by changeyoucant** [comment]
reconnecting (failed to send authentication request: read tcp [2408:8221:811:d1c0:cd89:b675:d021:e3d8]
![image](https://github.com/inconshreveable/ngrok/assets/51197525/4f786f25-9a96-44fc-8ea6-8c34ad3b719f)
 whats this? Dose anyone know it?

**Comment by merouane-tazeka** [comment]
> Try to change region `ngrok http 80 --region=eu` or download version `2.2.8` from https://dl.equinox.io/ngrok/ngrok/stable/archive

This solved the issue for me.

**Comment by devmaker-id** [comment]
> solusinya adalah. gunakan data seluler Anda dan di hotspot. itu dia! ez af

Tidak terfikir namun berjalan normal

**Comment by Himadrimo** [comment]
> Turn ON hotspot then try again

THANK YOU....turns out phone was stopping an outbound forwarding which was possible when hptspot was turned on..Thanks

**Comment by di-sukharev** [comment]
just wait a bit, it should connect automatically
