### ISSUE TITLE
Trying to tunnel to https://localhost instead of http://localhost

### ISSUE THREAD

**Issue by Luneya** [inconshreveable/ngrok#448]
This is slightly more difficult than I imagined.

I am trying to test my locally running website on VirtualBox (which runs on https://localhost:8447) against some google tools for SEO before we launch the site.

I am trying the following:
`$ ./ngrok http -hostname https://localhost 8447`

But I get the response: 
*Tunnel session failed: Only Pro & Business plans may bind custom hostnames.
Failed to bind the custom hostname 'https://localhost' for the account xxx*

So that doesn't work. But I don't see anything in the document on how to redirect the tunnel to https://localhost instead of http://localhost.

Can anybody help me?

**Comment by LoganDark** [comment]
`-hostname` is for the hostname you want to tunnel to, not the hostname you are tunneling from.

**Comment by mayeaux** [comment]
Doesn't work for me.

`ERROR:  Tunnel 'command_line' specifies invalid address 'https://localhost:8443': address https://localhost:8443: too many colons in address`

**Comment by LoganDark** [comment]
Don't use `https://`.

**Comment by mayeaux** [comment]
I needed https for localhost because of some WebRTC testing I was doing, I ended up building a workaround but it would have been nice if this instance, maybe it's too much of an edge case who knows

**Comment by LoganDark** [comment]
`https` will work over `ngrok`, but only because `ngrok` forwards whatever is sent to it, not because `ngrok` knows whether it is `https` or not.

**Comment by chris31389** [comment]
Has anyone managed to get https to https working?  I'm trying to solve the same issue.

**Comment by priyakh** [comment]
i am trying https://localhost:8881 with ngrok . I keep getting 502 Bad Gateway errrors

**Comment by kenzouno1** [comment]
same issues.  502 Bad Gateway errrors

**Comment by kenzouno1** [comment]
i tried create a nodejs proxy and this working for me.
here is my code

````javascript
var proxy = require('express-http-proxy');
var app = require('express')();
//fix ssl localhost
process.env.NODE_TLS_REJECT_UNAUTHORIZED = "0";

app.use('/', proxy('https://localhost:5001'));
app.listen(3000);
````

**Comment by dalepotter** [comment]
Looking at the comments, it seems @kenzouno1 has a good solution to this :-)

I have no experience in nodejs, so is there any chance someone be able to give me a quick set-by-step guide on how to:
- create a nodejs proxy
- use the above code
- start a node server

??!

I imagine it's probably only a few commands but google isn't helping me on where to start!

**Comment by danbriggs5** [comment]
@dalepotter You could also use something other than nodejs if you're more familiar with something else. But to get it running in node:
1. Install nodejs and npm. You should be able to find a guide for this on google.
2. Open a terminal and run these commands
```shell
# Create a new folder and enter it
mkdir node-proxy-server
cd node-proxy-server

# Initialize a nodejs project
npm init

# Install packages with nodejs
npm install --save express express-http-proxy

# Create a javascript file and open it
touch index.js
open index.js

# Paste the code above from kenzouno1 into the file and save it

# Run the proxy server
node index.js
```

I didn't test this myself so there may be a typo or two but should get you on your way ;)

**Comment by dalepotter** [comment]
Thanks so much for the tutorial @danbriggs5 - that worked perfectly!!

**Comment by nisckis** [comment]
I solved the 502 errors when using https on localhost:8443 by doing 

> ngrok tcp 8443

then accessed from the browser using **https://** instead of **tcp://** with the Forwarding URL you get in the console.

**Comment by th0mk** [comment]
I've just had mail contact with Ngrok, and they've fixed this in the beta that you can [download here](https://dl.equinox.io/ngrok/ngrok/beta).
Here's an example of how to start it with https localhost:
![image](https://user-images.githubusercontent.com/9088316/53579760-736bbc00-3b7a-11e9-8916-70b14f60809d.png)
Simply add `https://` before localhost.

They're expecting to release this update to the stable branch next week.

**Comment by jonsagara** [comment]
> I've just had mail contact with Ngrok, and they've fixed this in the beta that you can [download here](https://dl.equinox.io/ngrok/ngrok/beta).
> Here's an example of how to start it with https localhost:
> ![image](https://user-images.githubusercontent.com/9088316/53579760-736bbc00-3b7a-11e9-8916-70b14f60809d.png)
> Simply add `https://` before localhost:
> `ngrok http https://localhost`
> 
> They're expecting to release this update to the stable branch next week.

I just upgraded to `2.3.12`, and this fix works. Thanks!

**Comment by ZeeshanAhmadKhalil** [comment]
In case you are fan of cpy paste:
`ngrok http 44386 --host-header=localhost:44386`

**Comment by Chandan96100** [comment]
~ $ chmod 777 ngrok
~ $ ./ngrok authtoken 1y54WLRLCTMPKDTr78sPD3ans2e_5yJzdAP3Y48bXhRcMaDZj
bash: ./ngrok: Bad address
~ $

**Comment by erinloy** [comment]
> In case you are fan of cpy paste: `ngrok http 44386 --host-header=localhost:44386`

Above did not work for me. (1+ year later)

This works for me:

     ngrok http https://localhost:1234/ --host-header="localhost:1234"

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
