### ISSUE TITLE
QRCode

### ISSUE THREAD

**Issue by Ayc0** [inconshreveable/ngrok#449]
It could be awesome if a QRcode was displayed when a tunnel is opened and so, we don't have to copy paste the url when testing website on mobile

**Comment by LoganDark** [comment]
Is this an ngrok 2.0 feature request?

**Comment by Ayc0** [comment]
Maybe not for the v2, but it's proposal of feature

**Comment by LoganDark** [comment]
v1 will not have any new features added. Check the readme.

**Comment by russorat** [comment]
continued in https://github.com/ngrok/ngrok/issues/6
