### ISSUE TITLE
Packaging

### ISSUE THREAD

**Issue by Miserlou** [inconshreveable/ngrok#45]
Are they any plans to package ngrok?

Installing it seems to be the only hurdle to adoption right now - downloading a file, unzipping and installing it seems so.. 90s.

Would love it if I could install this through Apt or Homebrew!

**Comment by kevinSuttle** [comment]
Seems to be in Homebrew now. Is this not an officially supported package?

**Comment by inconshreveable** [comment]
@kevinSuttle i'm not sure what you mean, but the homebrew package is built from this ngrok source tree. this particular issue is honestly too broad. I'm going to close it. It would be nice to package ngrok as .app and .msi for osx/windows, but if anyone wants that, we'll make separate issues for each one and any other change to the building/packaging of it.

**Comment by kevinSuttle** [comment]
@inconshreveable Thanks for the explanation.
