### ISSUE TITLE
how to expose localhost domains?

### ISSUE THREAD

**Issue by videni** [inconshreveable/ngrok#452]
I have several localhost domains, for examples,
```
127.0.0.1 a.local
127.0.0.1 b.local
```
each domain is added to nginx , and listen port 80,   I'd like to expose the two domains to the internet, how to do this?  Currently , I can only expose 127.0.0.1: [any_port]

**Comment by tomasdev** [comment]
if you read `ngrok --help` it says

`ngrok http foo.dev:80`

So you can do `ngrok http a.local:80`

**Comment by videni** [comment]
@tomasdev , executing `ngrok http a.local:80` will complain
```
You may only specify one port to tunnel to on the command line, got 2: [http a.local:80]
```

**Comment by lafolle** [comment]
It seems this behaviour is portrayed by ngrok version 1.7.
```
lafolle@yoss:~/src/ngrok$ ./bin/ngrok version
1.7
lafolle@yoss:~/src/ngrok$ ./bin/ngrok http a.b.c:8080
You may only specify one port to tunnel to on the command line, got 2: [http a.b.c:8080]
```

This command works fine with version 2.8,  which can be downloaded from https://ngrok.com/download .
