### ISSUE TITLE
How to send HTTPS GET? 

### ISSUE THREAD

**Issue by crisol** [inconshreveable/ngrok#453]
I need send HTTPS with GET to Telegram API.

**Comment by tomasdev** [comment]
Not sure what you mean here @crisol 

ngrok is not a request client, that would be `wget` or `curl` for command line alternatives.

ngrok is a reverse proxy, meaning it allows to forward a local server to the internet via a proxy (by default, the proxy is ngrok.io website)

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
