### ISSUE TITLE
I Use Mac client segmentation fault

### ISSUE THREAD

**Issue by wujunze** [inconshreveable/ngrok#458]
hello

I've been compiling a Mac client
Error 28127 segmentation fault
![image](https://user-images.githubusercontent.com/12997869/32220656-880225ee-be00-11e7-8602-eb17df6ad265.png)

**Comment by zrcfdhj** [comment]
![image](https://user-images.githubusercontent.com/15134934/33523807-a1d31a82-d84a-11e7-9d96-2e41d20d6847.png)
same

**Comment by youxiaoriqi** [comment]
I have the same error

**Comment by gongroc** [comment]
I have the same error

**Comment by stajason** [comment]
I have the same error,my macos version is 10.13.2

**Comment by stajason** [comment]
I have solved the problem. Golang must be upgraded to more than 1.8.

**Comment by iamike** [comment]
@stajason do you mean upgrade mac's go-lang?

**Comment by YL2014** [comment]
same problem

**Comment by stajason** [comment]
@iamike 升级服务器的golang版本，golang1.6编译出来的版本在mac上运行是有bug的。

**Comment by delonzhou** [comment]
@stajason thanks! it really works by using a newer golang version. I used the current latest 1.10.
