### ISSUE TITLE
BUG Invalid address server_addr 'ngrokd.ngrok.com:443

### ISSUE THREAD

**Issue by matiasmasca** [inconshreveable/ngrok#460]
Hi,
I downloaded the Linux 64bit version (https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-amd64.zip). I use Linux Mint 18.2 Mate 64bit.

When I run: `ngrok 80`

I get this:  **"Invalid address server_addr 'ngrokd.ngrok.com:443': lookup ngrokd.ngrok.com: no such host"**

When I try to run, in this way:  `ngrok http 80`

I get this: **"You may only specify one port to tunnel to on the command line, got 2: [http 80]"**

when I do a ping to: `ping ngrokd.ngrok.com`
(ping from Argentina)

I receive this **"ping: unknown host ngrokd.ngrok.com"**

but the main domain works: PING ngrok.com (54.68.226.153) 56(84) bytes of data.

**Comment by m7mdcc** [comment]
Hello , if you are already installed ngrok via repository manager try to delete its . to be sue if you are running ngrok from downloaded package try to run with ./ngrok ?

**Comment by hesapadim** [comment]
@m7mdcc Downloading the package from ngrok.com fixed my problem! Thanks! :)

**Comment by xCuri0** [comment]
but why is there a broken package in the repo ?

**Comment by bberenberg** [comment]
Same thing on Ubuntu as well.

**Comment by juniordeveloperforlife** [comment]
step 1 downnload ngrok form official website
step 2 unzip it
step 3 now you will se ngrok in unzipped format
step4  fom the same folder issue cmd which have this syntax     ./ngrok http <ur exprees server port  only> 

 eg:  ./ngrok http 5000

**Comment by Gacekky1** [comment]
Ok, cool, but the package from the repository should work...

**Comment by mobagenie** [comment]
> step 1 downnload ngrok form official website step 2 unzip it step 3 now you will se ngrok in unzipped format step4 from the same folder issue cmd which have this syntax ./ngrok http
> 
> eg: ./ngrok http 5000

not work for me on arm64 based devices with ngrox arrm64 deb package. error :

bash: ./ngrok: cannot execute binary file: Exec format error

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
