### ISSUE TITLE
Feature Request - Port to ESP8266

### ISSUE THREAD

**Issue by dylancaponi** [inconshreveable/ngrok#464]
Would love to get this concept working on an ESP8266 and bypass having a Raspberry Pi or other type of hub.  Do you think it could be ported?

I would be happy to work on it myself with some guidance.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
For anyone else who makes it to this issue, check out this guide to running ngrok on Raspberry PI: https://ngrok.com/docs/guides/device-gateway/raspbian/
