### ISSUE TITLE
Chrome alert due to Symantec's certificate

### ISSUE THREAD

**Issue by ricardopieper** [inconshreveable/ngrok#466]
Chrome wont trust Symantec certificates anymore. When I open a ngrok URL on chrome/opera, I get this alert:

>    The certificate used to load https://xxxxxxx.ngrok.io/... uses an SSL certificate that will be distrusted in the future. Once distrusted, users will be prevented from loading this resource. See https://g.co/chrome/symantecpkicerts for more information.

ngrok uses rapidssl and geotrust certificate in its chain, but those are Symantec as well:

> On January 19, 2017, a public posting to the mozilla.dev.security.policy newsgroup drew attention to a series of questionable website authentication certificates issued by Symantec Corporation’s PKI. Symantec’s PKI business, which operates a series of Certificate Authorities under various brand names, including Thawte, VeriSign, Equifax, GeoTrust, and RapidSSL, had issued numerous certificates that did not comply with the industry-developed CA/Browser Forum Baseline Requirements. During the subsequent investigation, it was revealed that Symantec had entrusted several organizations with the ability to issue certificates without the appropriate or necessary oversight, and had been aware of security deficiencies at these organizations for some time.

**Comment by Suxsem** [comment]
i can confirm this problem

**Comment by phbernard** [comment]
Although there is nothing wrong with this issue (after all, the certificate will still be hold valid until October 2018), this is especially annoying when using the Chrome Dev Console. I constantly get this nagging warning I can't get rid of.

It would be great if ngrok could upgrade its certificate soon and not wait until 2018Q3 or Q4.

**Comment by ericlowry** [comment]
tripple confirmation - I am getting the same warnings in chrome:

The SSL certificate used to load resources from https://xyz-123.ngrok.io will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
