### ISSUE TITLE
Invalid Auth Token

### ISSUE THREAD

**Issue by ZeeshanSultan** [inconshreveable/ngrok#468]
I got my auth token from 
> [https://dashboard.ngrok.com/auth](url)
and set it up via

> ngrok authtoken [token]
but got this error.
![token](https://user-images.githubusercontent.com/8667667/34304057-e2be1c0e-e759-11e7-9007-f33d56145d6a.jpg)

i have confirmed the token is same as available on the site. and there's no option to renew or revoke this one.

**Comment by rezazoom** [comment]
Same issue for me #474

**Comment by fabiopaiva** [comment]
any update?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
