### ISSUE TITLE
Running ngrok in background on windows?

### ISSUE THREAD

**Issue by Symous** [inconshreveable/ngrok#469]
Hi, is there any way we can running ngrok in background(hiding the terminal totally). I would like to make a small tool(windows exe) to enable user to startup or shutdown ngrok manually without terminal but GUI.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
