### ISSUE TITLE
QR Code [Feature Request]

### ISSUE THREAD

**Issue by zachgibson** [inconshreveable/ngrok#473]
It’d be amazing to have the CLI generate a QR code to scan and open the URL.

**Comment by Sjeanpierre** [comment]
Hi I know this isn't exactly what you asked for, but this is a temporary solution that might help you,

this will create and ngrok connection and open your browser to the QR code for the connection. 

`ngrok http 8080 > /dev/null &2>1; open $(curl -s http://localhost:4040/api/tunnels | jq ".tunnels[1].public_url" | xargs -I{} echo "https://chart.googleapis.com/chart?cht=qr&chl={}&chs=180x180&choe=UTF-8&chld=L|2")`

and a slightly more portable version, in case `jq` isn't installed

`ngrok http 8080 > /dev/null &2>1; open $(curl -s http://localhost:4040/api/tunnels | egrep -o 'https:\/\/.{8}.ngrok.io' | xargs -I{} echo "https://chart.googleapis.com/chart?cht=qr&chl={}&chs=180x180&choe=UTF-8&chld=L|2")`

**Comment by Lokeshwaran-M** [comment]
## try this make it as a cli command and pass the port number as argument

``` python
import ngrok  
import qrcode

# Create an ngrok tunnel and get the public URL
tunnel = ngrok.connect(5000, authtoken_from_env=True)
print (f"Terminal Tunal Url : {tunnel.url()}")

# Get the public URL of the tunnel
public_url = tunnel.url()

# Generate a QR code for the ngrok URL
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data(public_url)
qr.make(fit=True)

# Save the QR code as an image
img = qr.make_image(fill_color="black", back_color="white")
img.save('ngrok_qr.png')
```

**Comment by Lokeshwaran-M** [comment]
## try this make it as a cli command and pass the port number as argument

``` python
import ngrok  
import qrcode

# Create an ngrok tunnel and get the public URL
tunnel = ngrok.connect(5000, authtoken_from_env=True)
print (f"Terminal Tunal Url : {tunnel.url()}")

# Get the public URL of the tunnel
public_url = tunnel.url()

# Generate a QR code for the ngrok URL
qr = qrcode.QRCode(
    version=1,
    error_correction=qrcode.constants.ERROR_CORRECT_L,
    box_size=10,
    border=4,
)
qr.add_data(public_url)
qr.make(fit=True)

# Save the QR code as an image
img = qr.make_image(fill_color="black", back_color="white")
img.save('ngrok_qr.png')
```

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Continued in https://github.com/ngrok/ngrok/issues/6
