### ISSUE TITLE
Something wrong with my auth

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#474]
Hey, I'm trying to establish a tunnel session, but I'm getting this error:

> The authtoken you specified is properly formed, but it is invalid.
> Your authtoken: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> This usually happens when:
>     - You reset your authtoken
>     - Your authtoken was for a team account that you were removed from
>     - You are using ngrok link and this credential was explicitly revoked
> Go to your ngrok dashboard and double check that your authtoken is correct:
> https://dashboard.ngrok.com/auth
> 
> ERR_NGROK_107

I've double checked my authtoken, even I've reset mine and check again, but nothing happens.
ngrok version 2.2.8 on Windows 10 x64

**Comment by Pusdk8** [comment]
Same issue works on a different one that i have just not this system

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
