### ISSUE TITLE
Getting an error as "502 Bad Gateway"

### ISSUE THREAD

**Issue by tanvishah-syn** [inconshreveable/ngrok#475]
Hi, I have installed ngrok version 2.2.8 on mac. I am trying to send http request to server using postman. A request is sending correctly. I am able to see headers in http://127.0.0.1:4040 ngrok web interface. I am getting a response as " 502 Bad Gateway. The server returned an invalid or incomplete response." How would I debug ngrok request?

**Comment by dannyfreed** [comment]
This just started happening to me. Any suggestions/fixes? Nothing knowingly changed on my end as of late...

**Comment by scrummitch** [comment]
bump on this, it seems to happen when i paste it into the facebook sharing debugger

**Comment by jefflam** [comment]
Getting this error too -- anyone resolution..?

**Comment by harksha** [comment]
+1. v2.2.8 running on windows 10.

**Comment by Joe118** [comment]
+1 v2.2.9 and v2.2.7 on windows server 2008. trying on windows 7 now.

**Comment by Joe118** [comment]
Well I am able to see localhost:4040 (which is the introspection page) through the tunnel, so its some disagreement between ngrok and my application. It'd be really nice if ngrok would log somewhere WHAT it did not like.

**Comment by harksha** [comment]
Try running it without ssl

**Comment by Joe118** [comment]
Thanks @harksha -- examining the documentation for how to ;)

EDIT -- you probably mean adding -bind-tls=false -- that did not work:

Incorrect Usage: flag provided but not defined: -bind-tls

**Comment by harksha** [comment]
@Joe118 No, I mean you need to disable ssl on your local solution, so it runs on http, not https

**Comment by Joe118** [comment]
@harksha my http server already was running on http only.

Anyways I'm pretty convinced this is not a problem with ngrok because I can direct ngrok to forward port 4040 (its own diagnostic) and then I can see it fine on the ngrok.io subdomain. So its something to do with my http server.

I still can't figure out why the port forwarding would cause a 502, because I can see the web page when I run a web browser on the same machine and look at it via localhost:8000/index.html

**Comment by harksha** [comment]
@Joe118 ok, I thought that's what fixed it, but you're right, it might be port forwarding(which got stopped when I removed ssl). Don't have any idea why, tho'.

**Comment by Joe118** [comment]
@harksha thanks!

I'm going to chat with the people who wrote the embedded web server I'm using -- EmbedIO. I'll report back here if they find anything.

**Comment by Joe118** [comment]
@harksha and @inconshreveable I opened https://github.com/unosquare/embedio/issues/154 on the EmbedIO project's github repository.

**Comment by Joe118** [comment]
OK its not an ngrok bug and not a bug in EmbedIO either. :)

The issue is that when you tell a webserver to serve pages on http://localhost:8787/ (as an example), *some* also bind http://127.0.0.1:8787/ and some do not. There's no rule that the webserver has to, but also no rule that it does NOT have to. So to be sure ngrok will tunnel your web server, you have to bind both localhost:8787 and 127.0.0.1:8787

@inconshreveable , so now the question becomes, did anything change in ngrok recently to require both localhost and 127.0.0.1 to be bound?

**Comment by sharonmalio** [comment]
Hey so you will need to start your server manually so that it listens on the port you want. 
Run **php -S 0.0.0.0:5000 -t public/** on linux command line with 5000 being the port you wanna feed to ngrok. Then go to ngrok and run ngrok http 5000

That will work

**Comment by andyfaizan** [comment]
Switching the protocol from `http` to `tls` worked for me.

**Comment by seannybgoode** [comment]
switching from http to tls killed the 502 error for me, but now i'm getting an invalid hostname 4xx error

**Comment by syberkitten** [comment]
Also getting the bad gateway for connecting to localhost running an HTTPS (TLS) server on port 9011.
When switching to HTTP (not HTTPS) it works.

Any new ideas?

**Comment by amardesaiZT** [comment]
This is what worked for me. 
Spent hours searching for it. Some of the above solution didn't work. 
I would recommend this order. 
ngrok http https://localhost:5443 -host-header="localhost:5443" -subdomain=<If you have pro>
ngrok http https://localhost:5443 -host-header="localhost:5443"

**Comment by nanddeepn** [comment]
Ngrok expects a web server to be running on localhost. If there isn’t a server running, you’ll see a 502 error

**Comment by karls** [comment]
I also ran into the same issue with testing some webhooks locally. In my case, I had to make sure ngrok was tunneling to my local development server running on _HTTPS_, not HTTP.

**Comment by dhanaSiggie1111** [comment]
Hi tanvish,

502 gateway error occurs because ngrok not able to receive any reponse from Localhost.

The things need to be done is : 1.Start a webserver in a Port 2.Trigger ngrok command in that Port.

What i have done is -> Started a tomcat Web Server in 8080. -> Then Triggered ngrok http 8080.

It works really Kool .. Try this .. Hope it works for You .

**Comment by sqram** [comment]
No luck here.

Running http://localhost:5000

i go to that url on the browser, looks good. page loads.

fired up ngrok 
`ngrok http 5000`

whcih outputs
`
Session Status                online                                            
Account                       bruce (Plan: Free)                                
Version                       2.3.35                                            
Region                        United States (us)                                
Web Interface                 http://127.0.0.1:4040                             
Forwarding                    http://9b899894.ngrok.io -> http://localhost:5000 
Forwarding                    https://9b899894.ngrok.io -> http://localhost:5000
                                                                                
Connections                   ttl     opn     rt1     rt5     p50     p90       
                              0       0       0.00    0.00    0.00    0.00 
`

but when going to `http://9b899894.ngrok.io`, it shows:
`The connection to https://9b899894.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:5000.`

localhost:5000 works though

**Comment by Nightrider0098** [comment]
just use 
ngrok http port_number
it works

**Comment by phelps-matthew** [comment]
For linux users w/ default port 80:
```bash
sudo apt-get install apache2
sudo service apache2 start
ngrok http 80
```
* Make sure port 80 is allowed through firewall
* place sample html file in `/var/www/html/index.html`

**Comment by RAJESHMUDI** [comment]
Sudo not install on Android phone when i using termux .

**Comment by heniotierra** [comment]
```
ngrok http 8080
```
This works for me! :+1:

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
