### ISSUE TITLE
https security error on nested subdomains

### ISSUE THREAD

**Issue by benkuhn** [inconshreveable/ngrok#476]
Steps to reproduce:

1. Run `python -m SimpleHTTPServer 8080`
2. In a separate terminal run `ngrok http 8080 --subdomain is.nested`
3. Visit https://is.nested.ngrok.io

Expected results: same page as http://is.nested.ngrok.io, or https://isnested.ngrok.io if you start that tunnel instead.

Actual results: (in Chrome) a `NET::ERR_CERT_COMMON_NAME_INVALID` error:

> This server could not prove that it is is.nested.ngrok.io; its security certificate is from *.ngrok.io.

I'm on macOS High Sierra and tested on Chrome 63, Firefox 57 and Safari 11.0.3. Using ngrok 2.2.8.

**Comment by benkuhn** [comment]
Ack--I thought this was a regression because I misread some internal docs, and it looks like this is actually impossible due to how SSL name validation works :( Sorry; closing.

**Comment by sunil3590** [comment]
Did you end up doing
`ngrok http 8080 --subdomain is-nested`
or something along that line?
