### ISSUE TITLE
Self-Hosted allows http connections but fails on https connections

### ISSUE THREAD

**Issue by jryd** [inconshreveable/ngrok#482]
I followed the steps here, step-by-step:

https://gist.github.com/lyoshenka/002b7fbd801d0fd21f2f

I start the server up with:

`sudo bin/ngrokd -tlsKey=device.key -tlsCrt=device.crt -domain="$NGROK_DOMAIN" -httpAddr=":8000" -httpsAddr=":8001"`

I then start my client up with:

`./ngrok.exe -config=ngrok-config -log=stdout -subdomain=example 80`

My config file:

```
server_addr: ngrok.my-actual-domain.com:4443
trust_host_root_certs: false
```

This gives me the below through the web interface:

> To get started, make a request to one of your tunnel URLs:
> http://example.ngrok.my-actual-domain.com:8000
> 
> https://example.ngrok.my-actual-domain.com:8000

If I visit the http URL it works perfectly. If I visit the https URL then I get a browser error and this in my server output:

> [20:33:06 EST 2018/02/28] [WARN] (ngrok/log.(*PrefixLogger).Warn:87) [pub:17faad03] Failed to read valid http request: malformed HTTP request "\x16\x03\x01\x00\xd0\x01\x00\x00\xcc\x03\x03\xccf;\x8d?A\\\xd2\xd0\x1a\xff\xdb\xf3\xe9\x81j\xaa5GM\b\v\xe41d\x16W:\x95\x90\xb7\x06\x00\x00\x1c\xca\xca\xc0+\xc0/\xc0,\xc00̨̩\xc0\x13\xc0\x14\x00\x9c\x00\x9d\x00/\x005\x00"

If I try visit https://example.ngrok.my-actual-domain.com:8001 instead, I get this in my server output:

> [20:34:29 EST 2018/02/28] [WARN] (ngrok/log.(*PrefixLogger).Warn:87) [pub:24ec9ac7] Failed to read valid https request: EOF

Where have I gone wrong in setting this up?

**Comment by adamk33n3r** [comment]
Running into this as well. Confused why it's setting up the https on the http port when one specifies a different one.

**Comment by fuqiangleon** [comment]
@jryd , hi, have you fixed your problem yet? we have faced the same problem.
