### ISSUE TITLE
dial tcp: lookup localhost on 127.0.0.1:53: no such host

### ISSUE THREAD

**Issue by zero-master** [inconshreveable/ngrok#484]
Version 2.2.8

The connection to https://06c1c54b.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:8080.

Make sure that a web service is running on localhost:8080 and that it is a valid address.

The error encountered was: dial tcp: lookup localhost on 127.0.0.1:53: no such host

**Comment by zero-master** [comment]
Solved by using 127.0.0.1 instead of localhost

Works
ngrok http 127.0.0.1:8080 -host-header="127.0.0.1:8080"

Doesn't work
ngrok http localhost:8080 -host-header="localhost:8080"

**Comment by mohwaili** [comment]
Make sure this line is included in the hosts file 
127.0.0.1       localhost

For MacOS you can find the hosts file here: /etc/hosts

**Comment by OzanKurt** [comment]
I am using WAMP as my http server. After I installed ngrox I started getting this same error on all my vhosts. 

```
dial tcp4: lookup example.local on 127.0.0.1:53: no such host
```

**Comment by jlnarvaez** [comment]
My problem was that I had the VPN on.

**Comment by shanmdphd** [comment]
@jlnarvaez, thanks for the response. I had the same issue and my VPN was on.

**Comment by queena-zhang** [comment]
@OzanKurt 
Problem is : You don't have a localhost named example.local
Solution :  add this host name and point it to localhost address
On mac you can do : 
1. open the terminal
2. sudo vi /etc/hosts
3. enter password
4. add this line : 127.0.0.1 example.local (replace the example)
Done

**Comment by Gauravpawar3102** [comment]
guys use localtunnel instead it solved my problem

**Comment by profermarquez** [comment]
Work for me:      ngrok http 127.0.0.1:5000 --host-header="127.0.0.1:5000"

with two --

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
