### ISSUE TITLE
ngrok won't let me tunnel to localhost

### ISSUE THREAD

**Issue by AstroNoudOx** [inconshreveable/ngrok#485]
I'm trying to setup up a minecraft for my son and his friends.

I'm using Ubuntu 16.04 and can connect to the server with the local ipv4 addres but not with the IP/TCP Addres i get from ngrok

**Comment by inconshreveabIe** [comment]
Whatever

**Comment by caseysoftware** [comment]
https://ngrok.com/docs/using-ngrok-with#minecraft

These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
