### ISSUE TITLE
How to actually tunnel to https://localhost?

### ISSUE THREAD

**Issue by lukewlms** [inconshreveable/ngrok#487]
I upgraded my account, attempted tls and tcp tunnels - nothing has worked.

Creating these types of tunnels is billed in other threads as the only way to tunnel to https://localhost (I need testing with the green check for Stripe PaymentRequest setup); but the URLs ngrok gives me when I use these protocols are not usable in a browser (e.g. tls://...)

How can I use a browser to tunnel to https://localhost:xxx domains?  It appears this must be possible given these threads:

https://github.com/inconshreveable/ngrok/issues/194 https://github.com/inconshreveable/ngrok/issues/123

Thanks!

**Comment by inconshreveabIe** [comment]
Figure it out yourself.

**Comment by JooLuiz** [comment]
I use ngrok to run a server in local host 3001, using rails servers.
My rails server is running in bash and, in another bash, I run the command "ngrok http 3001"
And it works. Usualy gives me and url like this: https://e83ca07e.ngrok.io
try that, maybe works.
"ngrok http YOURHOSTNUMBER"

**Comment by brasten** [comment]
@lukewlms did you ever get this figured out? I'm trying to do the same thing.

**Comment by lukewlms** [comment]
No :\ got a snarky comment from the dev but not solution.

**Comment by emptyflash** [comment]
This would be really nice to have. I'm trying to test the autocert code I've been writing, and it'd be nice if I could use ngrok to tunnel tcp 80 and 443 on the same domain.

**Comment by lalo312** [comment]
you need to upgrade

2018-11-21 22:26 GMT-03:00, jeff-h <notifications@github.com>:
> This all seems pretty odd. I run Laradock locally and don't even bother
> setting up nginx to listen on port 80. My sites are not available on
> anything but https, anywhere, ever. It's 2018 after all. I have no interest
> in port 80.
>
> Perhaps there's a technical reason why ngrok doesn't appear to support an
> https localhost? When you access a url such as https://14541v64.ngrok.io,
> the https cert is supplied by ngrok.io. The traffic is decrypted on their
> server, and then sent onwards unencrypted to your localhost (albeit
> encrypted via an SSH tunnel or however they implemented it, I presume).
>
> I wish we could tell ngrok to send our (probably self-signed) certs straight
> through to the client, and not use their cert at all. Just pass the
> https-encrypted traffic straight through to our localhost.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/inconshreveable/ngrok/issues/487#issuecomment-440881261


-- 
Raúl Gloodtdofsky Meirelles
26045165
tridejur.uy

**Comment by jeff-h** [comment]
@lalo312 — not sure what you're suggesting I should upgrade. I just installed ngrok today, so that would be the latest.

**Comment by lalo312** [comment]
i mean if you have localhos defined in your hosts file just do ngrok http
80 and youll be on localhost for https you need to upgrade

**Comment by ttbarnes** [comment]
+1, it doesn't seem possible to use a localhost https with ngrok 😢

I've gone through other related github issues and tried the suggestions - IP address, tcp tunnels etc. Nothing seems to work. It would be amazing if it did work 😄

**Comment by alkoval** [comment]
Will this opportunity ever work?

**Comment by th0mk** [comment]
This issue can be closed, see [this issue](https://github.com/inconshreveable/ngrok/issues/448#issuecomment-468329794)

**Comment by nelsonenzo** [comment]
this issue can not be closed. Basically, the problem is ngrok with tls certs can only forward to http, there is no https option when using tls, rather than http.  It's bumkis.

**Comment by ThorodanBrom** [comment]
https://github.com/inconshreveable/ngrok/issues/448#issuecomment-461398044 This seems to work

**Comment by pretech86** [comment]
the same issue with me

**Comment by rSkogeby** [comment]
The way to tunnel https on localhost is:

1. [Setup certificates]( https://www.freecodecamp.org/news/how-to-get-https-working-on-your-local-development-environment-in-5-minutes-7af615770eec/)
2. Make your server include `server.crt` and `server.key` in its headers. E.g. using Uvicorn I did  
    `uvicorn.run("views:app", host="localhost", port=5000, log_level="info", ssl_keyfile='server.key', ssl_certfile='server.crt')`
3. With your server running on e.g. https://localhost:5000 forward your port as described in [Local HTTPS Servers](https://ngrok.com/docs):
`ngrok http https://localhost:5000`
4. You should now have an ngrok instance using https all on free plan

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
