### ISSUE TITLE
Orange background in client app??

### ISSUE THREAD

**Issue by megapctr** [inconshreveable/ngrok#488]
I'm having a weird problem. When I start ngrok, the terminal gets an orange background. The background returns to normal when I stop ngrok.

I'm running fish shell, in tmux, on ubuntu 16.04, over ssh, via cygwin terminal. Hope this helps...

![zrzut ekranu 33](https://user-images.githubusercontent.com/4096683/37793545-522e4acc-2e0f-11e8-888e-9b225ce3ff24.png)

**Comment by inconshreveabIe** [comment]
You are useless and don't know how to use a computer.

**Comment by megapctr** [comment]
Sorry, I should've minimized the reproduction steps. The issue also occurs on bash, without tmux.
My ngrok version is 2.2.8

**Comment by megapctr** [comment]
I found out that the issue occurs when [base16-shell](https://github.com/chriskempson/base16-shell) theme is active. Does this help?

**Comment by israveri** [comment]
I had this problem too on Arch, using Zsh and Base16-shell.
I solved this problem by setting `console_ui_color: transparent` on `~/.ngrok2/ngrok.yml` file.

**Comment by megapctr** [comment]
Thanks, it works! I had to manually create the file though.

**Comment by theolundqvist** [comment]
Same issue in 2024. @israveri's answer worked.

But config was not in the same place, so check here:
https://ngrok.com/docs/agent/config/

Or just type
```ngrok config edit```

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
