### ISSUE TITLE
Provide a snap package

### ISSUE THREAD

**Issue by jsamr** [inconshreveable/ngrok#489]
[Snap](https://snapcraft.io/) is a cross-distro easy to setup package manager. Getting very popular. Would be so great if you could support!

**Comment by prithvihv** [comment]
sudo snap install --edge ngrok
thats the repo i found 
https://github.com/khiemdoan/ngrok-snap

**Comment by jsamr** [comment]
@prithvihv I think it's quite recent but thanks! I'll close for now.
