### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Cvar1984** [inconshreveable/ngrok#493]
Installed ngrok new version on Debian chroot ( android ) segment fault, so im tired install ngrok v 1.6 and 
boom "Invalid address server_addr 'ngrokd.ngrok.com:443': lookup ngrokd.ngrok.com: no such host"
:"(

**Comment by thomasliuh** [comment]
It would be better to have your own domain and resolve this domain to the IP address of your server on which runs the Debian system.
