### ISSUE TITLE
Possible to use ngrok on a single interface?

### ISSUE THREAD

**Issue by hook-s3c** [inconshreveable/ngrok#498]
Sometimes I change NICs, or need to turn one of them off - and because of this ngrok seems to disconnect briefly. 

Just wondering if there was an interface flag, or if one could be added?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
continued in https://github.com/ngrok/ngrok/issues/10
