### ISSUE TITLE
How to fix the port used by the TCP connection?

### ISSUE THREAD

**Issue by thomasliuh** [inconshreveable/ngrok#499]
I have set up a connection by the TCP protocols but I noticed that every time I run the program, the port that it used changes. I wonder if there is a method to fix this port.
![problem4](https://user-images.githubusercontent.com/40030349/41109966-d9f0a6b2-6aaa-11e8-9e9d-50d2db234251.png)

**Comment by jguice** [comment]
See https://ngrok.com/docs#remote-addr

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
