### ISSUE TITLE
where is the default configuration file path on Mac

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#500]
i started ngrok with `-config` option to specific the configuration file path,it went all right.
but i dont want to specific it all the time.i read the [document](https://ngrok.com/docs#default-config-location)  and [docs](https://github.com/inconshreveable/ngrok/blob/master/docs/SELFHOSTING.md).i suppose the default configuration file location is `/Users/username/.ngrok/ngrok.yml`,but it went wrong.
so!where is the default configuration file location on Mac?
![image](https://user-images.githubusercontent.com/28668354/41204624-8b5e5f6e-6d19-11e8-9f61-64e84f77a051.png)
> the ngrok was not downloaded from `ngrok.com`,it was build by myself which was followed [this](https://gist.github.com/lyoshenka/002b7fbd801d0fd21f2f) tutorial

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
