### ISSUE TITLE
hi, ask one question for connections, thank you!

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#501]
hi, 
   i can not know how many connections user will connect to my app server, i may serve 3000 users on concurrent connection.
   in this situlation, how should i do to pay? or if you have some idea for this? 

   best regards,
                    owey

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
