### ISSUE TITLE
regist && login error in china

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#502]
what's "failed to solve captcha"?

![dl](https://user-images.githubusercontent.com/32464691/41242539-69d94be2-6dd2-11e8-8960-c6b3580da0a7.jpg)

**Comment by thomasliuh** [comment]
You need a proxy server as the capcha service is usually provided by google.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
