### ISSUE TITLE
Provide an easier way to get generated url on another device

### ISSUE THREAD

**Issue by dpix** [inconshreveable/ngrok#506]
This is just a random feature request, not sure where else to put this.

Would be cool if when you generate the links, you also print out a QR code in the terminal with a link. Then you can just scan the QR code on a phone for example. Would make it heaps easier than typing in a randomised url.

Cheers, Dan

**Comment by hrumhurum** [comment]
Funny like this fairly frequently desired feature gets ignored for years.

I understand that such a convenience clearly goes against paid/pro plans.

A possible solution: include it in a paid plan and it will boost the sales.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Continued in https://github.com/ngrok/ngrok/issues/6
