### ISSUE TITLE
[SOLVED] ngrok http <port> crashes on linux manjaro (arch)

### ISSUE THREAD

**Issue by christophermlne** [inconshreveable/ngrok#507]
Linux Manjaro

Tried with the latest binary download from the website as well as two different versions that are available in the arch package manager (versions 2.2.8-2 and 2.2.9-1)

I would paste some log output but there isn't any and a quick search of the docs doesn't reveal a location for a log. Not really much to go on here other than to note it just doesn't work. Does ngrok have any dependencies?

**Comment by MrKickkiller** [comment]
Just found out that appending `--log=stdout` can get you log information.
Most likely is your `authtoken` invalid
