### ISSUE TITLE
Special characters

### ISSUE THREAD

**Issue by DasJott** [inconshreveable/ngrok#508]
What are all those special characters in ngrok for?
![image](https://user-images.githubusercontent.com/6298761/42678617-b6d91862-867f-11e8-9d63-c6d8083c650c.png)

Any special meaning?Using Arch lInux with Deepin DE in Deepin Terminal

**Comment by till-h** [comment]
Same here, on Arch Linux/Terminator.

**Comment by nmstoker** [comment]
BTW: as the **README.md** says, this repo is for ngrok **v1** and the issue with the characters in the screenshot above seems to be from **v2**, so it's quite likely there won't be a response here.

I observed the issue with v2 in Konsole in KDE on Arch Linux back in June.

I was in touch with Alan Shreve (founder of ngrok.com) about it and he confirmed then that had received a few reports of it. He did have plans in the pipeline to make it better but in the meantime suggested using xterm (which apparently doesn't exhibit the problem).

**Comment by rocketraman** [comment]
Running it with TERM=xterm seems to solve the immediate problem... e.g.

```
TERM=xterm ngrok ...
```

The usual value of my TERM variable is `xterm-256color`.

**Comment by rocketraman** [comment]
And it looks like the 2.3.15 release fixed it! I no longer need to override `TERM`.
