### ISSUE TITLE
Help Cant get past error!

### ISSUE THREAD

**Issue by ochrom** [inconshreveable/ngrok#509]
I went as far as purchasing a cloud server on 1&1, i want to start making shopify apps, so im at the ngrok point and I get this error, 

```
The connection to http://06f6fd60.ngrok.io was successfully tunneled 
to your ngrok client, but the client failed to establish a connection to 
the local address localhost:64135.

Make sure that a web service is running on localhost:64135 and that 
it is a valid address.

The error encountered was: dial tcp [::1]:64135: connectex: No connection 
could be made because the target machine actively refused it.
```

Doing tons of research I figured I needed to create a web server of some sort and use that port, still having bout this cloud server I dont see an option to change the port to the one I need, Im heavily confused D: any help is appreciated!

**Comment by ochrom** [comment]
crazy enough.. I figured I had to activate localhost within windows, under activate features.. ughh xD someone needs to make a way more detailed tutorial on this.

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
