### ISSUE TITLE
502 bad gateway error 

### ISSUE THREAD

**Issue by NikhilKanamarla** [inconshreveable/ngrok#510]
I am using a flask-ask Alexa tutorial and I am having issues with ngrok: https://github.com/3SpheresRoboticsProject/flask_ask_ros/issues/3

Screenshoot: https://photos.google.com/share/AF1QipPTaBHD3a17vV-ByQ4ch6OYpr50gTVcelb2yniizfJ-rj1ysrNpRqJ9s3_vgE6jxQ?key=dWxHamFjQ2FEaUJvc1Q4VjBjZHRpbDRObm15RGdn

**Comment by yosoyuva** [comment]
same issue here !

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
