### ISSUE TITLE
Image in front-end won't appear when using ngrok

### ISSUE THREAD

**Issue by Davidcamsan** [inconshreveable/ngrok#511]
I currently have an html file that includes an image (which is in the same folder as the file). When I right-click and open it in a brower, the image shows, but this is not the case when I use ./ngrok http. With ngrok, it shows the broken image icon instead. Why is this and how can I fix this so that the image shows when using ngrok as well?

**Comment by ecedenyo** [comment]
a newbie here, how does this ngrok exposing the local server work? all the media is linked to localhost, on my local server everything works fine, but once viewing by ngrok, all the media is broken, is this how it is supposed to work?

**Comment by rodrigogs** [comment]
Same with me, I'm trying to serve a Vue page.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
