### ISSUE TITLE
App won't show data

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#512]
Using ngrok v2.2.8 (free) to allow connection to a localhost app created when using Visual Studio 2015 Community Edition on a C# website using Telerik Kendo UI.

Used the command ngrok http 3470 -host-header=”localhost:3470” and was able to connect the tunnel.

Entered the Forwarding URL provided by ngrok and am able to run the application on my Samsun Galaxy Tab S3 with Android 8.0.0 and Chrome 68.0.3440.70.

All HTTP requests showing in the ngrok console have a 200 status code

I’m able to log into the application and navigate menus but data will not display.  Selecting any menu item shown should show a table grid.  See attached screen shot
![ngrok](https://user-images.githubusercontent.com/16087785/43482882-fdddd002-94d7-11e8-858f-331d87c9dc16.PNG)

Any ideas on what the issue would be?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
