### ISSUE TITLE
Possible to use https?

### ISSUE THREAD

**Issue by heihachi88** [inconshreveable/ngrok#516]
Currently, without https i'm launching the tunnel this way:

`ngrok http -host-header=rewrite home.test:80`

i get the following output in a console:

```
Forwarding                    http://ffe009ae.ngrok.io -> home.test:80
Forwarding                    https://ffe009ae.ngrok.io -> home.test:80
```

Can i change port on the https tunnel? so, if share https version of the tunnel, then it would resolve to my local app with ssl on.

**Comment by Lee182** [comment]
I'm having the same problem, would be nice to tunnel https://localhost:3443 or something

**Comment by heihachi88** [comment]
I just figured out that when you're using https version of tunnel - you don't need SSL on localhost at all, because it adds ngrok's SSL, so you can test your site with https.

**Comment by lalo312** [comment]
You saved my day
Lalo
tridejur
Director

**Comment by lalo312** [comment]
Hello I had a certificate forever on the web start your search at cómodo or if you wanna share that would be cool to

**Comment by lalo312** [comment]
I am gonna deactivate https on nginx

**Comment by lalo312** [comment]
Or try with my certificate as well
