### ISSUE TITLE
Reconnecting (EOF)

### ISSUE THREAD

**Issue by robparsonss** [inconshreveable/ngrok#518]
Keep getting "Reconnecting (EOF)" after a few seconds of it saying connecting. Not sure how to fix this. Can anyone help?

**Comment by S-Mann** [comment]
I get "Reconnecting (EOF)" then get a message saying "reconnecting (dial tcp [*some mac address*]:443: i/o timeout)". Everything was working fine for the past 10 days. I deleted the .ngrok folder than holds the auth token in a .yml still no fix.

**Comment by S-Mann** [comment]
I found the solution, basically for me there was an ad malware that was occupying the port ngrok usually uses. Please check and see what all services you have running on different ports.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
