### ISSUE TITLE
Stuck on Reconnecting #Client Error 1.7

### ISSUE THREAD

**Issue by GluGluGlu** [inconshreveable/ngrok#521]
i compiled ngrok client for Windows and Linux, but the client always show Reconnecting, 
![image](https://user-images.githubusercontent.com/17177437/44581601-8c10a900-a7c8-11e8-8727-99b924ec0b22.png) and no response in ngrokd server

Here's my client config
![image](https://user-images.githubusercontent.com/17177437/44581639-b5313980-a7c8-11e8-94de-2c666ebab3d5.png)

and when i test it using https://www.yougetsignal.com/tools/open-ports/ the port is open, and ngrokd also gave a response
![test port](https://user-images.githubusercontent.com/17177437/44581670-e14cba80-a7c8-11e8-8196-7b9db75c6144.PNG)

Please help...

**Comment by onlyGuo** [comment]
The problem been solved?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
