### ISSUE TITLE
Tunnel to IIS express fails to connect

### ISSUE THREAD

**Issue by seannybgoode** [inconshreveable/ngrok#522]
So I'm having the issues described here:

https://stackoverflow.com/questions/52192673/ngrok-with-visual-studio-2017-and-iis-express-fails-to-connect

I'm hoping someone here can point me in the right direction.

- I've tried using straight TLS, but I'm getting a 4xx hostname error

- Using the recommended configuration gives me a long load time and eventual 502 failure. Note here that the ngrok client sees the GET \ requests but does not record the 502 failure

- Attempted to switch the port to 8080, which gave me an instant 502 failure, which the ngrok client DID record

- Tried overwriting the hostname in ngrok, and changing the hostname in iis express settings, and got the same results (502 errors)

- Tried doing a tls-bind=true in ngrok, but no dice

Using windows 10 and VS 2017 community, w/ IIS Express

**Comment by gplwhite** [comment]
I'm having the same issue. 

If the IIS Express site exposes an HTTP endpoint, then the ngrok tunnel works fine, but if the tunnel is pointing to an HTTPS endpoint, then the connection (eventually) dies with the 502 error.

Incidently, I just forked out for the Pro plan thinking the TLS option was what's required, but it's not. I now realise that's for sending non HTTP traffic over a TLS channel :(

**Comment by Frontear** [comment]
For one, stop using `ngrok http 8080`. Run it on port 80 instead. `ngrok http 80`. Then report back

**Comment by jitterbox** [comment]
I continue to experience this issue as well. I would add that I also tried Kestrel in addition to IIS Express from within VS 2017 Enterprise, and I still get 502 errors in both cases even though ngrok **is** registering the requests. Based on that I assume it's an issue between ngrok and Windows networking rather than a problem with a specific web server.  HTTPS is required in my scenario as well, but I don't want to try the pro version if everyone is reporting additional issues with TLS.

**Comment by seannybgoode** [comment]
@jitterbox - Did you have any luck using Ngrok on port 80? I ended up assuming IIS express was sandboxed in some way, and installed IIS, which solved my issue. Would be interested to know if it works with IIS express on port 80. 

I'm pretty sure I tried port 80 first time around, but started getting fancy when the basic stuff didn't work.

**Comment by BitWizJason** [comment]
This should be resolved with the latest version see issue #448

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
