### ISSUE TITLE
Unable to get ngrok connection

### ISSUE THREAD

**Issue by sabyasachimustafi** [inconshreveable/ngrok#523]
I am using basic command in ngrok

ngrok.exe http 80

The server instance is running properly in http://localhost:4040/inspect/http

but whenever I am trying to connect it from xxx.ngrok.io it is showing following error message.

"the client failed to establish a connection to the local address localhost:80.
Make sure that a web service is running on localhost:80 and that it is a valid address.
The error encountered was: dial tcp [::1]:80: connectex: No connection could be made because the target machine actively refused it."

I have opened the inbound and outbound connection in port 80, even tried by disabling the firewall but it is making same issue. even with different ports also. Please help

**Comment by Khungersumit** [comment]
I am getting the same issue,

**Comment by peter-palmer** [comment]
Hello this is because you have not started you development server on your lcoal machine. Please initialise it with nodejs, react... on port 80.
You have to create your own development server localy.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
