### ISSUE TITLE
Fonts cant be loaded CORS

### ISSUE THREAD

**Issue by BonBonSlick** [inconshreveable/ngrok#525]
Page is loaded with everything except fonts

`Access to Font at 'https://test.vagrant/build/fonts/Raleway-Bold.woff' from origin 'http://ff4f8647.ngrok.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://ff4f8647.ngrok.io' is therefore not allowed access.`

**Comment by avishayp** [comment]
You are trying to access https resource from http. The protocol is part of the `origin` definition, and this is a CORS violation. The natural mitigation is either use protocol agnostic uris s.a `//test.vagrant/build/fonts/Raleway-Bold.woff`, or do everything over https (and use the https ngrok tunnel).

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
