### ISSUE TITLE
[bug] cli not loading font

### ISSUE THREAD

**Issue by oknozor** [inconshreveable/ngrok#526]
I've installed ngrok via [https://ngrok.com/download](https://ngrok.com/download)

it works fine but the cli is not rendering some info : 
![](https://framapic.org/f0ODMCwJMZSO/lKhw1cIePIK3)

Any idea how to fix this ? It's not very practical for debug.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
