### ISSUE TITLE
Start ngrok in subfolder only

### ISSUE THREAD

**Issue by jahirfiquitiva** [inconshreveable/ngrok#528]
Hello

I have a local website like `localhost/website` and I would like ngrok to only allow access to `website` and/or access it directly, instead of `localhost`
This, so when I access `*.ngrok.io`, it goes directly to `localhost/website`.

I can't seem to find the way to achieve this, so I am opening this issue, hoping you can help me or guide me to solve it.

Thanks in advance!

**Comment by avishayp** [comment]
I don't think that's a functionality `ngrok` should handle. Why don't you serve the subfolder on a different port and bind a tunnel to that?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
