### ISSUE TITLE
Ngrok successfully connect but fails to display the page 

### ISSUE THREAD

**Issue by peterwkc85** [inconshreveable/ngrok#534]
Dear All, 
I have configured properly using yml file but encounter error of establish connection from outside world to my web server. Please help to solve it. 

Config: 
authtoken: 7R1bFNoXikXmtVj31WENx_4jPeHTKoLLRDSirCRfEks

region: ap
console_ui: true
http_proxy: true
http_proxy: "http://kwong@who.int:Wlx40461@10.64.150.9:8080"
update: false
update_channel: stable
log_level: info
log: "C:\\custom_program\\ngrok\\log.txt"

Screenshot: 
![ngrok error](https://user-images.githubusercontent.com/44965697/48340980-df4b1700-e6a6-11e8-8da5-603b3b196567.png)

**Comment by yosoyuva** [comment]
same !
