### ISSUE TITLE
The repo (and website/service online, with paid plans) is maintained?

### ISSUE THREAD

**Issue by pedrofurtado** [inconshreveable/ngrok#536]
@inconshreveable 

The latest commit was in 2016 😞

**Comment by th0mk** [comment]
The repo is no longer used or updated, ngrok.io is now closed source. Some people still use this repo for issues tho.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
