### ISSUE TITLE
Ngrok silent run process 

### ISSUE THREAD

**Issue by karencho777** [inconshreveable/ngrok#538]
Hello, how can i run ngrok silently in windows machine? i have tried :
@echo off
start ngrok.exe http 82

but still the window pops up with the url address and etc...

i even tried this to 

Set WshShell = CreateObject("WScript.Shell" ) 
WshShell.Run chr(34) & "C:\web\runng.bat" & Chr(34), 0 
Set WshShell = Nothing

still the same, can some one help?

**Comment by karencho777** [comment]
no one can help?

**Comment by theevilhead** [comment]
Hey @karencho777 
Take a look at this
https://github.com/inconshreveable/ngrok/issues/57
and this
https://stackoverflow.com/questions/27162552/ngrok-running-in-background

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
