### ISSUE TITLE
unknown symbols

### ISSUE THREAD

**Issue by osgfarrukh** [inconshreveable/ngrok#539]
![image](https://user-images.githubusercontent.com/28592605/49271444-78dc3c00-f48f-11e8-8a0e-82d6cff5afb9.png)

**Comment by cknv** [comment]
Nice to see I am not the only one affected. Running a still very fresh Arch Linux here with Gnome on top - so I'm seeing similar output while in `gnome-terminal`.
It _seems_ unrelated to unicode, as running other CLI tools that output fancy unicode (emojis) works fine.

I am not entirely sure what could cause the problem, but I'd be happy to provide more information if anyone has any clues on how to troubleshoot.

**Comment by francescarpi** [comment]
Hi! I've the same problem in my sakura terminal. Over arch linux, as well. 

This is my locale:

```
LANG=es_ES.UTF-8
LC_CTYPE=es_ES.UTF-8
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE=es_ES.UTF-8
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
```
![image](https://user-images.githubusercontent.com/287872/51118158-f970b500-180f-11e9-968c-bdfe98d6354b.png)

Inside tmux, it works fine.

Let me know if you need more details. 

Thank you so much.

**Comment by dogweather** [comment]
Ditto, with Tilix on Fedora. Also, Terminal.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
