### ISSUE TITLE
Clients disconnect after exactly 10 minutes

### ISSUE THREAD

**Issue by iltew** [inconshreveable/ngrok#540]
I am using ngrok for an icecast stream run on localhost, but listening through the tunnel causes a client disconnect from the server exactly 10 minutes after connecting. The stream stays up, but requires a refresh or pause/play on the page to start playing again.

**Comment by theevilhead** [comment]
Hey maybe this could be of any help.
The `controlWriteTiming` and all the default timings https://github.com/inconshreveable/ngrok/blob/master/src/ngrok/server/control.go

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
