### ISSUE TITLE
Can I access the inspector :4040 remotely?

### ISSUE THREAD

**Issue by bakrianoo** [inconshreveable/ngrok#541]
Hi 

Is there any option to allow access the inspector on 4040 port remotely?
I allowed the port via the firewall for public access but it seems that I still can access it only via localhost.
I need to use my host IP address to access the Inspector tool (e.g. MY_IP:4040)

Thanks

**Comment by gklasen** [comment]
@bakrianoo could you resolve?

**Comment by KeeganEad** [comment]
I am also wondering how I might access the ngrok request inspector when ngrok is running on a remote server?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Thank you for your issue. We now have a cloud version of our [traffic inspector tool](https://dashboard.ngrok.com/observability/traffic-inspector) which you can access from anywhere.
