### ISSUE TITLE
Need infos/help about seflhosting

### ISSUE THREAD

**Issue by ArchangerOne** [inconshreveable/ngrok#543]
Hello, i've searched on entire repo and no way to find an explication about using bought wildcard cert as mentionned here https://github.com/inconshreveable/ngrok/blob/master/docs/SELFHOSTING.md in first point.

Actually, i have a wildcard cert for my-domain.com ( got 2 files, fullchain.pem and privkey.pem). How to use them to compile own ngrok server/client ?

Regards.

**Comment by mryalamanchi** [comment]
@ArchangerOne there is dev guide, check it out [here](https://github.com/inconshreveable/ngrok/blob/master/docs/DEVELOPMENT.md) and also a tutorial [here](https://www.svenbit.com/2014/09/run-ngrok-on-your-own-server/). These 2 docs will be helpful. Basically you need put the cert files inside the assets directory of the source ngrok and then compile it.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
