### ISSUE TITLE
Failed to read message: EOF ,fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by 66xc1** [inconshreveable/ngrok#545]

**Comment by cdown** [comment]
2329291534720323663 is `OPTIONS ` interpreted as a little-endian 8-byte integer, so you're probably using the wrong protocol. See https://chrisdown.name/2020/01/13/1195725856-and-friends-the-origins-of-mysterious-numbers.html.

In general, probably there should be some upper cap on message length to prevent rogue messages resulting in the application running out of memory.

**Comment by sunhuwh** [comment]
> 2329291534720323663被`OPTIONS `解释为低位字节8字节整数，因此您可能使用了错误的协议。参见https://chrisdown.name/2020/01/13/1195725856-and-friends-the-origins-of-mysterious-numbers.html。
> 
> 通常，可能应该在消息长度上设置一些上限，以防止流氓消息导致应用程序内存不足。



> 2329291534720323663 is `OPTIONS ` interpreted as a little-endian 8-byte integer, so you're probably using the wrong protocol. See https://chrisdown.name/2020/01/13/1195725856-and-friends-the-origins-of-mysterious-numbers.html.
> 
> In general, probably there should be some upper cap on message length to prevent rogue messages resulting in the application running out of memory.

how config message length?

**Comment by PwccaCode** [comment]
> 2329291534720323663 is `OPTIONS ` interpreted as a little-endian 8-byte integer, so you're probably using the wrong protocol. See [chrisdown.name/2020/01/13/1195725856-and-friends-the-origins-of-mysterious-numbers.html](https://chrisdown.name/2020/01/13/1195725856-and-friends-the-origins-of-mysterious-numbers.html).
> 
> In general, probably there should be some upper cap on message length to prevent rogue messages resulting in the application running out of memory.

How can i send requests like this myself so i can test if the fix i applied is working?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
