### ISSUE TITLE
A strange connection when start the client

### ISSUE THREAD

**Issue by longshengwang** [inconshreveable/ngrok#546]
After restart the ngrok client, I always find a strange remote connection(52.44.92.122/35.173.3.255...).
The ip changes after restart ngrok client. And the strange connect will disappear after a few minutes.

```
root@WLS-HOST:~# netstat -apn|grep  ngrok
tcp        0      0 127.0.0.1:4040          0.0.0.0:*               LISTEN      18096/ngrok
tcp        0      0 192.168.122.45:50606    52.44.92.122:443        ESTABLISHED 18096/ngrok
tcp        0      0 192.168.122.45:57336    (my ip):4443               ESTABLISHED 18096/ngrok
tcp        0      0 192.168.122.45:57340    (my ip):4443               ESTABLISHED 18096/ngrok
root@WLS-HOST:~# systemctl stop ngrok
root@WLS-HOST:~# systemctl start ngrok
root@WLS-HOST:~# netstat -apn|grep  ngrok
tcp        0      0 127.0.0.1:4040          0.0.0.0:*               LISTEN      18133/ngrok
tcp        0      0 192.168.122.45:58036     (my ip):4443      ESTABLISHED 18133/ngrok
tcp        0      0 192.168.122.45:58034     (my ip):4443      ESTABLISHED 18133/ngrok
tcp        0      0 192.168.122.45:35868    35.173.3.255:443        ESTABLISHED 18133/ngrok
```

**Who can tell me the reason?**

**Comment by longshengwang** [comment]
I find ngrok client will auto connect amazon ec compute.

### tcpdump package
```
 10:14:28.527888 IP 192.168.122.45.50520 > ec2-34-199-255-1.compute-1.amazonaws.com.https: Flags [S], seq 257121005, win 29200, options [mss 1460,sackOK,TS val 4294937739 ecr 0,nop,wscale 7], length 0
```

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
