### ISSUE TITLE
ngrok ssh connection closed by remote host

### ISSUE THREAD

**Issue by Conansoloman** [inconshreveable/ngrok#547]
I got a ubuntu MATE on raspberry pi 3 model B. I ran the ./ngrok tcp 22 and got
![image](https://user-images.githubusercontent.com/11034980/50552281-be8e4f00-0c5d-11e9-80c8-5c86c877677c.png)

But when I tried ssh username@0.tcp.ngrok.io -p 19532 on my Mac, it gives me an error:
ssh_exchange_identification: Connection closed by remote host.

Could you help on this? Thank you.

**Comment by ShadowDAssange** [comment]
I have same error.
If i change my network.,it will come out same error.
Then i change back,it will ssh successfully.

**Comment by SmittoStuff** [comment]
Running into the same error, trying to SSH into a raspberry pi.

**Comment by Conansoloman** [comment]
I forgot to start the ssh on Ubuntu. "sudo /etc/init.d/ssh start" solved my issue.

**Comment by SmittoStuff** [comment]
My issue came down to changing the default SSH configurations for the Raspbian OS, once that was updating ngrok worked successfully.

**Comment by adrianog** [comment]
@SmittoStuff - can you share the change? thanks!

**Comment by SmittoStuff** [comment]
@adrianog sure thing

In Raspbian, going to Preferences > Raspberry Pi Configuration > Interfaces will open a menu where different interfaces can be enabled. SSH is set to disabled by default - after this was enabled I was able to SSH in.

**Comment by gouyez** [comment]
> I forgot to start the ssh on Ubuntu. "sudo /etc/init.d/ssh start" solved my issue.

I forgot to start ssh on CentOs too. "service sshd start"

Thanks bro .

**Comment by abrahamperz** [comment]
If is the first time you need change to
1. add keygen $ssh-keygen -A
2. Edit $nano /etc/ssh/sshd_config 
3. Change PasswordAuthentication and ChallengeResponseAuthentication to yes.
4. Restart $ssh /etc/init.d/ssh restart.
5. Start $/etc/init.d/ssh start
6. Enjoy $ssh username@0.tcp.ngrok.io -p <port>
