### ISSUE TITLE
Possible error with Ngrok: failed MSpanList_Insert

### ISSUE THREAD

**Issue by gfcf14** [inconshreveable/ngrok#549]
Hi. I'm writing this problem here as I was suggested the problem I've been having may have to do with Ngrok.

I am attempting to complete the Confluence Multi-page Blueprint tutorial (https://developer.atlassian.com/cloud/confluence/multi-page-blueprints-with-confluence-connect/) and as I completed all the steps up to **Host and install your app** I attempted to run the project with `npm start`, I got the following error:

![66af88c0ae66ec5c5f94aeef0f204f9bf35ecb9e_1_690x367](https://user-images.githubusercontent.com/716412/52062803-31ca0000-253f-11e9-9c21-b418f305e9b9.jpeg)

The error **Failed MSpanList_Insert** seems to originate from `node_modules/ngrok/index.js:100:13`. I had posted my question [here](https://community.developer.atlassian.com/t/failed-to-establish-local-tunnel-on-multi-page-blueprints-with-confluence-connect/26693) and I was suggested that either I don't have ngrok installed, but that doesn't seem to be the case, or that I have a network restriction, but I am doing this tutorial on a mac for which I have admin rights. Is it possible that I am not following a step to use ngrok correctly? Please let me know, and thanks in advance.

**Comment by gfcf14** [comment]
I'll close this since the answer is pretty much described [here](https://community.developer.atlassian.com/t/failed-to-establish-local-tunnel-on-multi-page-blueprints-with-confluence-connect/26693). I can't post it here for copyright, but the trick would be (at least until webhooks are fully re-enabled) to play around with which [webhooks](https://developer.atlassian.com/cloud/confluence/modules/webhook/) to use, as some still work (such as the add-on System events)

**Comment by knagode** [comment]
I remove ngrok (search for executable first: `which ngrok`) and then reinstalled and it started working
