### ISSUE TITLE
Web Failed: Listen TCP 127.0.0.1:4040

### ISSUE THREAD

**Issue by zwilkin** [inconshreveable/ngrok#550]
When attempting to start a new ngrok tunnel, I am getting the following error...

`web failed: listen tcp 127.0.0.1:4040: bind: An attempt was made to access a socket in a way forbidden by its access permissions.`

I have no clue what's happening, I was using it fine on Friday and the first thing today (Monday) it is not working. The ONLY thing I did over the weekend was shut my computer down.

![image](https://user-images.githubusercontent.com/9438425/52212676-17ec2e00-285b-11e9-987c-37ad002c0031.png)

**Comment by ichivers** [comment]
I had this happen today, rebooted and it worked ok.

**Comment by zwilkin** [comment]
> I had this happen today, rebooted and it worked ok.

Coming back to this for to post an answer, and as @ichivers stated, a full reboot fixed the problem for me as well.

**Comment by OlaDates** [comment]
It probably means there are multiple sessions of ngrok running. On Windows open task manager, go to processes and find ngrok.exe and end task.

**Comment by Puvipavan** [comment]
`net stop hns && net start hns`

**Comment by Saadkhan041** [comment]
> > I had this happen today, rebooted and it worked ok.
> 
> Coming back to this for to post an answer, and as @ichivers stated, a full reboot fixed the problem for me as well.

Reboot what?

**Comment by BeastGamer81** [comment]
I rebooted my PC and it was fixed for me, in my case it was port 4049.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
