### ISSUE TITLE
Preventing ngrok command not found on both Mac and Windows

### ISSUE THREAD

**Issue by ishidas** [inconshreveable/ngrok#553]
Would you consider adding an instruction in the download instruction page to let users know to add path to their .bash_profile/.bashrc or windows variables for ngrok in order for them to use ngrok command? I know there is a note saying "Most people like to keep ngrok in their primary user folder or set an alias for easy command-line access.", but that makes it sound optional, but it's not. I've noticed that after following the instruction on ngrok download page both on Mac and on Windows, I was not able to use ngrok command unless I added the path. Documentation make it sounds like I didn't have to do so.  I appreciate your consideration!

**Comment by Mr-Doge** [comment]
I mean, you can search for it on google (10 seconds) and little edit -

> add path to their .bash_profile/.bashrc 

You can either do that, or easily `mv ./ngrok /bin/` so it is available anywhere (apt, apt-get etc. are in the same folder). (Also, do it in the folder where "./ngrok" is.

**Comment by jusce17** [comment]
Yes you could just add the following on the website:

After downloading and unziping the file, open The terminal in the current location (inside unzip folder) 
Execute the following command into the terminal : 

`sudo cp ngrok /usr/local/bin `        
 
Your ngrok execuatable file will be  copied to the /usr/local/bin directory. Now you should be able to run the **ngrok** command in the terminal

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
