### ISSUE TITLE
Remote port for TCP services not working?

### ISSUE THREAD

**Issue by Mr-Doge** [inconshreveable/ngrok#554]
Hey guys, I looked at the new `remote_port: 55522` config option, and I'd need that! When you do `./ngrok tcp 5522` it does/outputs **Forwarding tcp://0.tcp.ngrok.com:XXXXX to 127.0.0.1:5522** where you should be able to change the XXXXX using the remote_port! My config is `tunnels:
  demo:
    remote_port: 35864
    proto: tcp
    addr: 5522`

Now, it ignores the remote port and assigns its random one! Do I need a paid plan to make this work or what? Any help appreciated. Thanks in advance!

**Comment by black-byte** [comment]
Any info on that issue ?

**Comment by Mr-Doge** [comment]
How do I manage to get a reserved TCP address? Still kinda floating in this, I'd appreciate if you expanded your solution a bit more.

**Comment by black-byte** [comment]
Well that's quite simple. 
You have to go to dashboard.ngrok.com (sign in)
On the sidebar there is action 'Reserved' click on it. 
It should load a page which will contain reserved tcp addresses (look screen below)

![image](https://user-images.githubusercontent.com/9597824/71087206-ec84e000-219b-11ea-80ed-3f959f18f0fd.png)

**Comment by Mr-Doge** [comment]
Ah, so I need to buy a reserved address. Thanks for finding it out.
