### ISSUE TITLE
Ngrok TCP Port 21

### ISSUE THREAD

**Issue by aduhaiya** [inconshreveable/ngrok#556]
Hi Ngrok...

I have a problem on tunneling to tcp port 21 which will forward to my localhost ftp. I'm creating ftp by using IIS. When I'm asking ngrok to perform tunneling to my ftp server, i need to key in User Name and Password. I try to key in what i have setup which is by referring to Windows Authentication and IIS Authentication. Unfortunately, it fails. 

Any idea how to solve this. How to know the Username and Password to key in to get access for this?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
This question seems more related to your ftp server configuration, but instructions for using ngrok with sftp can be found here: https://ngrok.com/docs/using-ngrok-with/ftp/
