### ISSUE TITLE
Blocked ip

### ISSUE THREAD

**Issue by Simoron** [inconshreveable/ngrok#557]
Hi, i think your ip blocked for Russian Federation (eu zone, us zone) 
I checked it with https://blocklist.rkn.gov.ru/#anchor 
Check it pls
Im try zone ap - it worked.

P.S.: rkn.gov.ru it's not smart government service.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
