### ISSUE TITLE
Ngrok not passing response back to azure function from localhost when called multiple times

### ISSUE THREAD

**Issue by DigitalKahuna** [inconshreveable/ngrok#558]
Hi All,

This is a repost from the question I posted on stackoverflow

https://stackoverflow.com/questions/54583532/ngrok-not-passing-response-back-to-azure-function-from-localhost-when-called-mul

Wondering if anyone here can shed some light on this?

Thank you!

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
