### ISSUE TITLE
Unable to access the site

### ISSUE THREAD

**Issue by olegpolukhin** [inconshreveable/ngrok#560]
Hey. Please could you help me. When you start ngrok (./ngrok http 80 OR ./ngrok http 9674), redirection to the address does not work, an error in the browser: "Unable to access the site" - ERR_CONNECTION_REFUSED

os linux 18.04

**Comment by mrduxs** [comment]
Check the DNS configuration of the client computer to see if you can access the server

**Comment by dimasch** [comment]
I see the same error for `3000` port.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
