### ISSUE TITLE
HELP ngrok

### ISSUE THREAD

**Issue by zonix325** [inconshreveable/ngrok#561]
![изображение](https://user-images.githubusercontent.com/34164180/54557453-3b62d680-49cc-11e9-944f-de34f01c6a71.png)
![изображение](https://user-images.githubusercontent.com/34164180/54557466-41f14e00-49cc-11e9-865e-075b05acb5eb.png)
![изображение](https://user-images.githubusercontent.com/34164180/54557472-4584d500-49cc-11e9-97f0-6d1c25acdeca.png)

I DONT KNOW WHAT ME NEED  MAKE

**Comment by mrduxs** [comment]
Check the client's DNS configuration to see if you can access the server

**Comment by zonix325** [comment]
@mrduxs 
How?

**Comment by ajhello** [comment]
Did you ever find a solution to this problem?

**Comment by caseysoftware** [comment]
Use `ngrok diagnose` to determine what is and isn't working with your configuration.

These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
