### ISSUE TITLE
Incorrect runtime timestamp

### ISSUE THREAD

**Issue by JSmythSSG** [inconshreveable/ngrok#562]
I checked the time on the server and its correct, running on Ubuntu 18 but it seems to show 49 years ago ?

[NGROK](https://i.imgur.com/7slTJVJ.jpg)

**Comment by PapaKoop** [comment]
I just upgraded to v2.3.18 and all my timestamps say 49 years ago also.

**Comment by JSmythSSG** [comment]
Just fixed in the latest update

**Comment by PapaKoop** [comment]
Works as it should. Thanks.
