### ISSUE TITLE
URL filtering

### ISSUE THREAD

**Issue by davidkarlsen** [inconshreveable/ngrok#563]
It would be great if ngrok could do url filtering:
- add a prefix
OR
- limit url requests to match a given prefix / regex

this way one could limit what parts of the URL spectrum of the exposed service which would be externally reachable.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
thank you for your issue. I believe ngrok can do this now with our traffic policy module and the url-rewrite action: https://ngrok.com/docs/http/traffic-policy/actions/url-rewrite/

You should also be able to limit url requests using the rate-limit action: https://ngrok.com/docs/http/traffic-policy/actions/rate-limit/
