### ISSUE TITLE
Replay with Modifications issue

### ISSUE THREAD

**Issue by maksymseleznov** [inconshreveable/ngrok#564]
Hi there! 

I sent json body but when I'm trying to modify request I'm getting HTML, is it a bug?
Version is 2.3.23                                                                                                                          
Attached screenshot

<img width="615" alt="Screen Shot 2019-03-22 at 10 51 41 AM" src="https://user-images.githubusercontent.com/11084415/54831651-21a5e580-4c91-11e9-95a4-348d721f2544.png">

**Comment by cblanck** [comment]
I have the same issue. It looks like instead of extracting the json for modification, it includes the entire HTML of the body including the stuff that's used for syntax highlighting. When you click replay, it then sends that HTML as the body, which will fail.

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack

**Comment by russorat** [comment]
Thanks for the issue. We have recently launched a cloud version of our [Traffic Inspector tool](https://dashboard.ngrok.com/observability/traffic-inspector) that includes replay with modifications.
