### ISSUE TITLE
ngrok 504 gateway timeout on long running request

### ISSUE THREAD

**Issue by mcafaro** [inconshreveable/ngrok#566]
I've noticed ngrok returns a 504 gateway timeout after about 7 minutes into a long running HTTP request. Is this a bug or a configuration setting I have control over?

**Comment by zhongyuankeji** [comment]
There is a problem with your settings

**Comment by Mohammed-Alama** [comment]
i have also this problem can any one help me

**Comment by adamc-be** [comment]
> There is a problem with your settings，You can send me an email to help you see it
> [duhouya@mail.zhongyuankeji.cn](mailto:duhouya@mail.zhongyuankeji.cn)
@zhongyuankeji Can you post the config setting here, so we can all see how to change this please?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
