### ISSUE TITLE
Failed to get home directory

### ISSUE THREAD

**Issue by ancientzords** [inconshreveable/ngrok#567]
When i try to author token, then this happen to me.

```
./ngrok authtoken 5EFGBrreZGH1SoBDnM8SW_3n8VrsBrTKP4tpNnYKdnU
WARN[03-30|14:36:02] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/arm" $HOME=/data/data/com.termux/files/home
Authtoken saved to configuration file: /data/data/com.termux/files/home/.ngrok2/ngrok.yml
```

**Comment by Jauza24** [comment]
./ngrok authtoken 5EFGBrreZGH1SoBDnM8SW_3n8VrsBrTKP4tpNnYKdnU
WARN[03-30|14:36:02] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/arm" $HOME=/data/data/com.termux/files/home
Authtoken saved to configuration file: /data/data/com.termux/files/home/.ngrok2/ngrok.yml
me too

**Comment by Jauza24** [comment]
yaa me too
./ngrok authtoken 5EFGBrreZGH1SoBDnM8SW_3n8VrsBrTKP4tpNnYKdnU
WARN[03-30|14:36:02] failed to get home directory, using $HOME instead err="user: Current not implemented on linux/arm" $HOME=/data/data/com.termux/files/home
Authtoken saved to configuration file: /data/data/com.termux/files/home/.ngrok2/ngrok.yml

**Comment by somenath1903** [comment]
ERROR:  Failed to save authtoken to configuration file '/root/.ngrok2/ngrok.yml': open /root/.ngrok2/ngrok.yml: invalid argument

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
