### ISSUE TITLE
Can ngrok run on ESXi 6.5?

### ISSUE THREAD

**Issue by thetreythomas** [inconshreveable/ngrok#569]
I'm wondering if you all have ever tried testing ngrok on ESXi?

I tried running the command **./ngrok help**, and get the below error:

```
panic: Only generated 0 random bytes, 8 requested

goroutine 1 [running]:
go.ngrok.com/lib/id.NewRand(0x82f5dfe)
        /home/vagrant/ngrok/go/lib/id/id.go:77 +0x204
go.ngrok.com/lib/id.init.0()
        /home/vagrant/ngrok/go/lib/id/id.go.17 +0x1a
```

I am using the latest `ngrok-stable-linux-386.zip`. I started with this version, as the application we work on is built using a RHEL6 32-bit build system. Was hoping this would just work.

Are there any OS requirements for this to work? I know I need to open a port in the ESXi Firewall, but I didn't think that would be a requirement to use `help`.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
