### ISSUE TITLE
Daemon / Silent Mode

### ISSUE THREAD

**Issue by patrickheeney** [inconshreveable/ngrok#57]
I am running ngrok in a vagrant box via puppet and it seems to error out when I start the service which I assume is because of the interface being returned. It would be great to run `ngrok --daemon 80` or `--silent` which would only return a 0 status if successful or the error. If such an option does already exist I didnt see it on the help pages or in the code anywhere.

**Comment by larsfk** [comment]
Someone know how to log -proto=tcp 22 ?

**Comment by AndySedano** [comment]
I was successful using a tunnel for ssh in the config file and running
```ngrok -log=stdout > /dev/null start ssh &```

my config file looks like this 

```
tunnels:
  ssh:
    remote_port: 50800
    proto:
      tcp: 22
```

**Comment by selfagency** [comment]
When I try `ngrok -log=stdout 80 > ~/ngrok.log &` with v2.0.19, the output I get is the instructions as though I entered an invalid parameter.

**Comment by dragondgold** [comment]
@selfagency same issue here, the -log is the problem, how to achieve the same thing with the new version?

**Comment by gnhuy91** [comment]
As of version 2.0.24, `ngrok http 80 --log=stdout > ngrok.log &` did the trick.

**Comment by IgorGanapolsky** [comment]
@gnhuy91 Doesn't this fill up the log file and cause waste of memory?  I mean, does log rotation need to be turned on??

**Comment by gnhuy91** [comment]
@IgorGanapolsky yea you should bring up your own solution, but anw above command no longer available.

**Comment by stas00** [comment]
This solution no longer works. `Incorrect Usage: flag provided but not defined: -log`

**Comment by GuillaumeDesforges** [comment]
The right command is now

```
ngrok http 80 --log=stdout > ngrok.log &
```

**Comment by zentyk** [comment]
it works! now... how can i stop it?

**Comment by MarvinXu** [comment]
> 

```bash
kill -9 "$(pgrep ngrok)"
```

**Comment by TheGithubJoshua** [comment]
This is stupid, the ngrok team should really have a --daemon flag, because i'm sshing into my Raspberry Pi to run ngrok, except when I shut the terminal, the agent stops, so now I have to have my laptop running when when I'm using my Raspberry Pi with OMV.
