### ISSUE TITLE
Encountered error read tcp & connection reset by peer.

### ISSUE THREAD

**Issue by SilumanKera** [inconshreveable/ngrok#571]
Hi @inconshreveable , I currenty run self hosted ngrok and encounter this issue :

[INFO] (ngrok/log.(*PrefixLogger).Info:83) [pub:46fa8dea] New connection from MYHOST:40634
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:46fa8dea] Found hostname NGROK:12345 in request
[INFO] (ngrok/log.(*PrefixLogger).Info:83) [http://NGROK:12345 Got proxy connection pxy:df2cc24
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pxy:df2cc24] [800f4e1917f2b16ed519950295bc790f] [http://NGROK:12345] Writing message: {"Type":"StartProxy","Payload":{"Url":"http://NGROK:12345","ClientAddr":"MYHOST:40634"}}
[INFO] (ngrok/log.(*PrefixLogger).Info:83) [pub:46fa8dea] Joined with connection pxy:df2cc24
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [ctl:ca7235e] [800f4e1917f2b16ed519950295bc790f] Writing message: {"Type":"ReqProxy","Payload":{}}
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pxy:df2cc24] [800f4e1917f2b16ed519950295bc790f] [http://NGROK:12345] Copied 470 bytes to pub:46fa8dea
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pxy:df2cc24] [800f4e1917f2b16ed519950295bc790f] [http://NGROK:12345] Closing
[WARN] (ngrok/log.(*PrefixLogger).Warn:87) [pub:46fa8dea] Copied 267 bytes to pxy:df2cc24 before failing with error read tcp REMOTE_SERVER_IP:12345->MYHOST:40634: use of closed network connection
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:46fa8dea] Closing
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:46fa8dea] Closing
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:46fa8dea] Closing
[DEBG] (ngrok/log.(*PrefixLogger).Debug:79) [pub:46fa8dea] Closing

Any workaround to fix it?
Thanks in advance.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
