### ISSUE TITLE
[EROR] (ngrok/log.Error:120) control recovering from failure dial tcp: address tcp/803": unknown port

### ISSUE THREAD

**Issue by Eric8069** [inconshreveable/ngrok#572]
hello, 
When I started the ngrok client, I reported the following error.
[11:10:16 CST 2019/04/26] [INFO] (ngrok/log.Info:112) Waiting 30 seconds before reconnecting
[11:10:46 CST 2019/04/26] [EROR] (ngrok/log.Error:120) control recovering from failure dial tcp: address tcp/803": unknown port

The server's ngrokd has been started, the monitoring is normal, and the client telnet server port is no problem.

help me，please！

**Comment by azridev** [comment]
Having similar problem.
Any luck?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
