### ISSUE TITLE
An attempt was made to access a socket in a way forbidden by its access permissions.

### ISSUE THREAD

**Issue by kxion** [inconshreveable/ngrok#575]
web failed: listen tcp 127.0.0.1:4040: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

**Comment by taseentanvir** [comment]
same error :")

**Comment by KaiDevrim** [comment]
Same

**Comment by parsalotfy** [comment]
same

**Comment by parsalotfy** [comment]
I just restarted this service : `Host Network Services` on windows , and it fixed my problem

**Comment by rrrokhtar** [comment]
**Restarting commands for windows**
net stop winnat
net start winnat

**Comment by seantleonard** [comment]
has anyone determined **why** restarting Host Network Service works?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by vahidrad** [comment]
> I just restarted this service : `Host Network Services` on windows , and it fixed my problem

Hi parsalotfy
worked for me
tnx
