### ISSUE TITLE
im also new to ngrok too, my issue is that my connection status refused to go online...

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#576]
im also new to ngrok too, my issue is that my connection status refused to go online...

its displaying something like.
 Session Status                reconnecting (dial tcp (my ip: my port:) getsockopt: connection refused)             
Version                       2.2.8                                                                                  
Region                        United States (us)                                                                     
Web Interface                 http://127.0.0.1:4040                                                                  
                                                                                                                     
Connections                   ttl     opn     rt1     rt5     p50     p90                                            
                              0       0       0.00    0.00    0.00    0.00

_Originally posted by @GiddyCode in https://github.com/inconshreveable/ngrok/issues/465#issuecomment-440552804_

**Comment by loveablefellow007** [comment]
Im facing same issue

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
