### ISSUE TITLE
SSH connection closes after inactivity

### ISSUE THREAD

**Issue by shoalmedia** [inconshreveable/ngrok#577]
I'm using putty to connect to my Ubuntu server via SSH (it's behind a firewall). It works fantastic in general, but if I leave it inactive for about 10 minutes Putty loses the connection.

Is this configurable? In general SSH connections in Putty to servers not using ngrok never time out.

**Comment by rijotech** [comment]
Can you post your config file?

**Comment by harish-hyperDev** [comment]
Shall we close this??

**Comment by bensulli** [comment]
This is my ticket under a different account - please go ahead and close (I'm not sure I still have the login for that account).

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
