### ISSUE TITLE
Ngrok is tunneling to the localhost instead of the vhost.

### ISSUE THREAD

**Issue by kiranbhattarai** [inconshreveable/ngrok#579]
Version                       2.3.29
Bug detected: Is tunneling only through the localhost
Explanation: I have a virtual host set up and while trying to tunnel through that virtual host it does not do that instead it will tunnel through the localhost by default.
How to re create the problem: I have attached a video on how to recreate it
video url: https://youtu.be/dN0Ej8wn56g

**Comment by ljmoleiro** [comment]
Hey I solve it with this

ngrok http -host-header=rewrite [vhost-name:port]

See the full answer here

https://stackoverflow.com/questions/31632534/targeting-dev-sites-with-vhost-setup-using-ngrok
