### ISSUE TITLE
Ngrok sometimes fails on startup if there is not enough entropy just after a system boot.

### ISSUE THREAD

**Issue by dkiestra** [inconshreveable/ngrok#58]
The reason it's failing sometimes on startup is because it's try to generate a secure random number to use as a seed value for the pRNG. This calls into the operating system and will fail if there isn't much entropy which is common right after system boot. Ideally it should just wait for more entropy instead of dying.

**Comment by inconshreveable** [comment]
don't think this was ever fixed and it still could be, leaving this open

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
