### ISSUE TITLE
ngrok reconnecting

### ISSUE THREAD

**Issue by ajhello** [inconshreveable/ngrok#583]
I ran the command ngrok http 9595 and I keep getting the error reconnecting (dial tcp 3.**.***.**:**: i/o timeout). Is this because I am doing this at work and the company has a firewall? Is there a workaround for this?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
