### ISSUE TITLE
ngrok reconnecting 

### ISSUE THREAD

**Issue by WissalAbbassi** [inconshreveable/ngrok#585]
![2019-06-22_11-07-46](https://user-images.githubusercontent.com/47229851/59962510-9bdf4380-94e6-11e9-9ab5-7aaa260d0bf8.png)

**Comment by makaan20** [comment]
hi

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
