### ISSUE TITLE
First record does not look like a TLS handshake

### ISSUE THREAD

**Issue by azaeng04** [inconshreveable/ngrok#587]
Hi guys

I am experiencing the following error when laugning ngrok with the following command:

./ngrok http 1337 -config=ngrok.yml

**reconnecting (tls: first record does not look like a TLS handshake)** 

I am running this on a Linux based OS.

Anyone know what could cause this?
Let me know if any more information is required.

**Comment by xfzhang1974** [comment]
I see the same issue running on Windows 10
>ngrok http 5005

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
