### ISSUE TITLE
"ngrok is not yet ready to start tunnels" 503 Error

### ISSUE THREAD

**Issue by tbell511** [inconshreveable/ngrok#588]
I've never seen this message before. It started appearing today and has repeatedly come up. 

```
{ error_code: 104,
  status_code: 503,
  msg: 'ngrok is not yet ready to start tunnels',
  details:
   { err:
      'a successful ngrok tunnel session has not yet been established' } 
}
```

**Comment by andreasonny83** [comment]
Same error here. No idea why

**Comment by andreasonny83** [comment]
I solved this by installing the latest version of ngrok in my dependencies
`"ngrok": "3.1.1" => "ngrok": "3.2.3"`

**Comment by tbell511** [comment]
Awesome thanks! That was the fix.

**Comment by brunosiqueira** [comment]
We updated our version to 3.2.3 also and still facing this same issue. Any leads on this?

**Comment by andreasonny83** [comment]
@brunosiqueira  Try removing the `package-lock.json` and `node_modules` folder, then run `npm install` again. If doesn't work, open a new issue
