### ISSUE TITLE
How to set password on server side with ngrokd

### ISSUE THREAD

**Issue by mikolaje** [inconshreveable/ngrok#589]
I have a server started with ngrokd. 
The question is everyone are able to connect my server through ngrok client if they know the host and port. 
I want to prevent my server from being used by other people. 
How can I achieve this? Thanks

**Comment by yeradis** [comment]
have you tried:

`ngrok http -auth="username:password" 8080`

replace `8080` with your port and of course `username` and `password` with the desired one

**Comment by mikolaje** [comment]
Not client, I mean setting an auth for ngrok server.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
