### ISSUE TITLE
Add support for throttling speed

### ISSUE THREAD

**Issue by stevejalim** [inconshreveable/ngrok#59]
It would be great to have a --speed switch, or similar, which throttles throughput, so that ngrok could be used to replicate slow connections.

(Currenlty I use Sloppy https://github.com/d6y/sloppy) but it'd be great to roll the behaviour into ngrok and do away with a separate Java app)

**Comment by inconshreveable** [comment]
won't fix

**Comment by tconroy** [comment]
@inconshreveable hey there. Stumbled across this issue via google so apologies if this is answered elsewhere, but did this feature ever make it in? I'd love to be able to control the throughput so I can emulate poor connection on mobile devices.

Thanks!
