### ISSUE TITLE
India region Ngrok urls treated as phishing sites

### ISSUE THREAD

**Issue by MugilanGN** [inconshreveable/ngrok#591]
When I was trying to test my build with Ngrok on Chrome, Google reported it as a phishing site. I removed all of the Javascript and HTML, and even with a single paragraph tag, Ngrok urls are still being flagged. After further testing, it seems this is only an issue with the India region. Is this a common issue, and if so, how can I fix this?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
