### ISSUE TITLE
cant connect to TCP in basic subscription ASAP 

### ISSUE THREAD

**Issue by IbrahimBond** [inconshreveable/ngrok#592]
hi,

i have bought a basic subscribtion and reserved an address, but i cant establish a tcp connection.  i am using this command:
./ngrok tcp --region=us --remote-addr=myaddress.ngrok.io:20301 22

but it is giving ERR_NGROK_307

what is wrong here? 

and is using port 20301 correct? if not what is the correct way to specify the port number? 

please respond ASAP this is very important

thanks

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
