### ISSUE TITLE
[Feature] Add times to HTTP Request logging

### ISSUE THREAD

**Issue by worthy7** [inconshreveable/ngrok#598]
![image](https://user-images.githubusercontent.com/4762399/65206125-10675580-dac9-11e9-93bc-7342bd419018.png)
Can you stick the times on the left column?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
continued in https://github.com/ngrok/ngrok/issues/8
