### ISSUE TITLE
The tcp end points are not same

### ISSUE THREAD

**Issue by rajeshkrarora1** [inconshreveable/ngrok#601]
Hi ,
every time i fire a tcp tunnel the tunnel address is different, though  i have a reserved tcp tunnel address which i start, pls give a solution

Thanks and regards

Rajesh kumar

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
