### ISSUE TITLE
ngrok wamp conflict

### ISSUE THREAD

**Issue by OzanKurt** [inconshreveable/ngrok#606]
I am using WAMP as my http server. After I installed ngrox I started getting this same error on all my vhosts.

```
dial tcp4: lookup example.local on 127.0.0.1:53: no such host
```

**Comment by caseysoftware** [comment]
Use `ngrok diagnose` to evaluate your configuration.

These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
