### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by diadya** [inconshreveable/ngrok#607]
you guys can help, it’s not connecting, I don’t know what the problem is
![Screenshot_2019-10-20-17-38-20-861_com termux](https://user-images.githubusercontent.com/53941328/67160295-6f3a1c00-f360-11e9-8c09-b15c22cb895e.jpg)

**Comment by koliasyniuha** [comment]
Got the same issue.

**Comment by hamed473** [comment]
have you tried to start apache server?

**Comment by NHibiki** [comment]
I think this GitHub repo only contains the version that is 1.7.x and was deprecated. It seems that you are using the 2.x version, which should be commercialized? In that case, have you tried to send a ticket to them?

**Comment by ItKinlu** [comment]
Got the same issue.

**Comment by caseysoftware** [comment]
These forums are unmonitored. For active support, check out our slack community: https://ngrok.com/slack
