### ISSUE TITLE
need check return value when read an closed socket 

### ISSUE THREAD

**Issue by fr0zenrain** [inconshreveable/ngrok#612]
Control::reader failed with error read tcp *:4443->*:55331: use of closed network connection: goroutine 57 [running]:
runtime/debug.Stack(0xc000043eb8, 0x7b0b20, 0xc00020a730)
	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
ngrok/server.(*Control).reader.func1(0xc0002346c0)
	/root/xxx/ngrok/src/ngrok/server/control.go:229 +0x57
panic(0x7b0b20, 0xc00020a730)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
ngrok/server.(*Control).reader(0xc0002346c0)
	/root/xxx/ngrok/src/ngrok/server/control.go:246 +0x1f8
created by ngrok/server.NewControl
	/root/xxx/ngrok/src/ngrok/server/control.go:124 +0x8a7

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
