### ISSUE TITLE
tunneling website on remote server redirecting to suspended page

### ISSUE THREAD

**Issue by GhostRB47** [inconshreveable/ngrok#614]
when I tunnel my website i get redirected to 

><subdomain>.ngrok.io/cgi-sys/defaultwebpage.cgi

and I really do not know what to do. the website seems fine viewing it from my own domain

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
