### ISSUE TITLE
Once my tunnel expires, how can I stop the terminal command from running and reuse the terminal?

### ISSUE THREAD

**Issue by cbdeveloper** [inconshreveable/ngrok#616]
Once my tunnels are expired, I can't find a way to stop the ngrok command on my terminals. I alway have to delete the terminal and open a new one (VSCode).

Is there a command that will do it?

I tried `Ctrl +C`, `q`, `Esc`... Nothing seems to work.

```
ngrok http 8080 -host-header=\"localhost:8080\"
```

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
