### ISSUE TITLE
tunnel not found over the wan

### ISSUE THREAD

**Issue by hamed473** [inconshreveable/ngrok#618]
hello
so i have an issue with ngrok , its working perfectly within the network (Lan) but as soon as i try to open the link from outside the network(wan) i keep getting this (tunnel *************** not found )

can someone help please :(

**Comment by j1zzlet** [comment]
I currently have the same issue :(

**Comment by hamed473** [comment]
> 
> 
> I currently have the same issue :(

i have been trying to solve it for like 3 months now
and i still didnt find any solution :(

**Comment by Libross** [comment]
see my post in problem #626, may be helpful

**Comment by hamed473** [comment]
i have solved the problem 
and in case someone was wondering how , it was really simple (delete everything and reinstall it again ) (virtualbox)

**Comment by hamed473** [comment]
i have solved the problem
and in case someone was wondering how , it was really simple (delete everything and reinstall it again ) (virtualbox)

**Comment by sitech-security** [comment]
it's can't do because it have lot of tools
