### ISSUE TITLE
ngrok needs a documented API for third party clients

### ISSUE THREAD

**Issue by juanfra684** [inconshreveable/ngrok#62]
Hi. I would like to create a tunnel on OpenBSD on some platforms unsupported by golang. I understand that you like golang but it doesn't run everywhere. A simple public and documented API would help a lot to users like me and probably would attract to devs of third party clients.

**Comment by inconshreveable** [comment]
won't fix

**Comment by inconshreveable** [comment]
actually, reopening. if someone wants to document the 1.x protocol, that would be totally great

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
