### ISSUE TITLE
Ngrok is not working 

### ISSUE THREAD

**Issue by Kavin2910** [inconshreveable/ngrok#620]
While connecting the ngrok is showing "Proxy Avoidance" issue.
Why ngrok site suddenly move to proxy avoidance category.we are highly depend on this.
Please send me the solution for this 
![ngrok](https://user-images.githubusercontent.com/57636454/68608003-eeda8700-04d7-11ea-9b95-ae67990b7afb.png)

attched the image for your reference

**Comment by hamed473** [comment]
i am not sure tbh , but the problem might be from the router setting

**Comment by Hulkhulkthehulk** [comment]
This is due to your firewall/web filter, not Ngrok. You need to speak with whoever internally controls FortiGuard

**Comment by bapji** [comment]
How to stop running  Tunnel please tell me
Someone is using my tunnel
Please help
