### ISSUE TITLE
Does ngrok work through vpn?

### ISSUE THREAD

**Issue by h0las-dev** [inconshreveable/ngrok#621]
I want to debug a simple bot for telegram on my local machine.

I use Telegram.Bot and web hooks on asp.net core 3.0. I am from Russia and Telegram is blocked in my country, so I need to use a VPN if I want to connect to the Telegram API via Telegram.Bot.

I started ngrok but ran into a problem. Telegram post requests do not arrive on my local machine. But the get requests that I do myself on ngrok come correctly.

I run ngrok with the command: `ngrok http 54823 -host-header="localhost:54823"`. 54823 - my default debug port in visual studio, not ssl.

I get an url: `https://5bf38bda.ngrok.io`

Then I make requests: `get: https://5bf38bda.ngrok.io/api/message/update` and it activates breakpoint, **works correctly**. Then I make a post from the Telegram client and nothing happens.
In ngrok web interface i see next picture: 
![2019-11-13_21-19-33](https://user-images.githubusercontent.com/51745793/68804739-7f999a00-0673-11ea-8ff3-dbb86c164181.png)
![2019-11-13_21-21-40](https://user-images.githubusercontent.com/51745793/68804747-83c5b780-0673-11ea-8400-d68cbda56c91.png)

X-Forwarded-For field is different for get(uses ip vpn) and post(uses unknown ip) requests. Could this be the problem? **Can I use ngrok with vpn this way?** Or will it only work without vpn?

**Comment by h0las-dev** [comment]
Sory, answer here: [https://ru.stackoverflow.com/questions/1045833/%d0%97%d0%b0%d0%bf%d1%83%d1%81%d0%ba-%d0%b1%d0%be%d1%82%d0%b0-%d0%bd%d0%b0-%d0%bb%d0%be%d0%ba%d0%b0%d0%bb%d1%8c%d0%bd%d0%be%d0%b9-%d0%bc%d0%b0%d1%88%d0%b8%d0%bd%d0%b5-%d1%87%d0%b5%d1%80%d0%b5%d0%b7-ngrok-%d0%b8-vpn](url)

**Comment by sherlockteen** [comment]
Russia power!
Good
