### ISSUE TITLE
Terminal Stuck / hung on [process completed]

### ISSUE THREAD

**Issue by gregg-cbs** [inconshreveable/ngrok#627]
On my Mac : Catalina.

When I open ngrok it runs the initial opening script and gets hung on:
`[Process completed]`

Making it unusable because there does not seem to be a way to escape this.

<img width="577" alt="Screenshot 2019-12-27 at 09 25 12" src="https://user-images.githubusercontent.com/57114335/71511663-09e83700-288b-11ea-999f-af90075576a3.png">

**Comment by xmutaborx** [comment]
The same. Has anyone found how to fix this?

**Comment by gregg-cbs** [comment]
I am still facing this issue. Any answers on this?

**Comment by mstennett** [comment]
I have the same issue as well...grrrrr

**Comment by xmutaborx** [comment]
solution:
open your terminal, go to the folder where the ngrok is located 
- cd ./Downloads

open ngrok with parameters through your terminal
./ngrok http 80

**Comment by timbright** [comment]
Thx, it solved
