### ISSUE TITLE
VNC not viewing on ngrok

### ISSUE THREAD

**Issue by DuckBergen** [inconshreveable/ngrok#629]
So i am using ngrok to host VNC but it works fine, but the issue is that VNC viewers won't see it, i'm using TightVNC for it.
`ngrok tcp 5969`
The error i get when i try to connect:

"Connection has been gracefully closed"

Oh and, im using QEMU's VNC support.

**Comment by Libross** [comment]
Hi, I found one interesting link about similar problem:
https://sourceforge.net/p/vnc-tight/bugs/1386/

The interesting part is that one person posted that he was using changeIP.com service and if he was accessing tightVNC server using hostname address (xxx.changeip.net) he got the "Connection has been gracefully closed" message, if he ping the subdomain address to resolve the IP and then used IP to connect instead, it was working for him.
(Btw if I am correct this message is replied by VNC server so actual connection through ngrok must have been redirected/established properly)

So try also to ping the hostname address generated for you (in example "ping 0.tcp.ngrok.io" - please note that your address may be different depending on your region) the ping will probably timeout (as ICMP is probably blocked by ngrok servers), but you will anyway see which IP address was resolved.
Then try to use this IP in your VNC Viewer client (with port generated for you) to access your machine.

**Comment by ErtasVideos** [comment]
Thanks, but the problem still persists, even with the IP i can't connect to it.

**Comment by hizzyg** [comment]
So I got the same Issue, What I did was to check on which ":" it is running. For example mine was running on :2.
Don't tunnel the port 2, you have to tunnel f.e 5902 (in my case). (The default one is 5900 but my VNC is running on :2 so i had to +2 on 5900).

Try: ngrok tcp 590* (* stays for 0-∞)

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
