### ISSUE TITLE
problem about cross compilation of ngrok 

### ISSUE THREAD

**Issue by pzy2253999075** [inconshreveable/ngrok#631]
Hey, I'm currently using ngrok, but I'm having cross compilation problems. I have two computers, one as a server and one as a client. Their processors are different.

Server:
![image](https://user-images.githubusercontent.com/15712923/71656118-10881a00-2d75-11ea-9a6d-e5faa41d82e8.png)

Client:
![image](https://user-images.githubusercontent.com/15712923/71656138-2269bd00-2d75-11ea-8490-7a0e822dfe14.png)

I download and compile ngrok on the server

download:
![image](https://user-images.githubusercontent.com/15712923/71656331-d4a18480-2d75-11ea-892a-f3f0b06b5e92.png)

compile server-side program:
![image](https://user-images.githubusercontent.com/15712923/71656440-28ac6900-2d76-11ea-99ec-0af2a3336f15.png)

compile client-side program:
![image](https://user-images.githubusercontent.com/15712923/71656588-c43dd980-2d76-11ea-805d-4b9a6436d65b.png)

Copy ngrok to client to run：
![image](https://user-images.githubusercontent.com/15712923/71656634-f18a8780-2d76-11ea-8771-43ba39be03ed.png)

As you can see, when the client runs ngrok, it reports an error. I think this is a cross compilation problem. Could you help me to solve it，thanks.

**Comment by benyitzhaki** [comment]
I'm also experiencing similar issues. ngrok.com seems to be down, unsure if its related

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
