### ISSUE TITLE
panic: Asset assets/client/tls/ngrokroot.crt not found

### ISSUE THREAD

**Issue by xcg00** [inconshreveable/ngrok#632]
When i run `./ngrok 8080`，i got this log
`panic: Asset assets/client/tls/ngrokroot.crt not found`

macos

![image](https://user-images.githubusercontent.com/9269837/71968075-40389580-323f-11ea-89d7-fd30c83f4b3b.png)

![image](https://user-images.githubusercontent.com/9269837/71968172-56465600-323f-11ea-9c2e-6c4daba14492.png)

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
