### ISSUE TITLE
How to fetch the Ngrok address when Ngrok is running.

### ISSUE THREAD

**Issue by dsomel21** [inconshreveable/ngrok#634]
I tried to look in the developers guide, but couldn't find the answer: 

Is there a way I can get the Web Address that Ngrok generates? For example: 

When I run `./ngrok http 3001` It will create the following: 

```
Account                       fake (Plan: Free)                                           
Version                       2.3.35                                                      
Region                        New Zealand                                   
Web Interface                 http://XXX.0.0.1:4040                                       
Forwarding                    http://f5291e35.ngrok.io -> http://localhost:3001           
Forwarding                    https://f5291e35.ngrok.io -> http://localhost:3001          
```

I want to create a shell script that needs to get the `https://f5291e35.ngrok.io` address, but I am hoping I can get some light on where to look, or if there is a command that can be run to fetch it.

**Comment by sleirsgoevy** [comment]
`ngrok tcp 8080 -log stdout -log-format logfmt -log-level debug`

This command causes ngrok to print plain-text logs to stdout instead of using curses. The exact address can then be extracted by e.g. piping the output to `awk` or similar.

**Comment by chuck-wood** [comment]
ngrok also has [an HTTP API](https://ngrok.com/docs#client-api) for fetching information from the running instance. For instance, you can get the list of tunnels with, e.g., `GET http://127.0.0.1:4040/tunnels`.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
