### ISSUE TITLE
ngrok can't establish connection

### ISSUE THREAD

**Issue by ilhamderi** [inconshreveable/ngrok#635]
when i run` ngrok http 80` in session status is timeout, i dont know why, but last time its running well, but when i try to re-run, please help me 
here log when i re-run command `ngrok http 80`
![image](https://user-images.githubusercontent.com/19345472/73158392-43c08d80-4116-11ea-8678-152097d859aa.png)
please help me, what should i do?
thank before

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
