### ISSUE TITLE
Ngrok configuration file path

### ISSUE THREAD

**Issue by gogears** [inconshreveable/ngrok#640]
1) Where will be the configuration file that contains auth token of ngrok
2) Need to find file location in both MacOSX and Windows

**Comment by gogears** [comment]
**Found solution**
To access configuration file of ngrok. In terminal follow the steps,
`cd ~/
vi /Users/sriramkarthick/.ngrok2/ngrok.yml`

**Comment by ryguy77** [comment]
I am not seeing this file, located on my mac anywhere. Is this something that needs to be created if so what would the basic file look like?

**Comment by sriramgroot** [comment]
> I am not seeing this file, located on my mac anywhere. Is this something that needs to be created if so what would the basic file look like?

Can you please check this file under user profile folder using ls -la

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
