### ISSUE TITLE
Materialize Icons setup

### ISSUE THREAD

**Issue by RicardoEwertz** [inconshreveable/ngrok#643]
When using ngrok as a tunnel to the localhost we are loosing the styles for Materialize Icons.
The web site makes references to the material-Icons but does not load them as icons. We see them just as html.
We are using Opencart 3.0 and the theme is named Materialize Theme. 
The website at the localhost is shown OK
How should we fix it...
thanks

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
