### ISSUE TITLE
Still unable to see images from my website when using ngrok

### ISSUE THREAD

**Issue by RicardoEwertz** [inconshreveable/ngrok#644]
Website done on Opencart 3.0.2
Website is working OK on local
We are using windows server and Xampp.
We created the tunnel using ngrok and we got http/ and https/ addresses to get access.
We entered the address to the browser using Chrome, Firefox and IE
We get the connection to the local host and by using dashboard we are redirected to the Xampp server.
We can navigate on Xampp on all pages.
Once we replace the dashboard text by our website files hosted in the htdocs files for Xampp we get the access to the website.
Here we are facing three issues | unsolved
1.-  Images from the website show broken
2.-  Materialize Icons are shown as text and not as images
3.-  We can not navigate on other pages, it get us back to localhost and its not recognizable in the external browser.
Is it a problem with ngrok?
How and where we can find information on how to get it fixed?
We have looked around on many forums and we can not find answers that help us fix those problems.
Please help....

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
