### ISSUE TITLE
API Keys are missing

### ISSUE THREAD

**Issue by WassimBenzarti** [inconshreveable/ngrok#646]
I tried to use the ngrok API (api.ngrok.com). I read the related documentation [here](https://ngrok.com/docs/ngrok-link).

Unfortunately, I can't seem to find, in the dashboard, the section related to Bearer token nor the API keys.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
