### ISSUE TITLE
Basic auth in origin doesn't seem to work

### ISSUE THREAD

**Issue by vasilakisfil** [inconshreveable/ngrok#647]
I expose an http service that has basic auth in a specific path. The basic auth dialog shows up in the exposed ngrok url, but for some reason the origin service declines and resends the 401 response. I tried altering the host header but no luck. Not sure why this is happening, all headers seem identical except Host header and Referer. Any ideas ?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
