### ISSUE TITLE
Tunnel not found error on Debian 9

### ISSUE THREAD

**Issue by lordlabakdas** [inconshreveable/ngrok#648]
I have installed ngrok on Debian 9 and  I currently use the Basic version. I keep getting the Tunnel <url> not found error.

The same account works on my local system and on other Debian servers and thus I think this seems to be server specific. 

Is there something specific I should be looking at?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
