### ISSUE TITLE
Ngrok Commands getting killed

### ISSUE THREAD

**Issue by shubhamk1997** [inconshreveable/ngrok#649]
Any command I am writing is showing "zsh: no such file or directory: ./ngrok". I have installed it a lot of times and it's there in the /usr/local/bin directory. After I restart my computer it works the first time and after that it gives this error.
 ➜  ~ ngrok http 80          
[1]    63136 killed     ngrok http 80
and after that writing the ./ngrok http 80 it gives the same no such file or directory error. Any solution to this ?

**Comment by underGhost** [comment]
I'm use bash and also getting `Killed: 9`  after trying to run and the executable being deleted. After restarting I get to run it 1 time before it breaks again.

**Comment by ShenChen-Amazon** [comment]
same problem here +1. Anyone help ?

**Comment by Bigal2359** [comment]
Damn. Actually happy to know I'm not the only one this is happening to. Getting the `Killed: 9` after running ngrok authtoken command and then `Permission denied` when I try running it again. Any help?

**Comment by headcrabz** [comment]
any solutions yet  ? same issue

**Comment by ttylerlarsen** [comment]
+1

**Comment by ShenChen-Amazon** [comment]
I use docker to helper. 
Install docker, and run following script: https://gist.github.com/kakhaUrigashvili/42896a7bc4148abe94e3f87191462890

It works for me.

**Comment by dechimp** [comment]
Downgrading node from 17 to 15 did the trick for me (on a mac)

**Comment by kumarabhirup** [comment]
I tried downgrading from 17 to 15, didn't work for me 😅  @dechimp

**Comment by caseysoftware** [comment]
These forums are unmonitored. For active support, check out our slack community: https://ngrok.com/slack
