### ISSUE TITLE
Ngrok Just Went Down

### ISSUE THREAD

**Issue by dave4jr** [inconshreveable/ngrok#650]
Has been working fine all morning and all of a sudden it shows Internal Server Error: ERR_NGROK_802

Any thoughts?

**Comment by rlinehan** [comment]
Same here, just now.

**Comment by yesterday24** [comment]
Same here.

**Comment by nandakishorebhandari** [comment]
Same here

**Comment by pocketcolin** [comment]
+1

**Comment by luiscl32** [comment]
same here

**Comment by abachi** [comment]
Same here it fails with internal server error ERR_NGROK_802

**Comment by tbell511** [comment]
same here 🤔

**Comment by mksh** [comment]
Seems an outage is local to US region, adding region switch like `--region eu` makes it work.

**Comment by mhbm** [comment]
I put this `--region eu` and works for me

**Comment by Oriol726** [comment]
i put the `--region eu` and it worked for me too

**Comment by maiconcarraro** [comment]
saviors 🙌

**Comment by masudhossain** [comment]
It's back up !

**Comment by mhbm** [comment]
US region is normally now. 👍

**Comment by prabhathc** [comment]
Back down for me! I was going mad lol

**Comment by X4NDR0** [comment]
same any idea?

**Comment by kavipatel04** [comment]
Also experiencing the same issue.

**Comment by a4h8** [comment]
Same here thanks **mksh**  adding `-region=eu ` in _windows_ solved the issue

**Comment by dave4jr** [comment]
Closing this issue as normal functionality has been restored. Thank you!

**Comment by gterras** [comment]
I'm in Europe and this has just happened to me now (it was running flawlessly for days before that).

**Comment by qaiken** [comment]
seems to be happening again in US as well.

**Comment by maxtomczyk** [comment]
Looks like same here again. --region=eu fixed the problem

**Comment by ajw725** [comment]
yeah, down again here too.

**Comment by Oriol726** [comment]
mine's down again too

**Comment by KentDalrymple** [comment]
down again

**Comment by armiiller** [comment]
I am still seeing this aswell

**Comment by kavipatel04** [comment]
Just went down, working fine earlier today, even eu region not working

**Comment by linnia78** [comment]
down!!

**Comment by rezicosta** [comment]
Same

**Comment by rafaelmtorres** [comment]
Please check @maxtomczyk post above 👆🏻 That solved for me.
./ngrok http 3000 --region=eu

**Comment by griff4594** [comment]
Very Very Down!

**Comment by chiragsalian** [comment]
Down for me too

**Comment by rezicosta** [comment]
Specifying --region=eu should work now

**Comment by viictorhgc** [comment]
but using -region =eu change a URL to URL.eu.ngrok.io

**Comment by rezicosta** [comment]
> but using -region =eu change a URL to URL.eu.ngrok.io

So what?

**Comment by mohok** [comment]
> Specifying --region=eu should work now

It's working well 😄

**Comment by mo7amedmamdouh** [comment]
> > but using -region =eu change a URL to URL.eu.ngrok.io
> 
> So what?

i was using my ngrok url in different callbacks and i have to re-validate all of them

**Comment by mo7amedmamdouh** [comment]
Looks like same issue is happening again. @davej

**Comment by rezicosta** [comment]
> > > but using -region =eu change a URL to URL.eu.ngrok.io
> > 
> > 
> > So what?
> 
> i was using my ngrok url in different callbacks and i have to re-validate all of them

Try to make a variable where you will store ngrok url and use that variable in your callbacks.

**Comment by mo7amedmamdouh** [comment]
> > > > but using -region =eu change a URL to URL.eu.ngrok.io
> > > 
> > > 
> > > So what?
> > 
> > 
> > i was using my ngrok url in different callbacks and i have to re-validate all of them
> 
> Try to make a variable where you will store ngrok url and use that variable in your callbacks.

I know that, i mean i'm have to put the new url in all platforms my system uses like 
google, facebook, twilio and so on

**Comment by kprobinson** [comment]
+1

**Comment by lvca** [comment]
+1 Also here

**Comment by 0c370t** [comment]
+1 Also having issues, I use a hostname so unable to change regions

**Comment by dlowhorn** [comment]
+1 just went down about ~5 minutes ago

**Comment by kavipatel04** [comment]
+1

**Comment by egekhter** [comment]
+1, using switch -region=eu causes error:

Failed to bind the address '1.tcp.ngrok.io:XXXXX' in region 'eu' because it is reserved
in the 'us' region.

**Comment by Oriol726** [comment]
yesterday, the system came back up in about an hour, so we'll see I guess.

**Comment by zquintana** [comment]
+1

**Comment by gdsouza1992** [comment]
+1

**Comment by sauliusGTO3000** [comment]
+1

**Comment by zquintana** [comment]
And I just got done saying how useful this tool was to our engineering manager. :disappointed:

**Comment by JolenePek** [comment]
down for me too

**Comment by pjayme** [comment]
US down

**Comment by saharshjain** [comment]
Same here tried mobile hotspot, flushing DNS, restarting, reinstalling  and re authentication. 
```
Session Status                reconnecting (dial tcp 18.189.209.170:443: connect
Session Status                reconnecting (dial tcp 3.20.111.144:443: connect: 
Session Status                reconnecting (resolved tunnel.us.ngrok.com has no records)                    
```

**Comment by luobogenw** [comment]
+1

**Comment by davthomaspilot** [comment]
Same issue.  Is there a way to get a notification when things go down?  

Or, what's the easiest way to check status?

**Comment by Oriol726** [comment]
it's back up for me

**Comment by syednurulla** [comment]
Error not working 
internal server error

ERR_NGROK_802

**Comment by saharshjain** [comment]
Try using ```--region eu```. Outage in us.

**Comment by joaocps** [comment]
reconnecting (internal server errorERR_NGROK_802)

**Comment by mikeeus** [comment]
It seems to be cutting in and out intermittently. I signed up for a pro account and reserved urls in eu and jp but neither are working atm

**Comment by joaocps** [comment]
back again for me!

**Comment by frontoffice-dev** [comment]
covid-19 infected ngrok's us region :)))

use: `ngrok http 8000 --region=eu`

**Comment by davthomaspilot** [comment]
Starting ngrok with --region=eu doesn't help if external access to the tunnel needs to be fixed URL. 

If the URL needs to change, it's not useful for my application.

Or am I missing something?   (simply adding that flag didn't help)

**Comment by andrewpage** [comment]
Issues connecting as well. Unfortunately cannot connect to EU region without reconfiguring because my team is running on reserved tunnels in US region.

Would appreciate some communication+status updates from the Ngrok team!

**Comment by davthomaspilot** [comment]
This issue was closed.  Shoud a new one be opened?

**Comment by zquintana** [comment]
@saharshjain closing without a resolution?

**Comment by frontoffice-dev** [comment]
I already want to buy an ssl certificate((

**Comment by karthigb** [comment]
It just happened to me now. It was working fine until about ten minutes ago.

**Comment by karthigb** [comment]
Fixed :)

**Comment by viictorhgc** [comment]
I think we came back with the same problem ...

**Comment by kanagalingam** [comment]
Down again ! Was working fine till morning. 
Initially before a hour i was getting the error "Target machine actively refused" and now i am getting 

```
internal server error
ERR_NGROK_802
```

**Comment by papillioncristo** [comment]
happening to me as well.  i have tried to restart several times without success

`internal server error

ERR_NGROK_802`

**Comment by HSPDev** [comment]
EU Just went down I think.

They really lack a status page, don't they? Crazy unprofessional to not have one as a dev-tool...

**Comment by roncromberge** [comment]
ME Too. EU

**Comment by roncromberge** [comment]
Up again EU

**Comment by studentIvan** [comment]
Try with `sudo` if you a mac user

**Comment by Fustie** [comment]
> Try with `sudo` if you a mac user

It helps, but when you wrote authtoken to config file, it stops work.

**Comment by thiagofm** [comment]
same here

**Comment by tyomik-mnemonic** [comment]
same! Why it was closed? eu doesn't help

**Comment by GeorgeSeeger** [comment]
+1 more with this error

**Comment by tyomik-mnemonic** [comment]
guys check your auth keys, its can be not fresh.

**Comment by navid-farjad** [comment]
yep, same issue here

**Comment by navid-farjad** [comment]
i tried "sudo ngrok http 8081" with having "allowedHosts: ['.ngrok.io']" in webpack devServer. it worked!

**Comment by LainARG** [comment]
Same. 

an alternative?

**Comment by callmevari** [comment]
Same here.
This morning ngrok started to fail, none of the recommendations above works for me.

**Comment by mnlfischer** [comment]
same error.

**Comment by toivocat** [comment]
This problem is also going on with any type, tcp, and http. I am using tcp and is there a way u can reopen this issue? Because its still not working for my GDScript servers.

**Comment by junket** [comment]
I am also seeing an outage, all regions, today March 6, 2022. Not currently reported on the status page: https://status.ngrok.com/

**Comment by junket** [comment]
Confirmed just now by @inconshreveable:

hi jon -

we're working on recovering from a service failure, appreciate your patience, we should be recovered shortly

- alan
Founder, [ngrok.com](https://github.com/inconshreveable/ngrok/issues/ngrok.com)
