### ISSUE TITLE
Ngrok down 

### ISSUE THREAD

**Issue by masudhossain** [inconshreveable/ngrok#651]
https://prnt.sc/rrw73l

**Comment by ImoutoChan** [comment]
Same for me

**Comment by dfrank8** [comment]
Same for me

**Comment by gmelanta79** [comment]
Has this happened before?

**Comment by miguelcastro67** [comment]
Damn, the timing couldn't be poorer. Have a demo first thing tomorrow morning and I rely on this. Any update???

**Comment by gmelanta79** [comment]
Hah, i have a demo today for which i need it..

**Comment by miguelcastro67** [comment]
This is BS. Now it goes to "connecting" but instead of showing the red error message, the command console just closes

**Comment by miguelcastro67** [comment]
ok now the console stays open but still the red error messages - looks just like the screenshot some posted above

**Comment by saharshjain** [comment]
Try connecting with ```-region eu```  for now.

check this [Issue link](https://github.com/inconshreveable/ngrok/issues/650)

**Comment by masudhossain** [comment]
> Has this happened before?

A few days ago

**Comment by miguelcastro67** [comment]
ok --region eu does work - at least it will get me though my demo tomrrow

**Comment by gmelanta79** [comment]
Has it been stable for everyone?

**Comment by masudhossain** [comment]
> Has it been stable for everyone?

Yes, closing this issue.

**Comment by pretech86** [comment]
no not working any solution
