### ISSUE TITLE
Ngrok does not work over wan and virtualbox bridge adapters

### ISSUE THREAD

**Issue by Ch3sh1r3-C4t** [inconshreveable/ngrok#654]
I am encountering a problem when trying to access my local webserver over wan using ngrok ( I tried to access the page using my mobile phone and other devices connected to other networks).
I am using VirtualBox, with a kali 2020 virtual machine (I use it for my university course and is fully updated) using a NAT network adapter  to launch ngrok to access my webserver running on port 80 using 
`./ngrok http 80`

![startNgrok](https://user-images.githubusercontent.com/44528713/79342578-35b82700-7f25-11ea-9a0d-3c3da5b7bdcb.png)

The problem I am facing is that when I try to access the page from another machine on another machine it gives an error `Tunnel d605b4e8.ngrok.io not found`. From my kali machine, it is working fine and I can access the page without any issues. If I change the network adapter from NAT Network to bridge adapter I cannot access the pages, not even from my kali machine.

I was thinking, is it possible that mobile network providers and ISPs are blocking .ngrok.io domains for some reason? Is it there a way to fix this issue? 

![errorBridge](https://user-images.githubusercontent.com/44528713/79342663-52545f00-7f25-11ea-8a25-708f1d959da9.png)
_error from kali using Bridge network adapter_

![errorMobile](https://user-images.githubusercontent.com/44528713/79342889-99425480-7f25-11ea-8950-66aab1a816f9.PNG)
_error from mobile_

**Comment by chatterjeeshekhar** [comment]
Why is there no update on this since?

**Comment by chatterjeeshekhar** [comment]
@LucSai Could you find a solution to this/

**Comment by LucSai** [comment]
> @LucSai Were you able to find a solution to this problem?

No, I have not found a solution to this problem yet ...

**Comment by aditya6263722391** [comment]
Anyone have solution for this???

**Comment by TheBWoods** [comment]
Hello, could anyone solve the problem?

**Comment by nlylegel** [comment]
I have the same problem but when i start ngrok on windows it works. When i start it on kali it doesn't work. It's very problematic and there no solution on internet yet

**Comment by user13141** [comment]
use vmware instead of virtualbox and it will work
