### ISSUE TITLE
Added public key to authorized_keys, still get permission denied (public key)

### ISSUE THREAD

**Issue by bitcoinmeetups** [inconshreveable/ngrok#655]
Added public key to authorized_keys, still get permission denied (public key)

Hi,

I am trying to SSH into a remote machine. I have added the local machine's public key to the remote authorized_keys but I still get permission denied (public key). Was trying to reconfigure for hours without being able to fix this.

Any advice?

BM

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
