### ISSUE TITLE
Ngrok does not work on termux

### ISSUE THREAD

**Issue by hood1** [inconshreveable/ngrok#660]
Hi guys,
I don't know why ngrok is not connecting to it server on my termux. I have tried every means of install the package but it's still not working. I downloaded the Linux arm zip file from ngrok site and the follow the installation with the necessary authentication token but it is still showing this.
ngrok by @inconshreveable                             (Ctrl+C to quit)

Session Status                reconnecting (Get https://s3.amazonaws.c
Version                       2.3.35
Region                        United States (us)
Web Interface                 http://127.0.0.1:4040

Connections                   ttl     opn     rt1     rt5     p50
                              0       0       0.00    0.00    0.00
![Screenshot_20200429-152408](https://user-images.githubusercontent.com/64293471/80608434-ab94b600-8a2e-11ea-83f7-4e73259cb5ce.png)

**Comment by hood1** [comment]
Resolve personally. All you need to do is to Power ON your hotspot before launching Ngrok server

**Comment by RaydanOMGr** [comment]
> Resolve personally. All you need to do is to Power ON your hotspot before launching Ngrok server

I have a tablet which got no hotspot, how do I do that then?

**Comment by j-refs** [comment]
Necro'd. But try your luck with either foxfi or pdanet
