### ISSUE TITLE
Ngrok keeps throwing INVALID HOST HEADER when accessed from remote machine

### ISSUE THREAD

**Issue by nutharsh** [inconshreveable/ngrok#667]
I have free account in ngrok. 
I have setup authtoken and configured the same in ngrok yaml configuration.
I am running cmd:  ngrok http -host-header=rewrite 4200
Application is running with UI app on 4200 and backend in sprint boot on 9876

**Comment by Berus008** [comment]
is your ngrok is working at all?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
