### ISSUE TITLE
Getting “failed to complete tunnel connection” on iOS only

### ISSUE THREAD

**Issue by aral** [inconshreveable/ngrok#668]
1. Hit https://dev.ar.al in desktop Firefox, Chrome (Linux), Safari (Mac), Edge (Windows) – all work

2. Hit it in Mobile Safari on latest iOS and I get “failed to complete tunnel connection”. Same on refresh. Same after app restart.

**Comment by aral** [comment]
(Note: this is on the paid proprietary app, not this outdated open source version.)

**Comment by aral** [comment]
PS. Reproduced on second iPhone also.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
