### ISSUE TITLE
Trouble with ngrok and XAMPP 

### ISSUE THREAD

**Issue by SobieSki** [inconshreveable/ngrok#67]
Hi everyone :)

My problem is exactly the same as found in this closed thread : https://github.com/inconshreveable/ngrok/issues/63

When I run ngrock 80 and check the site with my forwarding domain (https://mydomain.ngrok.com) it redirects to https://mydomain.ngrok.com/xampp and works fine.

But when I try to access my site (located in the htdocs folder under XAMPP) via https://mydomain.ngrok.com/www/ the URL resolves to 127.0.0.1/www/ which works on my local machine but when testing on my other devices it cannot connect to the server.

The previous gentleman put the issue in better words than I could. I would really appreciate any help with this as I'm sure there are many others having this same problem.

Kind regards,

**Comment by inconshreveable** [comment]
this is solved in ngrok 2.x with the `-host-header` flag for rewriting. won't fix for ngrok 1.x
