### ISSUE TITLE
HTTPS not working. Redirecting to HTTP!!

### ISSUE THREAD

**Issue by ctwillie** [inconshreveable/ngrok#670]
I have ngrok installed on windows 10. Everything works perfectly, as far as I can tell, except the https forwarding urls generated by ngrok in the terminal. Then https url redirects to http url. I am using a registered domain name instead of the random domain generated. I thought the https urls should work out of the box?

**Comment by timendez** [comment]
@ctwillie Did you ever figure out your problem?

**Comment by ctwillie** [comment]
@timendez The specific problem I was having at the time, no. I'm now paying for the service to use daily at work. I use custom registered domains on my ngrok account and https is working fine. Not sure why http was redirecting to https without the paid account. Never solved that issue.
