### ISSUE TITLE
Support is non existent

### ISSUE THREAD

**Issue by yonnic** [inconshreveable/ngrok#671]
Hello

I am a paying customer and i tried to contact the support many times but never got a reply back.
Is the Support dead ?

**Comment by alibarrak** [comment]
I had issues with my two pro accounts for about a day and half. I couldn't get any feedback from support email either from Alan's. 
I've just finished watching a youtube video of Alan talking about ngrok. I understand now that Alan doesn't like replying to support emails. Instead he tried to make ngrok give proper feedback to common issues. However, I think ngrok just failed to give the correct error this time!
The good news is that it's working now (for me at least).
My issue was getting ERR_NGROK_309 for proto TCP (22) and http (with reserved names). It could be an outage issue.

**Comment by challgren** [comment]
I paid for the business account and have emailed support 5 days ago haven't heard anything

**Comment by RHQ-Rusty** [comment]
See [my comment](https://github.com/inconshreveable/ngrok/issues/653#issuecomment-735440250) on #653 for my temporary workaround! Might help you guys out :)

**Comment by caseysoftware** [comment]
My apologies for the previous support issues.

In the last ~8 months, we've completely revamped our support and have a standing Support team to help with account, billing, and technical issues.

For purely, day to day usage issues, check out our Slack Community for ongoing discussion https://ngrok.com/slack
