### ISSUE TITLE
 No “.ngrok2” directory (Kali Linux)

### ISSUE THREAD

**Issue by annonymous644** [inconshreveable/ngrok#673]
I downloaded the “ngrok-stable-linux-amd64.zip” file from the “Ngrok” page, for VirtualBox_Kali Linux; everything works fine (I’ve been using it for a considerable amount of time); but now, searching through the files, I realized that I have no: “home/user/.ngrok2/ngrok.yml” directory nor “ngrok.yml” file that I can locate. Tried with “Ctrl+h” for hidden files/folders, as well  as searching for it in the “Catfish File Search”, but no sign of it.

**Comment by mrchomik892** [comment]
On github it's 1.0?

**Comment by SKEMAM** [comment]
Go root then show hidden file. then go to .config/ngrok/ngrok.yml
