### ISSUE TITLE
Failed to complete tunnel connection 

### ISSUE THREAD

**Issue by mrquee1** [inconshreveable/ngrok#674]
Hello, install ngrok to create a local server, but when starting the server it shows me the following error:

```
The connection to http://3040c5cd2855.ngrok.io was successfully tunneled to your ngrok client, but the client failed to establish a connection to the local address localhost:80.

Make sure that a web service is running on localhost:80 and that it is a valid address. 

The error encountered was: dial tcp [::1]:80: connectex: A connection cannot be established as the destination computer expressly denied that connection

```

I tried disabling the firewall of the computer but it still gives me the same error. 

In the command console it shows me this other error  `"502 bad gateway".`, by the way the command that I use to start the server is  `ngrok http 80` 

 I am a novice and do not move about servers. Thank you very much for your attention.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
