### ISSUE TITLE
Can't embed grafana panel

### ISSUE THREAD

**Issue by KareemAnbar** [inconshreveable/ngrok#685]
I am creating graphs on a raspberry pi using Grafana. I can access the Grafana panels using URL : `localhost:3000`. I am using ngrok to be able to access the dashboard remotely. 

![Screen Shot 2020-07-30 at 19 00 49](https://user-images.githubusercontent.com/67562213/89070752-58a00700-d36d-11ea-983e-2fe61dbb0a6e.png)

I tried to embed the graph panels on to a square space website using the embedding code generated by Grafana. However, the embedded panel does not work and i get "refused to connect" on chrome and "content cannot be shown in frame" on internet explorer.
![Screen Shot 2020-07-30 at 18 52 04](https://user-images.githubusercontent.com/67562213/89070909-9d2ba280-d36d-11ea-96d1-4c6fbe4625d5.png)
![Screen Shot 2020-07-30 at 18 37 25](https://user-images.githubusercontent.com/67562213/89070914-9ef56600-d36d-11ea-9478-0cdf72a09731.png)
I emailed Square Space and they said the issue due to ngrok 

> setting an HTTP (X-Frame-Optons, Content-Security-Policy,etc) that prevents other websites from embedding it within a frame.

Any ideas on how i can embed my panel and have it actually display the panel?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
