### ISSUE TITLE
[Question] How to keep the Ngrok tunnel running (even after restart)

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#687]
Is there any way this is possible?
I know it is, but I'm not aware of any methods that would bring the tunnel back up after a system reboot.
If there are any, please consider sharing them.
Thanks

**Comment by Agrejus** [comment]
@mihabozic123 if you are using windows, then you can install Ngrok as a windows service and have it start when windows starts.  You will want the product Ngrok Link though, the consumer version of Ngrok cannot do what you are asking.  Ngrok Link is not free, if you are looking for a free option, you will need to write your own application to handle this.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
