### ISSUE TITLE
ERROR:  Invalid configuration property value for 'http_proxy', 'localhost/cursophp': URL scheme must be 'http' or 'https'

### ISSUE THREAD

**Issue by papeleon** [inconshreveable/ngrok#694]
i have text instead numbers what I do

**Comment by JeaNile** [comment]
You can try  `set http_proxy=false`

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
hi @papeleon , ngrok will automatically pick up the proxy url defined in `http_proxy` and `http_proxy_env` and use it to establish a connection. However, we expect the value to be a full url, including http and https. You can either unset that env variable or update it to include the proper scheme.
