### ISSUE TITLE
I cannot get cookie from ngrok url

### ISSUE THREAD

**Issue by AngeloMetal** [inconshreveable/ngrok#698]
I'm trying to parse cookies from the client to the server using node js. Everything works fine, but when I switch from localhost to an ngrok url, cookies are not parsed. Actually every time I call req.cookies["username"] I get undefined as a response from the server.

This is the important part from my ap.js:
`app.ws('/', function(ws, req, res) {
console.log(req.cookies["username"]) });`

Although, I don't think that this is a coding problem. I've installed every dependency and as I said cookie is successfully sent from client to server on localhost but not when I start ngrok. Something must be wrong with the random ngrok subdomain or/and with the ngrok server. I've tried Chrome and Firefox. Both have the same issue.

I have windows 7 64bit using node js v10.22.0.

**Comment by timgonzo** [comment]
I'm running into the same issue. Was this ever resolved?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
