### ISSUE TITLE
Weird hang up issue on Windows Server 2008 R2

### ISSUE THREAD

**Issue by JuanMdP** [inconshreveable/ngrok#700]
Hello everyone,

I've been using ngrok quite a bit since the pandemic started, for about 4 months everything worked just fine. Yet starting this week something started acting up and the console that runs the tunnel sorta freezes. I say "sort of" because it isn't really frozen the way apps in windows freeze, but it won't accept commands anymore (like Ctrl + C to terminate the tunnel) and the tunnel url stays waiting a response from the server forever~.

Nothing new was installed on the server PC (a server running Windows Server 2008 R2), I've tried to google about it but to no avail. Any idea of insight on this issue would be greatly appreciated~.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
