### ISSUE TITLE
Ngrok tunnel not found

### ISSUE THREAD

**Issue by jamesmiller9048** [inconshreveable/ngrok#704]
I tried social pish inside local network it's okay but outside the network the following error is shown
tunnel url.ngrok.io not found
So I went to the terminal where I started ngrok and saw some errors 404 and 503
Same thing while trying to use it for metasploit inside the network it's okay but outside the network it's not working

**Comment by krishnadevpmelevila** [comment]
I got the final and ultimate solution for this issue !
1.Just forget your old account and create a fresh account on [Ngrok](https://dashboard.ngrok.com/login)
2. Just add the new auth config to your terminal as per the ngrok documentation [here](https://dashboard.ngrok.com/get-started/setup)
3. That's all , now start your tunnel as usual. And it will be working fine on WAN.

**Comment by caseysoftware** [comment]
Hacking, phishing, etc are not welcome on ngrok. Once your account is discovered, it will be canceled
