### ISSUE TITLE
"There was a problem loading the billing plans" while trying to upgrade

### ISSUE THREAD

**Issue by poisa** [inconshreveable/ngrok#705]
This is most likely the wrong place to post this but there is no support link or form in the ngrok.com website.

While trying to upgrade to a paid plan https://dashboard.ngrok.com/billing/plan I get this error:

>There was a problem loading the billing plans

How can I solve this?

**Comment by caseysoftware** [comment]
For billing issues, feel free to email support@ngork.com

This issue queue is not monitored. Join our Slack Community for ongoing discussion https://ngrok.com/slack
