### ISSUE TITLE
Ngrok TCP port forwarding not working outside network

### ISSUE THREAD

**Issue by pranavkinicok** [inconshreveable/ngrok#706]
While trying to use it for metasploit inside the network it's okay but outside the network it's not working
The listener starts and waits for the connection but no session opens up

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
