### ISSUE TITLE
Unable to tunnel any port on Raspberry Pi, getting "operation not permitted" 

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#710]
I installed ngrok into my Raspberry Pi 4b through Snap. When running any command I always get this at first:

`ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.`

Then, when I try to tunnel either http or tcp, I get an error of operation not permitted:

```
ngrok tcp 22
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
listen tcp 127.0.0.1:4049: listen: operation not permitted

sudo /snap/bin/ngrok tcp 22
ERROR: ld.so: object '/usr/lib/arm-linux-gnueabihf/libarmmem-${PLATFORM}.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
listen tcp 127.0.0.1:4049: listen: operation not permitted
```

ngrok version 2.3.35

**Comment by Sapu98** [comment]
same problem here, did u fix?

**Comment by ocalde** [comment]
Nope, couldn't find the issue

**Comment by KiPetit** [comment]
Same problem

**Comment by KiPetit** [comment]
I have the same issue on RPi 4

**Comment by thakshbham319** [comment]
i had same issue but resolved.
please follow the instructions:-
1. go to prefrences then click on raspberry pi configuration
2. then click on interfaces and enable ssh  then reboot the pi.
3. download ngrok and install ngrok on pi.
4. extract ngrok to any folder like as to download folder.
5. copy the path of ngrok and paste in the pi terminal.
6. make cmd as   $ /home/pi/Downloads/ngrok http 192.168.0.1:1880
7. hit enter button.
8. i hope your problem will be solve after following instructions.

**Comment by woggledog** [comment]
> ngrok http 192.168.0.1:1880

Rather than just the port fixed this for me. That's the only thing I had to do

**Comment by Voxiks** [comment]
I have the same problem, but when I installed rocket chat everything was ok, but after reinstallation os something happened wrong, can someone help? I cant create tunel to share mc server, the same error code.

**Comment by raskin-bond** [comment]
I'm also got same problem then i download the ngrok directly from the website then i moved to raspberry pi home storage. Same like ngrok working termux android.. 

And then woking fine in raspberry pi. :)

**Comment by ejdoh1** [comment]
same issue with snap install. used the zip from ngrok and problem fixed  (Pi 3)
```
wget https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip
unzip ngrok-stable-linux-arm.zip
./ngrok --help
```

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
