### ISSUE TITLE
Changing account in NGrok settings

### ISSUE THREAD

**Issue by orenlande** [inconshreveable/ngrok#713]
Hello, I'm using NGrok as part of my company's project. So far I was using the free version, but we have decided to upgrade it to fully use it. However, my machine is locked to the free version due my personal account which considered as free. 

Any time I try to do custom domain, it throws me message 
`
Only paid plans may bind custom subdomains.
Failed to bind the custom subdomain 'local-dev' for the account .... 
`

I even tried to assign my account under the company's account, but no luck. I assume something in the initial NGrok settings is set to check my personal account and not the company's.

Wonder how can I fix this issue? Thanks

**Comment by caseysoftware** [comment]
Set an authtoken just like you would when you first install ngrok. Alternatively, you can edit your ~/.ngrok2/ngrok.yml

Also, this issue queue is not monitored. Join our Slack Community for ongoing discussion https://ngrok.com/slack
