### ISSUE TITLE
`ngrok null` would be a nice addition for pure HTTP inspection without forwarding the traffic

### ISSUE THREAD

**Issue by piejanssens** [inconshreveable/ngrok#714]

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
We've recently added [Traffic Inspection](https://dashboard.ngrok.com/observability/traffic-inspector) to our cloud Dashboard. You can start an ngrok agent to a dummy port and see all the traffic there.
