### ISSUE TITLE
tunnel not found: Tunnel bf256c0ea7e2.ngrok.io not found

### ISSUE THREAD

**Issue by Roaldkamman** [inconshreveable/ngrok#716]
I'm working on a Shopify app so I run the command: shopify serve and follow the url provided. I get a blank screen with this error:  Tunnel bf256c0ea7e2.ngrok.io not found. 

Not sure what's going wrong here. It was working fine yesterday. 

I might be completely unaware of something here I never had to use anything like a tunnel or ngrok before. 

Any help would be appreciated.

**Comment by caseysoftware** [comment]
This issue queue is unmonitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
