### ISSUE TITLE
Ngrok reconnecting 

### ISSUE THREAD

**Issue by Nina666c** [inconshreveable/ngrok#717]
It have been showing this issue reconnecting (resolved tunnel.us.ngrok.com has no records)
Does anyone know how to fix it?

**Comment by jlc-christie** [comment]
Getting the same issue. Can't even visit the ngrok site through a browser, some type of certificate issue. Very frustrating, can't find a solution anywhere. Any help would be appreciated. Says the domain on the certificate doesn't match and it shows the url written in reverse.

**Comment by PinkDev1** [comment]
@jlc-christie you can't do anything about it. This is a server error on Ngrok's side.
All we can do is annoy the devs / pay the devs more :p

**Comment by evoshawkins** [comment]
I'm receiving the same issue opening a tcp tunnel as in 'ngrok tcp 9010'

t=2021-04-16T08:31:43-0700 lvl=info msg="open config file" path=C:\\ProgramData\\Evosus\\.ngrok2\\ngrok.yml err=nil
t=2021-04-16T08:31:43-0700 lvl=info msg="starting web service" obj=web addr=127.0.0.1:4040
t=2021-04-16T08:31:43-0700 lvl=eror msg="failed to reconnect session" obj=csess id=622cdbf91d32 err="tls: failed to parse certificate from server: asn1: syntax error: invalid boolean"
t=2021-04-16T08:31:44-0700 lvl=eror msg="failed to reconnect session" obj=csess id=622cdbf91d32 err="tls: failed to parse certificate from server: asn1: syntax error: invalid boolean"
t=2021-04-16T08:31:45-0700 lvl=eror msg="failed to reconnect session" obj=csess id=622cdbf91d32 err="tls: failed to parse certificate from server: asn1: syntax error: invalid boolean"
t=2021-04-16T08:31:47-0700 lvl=eror msg="failed to reconnect session" obj=csess id=622cdbf91d32 err="tls: failed to parse certificate from server: asn1: syntax error: invalid boolean"
t=2021-04-16T08:31:48-0700 lvl=eror msg="failed to reconnect session" obj=csess id=622cdbf91d32 err="resolved tunnel.us.ngrok.com has no records"
t=2021-04-16T08:31:50-0700 lvl=info msg="Got quit command" obj=consoleui
t=2021-04-16T08:31:50-0700 lvl=info msg="received stop request" obj=app stopReq="{err:<nil> restart:false}"
t=2021-04-16T08:31:50-0700 lvl=info msg="session closing" obj=tunnels.session err=nil

I have tried the 32 and 64 bit version of the Windows executable. I have the issue on Windows Server 2016 but no issue with Windows 7 and Windows 10.

**Comment by caseysoftware** [comment]
This issue queue is unmonitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
