### ISSUE TITLE
Https tunnel setup works in command line, but not in config

### ISSUE THREAD

**Issue by DaveKallidus** [inconshreveable/ngrok#718]
Powershell command (works)
& "$ngrok" http https://objective-archive-function.Kallidus.Local:7901 --bind-tls "true" --subdomain "objective-archive-function-lpte2tcrn365"

Config Command (not work, am I missing something)
tunnels:
  identity-command:
    proto: http
    bind_tls: true
    addr: 7901
    subdomain: objective-archive-function-lpte2tcrn365
    host-header: objective-archive-function.Kallidus.Local

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
