### ISSUE TITLE
http auth not working 

### ISSUE THREAD

**Issue by praveendvd** [inconshreveable/ngrok#720]
`ngrok http --auth="user:pass" file:///D:/folder

Navigate to the url genrated 

The password prompt appears

**Refresh the page by pressing f5 multiple time , user is able to get access without password**

**Also https doesn't ask for any password at all**

ngrok version : 

ngrok version 2.3.35
`

**Comment by caseysoftware** [comment]
We recently published a blog post to walk through the auth options:

For ongoing support, check out our Slack community at http://ngrok.com/slack
