### ISSUE TITLE
Websocket error 404 or closed connection before ending handshake

### ISSUE THREAD

**Issue by VivianoRiccardo** [inconshreveable/ngrok#721]
https://stackoverflow.com/questions/64857113/websocket-over-ngrok-error-404-and-others, just to say i use webassembly websocket implementation so i use the ipaddress not the web domain

**Comment by houdz** [comment]
crashed

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
