### ISSUE TITLE
Error : bash: ./ngrok: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by NaNasuuAkiaa** [inconshreveable/ngrok#723]
When i try to run ngrok, it says : bash: ./ngrok: cannot execute binary file: Exec format error
i dont know why, because i've been using ngrok before on this computer...

**Comment by Mariosyian** [comment]
If you are using it on a Raspberry Pi, make sure you download the arm architecture. On a Linux machine ensure the URL ends in amd64 for 64bit Architecture and amd for 32 bit architecture. All these are in the download section of your dashboard. Hope this helps.

**Comment by Realbnglr** [comment]
> If you are using it on a Raspberry Pi, make sure you download the arm architecture. On a Linux machine ensure the URL ends in amd64 for 64bit Architecture and amd for 32 bit architecture. All these are in the download section of your dashboard. Hope this helps.

Which url ? Can you please tell

**Comment by Mariosyian** [comment]
@Realbnglr Sure, apologies I missed that.
The direct download link URL found in the "Setup & Installation" section of the ngrok dashboard.

Hovering over any of the hyperlinks under the "Linux" (Penguin) group, your browser should give you a preview to which URL that hyperlink navigates to. Each ends in `ngrok-stable-<platform>-<architecture>.zip` where `<platform>` is `linux` for the Linux OS, `windows` for Windows OS etc, and `<architecture>` is the `arm` for ARM 32 bit. `arm-64` for ARM 64 bit etc...

Hope this clears things up :smile: 

![image](https://user-images.githubusercontent.com/10303302/115378556-94635100-a1c8-11eb-8a77-55da743db23b.png)

**Comment by dinter167ts** [comment]
> @Realbnglr Sure, apologies I missed that.
> The direct download link URL found in the "Setup & Installation" section of the ngrok dashboard.
> 
> Hovering over any of the hyperlinks under the "Linux" (Penguin) group, your browser should give you a preview to which URL that hyperlink navigates to. Each ends in `ngrok-stable-<platform>-<architecture>.zip` where `<platform>` is `linux` for the Linux OS, `windows` for Windows OS etc, and `<architecture>` is the `arm` for ARM 32 bit. `arm-64` for ARM 64 bit etc...
> 
> Hope this clears things up 😄
> 
> ![image](https://user-images.githubusercontent.com/10303302/115378556-94635100-a1c8-11eb-8a77-55da743db23b.png)

It's worked for me! Many tks <3

**Comment by kasunudayanga** [comment]
Its worked
