### ISSUE TITLE
'Start a Tunnel' in GUI is incorrect

### ISSUE THREAD

**Issue by dev-manager-uk** [inconshreveable/ngrok#727]
ngrok GUI gives the wrong address to copy/paste

Should be:
$ngrok http --hostname=NAME.ngrok.io 80

not
$ngrok http -hostname=NAME.ngrok.io 80

![image](https://user-images.githubusercontent.com/12096704/102622313-bd9ba400-4138-11eb-9a2b-7d8e8d69119e.png)

**Comment by andrewmbenton** [comment]
Both flag prefix formats (`-` and `--`) work I believe.
