### ISSUE TITLE
"No requests to display yet" on TCP tunnel

### ISSUE THREAD

**Issue by kordexjan** [inconshreveable/ngrok#729]
I am forwarding port 25577 on TCP (for a minecraft server) but on the webinterface there are no requests like I said in the title.
Is it not possible or how can I fix this.

**Comment by andrewmbenton** [comment]
I don't think TCP tunnels have an internal concept of "requests" so there's nothing for the web interface to show.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
