### ISSUE TITLE
serve a filesystem directory

### ISSUE THREAD

**Issue by samuelcolvin** [inconshreveable/ngrok#732]
(I'm very sorry if this question/feature request has been asked before, I'm very surprised if it hasn't been, but I've search and can't find it)

It would be great if ngrok could create an http tunnel to a server which is serving files from a directory.

Effectively a glorified version of

```bash
python -m http.server 8000 && ngrok http 8000
```

in one command:

```bash
ngrok serve path/to/directory/
```

This would be preferable to the above because there would be no need to use another command to serve the local directory - no extra requirements and extra terminal window.

Extra great wizz-bang feature would include:
* support `index.html` and maybe `404.html`
* list of files when going to a directory without an `index.html` file - like apache
* livereload or equivalent functionality

**Comment by andrewmbenton** [comment]
You can do this with the ngrok agent directly. Documentation here: https://ngrok.com/docs#http-file-urls

**Comment by mcgrue** [comment]
"https://ngrok.com/docs#http-file-urls" doesnt link to the relevant page and hasnt for some time, rendering google results like this useless.

Furthermore your documentation search shows nothing if you enter "http file urls"

**Comment by russorat** [comment]
For anyone else who ends up here, the url is https://ngrok.com/docs/agent/cli/#ngrok-http and the command is something like: `ngrok http file:///full/path/to/dir/to/serve/`
