### ISSUE TITLE
ERR_NGROK_354

### ISSUE THREAD

**Issue by erdinc** [inconshreveable/ngrok#733]
starting from today, I'm getting this error.
```
ngrok http 3001 -subdomain=xxx.eu.ngrok.io
Failed to bind 'xxx.eu.ngrok.io.ngrok.io'. Nested subdomains of the ngrok base endpoint domain 'ngrok.io' are disallowed. Try 'xxx-eu-ngrok-io.ngrok.io' instead.
```

does anyone having same issue?

**Comment by edjames** [comment]
Hi. 

Any kind of information and/or an ETA for a solution would be greatly appreciated. I'm on a paid plan and with this error I'm blocked from progressing in my work, so it's a serious problem for me.

Thanks in advance.

**Comment by mfullbrook** [comment]
I've been using ngrok (on a paid plan) to tunnel from`my-subdomain.my-app.eu.ngrok.io` for as long as Ive been subscribing. This change to ngrok has broken our testing and mobile development workflows too.

I've looked at the documentation and I believe this usage is classified as [wildcard domains](https://ngrok.com/docs#wildcard). I reckon this change is to force people to upgrade to the Business plan to use wildcard domains.

**Comment by edjames** [comment]
> I reckon this change is to force people to upgrade to the Business plan to use wildcard domains.

If it's a mistake, fair enough. Hopefully we get a resolution fast.
If it's an intentional change then that is shockingly bad service and they will lose customers.

**Comment by mfullbrook** [comment]
Because my subdomains are all hardwired i've changed them from `.` to `-` and can now carry on.  However, I agree that fixing a regression (if it is one) could have been handled better.   For me, this is another reason to investigate https://github.com/beyondcode/expose

**Comment by NoorElkhatibToghoj** [comment]
We use Ngork in our development setup and we faced this issue. We contacted their support team and they created permanent exceptions for our account to use nested domains. Their reply was very swift. If you can send an email to their support teams I am sure they'll help.

**Comment by frankprogrammer** [comment]
We are on the business plan and are having this issue as well.

**Comment by wsbastian** [comment]
Has there been any official communication on this?

**Comment by andreas-globi** [comment]
The support team was able to enable nested subdomains on my account as well, but when I asked if this will work in perpetuity, they said it will not. This will only give a few months for us to figure it out.

This got me thinking though. Why do we even need ngrok? If you have a cname pointing to your local ip and a local /etc/hosts entry, then you can expose your vagrant (or other vm) vhosts without a tunnel. Combined with a simple script to enable and disable the firewall at will, and you're off to the races.

**Comment by gp-saurabh** [comment]
We are looking forward to get this resolved ASAP, as our testing and production environments depends on it. Please keep us updated.

**Comment by theblang** [comment]
We were using nested subdomains to locally test the sharing capability of cookies with the `Domain` attribute.

**Comment by adamzuckerberg** [comment]
Same issue. We use wildcard subdomains and need to test.  Just send ngrok an email.

**Comment by andrewmbenton** [comment]
Just following up on this and sorry for the lack of communication. The ngrok team doesn't actively monitor issues on this repo but we probably should.

We made a change to disallow "nested" subdomains of `ngrok.io` because we don't serve a valid TLS certificate for those DNS names, which was causing a lot of customer confusion.

For specific customers who depend on the old nested subdomain functionality, we do have a flag that we can switch on for your account if you send a quick email to support@ngrok.com requesting the change.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
