### ISSUE TITLE
Ngrok unable to forward

### ISSUE THREAD

**Issue by IRISnoir** [inconshreveable/ngrok#735]
Hello, I bought a new device and attempted to use ngrok on it. When I ran it, it kept displaying 'reconnecting' with some sentences along the lines of:
```
(dial tcp: lookup tunnel.us.ngrok.com on [::1]:53: read udp [::1]:42545->[::1]:53: read: connection refused)

(Get https://dns.google.com/resolve?cd=true&name=tunnel.us.ngrok.com&type=AAAA: dial tcp: lookup dns.google.com on [::1]:53: read udp [::1]:41290->[::1]:53: read: connection refused)

(Get https://s3.amazonaws.com/dns.ngrok.com/tunnel.json: dial tcp: lookup s3.amazonaws.com on [::1]:53: read udp [::1]:47310->[::1]:53: read: connection refused)

(resolved tunnel.us.ngrok.com has no records)
```
I sshed into my old device and it worked fine there so this must be my new device's problem.

Also, using the SSH method for ngrok returns:
```
Connection to tunnel.us.ngrok.com closed by remote host.
```

**Comment by andrewmbenton** [comment]
We may be able to investigate this with you if you email us at support@ngrok.com.

At first glance this looks like DNS queries from your new device are failing, so I would start by ensuring that your device has a network connection and can reach the internet, and confirm that traffic over port 53 is allowed.
