### ISSUE TITLE
ngrok

### ISSUE THREAD

**Issue by mudy47** [inconshreveable/ngrok#736]
they r saying this site cant be reached please help me very soon appreciate it
![Screenshot_2021-02-10-03-01-30](https://user-images.githubusercontent.com/67243311/107449501-57396d80-6b4c-11eb-9ed5-298b06436f36.png)
![Screenshot_2021-02-10-03-02-11](https://user-images.githubusercontent.com/67243311/107449536-67e9e380-6b4c-11eb-93df-1c450c770e9a.png)

**Comment by dexingadm** [comment]
Try https://6fce0b3b650d.ngrok.io
or maybe your 8080 port has already been occupied.

**Comment by mudy47** [comment]
its not connecting at all

**Comment by mudy47** [comment]
okay fuck u
