### ISSUE TITLE
Totally new to this, the forwarding URL fails to load?

### ISSUE THREAD

**Issue by matelot** [inconshreveable/ngrok#738]
I have a camera via an ESP32-CAM unit connected into my local server. It shows fine when I go to 192.168.0.26.
Looking through the paperwork for ngrok I assume that means it is on http 80.
I have loaded ngrok on my machine and opened it with    ngrok http 80.
It gives me a different forwarding address each time I open it as I have read that it should.
I am sure a few days ago when I first tried to do this I entered the forwarding URL shown on my
 screen into my explorer and it showed a similar page to the one I have on 192.168.0.26  (via http 80?)
Similar because the controls were there but the video picture wasn't?
Now all I get if I try to open the forwarding URL is 

This abd057a64612.ngrok.io page can’t be found
No web page was found for the web address: http://abd057a64612.ngrok.io/

Can anyone tell me what I am doing wrong?

**Comment by caseysoftware** [comment]
I hope this issue is long solved but if it's not, join us in Slack to share details and let's figure it out: http://ngrok.com/slack
