### ISSUE TITLE
UDP Support?

### ISSUE THREAD

**Issue by JohnB17** [inconshreveable/ngrok#740]
Can you please add support for UDP? Or at least special support for Minecraft Bedrock?

**Comment by spiderlord202** [comment]
I agree.

**Comment by p0t4t0sandwich** [comment]
Not sure we'll get UDP support, look at #26. Currently looking for a UDP alternative, but there's nothing else quite like ngrok

**Comment by goldman7911** [comment]
Trying to implemente a SNMP system thats needs UDP through NAT. Any suggestions ?

**Comment by ShiftyTR** [comment]
Try [https:](https://localtonet.com)

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Continued in https://github.com/ngrok/ngrok/issues/4
