### ISSUE TITLE
Failed to bind to port

### ISSUE THREAD

**Issue by SpiderUnderUrBed** [inconshreveable/ngrok#741]
I am hosting my server on is something.hosts free service with 2gs of RAM and node.js already installed. The reason I started using ngrok is because a person there affiliated with something.host said "You can host minecraft server in your free service but you can't connect minecraft server over internet. Or ... Connect locally? [Port 2000 only works for http] You can try tcp port forwarding thing. Ex. Ngrok, portmap, etc." so I tried using this. I asked the same thing in the npm ngrok package but I thought asking here would help speed up the process.

region: au
protocal: tcp

I get this whenever I try to join:
<h5>t=2021-02-27T06:04:26+0000 lvl=info msg="join connections" obj=join id=76a91e1e6afb l=127.0.0.1:25565 r=27.252.93.206:57275</h6>
I also got this log:

<h5>[06:47:11] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD' [06:47:16] [main/WARN]: Ambiguity between arguments [teleport, destination] and [teleport, targets] with inputs: [Player, 0123, @e, dd12be42-52a9-4a91-a8a1-11c01849e498] [06:47:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, destination] with inputs: [0.1 -0.5 .9, 0 0 0] [06:47:16] [main/WARN]: Ambiguity between arguments [teleport, location] and [teleport, targets] with inputs: [0.1 -0.5 .9, 0 0 0] [06:47:16] [main/WARN]: Ambiguity between arguments [teleport, targets] and [teleport, destination] with inputs: [Player, 0123, dd12be42-52a9-4a91-a8a1-11c01849e498] [06:47:16] [main/WARN]: Ambiguity between arguments [teleport, targets, location] and [teleport, targets, destination] with inputs: [0.1 -0.5 .9, 0 0 0] [06:47:16] [main/INFO]: Reloading ResourceManager: Default</h5>
and sometimes if I try joining twice I also get this:
<h5>
[07:30:02] [Server thread/WARN]: **** FAILED TO BIND TO PORT! [07:30:02] [Server thread/WARN]: The exception was: io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use [07:30:02] [Server thread/WARN]: Perhaps a server is already running on that port? [07:30:02] [Server thread/INFO]: Stopping server [07:30:02] [Server thread/INFO]: Saving worlds [07:30:02] [Server thread/ERROR]: Exception stopping the server java.lang.NullPointerException: null at net.minecraft.server.MinecraftServer.a(SourceFile:572) ~[Server.jar:?] at net.minecraft.server.MinecraftServer.t(SourceFile:599) ~[Server.jar:?] at zg.t(SourceFile:567) ~[Server.jar:?] at net.minecraft.server.MinecraftServer.w(SourceFile:707) ~[Server.jar:?] at net.minecraft.server.MinecraftServer.a(SourceFile:257) ~[Server.jar:?] at java.lang.Thread.run(Unknown Source) [?:?]</h5>
Port:45308
to create a webserver on the port is used express (a node package)

<b>server.properties:</b>
<h5>

#Minecraft server properties
#Sat Feb 27 18:51:09 UTC 2021 
enable-jmx-monitoring=false
rcon.port=45308
level-seed=
gamemode=survival
enable-command-block=false
enable-query=false
generator-settings=
level-name=world
motd=A Minecraft Server
query.port=45308
pvp=true
generate-structures=true
difficulty=easy
network-compression-threshold=256
max-tick-time=60000
use-native-transport=true
max-players=20
online-mode=false
enable-status=true
allow-flight=false
broadcast-rcon-to-ops=true
view-distance=10
max-build-height=256
server-ip=
allow-nether=true
server-port=45308
enable-rcon=true
sync-chunk-writes=true
op-permission-level=4
prevent-proxy-connections=false
resource-pack=
entity-broadcast-range-percentage=100
rcon.password=
player-idle-timeout=0
force-gamemode=false
rate-limit=0
hardcore=false
white-list=false
broadcast-console-to-ops=true
spawn-npcs=true
spawn-animals=true
snooper-enabled=true
function-permission-level=2
level-type=default
text-filtering-config=
spawn-monsters=true
enforce-whitelist=false
resource-pack-sha1=
spawn-protection=16
max-world-size=29999984
</h5>
<h5></h5>
If you do not have an answer I would appreciate it if you could give me troubleshooting advice.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
