### ISSUE TITLE
issue in npm run tunnel 

### ISSUE THREAD

**Issue by abhi19911225** [inconshreveable/ngrok#745]
>jsonserver@1.0.0 tunnel c:/Users/PC1/Desktop/jsonserver

>ngrok http 3000
![npm run tunnel](https://user-images.githubusercontent.com/77739801/111058318-d4d9fb80-84b3-11eb-82d5-3b2fc5dc2bb3.png)

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
