### ISSUE TITLE
Tunnel not found/ Error 502

### ISSUE THREAD

**Issue by jebz69** [inconshreveable/ngrok#746]
I have been blowing my mind over this. When using something such as Zphisher or Blackphish, the link that is provided leads to a page that reads "tunnel not found"
When going through terminal and trying both ./ngrok http 80 and ./ngrok http 8080, both ngrok links provided lead to a page that reads "failed to complete tunnel connection , error 502"
I've reset my router, updated my Linux distro, and have even tried uninstalling and reinstalling ngrok. I can't find a solution to this issue. Can someone help me out please?

**Comment by SakthiMahendran** [comment]
I am also getting the same issues did you fixed it ?

> I have been blowing my mind over this. When using something such as Zphisher or Blackphish, the link that is provided leads to a page that reads "tunnel not found" When going through terminal and trying both ./ngrok http 80 and ./ngrok http 8080, both ngrok links provided lead to a page that reads "failed to complete tunnel connection , error 502" I've reset my router, updated my Linux distro, and have even tried uninstalling and reinstalling ngrok. I can't find a solution to this issue. Can someone help me out please?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
@jebz69 @SakthiMahendran using ngrok with those tools is a violation of our terms of service and your account will be automatically suspended.
