### ISSUE TITLE
Redirect domain to ngrok tunnel

### ISSUE THREAD

**Issue by Sapu98** [inconshreveable/ngrok#748]
I've tried to redirect a domain of mine to a ngrok tunnel with CNAMES and A records, none works: CNAMES says it's unable to find tunnel and A can't work because it seems to be impossible to get ngrok tunnel's numerical ip.

Do you know if is it possible to do this:
myDomain.com -> http://whaterver.eu.ngrok.io/ -> my website
instead of this?:
http://whatever.eu.ngrok.io/ -> my website

It doesnt matter if ngrok's url changes, all I need is to be able to redirect my domain to it.

**Comment by grishinrv** [comment]
Have you tried to configure local domain alias on the host from which you need to access your website ?
For testing purposes (one of the mostly use cases of ngrok) it could resolve the problem

**Comment by caseysoftware** [comment]
Yes, it's possible via both a CNAME or a redirect on your domain (think: javascript or similar). Here's a setup guide:

https://ngrok.com/docs/guides/how-to-set-up-a-custom-domain

This is not available in the Free plan, only Pro or Enterprise.

Also, this issue queue is no longer monitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
