### ISSUE TITLE
Tunnel xxx.ngrok.io not found

### ISSUE THREAD

**Issue by cocxtrash** [inconshreveable/ngrok#749]
### Steps to reproduce

1. Start tunnel (ngrok http 5000)
2. Open the url in **tor** browser (for vpn) or from any device that **not** connected to your wifi.

### Expected behavior
It should simply work. (The connection to https://xxx.ngrok.io was successfully....).

### Actual behavior
It doesn't work. (Tunnel xxx.ngrok.io not found).
It works on normal browser and also on phone if the phone is connected to my wifi.

### Configuration
**Operating System:**
Microsoft Windows [Version 10.0.19042.572]

**Version of ngrok:**
Version 2.3.38 

![ngrok_problem](https://user-images.githubusercontent.com/76768193/113665188-dd96a980-96ce-11eb-8fef-5f05de6c0f51.PNG)

**Comment by cocxtrash** [comment]
**Problem Solved.**

![123](https://user-images.githubusercontent.com/76768193/113816105-1ea5c100-9796-11eb-9824-546f4c2cbfc4.PNG)

This option was unchecked.

**Comment by curseblood123** [comment]
![shit](https://user-images.githubusercontent.com/81659528/123552511-e22fa300-d78f-11eb-8197-9b4aeea01134.PNG)


help here someone else cannot see my phishing local host ??only i can see that but why tho????????????any one

**Comment by YissXD** [comment]
> ![shit](https://user-images.githubusercontent.com/81659528/123552511-e22fa300-d78f-11eb-8197-9b4aeea01134.PNG)
> 
> help here someone else cannot see my phishing local host ??only i can see that but why tho????????????any one

I have the same problem, did you find a solution?

**Comment by curseblood123** [comment]
> > ![shit](https://user-images.githubusercontent.com/81659528/123552511-e22fa300-d78f-11eb-8197-9b4aeea01134.PNG)
> > help here someone else cannot see my phishing local host ??only i can see that but why tho????????????any one
> 
> I have the same problem, did you find a solution?

It’s happening cuz ngrok blocked your ip

**Comment by YissXD** [comment]
but on my pc it works

**Comment by YissXD** [comment]
in the VM

**Comment by YissXD** [comment]
and on other smartphones not connected to my IP it doesn't work too

**Comment by curseblood123** [comment]
its only showing on your pc or in your phone  its cuz you are on the same
router they've blocked you because you've sent multiple phishing links to
ppl

**Comment by YissXD** [comment]
ah okay

**Comment by curseblood123** [comment]
Am Working on it I’ll let you know if I find anything:))

**Comment by Daysuke-kun** [comment]
Tengo un problema desde termux
Ngrok.io not found y no puedo realizar mis phishing alguien me ayuda???
