### ISSUE TITLE
Tunnel 46bccc065b01.ngrok.io not found

### ISSUE THREAD

**Issue by AnonymusNETER** [inconshreveable/ngrok#751]
Hello,
I installed zphisher and tried a phishing attack on my friend (with his permission, of course). However, the error message named in the title is displayed to him. Could someone help me?

![1](https://user-images.githubusercontent.com/82417598/114466400-bcf7b380-9be8-11eb-9c10-e6d7f2b63ea1.PNG)
![Unbenannt](https://user-images.githubusercontent.com/82417598/114466401-bd904a00-9be8-11eb-8e9b-de986f451b31.PNG)

**Comment by Esteban26** [comment]
have you solved this error? I'm facing the same issue right now and seems to be failing intermittently

**Comment by Eden4897** [comment]
Same here, tried hosting on 3 different machines, and still resulted in a Tunnel not found.
