### ISSUE TITLE
Tunnel not found error

### ISSUE THREAD

**Issue by Eden4897** [inconshreveable/ngrok#752]
Is ngrok down or something? I've tried hosting ngrok urls on 3 machines and all 3 urls read "Tunnel something.ngrok.io not found"

**Comment by Nightmare99** [comment]
Similar problem here, I can access my server through something.ngrok.io only on LAN. Getting "Tunnel something.ngrok.io not found" on devices not connected to LAN.

**Comment by caseysoftware** [comment]
Visit https://status.ngrok.com/ to check the status at any time.

Further, this issue queue is no longer monitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
