### ISSUE TITLE
ngrok start -all no longer working

### ISSUE THREAD

**Issue by josemolina001** [inconshreveable/ngrok#757]
I recently updated my ngrok app. After the update, starting ngrok from a file no longer works without errors. My file contents are;
authtoken: "my_token"

tunnels:
    identity:
       addr: 58434
       proto: http
       host_header: localhost:58434
       bind_tls: true
   portalapi:
       addr: 49700
       proto: http
       host_header: localhost:49700
       bind_tls: true
   manageidentity:
       addr: 44319
       proto: http
       host_header: localhost:44319
       bind_tls: true
   registration:
       addr: 64157
       proto: http
       host_header: localhost:64157
       bind_tls: true

I'm getting 502 errors and invalid hostname. Any ideas?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
