### ISSUE TITLE
Update failed

### ISSUE THREAD

**Issue by LiliWii2004** [inconshreveable/ngrok#758]
Hello, ngrok so far very good, I only have the disadvantage that it does not want to update me, I get this error:
root  ~  ngrok update
Update available! Updating to version 2.3.40. . .
Update failed: open /snap/ngrok/32/.ngrok.new: read-only file system
Your guidance would be very helpful

**Comment by mixa2130** [comment]
You have to reinstall it from official [ngrok website](https://ngrok.com/download)
