### ISSUE TITLE
Offer health-monitoring endpoint

### ISSUE THREAD

**Issue by davidkarlsen** [inconshreveable/ngrok#759]
We run ngrok in a container (`/usr/local/bin/ngrok http --region=eu ....`).
We noticed that it started malfunctioning at a point, and had to restart it to make the tunnel healthy again.
It would be useful if ngrok could expose a health-monitoring endpoint, so that we can probe this from Kubernetes and automate restarts.

A simple http endpoint `/healthz` (possibly on a dedicated port - to avoid clashes with the vanilla tunnel) would be preferable.

**Comment by caseysoftware** [comment]
Our Agent API may be a good option for this already - https://ngrok.com/docs/ngrok-agent/api

Also, this issue queue is no longer monitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
