### ISSUE TITLE
It seems that ngrok does not support UTF-8 coding yet

### ISSUE THREAD

**Issue by uname** [inconshreveable/ngrok#76]
panic: json: invalid UTF-8 in string: "GET /\xb7\xbf\xd7\xd3.txt"

goroutine 99 [running]:
ngrok/util.MakePanicTrace(0x651840, 0x12909db0, 0x12909db0, 0x0)
    /home/travis/build/inconshreveable/ngrok/src/ngrok/util/errors.go:19 +0x75
ngrok/client/views/web.func·004()
    /home/travis/build/inconshreveable/ngrok/src/ngrok/client/views/web/http.go:238 +0x50
ngrok/client/views/web.func·005(0x12822880, 0x128a6540, 0x1288ecb0)
    /home/travis/build/inconshreveable/ngrok/src/ngrok/client/views/web/http.go:258 +0x24b
net/http.HandlerFunc.ServeHTTP(0x1280b050, 0x12822880, 0x128a6540, 0x1288ecb0)
    /home/travis/.gvm/gos/go1.1.1/src/pkg/net/http/server.go:1149 +0x3b
net/http.(_ServeMux).ServeHTTP(0x1276bba0, 0x12822880, 0x128a6540, 0x1288ecb0)
    /home/travis/.gvm/gos/go1.1.1/src/pkg/net/http/server.go:1416 +0xdc
net/http.serverHandler.ServeHTTP(0x127d1fc0, 0x12822880, 0x128a6540, 0x1288ecb0)
    /home/travis/.gvm/gos/go1.1.1/src/pkg/net/http/server.go:1517 +0x120
net/http.(_conn).serve(0x128990f0)
    /home/travis/.gvm/gos/go1.1.1/src/pkg/net/http/server.go:1096 +0x652
created by net/http.(*Server).Serve
    /home/travis/.gvm/gos/go1.1.1/src/pkg/net/http/server.go:1564 +0x241

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
