### ISSUE TITLE
Ngrok login should sanitize the email value

### ISSUE THREAD

**Issue by mayeaux** [inconshreveable/ngrok#763]
I was trying to login here: https://dashboard.ngrok.com/login

But the email I was using had a leading space, so the password wasn't working but I couldn't tell what was going on.

Maybe the devs want to look at that? Sanitize automatically perhaps? Thanks

**Comment by caseysoftware** [comment]
Thanks for this. We've done quite a bit since then and have more sanitization/filtering coming.

Also, this issue queue is no longer monitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
