### ISSUE TITLE
Ngrok site loads forever

### ISSUE THREAD

**Issue by Siddzej** [inconshreveable/ngrok#764]
Hi, im totally new to ngrok, but when i try to sign up and click "Get Started" on ngrok.com it's just loading forever.

**Comment by Soufyanhl** [comment]
Where i can use the authoken for ngrok

**Comment by caseysoftware** [comment]
https://dashboard.ngrok.com/get-started/setup

This queue is unmonitored. Please visit http://ngrok.com/slack for our Community Slack
