### ISSUE TITLE
Failed to read message: remote error: tls: bad certificate

### ISSUE THREAD

**Issue by q396921921** [inconshreveable/ngrok#765]
![image](https://user-images.githubusercontent.com/37297228/121630713-42e08f80-cab0-11eb-8c53-aa17d11e4440.png)

My domain name is the same as server_addr and NGROK_DOMAIN that generated key and CRT files, but I still report this error

**Comment by chenyuantao** [comment]
the same here.

**Comment by twelife** [comment]
it's solved?

**Comment by zwfan2012** [comment]
I had this problem with go1.17, but had no problem with go1.14.7.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
