### ISSUE TITLE
Problems with logging

### ISSUE THREAD

**Issue by chupocro** [inconshreveable/ngrok#766]
When logging is configured as:

```
log_level: debug
log_format: logfmt
log: /var/log/ngrok.log
```

There is the error:

```
./ngrok start --all

ERROR:  Failed to configure logging: Failed to open log file '/var/log/ngrok.log': open /var/log/ngrok.log: permission denied
ERROR:
```

`sudo ./ngrok start --all` **does not start ngrok**, it just lists the help.

When logging is configured as:

```
log_level: debug
log_format: logfmt
log: ~/ngrok.log
```

the error is:

```
./ngrok start --all

ERROR:  Failed to configure logging: Failed to open log file '~/ngrok.log': open ~/ngrok.log: no such file or directory
ERROR:
```

This works:

```
log_level: debug
log_format: logfmt
log: /home/username/ngrok.log
```

**Why the other options don't work and why ngrok can't be started with `sudo`?**

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
