### ISSUE TITLE
UDP Support for ngrok

### ISSUE THREAD

**Issue by 10542hsrif** [inconshreveable/ngrok#770]
@inconshreveable Hello! I'm hosting a Minecraft Server. I am grateful on you that you made this program, but your app don't work on Java/Bedrock crossplay. It just work on Java. I used GeyserMC plugin, but it won't work. I asked in the YouTube communisty and they said that ngrok don't support UDP protocol that GeyserMC needs in order to run itself successfully. Hope you can help me in this issue. What should I do to enable UDP support for ngrok?

**Comment by loriopatrick** [comment]
Ngrok doesn't support UDP. Use [playit.gg](https://playit.gg). https://github.com/playit-cloud/playit-agent

**Comment by russorat** [comment]
Continued in https://github.com/ngrok/ngrok/issues/4
