### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by mehdikhody** [inconshreveable/ngrok#772]
Hi, I use Ngrok to expose `http://localhost:3000` and It work but when I try to reach the url This happen.

<img width="598" alt="2021-08-07 (2)" src="https://user-images.githubusercontent.com/22590626/128595426-4c49d21e-9e5c-4f56-9365-c724edf9781f.png">

<img width="865" alt="2021-08-07 (3)" src="https://user-images.githubusercontent.com/22590626/128595521-85d26f6a-fe1d-4a9a-833b-4737016b192a.png">

**Comment by caseysoftware** [comment]
These issues are unmonitored.

For status updates, visit https://status.ngrok.com/

For community/discussion, visit: http://ngrok.com/slack

**Comment by andrewbunac** [comment]
Hi is this issue still exist? I just tried ngrok now,  command execution seems ok, but when I try to access the public URL  there result is "This Site can't be reached

**Comment by jadurani** [comment]
> Hi is this issue still exist? I just tried ngrok now, command execution seems ok, but when I try to access the public URL there result is "This Site can't be reached

I have the same problem.

My environment:
- Node v18.15.0
- NPM 9.5.0
- Mac; Apple Silicon M2

**Comment by caseysoftware** [comment]
Check out our Slack channel (linked above) for support

**Comment by vrkansagara** [comment]
I confirm this issue still exists, so @caseysoftware, instead of forwarding to the slack channel, let's put the solution here to help others.

and this issue need to re-open

**Comment by oscar-dias** [comment]
Same problem here, it only works with my phone's internet, when I switch to my cable internet it just can't be reached, I try to change the dns but the problem still persists.
I think this is something about my provider, but I can't say for sure.

**Comment by baltasaurusrex** [comment]
any update on this? having the same problem as oscar-dias

**Comment by Joao-Pimenta** [comment]
Same issue here
@baltasaurusrex @oscar-dias did you find a solution?

**Comment by russorat** [comment]
Thank you for replying to this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
