### ISSUE TITLE
WebSocket traffic

### ISSUE THREAD

**Issue by inter-jakyb** [inconshreveable/ngrok#773]
Are there issues with websocket traffic?

```
GET /session HTTP/1.1
Sec-WebSocket-Version: 13
Sec-WebSocket-Key: 2PUwsnu7INXXWDDzjfd/Ow==
Connection: Upgrade
Upgrade: websocket
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits
Host: 9224458b3778.ngrok.io

HTTP/1.1 503 Service Unavailable
Connection: close
Content-Type: text/plain
Date: Wed, 18 Aug 2021 11:41:06 GMT
Content-Length: 79

ngrok gateway error
The server returned an invalid or incomplete HTTP response.
```

**Comment by Ni55aN** [comment]
Same. A simple Node.js server based on [websockets/ws](https://github.com/websockets/ws) doesn't work

I have tried [localtunnel](https://github.com/localtunnel/localtunnel) and it works fine

**Comment by mahesh548** [comment]
Hey did you figure out how use Web sockets with ngrok??

**Comment by Ni55aN** [comment]
@mahesh548 I have replaced ngrok with localtunnel

**Comment by mahesh548** [comment]
Is this also work for wss or only ws?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
