### ISSUE TITLE
Ngrok says that I already have an active portforward but I have closed it. Started after a script installed ngrok too. double install I think.

### ISSUE THREAD

**Issue by ghost** [inconshreveable/ngrok#777]
./ngrok http 4444                                                                                                                                              1 ⨯
Your account 'Alexander' is limited to 1 simultaneous ngrok client session.
Active ngrok client sessions in region 'us':
  - ts_1xOhhYBOmgclE7KSt6Xxxxxxxxx4eefe4r34wrefdsf3wr323Id8DeWK (xxxxxxxxxx)

ERR_NGROK_108

**Comment by ajgamer** [comment]
I replaced my token and ip with random characters

**Comment by Blackdragan45** [comment]
Please tell me this problem solution

**Comment by ProtDos** [comment]
Did you try finding and killing the old process? Maybe it's loading in the background.

**Comment by SecretRecipe** [comment]
> Did you try finding and killing the old process? Maybe it's loading in the background.

I had this problem a few times. His issue is likely the same.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
