### ISSUE TITLE
Ngrok link not published

### ISSUE THREAD

**Issue by hunxjunedo** [inconshreveable/ngrok#779]
Hi, I used a tool named zphihser which uses Ngrok, first of all, it created the URL but it contains my IP in the URL, and secondly the URL only appears to be fine until my side, but when I use a VPN or something and then open it, it shows Ngrok tunnel not found, please help!

**Comment by caseysoftware** [comment]
Don't use ngrok to hack, phish, or commit other crimes. We don't care if you're "experimenting"
