### ISSUE TITLE
Link that generated only works on my LAN

### ISSUE THREAD

**Issue by Katkee29** [inconshreveable/ngrok#783]
If i try to connect to the link that was generated ( port 80 ) it says tunnel not found. I tried dual boot kali linux, its still the same issuse? Any fix or thoughts on this?

**Comment by Gargen** [comment]
Same problem, may I ask, did you manage to do something about it?

**Comment by Jacobsentertainment** [comment]
Same issue on my side here!
I tried an complete fresh install of OS and ngrok, even with a new/other key no success! it works local but remotely it won't work. It results in error 3200. Tested on two mobile devices with two divergent providers (Dutch and a German provider) so I can rule out that it's not the ISP that blocks the connection.

**Comment by sroma12** [comment]
Same Problem here, It's really pissed me off as I paid $60 bucks for the Premium version

**Comment by caseysoftware** [comment]
We disabled Kali support due to the large number of malicious users. If you have a legitimate use case, please contact Support. We do not allow "ethical hacking"
