### ISSUE TITLE
Ngrok bad adress

### ISSUE THREAD

**Issue by Chandan96100** [inconshreveable/ngrok#785]
~ $ chmod 777 ngrok
~ $ ./ngrok authtoken 1y54WLRLCTMPKDTr78sPD3ans2e_5yJzdAP3Y48bXhRcMaDZj
bash: ./ngrok: Bad address
~ $

**Comment by aksbyte** [comment]
/\
     /  \   _ __   ___  _ __  _   _ _ __ ___   ___  _   _ ___
    / /\ \ | '_ \ / _ \| '_ \| | | | '_ ` _ \ / _ \| | | / __|
   / ____ \| | | | (_) | | | | |_| | | | | | | (_) | |_| \__ \
  /_/    \_\_| |_|\___/|_| |_|\__, |_| |_| |_|\___/ \__,_|___/
                               __/ |
                              |___/


Work for me just try to $ apt upgrade 

~ $ ./ngrok
WARN[02-18|11:31:46] failed to get home directory, using $HOME instead err="user: Current requires cgo or $USER set in environment" $HOME=/data/data/com.termux/files/home
NAME:
   ngrok - tunnel local ports to public URLs and inspect traffic

DESCRIPTION:
    ngrok exposes local networked services behinds NATs and firewalls to the
    public internet over a secure tunnel. Share local websites, build/test
    webhook consumers and self-host personal services.
    Detailed help for each command is available with 'ngrok help <command>'.
    Open http://localhost:4040 for ngrok's web interface to inspect traffic.

EXAMPLES:
    ngrok http 80                    # secure public URL for port 80 web server
    ngrok http -subdomain=baz 8080   # port 8080 available at baz.ngrok.io
    ngrok http foo.dev:80            # tunnel to host:port instead of localhost
    ngrok http https://localhost     # expose a local https server
    ngrok tcp 22                     # tunnel arbitrary TCP traffic to port 22
    ngrok tls -hostname=foo.com 443  # TLS traffic for foo.com to port 443
    ngrok start foo bar baz          # start tunnels from the configuration file

VERSION:
   2.3.40

AUTHOR:
  inconshreveable - <alan@ngrok.com>

COMMANDS:
   authtoken    save authtoken to configuration file
   credits      prints author and licensing information
   http         start an HTTP tunnel
   start        start tunnels by name from the configuration file
   tcp          start a TCP tunnel
   tls          start a TLS tunnel
   update       update ngrok to the latest version
   version      print the version string
   help         Shows a list of commands or help for one command
~ $ ./ngrok authtoken 24UVsbIY6abKfmKhtiRSDKUiQCN_83my***********
WARN[02-18|11:32:47] failed to get home directory, using $HOME instead err="user: Current requires cgo or $USER set in environment" $HOME=/data/data/com.termux/files/home
Authtoken saved to configuration file: /data/data/com.termux/files/home/.ngrok2/ngrok.yml
~ $

**Comment by HEZRON1337** [comment]
bash: ./ngrok: Bad address
How do I fix it

**Comment by caseysoftware** [comment]
This issue queue is no longer monitored. For ongoing support, check out our Slack community at http://ngrok.com/slack

**Comment by Danyalkk** [comment]
Please solve my problem of the bad address

**Comment by Shriram090** [comment]
Solve bad address
