### ISSUE TITLE
Self-hosted ngrok?

### ISSUE THREAD

**Issue by prologic** [inconshreveable/ngrok#786]
Hi,

Given that nrok itself is open source are there any docs on deploying ngrok the service yourself?

The closest issue If could was #154 but it doesn't really cover docs, I can only find end-user docs on teh website.

cheers
James

**Comment by prologic** [comment]
@caseysoftware Mind elaborating a bit on "not planned"?

**Comment by caseysoftware** [comment]
This is an unmaintained repository and there won't be any further development on it.

**Comment by prologic** [comment]
> This is an unmaintained repository and there won't be any further development on it.

So the community is free to fork this project under the terms of the Apache v2 license?

**Comment by caseysoftware** [comment]
The Apache 2 license lets you do quite a bit.

I'd recommend consulting their FAQ for specifics - https://www.apache.org/foundation/license-faq.html
