### ISSUE TITLE
ngrok does not work outside the local network

### ISSUE THREAD

**Issue by Gargen** [inconshreveable/ngrok#788]
I faced such a problem that the ngrok does not work on devices that are not in my network environment. Shows me an error:

Tunnel ........ngrok.io not found

Can you help me with this problem?

**Comment by K1nd3L** [comment]
> Same here.
> 
> Ngrok is working when devices are in the same network (Wi-Fi), but I can't access from 4G, for example.

when u using ngrok in mobile phone u must aktivate mobile hostspot. trust me, it works

**Comment by Gargen** [comment]
> когда вы используете ngrok в мобильном телефоне, вы должны активировать мобильный hostspot. поверь мне это работает

could you help me, how to do it?

**Comment by K1nd3L** [comment]
> > когда вы используете ngrok в мобильном телефоне, вы должны активировать мобильный hostspot. поверь мне это работает
> 
> could you help me, how to do it? I'm just a beginner and I'm 14 years old, so there are difficulties in mastering. I need a seeker and a nexfisher for pentesting outside of my network, but at a great distance.

ur using ngrok in termux?

**Comment by sroma12** [comment]
What the hell is going on with the support team?! Straight up just ignore the clients?

**Comment by Gargen** [comment]
> > > когда вы используете ngrok в телефоне, вы должны активировать мобильный hostspot. поверь мне это работает
> > 
> > 
> > не могли бы вы мне помочь, как это сделать? Я только новичок, мне 14 лет, поэтому есть трудности с освоением. Мне нужен искатель и нексфишер для пентестинга вне моей сети, но на большом расстоянии.
> 
> вы используете ngrok в termux?

Yes, I am using termux in. Sorry, a lot of workload and therefore did not go to Github.

**Comment by czonta96** [comment]
All the support says is something like "show us a screenshot of the webapplication you're are trying to serve with a related description of what it does etc." even if you forward them what they are asking for you don't get replied back, and I don't know why they are behaviouring like this, I'm even on business plan and I have same issue here.

**Comment by JasonMarcos** [comment]
> Tudo o que o suporte diz é algo como "mostre-nos uma captura de tela da webapplicação que você está tentando servir com uma descrição relacionada do que ele faz etc." mesmo se você encaminhá-los o que eles estão pedindo você não é respondido de volta, e eu não sei por que eles estão se comportamentos assim, eu estou mesmo no plano de negócios e eu tenho o mesmo problema aqui.



> Tudo o que o suporte diz é algo como "mostre-nos uma captura de tela da webapplicação que você está tentando servir com uma descrição relacionada do que ele faz etc." mesmo se você encaminhá-los o que eles estão pedindo você não é respondido de volta, e eu não sei por que eles estão se comportamentos assim, eu estou mesmo no plano de negócios e eu tenho o mesmo problema aqui.

do they respond fast? I just emailed them the error prints at support@ngrok.com
