### ISSUE TITLE
Can ngrok urls be used to configure SMTP/Email servers

### ISSUE THREAD

**Issue by infinitronic** [inconshreveable/ngrok#794]
Can ngrok urls work performantly on very busy SMTP/Email servers - as the domain name for the server

**Comment by caseysoftware** [comment]
Likely you can with the paid plan where you have a continuous connection with a static domain.

These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack

**Comment by russorat** [comment]
Yes, ngrok can. Here's a small docs page to explain how to get the basics started: https://ngrok.com/docs/using-ngrok-with/smtp/
