### ISSUE TITLE
ngrok down? internal server error (ERR_NGROK_802) all regions

### ISSUE THREAD

**Issue by croverindustries** [inconshreveable/ngrok#798]

**Comment by croverindustries** [comment]
![image](https://user-images.githubusercontent.com/74108205/139581137-3dde7055-bb15-420e-8399-57e282ff09e3.png)

**Comment by injarapuveerabrahmendra** [comment]
how to solve this problem

**Comment by caseysoftware** [comment]
These issues are unmonitored.

For status updates, visit https://status.ngrok.com/

For community/discussion, visit: http://ngrok.com/slack
