### ISSUE TITLE
ip address

### ISSUE THREAD

**Issue by unknownPerson115** [inconshreveable/ngrok#800]
when hosting an ngrok http tunnel without a domain after the tunnel id for example http://bbbb-000-000-000-000.ngrok.io 0 represents the IP
is there a way to host without displaying the IP address of where the tunnel is hosted?

**Comment by caseysoftware** [comment]
Free accounts include the IP address to mitigate bad actors. To remove it, upgrade to a paid plan.

Further, this issue queue is no longer monitored. For ongoing support, check out our Slack community at http://ngrok.com/slack
