### ISSUE TITLE
For me, it doesn't work (internal server error 802) when I specify -host-header option like:

### ISSUE THREAD

**Issue by Bwiiza** [inconshreveable/ngrok#801]
same here
can't work with -host-header
 changing region too can't work

**Comment by magsto** [comment]
Same error here:
`ngrok http 7071 --host-header rewrite` gives:

> internal server error
> 
> ERR_NGROK_802

Have tried with all regions (eu, jp etc) `--region eu`

**Comment by johnnyboldt** [comment]
Same here.

**Comment by magsto** [comment]
> Same error here: `ngrok http 7071 --host-header rewrite` gives:
> 
> > internal server error
> > ERR_NGROK_802
> 
> Have tried with all regions (eu, jp etc) `--region eu`

I solved it by signing in and get my auth token. Then run `ngrok authtoken <my token>`.
After that everything worked again.

**Comment by caseysoftware** [comment]
These issues are unmonitored.

For status updates, visit https://status.ngrok.com/

For community/discussion, visit: http://ngrok.com/slack
