### ISSUE TITLE
ERR_NGROK_802 if host-header set

### ISSUE THREAD

**Issue by jekru** [inconshreveable/ngrok#802]
```ngrok.exe http 4200``` is working fine. But if I set ```host-header``` to ```localhost:4200```, **ERR_NGROK_802 (internal server error)** occurs.

```bash
ngrok.exe http 4200 -host-header="localhost:4200"
```

I also tried with a different region, same error. This is weird because some days ago, everything worked without a problem.

**Comment by zachbugay** [comment]
I am getting the exact same issue right now as well. Here's the command I am running `ngrok http -host-header=localhost 7071`

**Comment by johnnyboldt** [comment]
releated to https://github.com/inconshreveable/ngrok/issues/801

**Comment by magsto** [comment]
Possible solution: https://github.com/inconshreveable/ngrok/issues/801#issuecomment-963424171

**Comment by jekru** [comment]
The solution proposed from @magsto worked!

1. Go to [https://ngrok.com/](https://ngrok.com/)
2. Login with your account
3. Click on "Getting Started" -> "Your Authtoken"
4. Copy your authtoken

Execute this in your terminal:
```bash
ngrok authtoken [YOUR_AUTH_TOKEN]
```

**Comment by tedspare** [comment]
For me, the solution was running `unzip ~/.ngrok2/[ngrok-file].zip` before `ngrok authtoken [token]`
