### ISSUE TITLE
Ngrok won't display wamp localhost

### ISSUE THREAD

**Issue by oseno** [inconshreveable/ngrok#805]
Hello I'm in need of assistance, I use wamp server as my localhost and while ngrok works fine when I use xampp it doesn't display my folder contents when I use wamp server. It displays the localhost fine but once I add the path to my folder it displays a blank screen. Please help.

**Comment by Newtoxton** [comment]
That behaviour has everything to do with the port assigned on ngrok with that wamp is running on. Fix the ports and see what comes thru. Option 2 is you have a hardcoded url in your wamp site, so you might consider changing that and pointing it to the dynamic ngrok url generated. Check and see if any of those can give a better kick off
