### ISSUE TITLE
Don't buy the premium - Still waiting for almost a month for a resolution to my problem

### ISSUE THREAD

**Issue by sroma12** [inconshreveable/ngrok#806]
Paid for a 3 year license -

The tunnel worked fine before I paid for the license, after I pay for the license the tunnel stops work. "Tunnel not found" when I try to resolve it. Contacted your brilliant support team and It's been almost a month since I've heard back from anyone. 

Seriously what is the point of me wasting 60 bucks on a service that doesn't even work! More to the point what's the point of me spending money if you'll just ignore my problems!

How do I get a refund??

**Comment by caseysoftware** [comment]
My apologies. I'm sorry this was frustrating & didn't work. I hope this is long resolved and/or you got a refund. 

If you still need a hand, feel free to ping support@ngrok.com again and ask for me.
