### ISSUE TITLE
 Reconnecting (dial tcp: i/o timeout) 

### ISSUE THREAD

**Issue by alexadcritter** [inconshreveable/ngrok#810]
Hi there!

When running a command that works every time on my older mac I will sometimes get the following error: reconnecting (dial tcp: i/o timeout) .

I am working on the brand new Mac with the Apple M1 Pro chip.

I do not have a VPN running.

I have restarted a few times and restarted just my wifi. After a couple of hours of trying this it will sometimes work temporarily, but if I shut down my computer and try it again it won't work.

Any ideas?

**Comment by trm217** [comment]
Experiencing the same issue on a regular basis. Not acceptable for a payed product.

**Comment by caseysoftware** [comment]
These forums are unmonitored. For ongoing support, check out our slack channel: http://ngrok.com/slack
