### ISSUE TITLE
Pls help to solve a problem!

### ISSUE THREAD

**Issue by negras13** [inconshreveable/ngrok#816]
![Screenshot_2022-01-13-14-43-50-058_com termux](https://user-images.githubusercontent.com/97676781/149332436-e019d3d6-5dc0-4082-91ad-fc4931566902.jpg)
I can't update and upgrade termux. NOTHING help. pls 🙏 help. I have Android 11

**Comment by peterhoeg** [comment]
This is completely unrelated to ngrok. Also, screenshots of error messages (which cannot be found through search) is generally frowned upon. Use text in a `pre` tag.
