### ISSUE TITLE
http tunnel always detected Dangerous

### ISSUE THREAD

**Issue by cwz6h** [inconshreveable/ngrok#819]
So I've Started Using Ngrok But Now When I'm Making a http url It Always Detects It Dangerous When It's A Simple HTML URL

**Comment by hello-smile6** [comment]
> So I've Started Using Ngrok But Now When I'm Making a http url It Always Detects It Dangerous When It's A Simple HTML URL

Disable Microsoft Edge SmartScreen.

**Comment by hackNcode** [comment]
> > So I've Started Using Ngrok But Now When I'm Making a http url It Always Detects It Dangerous When It's A Simple HTML URL
> 
> Disable Microsoft Edge SmartScreen.

I'm On Chrome, Btw. I Figured Out The problem, It Is The Port Numbers. Is There Any Possible Way To Reset All Ports To Default? Or Delete Them?

**Comment by hello-smile6** [comment]
> > > So I've Started Using Ngrok But Now When I'm Making a http url It Always Detects It Dangerous When It's A Simple HTML URL
> > 
> > 
> > Disable Microsoft Edge SmartScreen.
> 
> I'm On Chrome, Btw. I Figured Out The problem, It Is The Port Numbers. Is There Any Possible Way To Reset All Ports To Default? Or Delete Them?

You can use HTTP instead of HTTPS, I think

**Comment by hackNcode** [comment]
> > > > So I've Started Using Ngrok But Now When I'm Making a http url It Always Detects It Dangerous When It's A Simple HTML URL
> > > 
> > > 
> > > Disable Microsoft Edge SmartScreen.
> > 
> > 
> > I'm On Chrome, Btw. I Figured Out The problem, It Is The Port Numbers. Is There Any Possible Way To Reset All Ports To Default? Or Delete Them?
> 
> You can use HTTP instead of HTTPS, I think

i've been using http so https i guess

**Comment by hackNcode** [comment]
> i've been using http so https i guess

https doesn't work

**Comment by caseysoftware** [comment]
This happened because some bad actors have been using ngrok for launching attacks. We've blocked/stopped most but there are still lingering effects. Hacking, phishing, etc - even for "educational purposes" - are not allowed via ngrok.

Also, this queue is unmonitored join our Community Slack for ongoing discussions: https://ngrok.com/slack
