### ISSUE TITLE
How can I backup the inspect db?

### ISSUE THREAD

**Issue by zalmanlew** [inconshreveable/ngrok#823]
I'd like to be able to backup the inspect DB (download for future browsing).

Is this possible? Where is the file located?

**Comment by caseysoftware** [comment]
This issue queue is unmonitored. Please visit http://ngrok.com/slack for community support & discussion.

**Comment by russorat** [comment]
Thanks! There is no way to download the local inspect DB. We just released our [Traffic Inspector](https://dashboard.ngrok.com/observability/traffic-inspector) which provides 3 days of retention but can be upgraded to 90 if you'd like to keep requests around for longer.
