### ISSUE TITLE
Anyone with free account facing "Region Blocked issue? 

### ISSUE THREAD

**Issue by TackleIt** [inconshreveable/ngrok#824]
This is what shows when i try to show something on the server. 
"Region Blocked"
"HTML content may only be served to this region after you upgrade to a paid account. "
![image](https://user-images.githubusercontent.com/68126567/153761673-bb5bdc2c-b1af-4f64-9c28-e954eaee18cb.png)

I am logged in and using authtoken, the last time i checked it was working (around 1-2 months back), so not sure if it is something they have implemented for security. 

I am sending `HTML/1.1 200 OK` 
followed by content type and a bit of for my client to read from.

Also i have tried, text/plain and application/json in content type as well, but it still shows the same screen.

Can anyone help me on what is happening? couldn't get anything on google as well

**Comment by decoherencer** [comment]
Yep. seems some countries were blocked few days back on free plan.

**Comment by NandaKishorJeripothula** [comment]
+1

**Comment by GowthamRayar** [comment]
same Issue , any update on this?

**Comment by avva555** [comment]
same Issue , any update on this?

is there any alternate to this ngrok

**Comment by quazmavaibhav** [comment]
same issue.

**Comment by edwinwilmz** [comment]
same here any alternates for ngrok?

**Comment by becauseme** [comment]
Same here any solution for it.

**Comment by mandleyaditya18** [comment]
Try localtunnel - https://github.com/localtunnel/localtunnel

**Comment by rajiv-eulogik** [comment]
Same here, and it says free forever -_-
![image](https://user-images.githubusercontent.com/50582660/153808473-4fa48024-151a-4a3d-824d-29d6e7a1bd1c.png)

**Comment by GowthamRayar** [comment]
> Try localtunnel - https://github.com/localtunnel/localtunnel

@[mandleyaditya18](https://github.com/mandleyaditya18) This gets disconnected now and then

**Comment by samiravdev** [comment]
localtunnel not working with virtual host

**Comment by sushant-awalekar** [comment]
https://github.com/anderspitman/awesome-tunneling

**Comment by Archish27** [comment]
Any fixes facing same issue :(

**Comment by ShikhaPant** [comment]
Same issue.

Any alternatives?

**Comment by madhavrathore** [comment]
Same issue facing here.
Please help with other alternative to access localhost.

**Comment by akshayF12** [comment]
Try to Connect vpn its worked for me

**Comment by tarunspartan** [comment]
+1

**Comment by madhavrathore** [comment]
@akshayF12 
vpn is working but still sometime it is giving me an tunnel error

**Comment by goutham-ally** [comment]
Same issue. Happening with the Free plan. 
Terrible idea if ngrok team is pushing users to upgrade the plan

**Comment by Ganesh9100** [comment]
Same here hope there are different methods to run the server

**Comment by kpratik84** [comment]
Same here!! I also tried localtunnel. But there is an upload size limit of 1MB which is causing problems in my app. Can anybody help me with increasing the size of an uploaded file while using localtunnel? Many thanks.

**Comment by akshayF12** [comment]
> Same here!! I also tried localtunnel. But there is an upload size limit of 1MB which is causing problems in my app. Can anybody help me with increasing the size of an uploaded file while using localtunnel? Many thanks.


try vpn ?

**Comment by kpratik84** [comment]
> > Same here!! I also tried localtunnel. But there is an upload size limit of 1MB which is causing problems in my app. Can anybody help me with increasing the size of an uploaded file while using localtunnel? Many thanks.
> 
> try vpn ?

I am using Google colab as a server for hosting my app

**Comment by avva555** [comment]
> > > Same here!! I also tried localtunnel. But there is an upload size limit of 1MB which is causing problems in my app. Can anybody help me with increasing the size of an uploaded file while using localtunnel? Many thanks.
> > 
> > 
> > try vpn ?
> 
> I am using Google colab as a server for hosting my app

do you have any link how to use Google colab i have web application with mysql backend earlier i am using ngrok now its asking payment so looking for some alternate localtunnel also not stable so please let me know about this option

**Comment by samiravdev** [comment]
Use vpn master chrome extensions with ngrok and its working for me

**Comment by kpratik84** [comment]
> > > > Same here!! I also tried localtunnel. But there is an upload size limit of 1MB which is causing problems in my app. Can anybody help me with increasing the size of an uploaded file while using localtunnel? Many thanks.
> > > 
> > > 
> > > try vpn ?
> > 
> > 
> > I am using Google colab as a server for hosting my app
> 
> do you have any link how to use Google colab i have web application with mysql backend earlier i am using ngrok now its asking payment so looking for some alternate localtunnel also not stable so please let me know about this option

Sorry, I meant I am using Colab as a development server. In order to get a public URL, I tried ngrok and localtunnel but both of them are causing issues.

**Comment by faizaankhan** [comment]
I tried all the regions I could find and it's all blocked 

```
us - United States (Ohio)
eu - Europe (Frankfurt)
ap - Asia/Pacific (Singapore)
au - Australia (Sydney)
sa - South America (Sao Paulo)
jp - Japan (Tokyo)
in - India (Mumbai)
```

**Comment by sachin-surya-soft** [comment]
Use VPN on your device from which you are hitting the URL. It's a temporary solutions though.

**Comment by decoherencer** [comment]
[Pagekite](https://pagekite.net) - one-month free trial service and works as well as ngrok. 
Atleast, until someone experiments a good solution from the alternatives.

**Comment by niketdave-codal** [comment]
Try VPN current solution is this only

**Comment by gsaranya256** [comment]
Try using Cloudflare Tunnel.. I got resolved this issue by Cloudflare.

**Comment by leenjass** [comment]
> Use vpn master chrome extensions with ngrok and its working for me

thanks that's working :)

**Comment by C3ITAnandMore** [comment]
I am also getting the same error "_**### Region Blocked \n HTML content may only be served to this region after you upgrade to a paid account**_." when accessing the ngrok URL. It was perfectly working till 11-Feb-2022 but suddenly it stopped working from 12-Feb-22. Does anyone get the reason/answer?

<img width="549" alt="ngrok - error" src="https://user-images.githubusercontent.com/60211061/153871181-b6bc89e0-9f49-4f15-98b3-ed16fdfa6d4e.png">

**Comment by RajKKapadia** [comment]
I am facing the same problem.
I am using Localtunnel
https://localtunnel.github.io/www/

**Comment by priyankagadhiya** [comment]
I am facing the same problem.

**Comment by sankaretey** [comment]
> 

Thanks a lot. its working for me. Just added the VPN master chrome extension.

**Comment by chinni070707** [comment]
Thanks. VPN Master on chrome helped

**Comment by avva555** [comment]
VPN Master on chrome no working for some browsers

**Comment by TackleIt** [comment]
so the vpn works. If the client side is using vpn then the content can be shown.  Server side doesn't matter.

Though anyone found a specific reason on why the content is blocked?

**Comment by Anjali-Maru** [comment]
VPN Master on chrome has not worked for me, any other solution for this issue?

**Comment by C3ITAnandMore** [comment]
> I am also getting the same error "_**### Region Blocked \n HTML content may only be served to this region after you upgrade to a paid account**_." when accessing the ngrok URL. It was perfectly working till 11-Feb-2022 but suddenly it stopped working from 12-Feb-22. Does anyone get the reason/answer?
> 
> <img alt="ngrok - error" width="549" src="https://user-images.githubusercontent.com/60211061/153871181-b6bc89e0-9f49-4f15-98b3-ed16fdfa6d4e.png">

-----------------------------------------------------------------------
Hey, it seems to be a ngrok issue, **_I just verified it again and it is working now_**, thank God. I spent almost a day finding alternatives for the ngrok but did not work/fit my needs.

**Comment by avva555** [comment]
ok thanks man good news

**Comment by TackleIt** [comment]
Checked, yeah it is working now. again. Nice
