### ISSUE TITLE
NGROK won't handle local DNS on M1 Apple Silicon

### ISSUE THREAD

**Issue by jbrodie** [inconshreveable/ngrok#825]
We run invoker on our machines, and when we are running ngrok with a addr specified in the ngrok.yml, it is unable to lookup that local *.test dns and get a proper response for it.

I have tested that if I download the x86 version and install it on the the machine, and run under the arch x86 it behaves as it should.

**Comment by TechnicallyGio** [comment]
Following.

**Comment by pieterclaerhout** [comment]
Same problem here when using Laravel Valet…

**Comment by vaibsharma** [comment]
same problem

**Comment by fbengtsson** [comment]
Following.

**Comment by aekanshd** [comment]
Following.

**Comment by caseysoftware** [comment]
What version of ngrok does this relate to?

If it's the version currently available from this repository, it is no longer supported or maintained. While we appreciate fixes shared in the community, we won't merge them upstream.

If it's the version currently available from ngrok.com, we are definitely happy to dig into that. Join us in ngrok.com/slack so we can figure it out!
