### ISSUE TITLE
Need 4 ports on same subdomain for Amcrest camera

### ISSUE THREAD

**Issue by FreeGoldRush** [inconshreveable/ngrok#827]
After much reading it appears ngrok will forward only ONE port per subdomain.  This means that things like Amcrest cameras that use 4 ports on the same device will not work through ngrok.  You can configure multiple tunnels with ngrok but each tunnel will appear on a separate subdomain.  I paid the $60 annual fee for a single user account but it does not appear this is going to work.

Has anyone found a solution for tunneling devices that use more than one TCP port?

**Comment by FreeGoldRush** [comment]
After a couple hours of tinkering I discovered that ssh reverse tunnels work great.  You just need a device on each end of the connection (raspberry pi for example) and you can then forward as many TCP ports as you want.  The pi acts as a proxy to other machines on your remote netowrk.  The ngrok pro plan limit is 2 and it's $99/year.

For this solution I used autossh to keep the connection alive.  Not sure how reliable this will be.

**Comment by eightsixeight** [comment]
> . The pi acts as a proxy to other machines on your remote netowrk. The ngrok pro plan limi

how you forward from pi ?
