### ISSUE TITLE
Accessing many times (1000x) in a session causes a critical failure.

### ISSUE THREAD

**Issue by jbrodie** [inconshreveable/ngrok#83]
So when I have ngrok running and leave it running while I batch approx 200 files with probably 5 call back calls through ngrok, it ultimately has a critical failure and locks up the terminal window so I can't even get any addition details on what the error is.

If someone could tell me a way to enable to logging on the application when launched I might be able to gather a little more for debugging.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
