### ISSUE TITLE
The server cannot access Github 

### ISSUE THREAD

**Issue by wxz0107** [inconshreveable/ngrok#831]
[root@VM-24-7-centos ngrok]# sudo make release-server release-client 
GOOS="" GOARCH="" go get github.com/jteeuwen/go-bindata/go-bindata
go get: module github.com/jteeuwen/go-bindata/go-bindata: Get "https://proxy.golang.org/github.com/jteeuwen/go-bindata/go-bindata/@v/list": dial tcp 142.251.42.241:443: i/o timeout

The server cannot access Github 
I can access Github  on my personal computer 
Is it possible to download a file and put it on the server

**Comment by peterhoeg** [comment]
This seems unrelated to ngrok. Please close.
