### ISSUE TITLE
how to get the url when I run the command nohup in linux?

### ISSUE THREAD

**Issue by Pluto-0906** [inconshreveable/ngrok#834]
I'm a newbie to ngrok, I'm trying to run ngrok as a background application on a linux server to do intranet penetration, and I will use the command : **nohup . /ngrok tcp 22 &** , but after that I will not be able to see the specific URL after mapping(only return the pid), please tell me how to get the URL after mapping in this case? I would appreciate it if you could contact me via email：caoyifan0906@gmail.com    THX~

**Comment by peterhoeg** [comment]
Just run it in tmux or screen.This will allow you to interact with the process as normal and still use the session for something else.

**Comment by caseysoftware** [comment]
This issue queue is unmonitored. Please visit http://ngrok.com/slack for community support & discussion.

**Comment by Sonu-Sukralia** [comment]
Yes it is easy to locate that URL link. i also had the same problem. 
few steps are there like i am running my Jellyfin server on Ngrok so few commands is use to forwards my Jellyfin media server to over internet.
during installation you need to configure your Ngrok account to your personal email id. and you need to remember you passwords and login details then please follow the few steps.

1   nohup sudo ./ngrok http 192.168.29.15:8096 & 
2   then login to " https://ngrok.com/  
     there in login dashboard go to  " CloudEdge  -> Endpoints -> Url ( https://7xx-2exx-49xx-e9xx.......in.ngrok.io/)" 
   
I am Happy to help you..!
Thanks 
for more info contact me please
sonukr023@gmail.com
https://github.com/sonu-sukralia

**Comment by minhnq64** [comment]
> Yes it is easy to locate that URL link. i also had the same problem. few steps are there like i am running my Jellyfin server on Ngrok so few commands is use to forwards my Jellyfin media server to over internet. during installation you need to configure your Ngrok account to your personal email id. and you need to remember you passwords and login details then please follow the few steps.
> 
> 1 nohup sudo ./ngrok http 192.168.29.15:8096 & 2 then login to " https://ngrok.com/ there in login dashboard go to " CloudEdge -> Endpoints -> Url ( Example :- https://7xx-2exx-49xx-e9xx.......in.ngrok.io/)"
> 
> I am Happy to help you..! Thanks for more info contact me please [sonukr023@gmail.com](mailto:sonukr023@gmail.com) https://github.com/sonu-sukralia

It work. Tks
