### ISSUE TITLE
ERR_NGROK_108 when passing `--region eu`

### ISSUE THREAD

**Issue by mr-moon** [inconshreveable/ngrok#836]
Just as title says. 
```
ngrok http --region eu 9000  
Your account is limited to 1 simultaneous ngrok agent session.
Active ngrok agent sessions in region 'eu':
  - ...
ERR_NGROK_108
```

Without `--region eu` bit works as expected.

```
ngrok --version
ngrok version 2.3.40
```

On Mac Intel i9

**Comment by ebrahimalshrby** [comment]
لماذا يتكرر هذا الخطا كثيرا 
اصلحه وهو يرجع بعد فتره

**Comment by caseysoftware** [comment]
This issue queue is unmonitored. Please visit http://ngrok.com/slack for community support & discussion.
