### ISSUE TITLE
Suddenly ERR_NGROK_9018

### ISSUE THREAD

**Issue by rolandjohann** [inconshreveable/ngrok#837]
Since azure function development often requires an implementation of local tunneling which will be advertised to be ngrok at the ms azure functions docs, we are using it. It works pretty well and the ability to instrument it is awesome!

Recently I discovered that I am not able to start ngrok with host header rewrite, which worked earlier the day. Is there any trial period that expired?

**Comment by DanielGSoftware** [comment]
Got the same error here, using the Laravel framework, which has a "valet share" command that uses ngrok.

**Comment by DGulshan** [comment]
Same here. It was working fine last week but today it's asking me to upgrade to a Pro or Enterprise plan.

**Comment by s3vi26** [comment]
bump ^^ having an issue where it'd telling me to upgrade to a Pro or Enterprise plan.

**Comment by austin-lolli** [comment]
Getting this error when running the 'valet share' command from Laravel.

**Comment by mgilberties** [comment]
Getting the same issue here after moving to a new m1 mac and installing the latest ngrok. My colleague is running the same version ( supposedly - according to ngrok) and doesn't encounter the problem when running `valet share`. Have tried the steps recommended here but with no joy: [https://github.com/laravel/valet/issues/1172#issuecomment-1090290544](https://github.com/laravel/valet/issues/1172#issuecomment-1090290544)

**Comment by mgilberties** [comment]
So..... @minimatrix came through with some great steps that got it working for me in the Laravel Valet case:

1. `brew install ngrok`
2. `cd ~/.composer/vendor/laravel/valet/bin`
3. `./ngrok authtoken [yourtoken]`
4. `cd [back to your laravel proj]`
5. `valet share`
6. Celebrate because it works now! :tada:

**Comment by drmanhatin** [comment]
So is this a feature or a bug? The site https://ngrok.com/pricing still states that header rewrite should be possible in the free tier

**Comment by caseysoftware** [comment]
Thanks for the heads up on this one. Digging around in how things work, it appears there's a version mismatch. If you upgrade from the v2.x Client to the v3.x Client, you should see the behavior flip back.

Here are the step by step instructions: https://ngrok.com/docs/guides/upgrade-v2-v3

**Comment by russorat** [comment]
PM from ngrok here. we are investigating this as it shouldn't require an upgrade of the ngrok agent. I will comment here when we have an update.

**Comment by russorat** [comment]
Dug in a little bit here. The error message returned is (obviously) incorrect and we will get that updated. It should ask you to create an ngrok account and install your authtoken.

For those that hit this issue in the future, please ensure you have an ngrok account and have correctly installed your authtoken for the agent (`ngrok authtoken [token]` for agent v2 and `ngrok config add-authtoken [token]` for v3).

also, this project isn't actively maintained anymore. in the future, you can get a faster answer by joining us in slack (https://ngrok.com/slack) or contacting support.

**Comment by bryanstevens314** [comment]
Just ran into this when setting up the twilio cli and trying to configure a web hook url, found this on ngrok's site - 

ERR_NGROK_9018 - "Only Pro or Enterprise accounts can use host header rewrite. Your account is not authorized to use host header rewrite. Upgrade to a Pro or Enterprise plan at: https://dashboard.ngrok.com/billing/subscription"

https://ngrok.com/docs/errors/err_ngrok_9018

**Comment by thetateman** [comment]
> Just ran into this when setting up the twilio cli and trying to configure a web hook url, found this on ngrok's site -
> 
> ERR_NGROK_9018 - "Only Pro or Enterprise accounts can use host header rewrite. Your account is not authorized to use host header rewrite. Upgrade to a Pro or Enterprise plan at: https://dashboard.ngrok.com/billing/subscription"
> 
> https://ngrok.com/docs/errors/err_ngrok_9018

Had the exact same issue. This fixed it for me:

1. Sign up for a free account at ngrok.com
2. Copy the auth token for your account.
3. Locate the ngrok executable that Twilio uses. If you installed Twilio with npm on Windows, it should be in .ngrok in your user directory.
4. cd to the directory with the ngrok executable and run: ./ngrok authtoken <your auth token>

**Comment by jonathaneemmett** [comment]
@thetateman I appreciate you posting that, I wasn't aware that twilio installed it's own ngrok.. anyone on a mac just do a find / -name ngrok and if you installed with brew it will be somewhere around /usr/loca/Cellar/twilio/3.4.1/libexec/node_modules/ngrok/bin/ngrok.

**Comment by caseysoftware** [comment]
@rolandjohann Thanks for the note.

While we'd like to be able to run ngrok without requiring user accounts at all, it's not feasible. Unfortunately, various bad actors have misused/abused us to create anonymous proxies and launch various attacks. Requiring an account with a verifiable email address is one of the many steps we take to mitigate those users up front.

Regardless, we are working to expand and improve upon the Free account so people can play, build, and launch their projects easily. I hope that meets your needs.

**Comment by PaulMest** [comment]
My project is using Twilio's TypeScript starter template and it does indeed use ngrok v2. So here was my Twilio work around...

```sh
# Ngrok v3 config
$ brew install ngrok
$ ngrok config add-authtoken <my auth-token>

# Configure Twilio's copy of ngrok v2 in node_modules
$ yarn ngrok authtoken <my auth-token>
```

**Comment by kvasconcelos** [comment]
> 

That just worked for Laravel 9 + valet with an macbook air m2

Thank you very much

**Comment by EmilioJD** [comment]
> @thetateman I appreciate you posting that, I wasn't aware that twilio installed it's own ngrok.. anyone on a mac just do a find / -name ngrok and if you installed with brew it will be somewhere around /usr/loca/Cellar/twilio/3.4.1/libexec/node_modules/ngrok/bin/ngrok.

Had to use this work around today, thanks! Seems to still be a huge issue.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
