### ISSUE TITLE
Console: Repeated requests cannot be distinguished from each other

### ISSUE THREAD

**Issue by iandunn** [inconshreveable/ngrok#838]
![Screen Shot 2022-04-14 at 12 24 13 PM](https://user-images.githubusercontent.com/484068/163461755-95e9a7f3-4033-4556-babe-1a7fe75b67c0.png)

It'd help to include a timestamp, or some other unique way to tell them apart.

**Comment by iandunn** [comment]
Including the IP of the requester would be nice too

**Comment by caseysoftware** [comment]
The request headers - available via the web UI - have quite a bit more detail. Check out your web ui at http://localhost:4040/

These issues are unmonitored. Check out our Slack channel:  http://ngrok.com/slack

**Comment by russorat** [comment]
Thanks! Continued in https://github.com/ngrok/ngrok/issues/8
