### ISSUE TITLE
ngrok systemd service exit code 1/FAILURE

### ISSUE THREAD

**Issue by yellowjacketcoder** [inconshreveable/ngrok#839]
I searched the existing open issues and couldn't find a similar issue hence making a new one:

I followed the ngrok docs and installed ngrok 3 in my system(Lenovo Thinkpad L14 Gen2 Ubuntu Certified) with Ubuntu 20.04 LTS via apt and I can run it fine with ngrok tcp <PORT>. I wanted to install ngrok as a service though so that I don't have to manually start ngrok manually on every boot and followed [the docs](https://ngrok.com/docs/secure-tunnels#installing-as-a-service) again and got the following output on running `ngrok service install`:

```console
com167@thinkpad-l14:~$ ngrok service install --config ~/.config/ngrok/ngrok.yml 
INFO[04-20|10:18:46] open config file                         path=/home/com167/.config/ngrok/ngrok.yml err=nil
INFO[04-20|10:18:46] detect init system                       sys=linux-systemd
CRIT[04-20|10:18:46] install failed                           err="Failed to install ngrok: open /etc/systemd/system/ngrok.service: permission denied"
```
so I figured I had to run it as root and this was the output with `sudo`:

```console
com167@thinkpad-l14:~$ sudo ngrok service install --config ~/.config/ngrok/ngrok.yml 
INFO[04-20|10:19:40] open config file                         path=/home/com167/.config/ngrok/ngrok.yml err=nil
INFO[04-20|10:19:40] detect init system                       sys=linux-systemd
INFO[04-20|10:19:41] install ok 
```

and I started the service:

```console
com167@pranjals-l14:~$ ngrok service start
INFO[04-20|10:19:51] detect init system                       sys=linux-systemd
INFO[04-20|10:19:53] start ok 
```

SUCCESS! Right? Or so I thought but when I wanted to get the public port number(free account) and didn't know where to find it so I figured I can check the status in `systemctl` but ALAS this was the output:

```console
com167@pranjals-l14:~$ sudo systemctl status ngrok
● ngrok.service - ngrok secure tunnel client
     Loaded: loaded (/etc/systemd/system/ngrok.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Wed 2022-04-20 10:19:54 IST; 3s ago
    Process: 19554 ExecStart=/usr/local/bin/ngrok service run --config /home/com167/.config/ngrok/ngrok.yml (code=exited, status=1/FAILURE)
   Main PID: 19554 (code=exited, status=1/FAILURE)
```

I tried adding `log_level` and `log` to my config file but there was no output in the same. I have not been able to diagnose the actual problem why I am getting 1/FAILURE exit code on my service. As of writing my config file stands as follows:

```yaml
authtoken: <my-auth-token>
region: <my-region>
log: /home/com167/.log/ngrok.log
log_level: debug
tunnels:
    vnc:
        proto: tcp
        addr: 5900
version: "2"
```

I highly suspect that installing the service as `sudo` is messing with permissions somewhere but I am not sure and even if I was I still need help as I tried installing the service without sudo but that didn't work out for me. I will be highly thankful if someone can help me to resolve this issue.

Also if I manually run `ngrok tcp 5900` it works fine

**Comment by caseysoftware** [comment]
This issue queue is unmonitored. Please visit http://ngrok.com/slack for community support & discussion.

**Comment by kovaacs** [comment]
Run `journalctl -u ngrok.service` and see the full error. In my case it was that my account was not authorised to run ngrok as a service.

**Comment by yellowjacketcoder** [comment]
> Run `journalctl -u ngrok.service` and see the full error. In my case it was that my account was not authorised to run ngrok as a service.

Thank you! I ran the command and this was the output:

`Sep 05 11:00:56 com167 ngrok[3802]: t=2022-09-05T11:00:56Z lvl=eror msg="terminating with error" obj=app err="Your account is not authorized to run the agent as a service.\n\nUpgrade to a Pro or Enterprise >
`

Well I guess that means free users aren't allowed to run ngrok as a service. Well that's a shame, anyways, that sorts the issue. Closing the ticket then

**Comment by Andrew080108** [comment]
> > Run `journalctl -u ngrok.service` and see the full error. In my case it was that my account was not authorised to run ngrok as a service.
> 
> Thank you! I ran the command and this was the output:
> 
> `Sep 05 11:00:56 com167 ngrok[3802]: t=2022-09-05T11:00:56Z lvl=eror msg="terminating with error" obj=app err="Your account is not authorized to run the agent as a service.\n\nUpgrade to a Pro or Enterprise > `
> 
> Well I guess that means free users aren't allowed to run ngrok as a service. Well that's a shame, anyways, that sorts the issue. Closing the ticket then

Have you found any alternative for this software or did you fix it somehow?
