### ISSUE TITLE
Issue 285 is back.

### ISSUE THREAD

**Issue by franasal** [inconshreveable/ngrok#840]
Issue is back.

_Originally posted by @pernydev in https://github.com/inconshreveable/ngrok/issues/285#issuecomment-1105268996_

**Comment by JonathanSchndr** [comment]
any news? workarounds? we cannot forward such a url to our customers. with a custom domain the problem would be solved?

**Comment by caseysoftware** [comment]
Yes, custom domains generally mitigate this issue. We're working on a number of other solutions.

For further discussion, check out our Slack channel:  http://ngrok.com/slack
