### ISSUE TITLE
I'm already signed in but getting sign up error again

### ISSUE THREAD

**Issue by Panda1994s** [inconshreveable/ngrok#843]
```
ERR_NGROK_6022
Before you can serve HTML content, you must [sign up for a free ngrok account](https://dashboard.ngrok.com/signup) and install your [authtoken](https://dashboard.ngrok.com/get-started/your-authtoken).
```
Anyone can help with this problem?
_Thanks in advance_

**Comment by Jhormannocua** [comment]
Tengo el mismo problema

**Comment by dabelle** [comment]
same. Also token has been installed.

**Comment by rutkovskii** [comment]
Same. Do not know what to do

**Comment by caseysoftware** [comment]
Follow the instructions at the link included: https://dashboard.ngrok.com/get-started/your-authtoken

**Comment by dabelle** [comment]
Apparently ngrok no longer allows use on Kali Linux. You can use ngrok on other linux distros just fine.

Here is the response from support:

"To curtail abuse on our platform, we had to stop allowing Kali Linux but other Linux variants should work fine. To look at what is supported take a look at our download page (https://ngrok.com/download) and select Linux. Apologies for any inconvenience this may have caused."

**Comment by louis-sanna-eki** [comment]
On mac I add to create the file `~/.ngrok2/ngrok.yml` myself and add the token.
