### ISSUE TITLE
ERR_NGROK_8012

### ISSUE THREAD

**Issue by Manikandan-squashapps** [inconshreveable/ngrok#847]
Getting ERR_NGROK_8012 while try to connect with public host. Anyone having idea about this.

**Comment by beaudevanney** [comment]
ya im getting the same thing

**Comment by AjnaAnon** [comment]
same here

**Comment by zelal-dev** [comment]
Same here

**Comment by ENdonga** [comment]
execute ngrok http {port_number} in the same host machine as where your application is running

**Comment by hubobj** [comment]
> execute ngrok http {port_number} in the same host machine as where your application is running

I run ngrok http 8443 in the same host machine but it's still doesn't work

**Comment by romanstingler** [comment]
Same here using Archlinux downloaded the latest binary 
my service is running fine (tested hosting with nginx and artisan serve / Laravel) 
but always gives me ERR_NGROK_8012.

My 2 colleagues (windows and Mac user in the same Network are able to access their web projects)

**Comment by caseysoftware** [comment]
These forums are not monitored. Check out https://ngrok.com/slack for our Community Support

**Comment by keitata** [comment]
ああ

**Comment by kr1pt0n2007** [comment]
Help

**Comment by ThiagoCarrijo1** [comment]
Guy try this video it worked for me, it's in pt-br but just follow exactly what it does and it might work.

[https://www.youtube.com/watch?v=a61rTPadEvU&t=343s](url)

**Comment by MHR-RONY** [comment]
same problem here any solution

**Comment by nvelychenko** [comment]
In my case, I added `127.0.0.1       *.localhost` to my `/etc/hosts` file. I'm using *.localhost for local development, so adjust accordingly.  I'm not sure why that was required. Have no time to investigate, it was working without such configuration before, without any problems.

**Comment by alvesvaren** [comment]
Adding `127.0.0.1        localhost` to `/etc/hosts` fixed this for me
