### ISSUE TITLE
[Feature request] Add copy to clipboard button for admin UI

### ISSUE THREAD

**Issue by SergeyPirogov** [inconshreveable/ngrok#857]
It will be very useful to have a button that will allow to copy a response body to a clipboard

**Comment by caseysoftware** [comment]
Great idea. 

Please share future ideas in our community slack so we can discuss, explore, and learn more: http://ngrok.com/slack

**Comment by SergeyPirogov** [comment]
Very user friendly lol

**Comment by russorat** [comment]
Thanks! We've added this ability to our new [Traffic Inspector](https://dashboard.ngrok.com/observability/traffic-inspector) in the ngrok dashboard.
