### ISSUE TITLE
ERR_NGROK_6204 - Visit Site button on Splash Screen does not navigate to website

### ISSUE THREAD

**Issue by tyschreiver** [inconshreveable/ngrok#860]
For the last few months, I have been using ngrok (specifically the node.js wrapper) to host a website. Starting a few days ago, when you navigate to the ngrok link, it shows a splash screen before navigating to my website. There is a "Visit Site" button, but clicking on it just refreshes the page. I have been unable to get past this screen:

https://user-images.githubusercontent.com/21366264/179523447-ec06c055-5a51-4a01-a42d-f4e0ad87bf10.mov

Is this a bug, or does anyone have advice to get past this?

There are a couple of suggestions at the bottom of the screen, but I haven't been able to find any information about how to implement them.

* Set and send an [ngrok-skip-browser-warning] request header with any value.
* Or, set and send a custom/non-standard browser [User-Agent] request header.

If someone knows how to implement either of those two suggestions, I would appreciate a little guidance

**Comment by caseysoftware** [comment]
This issue queue is not monitored.

For active conversation & support, check out our Slack Community: http://ngrok.com/slack

**Comment by caseysoftware** [comment]
Arg. Sorry about that. here's a new:
https://join.slack.com/t/ngrokcommunity/shared_invite/zt-1cpwzjf6s-0uHEqGRjxnfd1R2xsvWYfg

**Comment by R-jee** [comment]
### *** You have to follow steps to bypass these in testing mod ***

- 1): Request headers   --> ngrok-skip-browser-warning = any integer value
- 2): install ModHeader Modify HTTP Header extension in browser 

![Screenshot from 2023-02-20 13-41-23](https://user-images.githubusercontent.com/48676778/220056166-01140a92-f1bf-4718-927a-af46ff0d7c1d.png)
