### ISSUE TITLE
 File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 145, in start_ngrok                                                                              print(localization.lang_start_ngrok["ngrok_url"] +                                                                                                                 TypeError: can only concatenate str (not "NgrokTunnel") to str  

### ISSUE THREAD

**Issue by dashamoolamdhamu** [inconshreveable/ngrok#862]
File "/root/HiddenEye/Defs/ActionManager/Server/server_runner.py", line 145, in start_ngrok                                                                         
    print(localization.lang_start_ngrok["ngrok_url"] +                                                                                                                
TypeError: can only concatenate str (not "NgrokTunnel") to str

**Comment by caseysoftware** [comment]
HiddenEye is a phishing tool. Phishing is not supported on the ngrok platform and is a breach of our TOS.

This includes for "educational" and "ethical" purposes.
