### ISSUE TITLE
Ngrok works when running in forefront, but fails running in background

### ISSUE THREAD

**Issue by NerdyBaseballDude** [inconshreveable/ngrok#868]
Hello all, I have an odd issue I wanted to ask you all about. I am trying to host a mariadb that is running locally on my computer with ngrok. (I've made sure to give restrictive permissions to only allow connections from authentic users that are password authenticated).

When I run a ```./ngrok tcp 3380``` command I am able to access the database as expected from an external computer. However, if I try to run ngrok in the background by using the command ```./ngrok tcp 3380 --log=stdout > ngrok.log &``` it looks like it is running correctly, but when I try to connect I get a “lost connection to mysql server at reading initial communication packet” error. Any ideas on this? I

t doesn't make sense to me that it works as expected when running ngrok in the front, but fails when running ngrok as a background process. Any help greatly appreciated. Thanks in advance!

**Comment by caseysoftware** [comment]
This repository is not monitored for support issues. Please visit us at ngrok.com/slack so we can dig in. Thanks!
