### ISSUE TITLE
Disable color

### ISSUE THREAD

**Issue by mdi** [inconshreveable/ngrok#87]
It would be nice to either disable color or change colors, as the default colors are unreadable on a terminal with a light background.

**Comment by iloveitaly** [comment]
:+1:

**Comment by MarioRicalde** [comment]
:+1:

**Comment by dukedave** [comment]
+1

**Comment by hibooboo2** [comment]
Why don't you submit a pr so that you can change it.

**Comment by dukedave** [comment]
Ah, FYI with my setup (tmux/solarized-light) the background color is set to dark (i.e. everything's readable) on 2.0.19.

**Comment by eproxus** [comment]
:+1:

**Comment by inconshreveable** [comment]
ngrok 2.X supports changing the background color of the terminal: https://ngrok.com/docs#config_console_ui

won't fix for 1.x

**Comment by adolfousier** [comment]
Still happening to this day xD
