### ISSUE TITLE
make ngrok server i can not fix problem 

### ISSUE THREAD

**Issue by mica1002** [inconshreveable/ngrok#870]
![bcc6acd6c1d51f6b2a82f7b57e83668](https://user-images.githubusercontent.com/112140679/186798246-b5a3530d-2feb-4003-93b2-6e8c7a9fe47f.jpg)

**Comment by mica1002** [comment]
@davej @mattn @vroy @is plz help me

**Comment by BigBaBei** [comment]
I have same problem

**Comment by caseysoftware** [comment]
This repository is not maintained or monitored. For help with this code, please look at one of the publicly available forks.

We recommend that you use the most recent version from ngrok.com/download for active development and support.
