### ISSUE TITLE
make release-client problem 

### ISSUE THREAD

**Issue by KyleLee233** [inconshreveable/ngrok#873]
go install -tags 'release' ngrok/main/ngrok
# github.com/rivo/uniseg
src/github.com/rivo/uniseg/properties.go:130:6: missing function body
src/github.com/rivo/uniseg/properties.go:130:20: syntax error: unexpected [, expecting (
make: *** [Makefile:17: client] Error 2

**Comment by caseysoftware** [comment]
This repository is not maintained or monitored. For help with this code, please look at one of the publicly available forks.

We recommend that you use the most recent version from ngrok.com/download for active development and support.

**Comment by diandiancm** [comment]
我也是这个问题，用的也是最新的代码

**Comment by ruralharry** [comment]
Me too.I use the newest code, but properties.go goes wrong...

**Comment by xsm818** [comment]
请问有人解决了吗 我也是这个问题

**Comment by leadscloud** [comment]
不是很懂go的包管理，但发现了解决办法，出现错误的原因是uniseg版本过高，我使用的一个笨办法实现的解决

`ngrok/src/github.com/rivo/`

删除掉uniseg，然后下载老版本替换即可

`wget https://github.com/rivo/uniseg/archive/refs/tags/v0.1.0.zip`
