### ISSUE TITLE
Ngrok problem 

### ISSUE THREAD

**Issue by Howel77** [inconshreveable/ngrok#876]
![Screenshot_20220920-152416_1](https://user-images.githubusercontent.com/113806069/191284310-3677aa86-a9a2-4603-baab-9a980474e244.png)

When I use my hiddeneye phishing tool and I choose ngrok as my server 
This is what always comes up 
Please how do I fix it

**Comment by caseysoftware** [comment]
_You agree that, except as expressly provided in these Terms, you will not:_

_(vi) use the ngrok Services or Site Materials to conduct “phishing” or other similar activities or in any other manner that could be misleading to third parties;_

Reference: https://ngrok.com/tos
