### ISSUE TITLE
Compiling using "make" fails

### ISSUE THREAD

**Issue by TadavomnisT** [inconshreveable/ngrok#878]
Greeting , and Thanks for this project.

I was interested to find out how does the project worked under the hood, so I took steps as [Developer's guide to ngrok](https://github.com/inconshreveable/ngrok/blob/master/docs/DEVELOPMENT.md) but during the compiling using `make` command, I get the following errors:

```shell
┌──(user㉿dhcppc4)-[~/Desktop/ngrok]
└─$ make  
```
```
go fmt ngrok/...
go: warning: "ngrok/..." matched no packages
bin/go-bindata -nomemcopy -pkg=assets -tags=debug \
        -debug=true \
        -o=src/ngrok/client/assets/assets_debug.go \
        assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=debug \
        -debug=true \
        -o=src/ngrok/server/assets/assets_debug.go \
        assets/server/...
go get -tags 'debug' -d -v ngrok/...
go get ngrok/...: malformed module path "ngrok": missing dot in first path element
make: *** [Makefile:8: deps] Error 1

```

I searched about that , and it led me into this issue #832 , but it didn't help.
Any idea what might be the problem?
Also I would appreciate it, if anyone could introduce me a detailed tutorial about compiling and running **ngrok** as server in local.

Thanks in advance <3

**Comment by kssion** [comment]
Try before make.
```shell
go env -w GO111MODULE=off
```

**Comment by TadavomnisT** [comment]
> Try before make.
> 
> ```shell
> go env -w GO111MODULE=off
> ```

@kssion 
Thank you, it worked.
