### ISSUE TITLE
ngrok(ver.3) doesn't work to tunnel localhost has subdomain

### ISSUE THREAD

**Issue by hibriiiiidge** [inconshreveable/ngrok#879]
Hi, there.
I have a problem.
After I upgraded ngrok version from 2.3.40 to 3.1.0, ngrok doesn’t work in my env.
But doesn’t happen errors, no error messages.
So at a glance, it looks no problem.

![ngrok](https://user-images.githubusercontent.com/10884347/195847470-0094d7a3-ae29-4366-986c-02205fb6adc6.png)

■ My development configuration
・ngrok version: 3.1.0
・Ruby on Rails: 6.0.3
・Ruby: 2.6.3
・dev url（my localhost url）: http://sample.localhost.local:3001/

■ What I want to do
・I want to tunnel to my localhost (my dev url) by ngrok.
Specifically…
https://random-string.ngrok.io → http://sample.localhost.local:3001/

■ What I tried
This command

```
$ ngrok http http://sample.localhost.local:3001 --host-header="sample.localhost.local"
```

↑ When ngrok version was 2.3.40, this command worked.
But When ngrok version is 3.1.0, this command doesn’t work.

ref: https://github.com/inconshreveable/ngrok/issues/448#issuecomment-1190461134

 Can anybody help me?

**Comment by hibriiiiidge** [comment]
I solved this problem by myself.   
This problem is specific to Ruby on Rails.

https://github.com/rails/rails/issues/29893 
This issue says ...

```ruby
If the header is not required, removing it appears to solve the problem. 
One way to do this is with a small piece of Rack middleware in config/application.rb:
```


Like that

`config/initializers/strip_x_forwarded_host.rb`

```ruby
class StripXForwardedHost
  def initialize(app)
    @app = app
  end

  def call(env)
    env.delete('HTTP_X_FORWARDED_HOST')
    @app.call(env)
  end
end
```

`config/environments/development.rb`

```ruby
require_relative "../initializers/strip_x_forwarded_host.rb"

Rails.application.configure do
    ...
    config.middleware.use StripXForwardedHost
end
```

I hope this will be useful to someone.

**Comment by marktong11** [comment]
@hibriiiiidge I ran into this issue today after upgrading from ngrok v2 to v3. Thanks to your added information I was able to get ngrok v3 working with rails 6 by manually overriding the HTTP_X_FORWARDED_HOST header when starting ngrok using the following:

`ngrok http lvh.me:3000 --request-header-add=x_forwarded_host:lvh.me:3000`
