### ISSUE TITLE
Failed to fetch CRL

### ISSUE THREAD

**Issue by thebluelake** [inconshreveable/ngrok#885]
Hi!

I have a vite project running on localhost:5173 and I tried to run `ngrok http 5173` to expose it for testing on mobile but encountered this error. Tried it on both WSL2 and windows command prompt. 

```
reconnecting (failed to fetch CRL. errors encountered: Get "http://crl.ngrok.com/ngrok.crl": read tcp 172.18.216.30:54850->13.33.33.108:80: read: connection reset
```

Version: 3.1.0 (on both WSL2 and windows)

Couldn't find anything online about the same error so I came here. Appreciate any help!

**Comment by caseysoftware** [comment]
Thanks for the note. This repository is not monitored. Please visit us in our community slack - https://ngrok.com/slack - for ongoing activity and support
