### ISSUE TITLE
Ngrok region US is down for several accounts

### ISSUE THREAD

**Issue by yinghechen** [inconshreveable/ngrok#886]
Hi NGROK Support,

I find ngrok US is down. It appears that 'ngrok --region=us http 80' is down. I also tried this command with multiple free and paid accounts.  

I believe this is a NGROK only bug because 'ngrok --region=au http 80' and 'ngrok --region=jp http 80' work. However, I count't change to a different region because my domain binds to US only. Can you help to fix this as soon as possible ?

The tunnel can be created successfully in us region, but the web access is not allowed.

**Comment by caseysoftware** [comment]
Thanks for the note. This repository is not monitored. Please visit us in our community slack - https://ngrok.com/slack - for ongoing activity and support
