### ISSUE TITLE
ngrok issue

### ISSUE THREAD

**Issue by sathiyaragavan** [inconshreveable/ngrok#889]
when i was performing the below command 
**sudo make release-client**
 i am facing this error
ubuntu@ip-172-25-2-149:~/ngrok$ sudo make release-client
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
	-debug=false \
	-o=src/ngrok/client/assets/assets_release.go \
	assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
	-debug=false \
	-o=src/ngrok/server/assets/assets_release.go \
	assets/server/...
go get -tags 'release' -d -v ngrok/...
src/github.com/mattn/go-runewidth/runewidth.go:7:2: found packages uniseg (doc.go) and main (gen_breaktest.go) in /home/ubuntu/ngrok/src/github.com/rivo/uniseg
Makefile:8: recipe for target 'deps' failed
make: *** [deps] Error 1
 could anyone help us to resolve this issue

**Comment by caseysoftware** [comment]
Thanks for the note. This repository is no longer maintained. Please check out one of the forks or visit https://ngrok.com/download for the latest release
