### ISSUE TITLE
Illegal instruction error openwrt

### ISSUE THREAD

**Issue by Spothz** [inconshreveable/ngrok#890]
![1](https://user-images.githubusercontent.com/64120245/208240082-64059d74-8425-4b2e-a093-b6344ee331fc.jpg)
Hi, I want to install ngrok on openwrt, Router Newifi D2 mt7621 MIPS mipsle. 
# My procedure:
wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-mipsle.tgz
tar -zxvf ngrok-v3-stable-linux-mips.tgz
 ./ngrok config add-authtoken my_token
# I get an error Illegal instruction
Can you help me figure out what I'm doing wrong?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
