### ISSUE TITLE
ssh only works over lan

### ISSUE THREAD

**Issue by nathanLeDall** [inconshreveable/ngrok#893]
Hello,

I am having an issue with ngrok only working over lan.

my setup:
a raspi 4b connected over lan to my network
a w11 pc connected over lan to the same network
a w10 pc connected over wifi to the same network
an m1 mac pro connected over wifi to the same network

for some reason only the w11 pc can connect to the pi.

any ideas as to why that might be?

thanks in advance to anyone who tries to help.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
