### ISSUE TITLE
ngrok configuration file error

### ISSUE THREAD

**Issue by TBSFL** [inconshreveable/ngrok#894]
Hello,

Here is my configuration file with a changed authtoken:

version: "2"
region: us
authtoken: xKgVUrpQxxxOEwFmmCagfsYhop8_3xxxxxxxxSoYuVxxxxxdA

No matter what I try I will get this error:

ngrok http 80
ERROR:  Invalid configuration property value for 'http_proxy_env', 'localhost': URL scheme must be 'http' or 'https'

I tried changing the version in the file as someone suggested here, but nothing seems to help. I installed version 3 of ngrok. Is there something else I need to do? Should I install version 2? Where can I download that version? Thank you.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Hi @TBSFL, you will need to `unset http_proxy_env` before running ngrok. ngrok will automatically look in that env var to figure out if it needs to connect via a proxy. 

if you are still having issues, please open a new issue in https://github.com/ngrok/ngrok and we will take a look.
