### ISSUE TITLE
how do i connect ngrok to my godaddy domain

### ISSUE THREAD

**Issue by J-K-Tech** [inconshreveable/ngrok#899]
this.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
You will need to follow the instructions here: https://www.godaddy.com/help/add-a-cname-record-19236 to configure the cname targets for your ngrok domain. If you are still having trouble, please open an new issue in https://github.com/ngrok/ngrok.
