### ISSUE TITLE
Auth

### ISSUE THREAD

**Issue by faizanjan123** [inconshreveable/ngrok#900]
Run .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
NAME:
   authtoken - save authtoken to configuration file

USAGE:
   ngrok authtoken [command options] [arguments...]

DESCRIPTION:
   The authtoken command modifies your configuration file to include
   the specified authtoken. By default, this configuration file is located
   at $HOME/.ngrok2/ngrok.yml

   The ngrok.com service requires that you sign up for an account to use
   many advanced service features. In order to associate your client with
   an account, it must pass a secret token to the ngrok.com service when it
   starts up. Instead of passing this authtoken on every invocation, you may
   use this command to save it into your configuration file so that your
   client always authenticates you properly.

EXAMPLE:
    ngrok authtoken BDZIXnhJt2HNWLXyQ5PM_qCaBq0W2sNFcCa0rfTZd

OPTIONS:
   --config 		save in this config file, default: ~/.ngrok2/ngrok.yml
   --log "false"	path to log file, 'stdout', 'stderr' or 'false'
   --log-format "term"	log record format: 'term', 'logfmt', 'json'
   --log-level "info"	logging level

ERROR:  You must pass a single argument, the authtoken to save to configuration file.
Error: Process completed with exit code 1.
 
Problem

**Comment by hichamovich7** [comment]
Hello,
I had the same issue, the only thing I did is Create a new  Repository secrets with Name: NGROK_AUTH_TOKEN and I past there my ngrok personal Authtoken.

![Solution_ngrok](https://user-images.githubusercontent.com/61650642/234612212-aadea2a2-88f8-4837-8d02-1145907f785d.PNG)

**Comment by hichamovich7** [comment]
In your forked repo: Go to Settings > Secrets > Action > New Repository Secret
In the name section, enter this text: NGROK_AUTH_TOKEN
In the value section, enter the ngrok token
Then press Add Secret
Now go to Action > AWS (Left Menu) > Run Workflow
Refresh the page and go to AWS > build option
You'll get IP, Username & Password from Connect to RDP section.

**Comment by atala10** [comment]
Successfully Installed !, If the RDP is Dead, Please Rebuild Again! . how fix?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
