### ISSUE TITLE
Is it possible to use ngrok to tunnel 80 and 443 on the same domain?

### ISSUE THREAD

**Issue by hatem-amer** [inconshreveable/ngrok#903]
**Use case**
1. Test ACMEv2 ([RFC 8555](https://datatracker.ietf.org/doc/html/rfc8555))
2. Test HTTP to HTTPS redirect 
3. etc

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
