### ISSUE TITLE
NGROK doesn't work with windows authentication 

### ISSUE THREAD

**Issue by SoetZombie** [inconshreveable/ngrok#907]
I have simple Blazor app, that uses windows authentication. In the launch settings I have enabled both anonymous authentication and windows authentication (windows required by blazor)

```
  "iisSettings": {
    "windowsAuthentication": true,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:54819",
      "sslPort": 44398
    }
  },
```

When I run the app locally everything works just fine, however when I provision tunnel in ngrok via: 

`ngrok http https://localhost:44398/ --host-header=localhost:44398`

I get login prompt when I visit the tunneled site, no matter what I include it always fails. 

The response then looks as follows:

[![img][1]][1]

  [1]: https://i.stack.imgur.com/fVCac.png

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
