### ISSUE TITLE
Compile failed because of go-update.v0?go-get=1: x509: certificate has expired or is not yet valid

### ISSUE THREAD

**Issue by cc5zhenhua** [inconshreveable/ngrok#908]
/ngrok # make release-server
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/client/assets/assets_release.go \
        assets/client/...
bin/go-bindata -nomemcopy -pkg=assets -tags=release \
        -debug=false \
        -o=src/ngrok/server/assets/assets_release.go \
        assets/server/...
go get -tags 'release' -d -v ngrok/...
Fetching https://gopkg.in/inconshreveable/go-update.v0?go-get=1
https fetch failed: Get https://gopkg.in/inconshreveable/go-update.v0?go-get=1: x509: certificate has expired or is not yet valid
package gopkg.in/inconshreveable/go-update.v0: unrecognized import path "gopkg.in/inconshreveable/go-update.v0" (https fetch: Get https://gopkg.in/inconshreveable/go-update.v0?go-get=1: x509: certificate has expired or is not yet valid)
Fetching https://gopkg.in/inconshreveable/go-update.v0/check?go-get=1
https fetch failed: Get https://gopkg.in/inconshreveable/go-update.v0/check?go-get=1: x509: certificate has expired or is not yet valid
package gopkg.in/inconshreveable/go-update.v0/check: unrecognized import path "gopkg.in/inconshreveable/go-update.v0/check" (https fetch: Get https://gopkg.in/inconshreveable/go-update.v0/check?go-get=1: x509: certificate has expired or is not yet valid)
Fetching https://gopkg.in/yaml.v1?go-get=1
https fetch failed: Get https://gopkg.in/yaml.v1?go-get=1: x509: certificate has expired or is not yet valid
package gopkg.in/yaml.v1: unrecognized import path "gopkg.in/yaml.v1" (https fetch: Get https://gopkg.in/yaml.v1?go-get=1: x509: certificate has expired or is not yet valid)
Makefile:8: recipe for target 'deps' failed
make: *** [deps] Error 1

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
