### ISSUE TITLE
SSL/Cipher Mismatch

### ISSUE THREAD

**Issue by fitlibadmin** [inconshreveable/ngrok#913]
Whatever PHP application I try to serve publicly results in the same issue. Ngrok is able to create a link but in all browsers, a secure connection couldn't be made. This is regardless of whether it's using the built in PHP web server (v8.2.5) or a Laravel app inside a docker container (v8.1.18).

I'm on a Mac running Monterey 12.6.5 and have tried Chrome, Safari and FireFox. All browsers are up to date, so is the Mac version for this model.

**Comment by brendanlawton** [comment]
Ignore - it's the ISP's security feature blocking it

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
