### ISSUE TITLE
Ngrok fails to install on Linux with provided script in Domain Setup

### ISSUE THREAD

**Issue by ontoneio** [inconshreveable/ngrok#916]
In setting up a tunnel after making a domain.

<img width="244" alt="image" src="https://github.com/inconshreveable/ngrok/assets/24515434/e7e1db7c-0460-4992-baf5-8bfd3fa6c02a">

You are given this script to install ngrok:

```bash
curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.ngrok.com/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list apt update && apt install ngrok
```

This does not work and is different from the install script on the [Documentation page](https://ngrok.com/docs/getting-started/#step-2-install-the-ngrok-agent) that actually works.

```bash
curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | \
  sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null && \
  echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | \
  sudo tee /etc/apt/sources.list.d/ngrok.list && \
  sudo apt update && sudo apt install ngrok
```

Please correct the scripts in the proper locations. 

Thanks!

**Comment by ryanhiebert** [comment]
I'm having this issue as well. Attempting to use it in a docker container build based on `mcr.microsoft.com/devcontainers/python:0-3.10`, and it says that it doesn't have a signature. It doesn't appear to be docker caching related, because removing the base image doesn't resolve it.

I do think this was working for me more recently than this issue was created, though.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by marcindulak** [comment]
@russorat One could think that unresolved issues could be transferred to the new https://github.com/ngrok/ngrok repo.

Please note that using github discussions instead of issues will result in limited discoverability of problems, see https://github.com/orgs/community/discussions/2971

**Comment by russorat** [comment]
@marcindulak thanks! i'm looking through these issues to move them over as suggested. i believe this issue was fixed though. I don't see any places in the code that reference the original string. If that's not the case, please open a new issue in https://github.com/ngrok/ngrok.
