### ISSUE TITLE
Stuck in the reconnect screen

### ISSUE THREAD

**Issue by meohent41zhead** [inconshreveable/ngrok#919]
![Screenshot_20230529_210339_Termux](https://github.com/inconshreveable/ngrok/assets/80139315/1d7879da-0704-4d3a-93c0-055ed1661852)
Help me iam running it for a hour but no happend it just reconnecting 

Os: termux linux 0.118.0
Ss galaxy a14

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
