### ISSUE TITLE
Headers Missing

### ISSUE THREAD

**Issue by dsshap** [inconshreveable/ngrok#92]
I am missing some headers when i send http requests through ngrok.

HTTP_X_MOBILE_TOKEN

**Comment by Xavdidtheshadow** [comment]
I'm seeing this issue how when receiving a webhook from classmarker.com that's supposed to contain a `HTTP_X_CLASSMARKER_HMAC_SHA256` header. It looks like the other headers make it through ok though. 

This is with `v1.7.1`

**Comment by kellermanrivero** [comment]
@Xavdidtheshadow, as @inconshreveable explains above invalid http headers are filtered. So I believe 'HTTP_X_CLASSMARKER_HMAC_SHA256' is not a valid header, maybe if you can rename it to 'X-HTTP_X_CLASSMARKER_HMAC_SHA256' it should work.
