### ISSUE TITLE
Can you login in your localhost website via ngrok? It doesn't work

### ISSUE THREAD

**Issue by statsconchris** [inconshreveable/ngrok#921]
I'm new to ngrok. I have a website in my localhost that has a login page. I was able to connect to it via ngrok, so I could see the login page.. However, after typing my username and password I'm not redirected to the next page.... Nothing happens. Is this fixable?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
