### ISSUE TITLE
Ngrok version 3.3.4 diagnose show strange warnings localhost

### ISSUE THREAD

**Issue by cesarjorgemartinez** [inconshreveable/ngrok#927]
Hi,

I use ngrok version 3.3.4 with ssh tunnels. Show this when launch ngrok diagnostics:

```
Localhost Connectivity
  Name Resolution                         [ WARN ]

Warnings and non-fatal errors encountered during diagnostics:

* Diagnostics
  * Name Resolution
    * Resolver: 8.8.8.8
      * Hostname: localhost
        - Err: Failed to resolve host localhost: resolver returned no IPs
               (NGROK_ERR_8000)
    * Resolver: 8.8.4.4
      * Hostname: localhost
        - Err: Failed to resolve host localhost: resolver returned no IPs
               (NGROK_ERR_8000)
```

Reverting back to version 3.3.3 works correctly.
Can you fix it so we can use the latest version without those strange warnings?

Regards

**Comment by zhanglijinze** [comment]
@cesarjorgemartinez Hi there, I have the same issue. Suddenly, I could not use it with react native project. How to revert back to version 3.3.3. I looked at the command line tool. No such command. Only the update to latest version option. Thanks.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Hi, Please upgrade to the latest ngrok agent version 3.9 and check if the issue persists. If so, please open a new issue in the https://github.com/ngrok/ngrok repo and we will take a look.
