### ISSUE TITLE
labelstudio with ngrok not working on firefox

### ISSUE THREAD

**Issue by Reasat** [inconshreveable/ngrok#928]
Hi, thanks for the amazing software!

I set up an image annotation scheme using labelstudio and forwarded the port using ngrok. 

From another computer I can use the chrome browser, login to labelstudio and access images and do my annotation. 

When I try to access the link through firefox I can login to labelstudio but none of my images load (there's an indefinite loading symbol) when I click on an example. Although I can see the images in the thumbnails. Here's a screenshot of the problem,

![Screenshot from 2023-09-19 14-08-08](https://github.com/inconshreveable/ngrok/assets/15989033/7c2e428e-438d-4517-9b2f-015b6727473e)

Can you give me some suggestions on where to start debugging the issue?

Thanks in advance!

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
