### ISSUE TITLE
Dosen't work header

### ISSUE THREAD

**Issue by Izumra** [inconshreveable/ngrok#929]
ngrok http 8080 --host-header=rewrite --request-header-add "ngrok-skip-browser-warning: t;"

This command doesn't work and preload warning screen dosen't skip

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
@Izumra you cannot use the ngrok header-add capability to skip the browser warning. You will need to try one of the workarounds described here: https://ngrok.com/docs/guides/limits/#why-is-there-an-interstitial-in-front-of-my-html-content

If you are still having problems, please open a new issue in the https://github.com/ngrok/ngrok repo and we will take a look.
