### ISSUE TITLE
ngrok status reconnecting issue failed to send authentication request: read tcp

### ISSUE THREAD

**Issue by changeyoucant** [inconshreveable/ngrok#931]
when i  run ngrok ngrok http 5173 , end with error.
reconnecting (failed to send authentication request: read tcp [2408:8221:811:d1c0:cd89:b675:d021:e3d8]:50980;
![image](https://github.com/inconshreveable/ngrok/assets/51197525/e137d072-c1a9-481d-a491-c9e985caf299)

when i run ngrok diagnose 
![image](https://github.com/inconshreveable/ngrok/assets/51197525/07488be5-7215-4191-a075-eb77357bcea2)
Does anyone know it?  i try ngrok http port --host-header="localhost:port" and  ngrok http port --region=auto.
doesnt work

**Comment by changeyoucant** [comment]
![image](https://github.com/inconshreveable/ngrok/assets/51197525/8b313e15-c497-4465-b102-03b6c8b294f8)

**Comment by baoch254** [comment]
You can use docker to host ngrok.
`docker run -it -e NGROK_AUTHTOKEN=<Token> ngrok/ngrok:latest http host.docker.internal:80`
It works for me!

Ref: [https://ngrok.com/docs/using-ngrok-with/docker](https://ngrok.com/docs/using-ngrok-with/docker)

**Comment by natraj-ng-17587** [comment]
I am also having same issue

**Comment by LE-lingxue** [comment]
Is there a solution?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Hi, in the original issue, the ngrok agent was not able to connect to any external services. If you are seeing a similar error, it usually means there is some sort of proxy or firewall software that is blocking connections from the agent software. I recommend checking with your system administrator or ISP to see if there is anything that might be blocking ngrok connections. 

If you still have an issue, please open an issue or discussion in the https://github.com/ngrok/ngrok repo with the relevant details and we will take a look.
