### ISSUE TITLE
Not registering server responses

### ISSUE THREAD

**Issue by joachimbulow** [inconshreveable/ngrok#934]
I am not entirely sure what the issue may be, but we recently migrated to use a `http2` client for our Flutter app, for which i use ngrok to connect to my localhost. This could be the differentiating factor.

Recently, the web inpsector is now oftentimes not registering responses, even though the app obviously recieves them.
Ngrok inspector registers them as hanging forever.

<img width="1203" alt="image" src="https://github.com/inconshreveable/ngrok/assets/43139346/7d715913-0039-430f-878c-1280675d787f">

**Comment by joachimbulow** [comment]
Appears restarting ngrok solved the problem. For now.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
@joachimbulow ngrok started supporting http/2 for connections between the agent and the upstream service in Dec 2023 (https://ngrok.com/docs/whats-new/#december-2023). Ensure you're on the latest ngrok agent and let us know in https://github.com/ngrok/ngrok if you still have an issue.
