### ISSUE TITLE
question regarding memory usage

### ISSUE THREAD

**Issue by PwccaCode** [inconshreveable/ngrok#935]
after my ngrok client is running for a few hours or days, the memory usage is already well above 1gb.

initially its less than 100mb.

For some reason connections doesn't seem to be droped after a while, so i just have 18000 connections and average conn time 178172319ms

any idea how to make the connections get automatically dropped if being unused?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
@PwccaCode thanks! Please confirm you are on the latest version of the ngrok agent (v3.9 as of today) and if this issue still exists, open a new issue on https://github.com/ngrok/ngrok with what you see and we will take a look.
