### ISSUE TITLE
"An SSL error has occurred and a secure connection to the server cannot be made"

### ISSUE THREAD

**Issue by Goekdeniz-Guelmez** [inconshreveable/ngrok#936]
Hey, I'm new on this. So I have made an API with FastAPI and am using ngrok to make it public. When deleting the config file and starting a service via basic command prompt `ngrok http 8000`, the API call works perfectly as intended, but on using the config file and calling the API from outside the network, I get the error message`An SSL error has occurred and a secure connection to the server cannot be made` (I am making an API call from my iPhone via the shortcuts app). The config file is:```
authtoken: <AUTH-TOKEN>
tunnels:
    josie:
        proto: http
        addr: 8000
        domain: cheetah-careful-grizzly.ngrok-free.app
version: "2"
region: us
```
Is that something that I have to set on my router for the port forwarding? 
Or what the hell is going on?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
