### ISSUE TITLE
ngrok service doesn't reconnect after laptop sleep with ERR_NGROK_334

### ISSUE THREAD

**Issue by jheintz** [inconshreveable/ngrok#937]
I'm pretty sure the session is getting reused by someone else after my laptop goes to sleep... I just want ngrok to regenerate a new session with new port.

Mac Sonoma 14.1.1, used ngrok service to create plist, launchctl works as expected. It's just after sleep that this happens.

Error messages that keep repeating in log:
t=2023-11-18T09:56:08-0600 lvl=eror msg="failed to reconnect session" obj=tunnels.session obj=csess id=534c7250f638 err="The tunnel 'tcp://0.tcp.ngrok.io:18899' is already bound to another tunnel session\r\n\r\nERR_NGROK_334\r\n"
t=2023-11-18T09:56:38-0600 lvl=eror msg="failed to reconnect session" obj=tunnels.session obj=csess id=534c7250f638 err="The tunnel 'tcp://0.tcp.ngrok.io:18899' is already bound to another tunnel session\r\n\r\nERR_NGROK_334\r\n"
t=2023-11-18T09:57:09-0600 lvl=eror msg="failed to reconnect session" obj=tunnels.session obj=csess id=534c7250f638 err="The tunnel 'tcp://0.tcp.ngrok.io:18899' is already bound to another tunnel session\r\n\r\nERR_NGROK_334\r\n"
t=2023-11-18T10:00:32-0600 lvl=eror msg="failed to reconnect session" obj=tunnels.session obj=csess id=534c7250f638 err="The tunnel 'tcp://0.tcp.ngrok.io:18899' is already bound to another tunnel session\r\n\r\nERR_NGROK_334\r\n"
t=2023-11-18T10:01:02-0600 lvl=eror msg="failed to reconnect session" obj=tunnels.session obj=csess id=534c7250f638 err="The tunnel 'tcp://0.tcp.ngrok.io:18899' is already bound to another tunnel session\r\n\r\nERR_NGROK_334\r\n"

**Comment by Tejnium** [comment]
i am using the google colab, flask and ngrok and the same issue i am getting.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
