### ISSUE TITLE
Proposal to Fork and Maintain ngrok

### ISSUE THREAD

**Issue by tra4less** [inconshreveable/ngrok#938]
Hello everyone,

I'm considering forking the ngrok project due to its lack of recent updates and maintenance. My intention is to continue maintaining and improving it.

I'd love to hear your thoughts on this:

Do you believe maintaining ngrok is valuable for the developer community?
Is anyone interested in contributing to this maintenance effort?
Any suggestions or ideas on how I should proceed with this maintenance work?
Your input and feedback would be greatly appreciated!

new repo [ngrox-io/ngrox](https://github.com/ngrox-io/ngrox)

**Comment by philipleonardgriffiths** [comment]
Why not just use other free and open source alternatives - https://github.com/anderspitman/awesome-tunneling. Personally, I work on the project behind [zrok.io](https://zrok.io/) which is on the list.

**Comment by philipleonardgriffiths** [comment]
Right, we agree it's significant... but why invest all your time into code which hasn't been touched in 7 years, and admits it has serious reliability issues as well as crashes, and when you would be fighting with Ngrok 2.0 org (who has $50M) for the 'brand' when you can invest into FOSS alternatives? For example, the aforementioned zrok.io has 1 full-time developer and other helping, it was built in a way that makes building new features quicker (incl. HA coming soon, already have Golang SDK, NodeJS and Python soon), has many people in production who say its stable, and has a grander vision??

**Comment by russorat** [comment]
The code in this repository is licensed under Apache License, Version 2.0, and as long as any fork follows the terms of the original license, you are free to do what you'd like. 

As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
