### ISSUE TITLE
There was an issue when use ngrok http http://xxx.xxx.xxx.xxx

### ISSUE THREAD

**Issue by bearbee123** [inconshreveable/ngrok#939]
![3db61ff1-b601-4abb-8e8c-cc2bb8e526f5](https://github.com/inconshreveable/ngrok/assets/79078255/ea152e07-592b-4497-b2f7-c8bfa88580c6)
this promble append when i use ngrok http http://127.0.0.1:7890,what can i do ?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
