### ISSUE TITLE
Ngrok not working correctly for me

### ISSUE THREAD

**Issue by bl3nd11** [inconshreveable/ngrok#941]
![Screenshot 2023-12-17 010858](https://github.com/inconshreveable/ngrok/assets/154061796/b5a544f9-1d09-4b60-ab78-57b0dc186391)
I want to open a certant html file but it opens this anyone got any idea how to fix this

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
