### ISSUE TITLE
NGROK won't send image if it is embedded in HTML

### ISSUE THREAD

**Issue by Maki2007** [inconshreveable/ngrok#942]
I am making a platform, where you can upload files to my server. I want my users to be able to preview the image, without downloading it. 
I have this HTML for example to preview it:
`<img src="https://ace-gladly-spaniel.ngrok-free.app/media/get/FDgSXI2xl2/i-bs4sd" alt="image">`
But everything that appears is the infamous blue question mark.
<img width="57" alt="image" src="https://github.com/inconshreveable/ngrok/assets/95092798/e5fef17e-00f2-46b5-befc-5b3add27d05c">

But when visiting my server directly, the image appears (https://ace-gladly-spaniel.ngrok-free.app/media/get/FDgSXI2xl2/i-bs4sd). What can I do, to make my image show up in embedded elements?

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
