### ISSUE TITLE
NgRok minecraft 1 20 4 server (vanila)

### ISSUE THREAD

**Issue by Foll228** [inconshreveable/ngrok#944]
Такая проблема что в один момент перестало видеть в списке серверов мой сервер по ip (созданный через NgRok) 
Но я могу зайти на него через localHost а другие не могут.
Как это справить? Ngrok вроде не выдает ошибок как и сервер
![image](https://github.com/inconshreveable/ngrok/assets/116664004/2be093e9-ed57-4f2a-b013-e17088ccaeac)

**Comment by Foll228** [comment]
> Такая проблема что в один момент перестало видеть в списке серверов мой сервер по ip (созданный через NgRok) Но я могу зайти на него через localHost а другие не могут. Как это справить? Ngrok вроде не выдает ошибок как и сервер ![image](https://private-user-images.githubusercontent.com/116664004/316629336-2be093e9-ed57-4f2a-b013-e17088ccaeac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzOTU2NTAsIm5iZiI6MTcxMTM5NTM1MCwicGF0aCI6Ii8xMTY2NjQwMDQvMzE2NjI5MzM2LTJiZTA5M2U5LWVkNTctNGYyYS1iMDEzLWUxNzA4OGNjYWVhYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNVQxOTM1NTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MTRiNmE0MTQ0ODIwYTQxNmJiZmQ4ZWRlOWNmODEzZDg4ZTg0MjE4ZGEyMTlhNTJkMjlhZjQ4ZjgyYjczNDA4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.WhpQJ1xzorPcESxwNArFiULWHR49vEjmzQ7VZG2967c)
Such a problem that at one point it stopped seeing my server by ip in the list of servers (created via NgRok)
But I can log in to it via localHost and others can't.
How to celebrate it? Ngrok does not seem to issue errors, as does the server

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
