### ISSUE TITLE
Threat detected by Windows Security: AndroidOS/ZkarletFlash 

### ISSUE THREAD

**Issue by mateusriff** [inconshreveable/ngrok#948]
I installed ngrok on my Windows 11 machine yesterday. Windows Security has been warning me since of a threat named [AndroidOS/ZkarletFlash](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Tool%3AAndroidOS%2FZkarletFlash&threatid=302097), affecting precisely the ngrok instalation: 

![image](https://github.com/inconshreveable/ngrok/assets/105450782/f6845044-b6b2-4f99-9794-fd1f8e47464a)

I suspect (and hope) this is a false positive... Any thoughts? Couldn't find a lot of information online about AndroidOS/ZkarletFlash. I found [a similar issue](https://github.com/SeriousCache/UABE/issues/623) reported on a different repository involving the detection of same tool, which turned out to be a false positive, but not much else.

**Comment by russorat** [comment]
submitted as a false positive and it has been reclassified:
https://www.microsoft.com/en-us/wdsi/submission/9d9c2dc3-2a22-4941-8dba-8fe7edfc5444

<img width="994" alt="image" src="https://github.com/inconshreveable/ngrok/assets/4805997/5c05fa44-e778-414a-8eeb-ebd047117e40">
