### ISSUE TITLE
Ngrok service start failed on macos

### ISSUE THREAD

**Issue by chungbn** [inconshreveable/ngrok#950]
I'm using ngrok with version 3.9.0 on MacOS
When I started ngrok service with the command `ngrok service start`, I got this error

> CRIT[05-02|09:22:06] start failed                             err="Failed to start ngrok: \"launchctl\" failed with stderr: Load failed: 5: Input/output error\nTry running `launchctl bootstrap` as root for richer errors.\n"

Please anyone can help me to fix this problem?

Regards.

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).

**Comment by russorat** [comment]
Continued in https://github.com/ngrok/ngrok/issues/1
