### ISSUE TITLE
Consider transferring issues to the new repo

### ISSUE THREAD

**Issue by marcindulak** [inconshreveable/ngrok#952]
Please consider transferring unresolved, reproducible issues to the new https://github.com/ngrok/ngrok repo.

Please note that using github discussions instead of issues will result in limited discoverability of problems, see https://github.com/orgs/community/discussions/2971

**Comment by inconshreveable** [comment]
cc @russorat

**Comment by russorat** [comment]
@marcindulak thanks for the suggestion. I'm going to take a run through these issues and move the relevant ones over before we archive. stay tuned.

**Comment by russorat** [comment]
I've gone through all of these and moved the relevant ones to the new repo. Thanks!
