### ISSUE TITLE
ngrok's web ui fails ungracefully when parsing gzipped content as JSON

### ISSUE THREAD

**Issue by Miserlou** [inconshreveable/ngrok#97]
For some reason, sometimes when my server returns JSON data, the web interface for ngrok shows this message instead of correctly displaying the text on the "Summary" and "Raw" tabs. 

![screen shot 2014-03-11 at 4 02 07 pm](https://f.cloud.github.com/assets/139987/2391986/3f461100-a971-11e3-84d2-d49e110721d1.png)
![screen shot 2014-03-11 at 4 02 02 pm](https://f.cloud.github.com/assets/139987/2391987/3f593a32-a971-11e3-9a45-1ff2c239cb6f.png)
![screen shot 2014-03-11 at 4 02 11 pm](https://f.cloud.github.com/assets/139987/2391990/3ff4274a-a971-11e3-9465-7b4199e7ce56.png)
![screen shot 2014-03-11 at 4 02 16 pm](https://f.cloud.github.com/assets/139987/2391991/40018430-a971-11e3-97d9-0699f8307e40.png)

**Comment by axelson** [comment]
Any progress on this? Would be really nice to transparently inspect gzip responses.

**Comment by inconshreveable** [comment]
will eventually make it into 2.x, no plans for 1.x, closing

**Comment by peringathody** [comment]
Can this prioritized for fixing?
