### ISSUE TITLE
ngrok panics on fringe www-form-url-encoded payload

### ISSUE THREAD

**Issue by yannk** [inconshreveable/ngrok#99]
Paypal has this (weird) idea of sending its IPNs with windows-1252 encoding.

I believe the panic occurs in the UTF8 Decoder when the console tries to decode it to populate the request inspector data.

For instance, given the following data for one of the field value:
"†
2020
134 ‡"

yields:

```
panic: json: invalid UTF-8 in string: "\x86\n2020\n134\t\x87"

goroutine 143 [running]:
ngrok/util.MakePanicTrace(0x2fb840, 0xc20034e0d0, 0xc20034e0d0, 0xc200389c00)
    /Users/travis/build/inconshreveable/ngrok/src/ngrok/util/errors.go:19 +0x77
ngrok/client/views/web.func·004()
    /Users/travis/build/inconshreveable/ngrok/src/ngrok/client/views/web/http.go:238 +0x5f
ngrok/client/views/web.func·005(0xc200559f00, 0xc200a54bd0, 0xc2005b8b60)
    /Users/travis/build/inconshreveable/ngrok/src/ngrok/client/views/web/http.go:258 +0x344
net/http.HandlerFunc.ServeHTTP(0xc200146bc0, 0xc200559f00, 0xc200a54bd0, 0xc2005b8b60)
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/net/http/server.go:1149 +0x3e
net/http.(*ServeMux).ServeHTTP(0xc2000d5450, 0xc200559f00, 0xc200a54bd0, 0xc2005b8b60)
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/net/http/server.go:1416 +0x11d
net/http.serverHandler.ServeHTTP(0xc2000d2f00, 0xc200559f00, 0xc200a54bd0, 0xc2005b8b60)
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/net/http/server.go:1517 +0x16c
net/http.(*conn).serve(0xc200488c60)
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/net/http/server.go:1096 +0x765
created by net/http.(*Server).Serve
    /usr/local/Cellar/go/1.1.2/libexec/src/pkg/net/http/server.go:1564 +0x266
```

Now, the spec[1] reads: "This form data set encoding is in many ways an aberrant monstrosity" so you might want to set a limit to what you want to support in there...

Here is a reproducible request:

```
bash$
curl --data-binary $'charset=windows-1252&foo=\x87' <tunnel address>
```

Note that its a bash prompt (special format to send binary data over).
Also, the spec says `_charset_`, but PayPal uses `charset`... whatever :)

Suffice to say, if ngrok just falls back to display the binary payload, maybe it's enough...

[1] http://www.w3.org/TR/html5/forms.html#application/x-www-form-urlencoded-encoding-algorithm

**Comment by russorat** [comment]
Thank you for opening this issue! As of April 2016, the ngrok service has permanently moved to https://ngrok.com/. To join the community and file bug reports or feature enhancements for the ngrok agent, please go to https://github.com/ngrok/ngrok.

This repository is no longer actively maintained and will be archived soon to reduce confusion with the latest ngrok versions. We thank you for the continued support of ngrok and look forward to seeing you over at [ngrok.com](https://ngrok.com/) and the [ngrok Community Repo](https://github.com/ngrok/ngrok).
